IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,AND)
  GlobalGT("MIREK_QUEST","GLOBAL",3)
THEN
  RESPONSE #100
    SetSavedLocationPoint(2084,1714,SE)
    SetStartPos([2084.1714])
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,OR)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  NumberOfTimesTalkedTo(0)
  See([PC])
  !Allegiance(Myself,ENEMY)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    SetDialogueRange(75)
    Dialogue([PC])
END

IF
  Or(2)
    See([ENEMY])
    See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  Or(2)
    AttackedBy([ENEMY],DEFAULT)
    AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastAttackerOf(Myself),45)
END

IF
  ActionListEmpty()
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

