IF
  Global("MADE_FRIENDLY","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MADE_FRIENDLY","LOCALS",1)
    ChangeEnemyAlly(Myself,NEUTRAL)
END

IF
  Allegiance(Myself,ENEMY)
  Global("THRONE_ROOM_ATTACK","MYAREA",0)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("THRONE_ROOM_ATTACK","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

