IF
  OnCreation()
  Global("Liz_King_Quest","GLOBAL",1)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Die()
THEN
  RESPONSE #100
END

IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),150)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
END

IF
  !NearSavedLocation(2)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

