IF
  HPPercentLT("Bone_1_1",75)  // Bone_1_1
THEN
  RESPONSE #100
    Spell("Bone_1_1",TANARI_VAMPIRIC_TOUCH)
    Continue()
END

IF
  HPPercentLT("Bone_1_2",75)  // Bone_1_2
THEN
  RESPONSE #100
    Spell("Bone_1_2",TANARI_VAMPIRIC_TOUCH)
    Continue()
END

IF
  HPPercentLT("Bone_1_3",75)  // Bone_1_3
THEN
  RESPONSE #100
    Spell("Bone_1_3",TANARI_VAMPIRIC_TOUCH)
    Continue()
END

IF
  HPPercentLT("Bone_1_4",75)  // Bone_1_4
THEN
  RESPONSE #100
    Spell("Bone_1_4",TANARI_VAMPIRIC_TOUCH)
    Continue()
END

