IF
  Global("CHAPTER","GLOBAL",2)
THEN
  RESPONSE #100
    IncrementChapter("")
    Continue()
END

IF
  Global("KULDAHAR_ATTACK","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("KULDAHAR_ATTACK","GLOBAL",3)
    Continue()
END

IF
  Global("KULDAHAR_FORCEREMOVE","GLOBAL",0)
  GlobalGT("KULDAHAR_ATTACK","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("KULDAHAR_FORCEREMOVE","GLOBAL",1)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

