IF
  Global("MAIDEN_BADGE","GLOBAL",0)
  PartyHasItem("MAIDEN")  // ~Maiden Ilmadia's Badge~
THEN
  RESPONSE #100
    SetGlobal("MAIDEN_BADGE","GLOBAL",1)
    AddXPVar("LEVEL_11_HARD",19562)  // ~You have retrieved Maiden Ilmadia's badge.~
    Continue()
END

IF
  GlobalLT("BEORN_QUEST","GLOBAL",3)
  GlobalGT("8008_SALAMANDERS_DEAD","GLOBAL",11)
  !Global("SHIKATA_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("BEORN_QUEST","GLOBAL",3)
    Continue()
END

IF
  Global("MAP_GROUP_HOSTILE2","MYAREA",0)
  !Global("ILMADIA_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("MAP_GROUP_HOSTILE2","MYAREA",1)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

