IF
  Global("SETUP_MURDER","MYAREA",0)
  Global("PURVIS_DEAD","GLOBAL",0)
  Global("BODY_COUNT","GLOBAL",4)
THEN
  RESPONSE #100
    SetGlobal("SETUP_MURDER","MYAREA",1)
    CreateCreature("ARDEND",[391.431],10)  // ~Arden Thurlow~
    Continue()
END

IF
  Exists("PURVIS")  // ~Purvis~
  Or(2)
    !Global("PURV7_VIS","GLOBAL",0)
    !Global("PURVIS_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    HideCreature("PURVIS",TRUE)
    ActionOverride("PURVIS",DestroySelf())
    Continue()
END

IF
  Global("LONELYWOOD_ALARM","GLOBAL",0)
  !Global("AREA_HOSTILE","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("LONELYWOOD_ALARM","GLOBAL",1)
    Continue()
END

IF
  Global("AREA_HOSTILE","MYAREA",0)
  !Global("LONELYWOOD_ALARM","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("AREA_HOSTILE","MYAREA",1)
    Continue()
END

IF
  !Global("TOWNIE_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("TOWNIE_HOSTILE","MYAREA",0)
    SetGlobal("TOWNIE_DEAD","GLOBAL",0)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

