IF
  Global("ATK_MEL","LOCALS",1)
  TimerExpired(28)
THEN
  RESPONSE #100
    SetGlobal("ATK_MEL","LOCALS",0)
    Continue()
END

IF
  Global("FLOATED_MESSAGE","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("FLOATED_MESSAGE","LOCALS",1)
    FloatMessage(Myself,24943)  // ~"This is my last act of service to you, pig.  I'll see you in the Abyss!"~
    Continue()
END

IF
  !Global("ATK_MEL","LOCALS",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  See(NearestEnemyOf(Myself))
  Global("ATK_PHASE","LOCALS",3)
THEN
  RESPONSE #100
    SetGlobal("ATK_PHASE","LOCALS",4)
    SetGlobal("ATK_MEL","LOCALS",2)
    ForceSpell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  Global("ATK_PHASE","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("ATK_PHASE","LOCALS",3)
    ForceSpell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  Global("ATK_PHASE","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("ATK_PHASE","LOCALS",2)
    StartRandomTimer(28,14,35)
    SetGlobal("ATK_MEL","LOCALS",1)
    ForceSpell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("ATK_PHASE","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("ATK_PHASE","LOCALS",1)
    FloatMessage(Myself,24943)  // ~"This is my last act of service to you, pig.  I'll see you in the Abyss!"~
    ForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    Wait(2)
END

IF
  See([PC])
  !Range(LastSeenBy(Myself),10)
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
END

IF
  !See([PC])
THEN
  RESPONSE #100
    MoveToObject([PC][0.0.10000.10000])
END

