IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    StartRandomTimer(24,10,20)
    Continue()
END

IF
  !CreatureHidden(Myself)
  !TimerActive(24)
THEN
  RESPONSE #100
    FloatMessage(Myself,24903)  // ~"To avenge the dead, we will claim the living!"~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,24904)  // ~"My beautiful hair!  What has become of it?"~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,24905)  // ~"Mother, I will not dishonor you!"~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,24906)  // ~"When I was a child, I did not know the meaning of honor."~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,24907)  // ~"I was never a woman in life.  In death, I am free to wage war."~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,24908)  // ~"We shall eternally bleed for our masters."~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,24909)  // ~"I have a son.  His name is 'vengeance.'"~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,24910)  // ~"It was only important to smile and hold still..."~
    StartRandomTimer(24,10,20)
    Continue()
END

