IF
  !Global("BARBARIAN_CAMP_HOSTILE","GLOBAL",0)
THEN
  RESPONSE #100
    ChangeCurrentScript("BCHSTCMP")
END

IF
  GlobalGT("HJOLLDER_QUEST","GLOBAL",10)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("BC_GROUP_HOSTILE5","GLOBAL",0)
  !CreatureHidden(Myself)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobal("BC_GROUP_HOSTILE5","GLOBAL",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("BC_GROUP_HOSTILE5","GLOBAL",0)
THEN
  RESPONSE #100
    Enemy()
    SetGlobal("BC_GROUP_HOSTILE5","GLOBAL",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  !Global("BC_GROUP_HOSTILE5","GLOBAL",0)
  ActionListEmpty()
  !See([PC])
THEN
  RESPONSE #100
    MoveToObject([PC][0.0.10000.10000])
END

