IF
  !Global("BARBARIAN_CAMP_HOSTILE","GLOBAL",0)
THEN
  RESPONSE #100
    Enemy()
    MultiPlayerSync()
    EquipItem("MIN1HP",1)
    DestroyItem("MIN1HP")  // <Invalid Strref -1>
    MultiPlayerSync()
    ChangeCurrentScript("BCHSTCMP")
END

IF
  GlobalGT("HJOLLDER_QUEST","GLOBAL",10)
THEN
  RESPONSE #100
    CloseDoor("AR9200_GATE1")
    Explore()
    EquipItem("MIN1HP",1)
    DestroyItem("MIN1HP")  // <Invalid Strref -1>
    ChangeCurrentScript("BCANGBTL")
END

IF
  Global("BC_CUTSCENE","GLOBAL",14)
  !Global("WARRIORS_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("BC_CUTSCENE","GLOBAL",10)
END

IF
  Global("BC_CUTSCENE","GLOBAL",0)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetGlobal("BARBARIAN_CAMP_HOSTILE","GLOBAL",1)
    Enemy()
END

IF
  NumberOfTimesTalkedTo(0)
  See([PC])
THEN
  RESPONSE #100
    SetDialogueRange(300)
    Dialogue(LastSeenBy(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    NoAction()
END

