IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    StartCutSceneMode()
    StopJoinRequests()
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    MultiPlayerSync()
    ClearAllActions()
    MultiPlayerSync()
    FadeToColor([0.0],0)
    Wait(1)
    MultiPlayerSync()
    SetGlobal("9100_RESET_JOIN","GLOBAL",1)
    SetGlobal("NED_IN_9300","GLOBAL",0)
    MultiPlayerSync()
    EndCutSceneMode()
    StartCutScene("IDNED2LW")
END

