IF
  Global("EGANIA_MOVE","GLOBAL",1)
THEN
  RESPONSE #100
    SetSavedLocationPoint(2830,1790,E)
    SetGlobal("EGANIA_MOVE","GLOBAL",2)
    MultiPlayerSync()
    JumpToPoint([2830.1790])
    MultiPlayerSync()
    SetStartPos([2830.1790])
    MultiPlayerSync()
    Face(E)
END

IF
  !Global("YXUNOMEI_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  See([PC])
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastAttackerOf(Myself),45)
END

IF
  ActionListEmpty()
  !NearSavedLocation(12)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

