IF
  See([PC])
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastAttackerOf(Myself),75)
END

IF
  Help([PC])
THEN
  RESPONSE #100
    MoveToObject(LastHelp(Myself))
END

IF
  AttackedBy([0.0.TROLL],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  HelpEX(Myself,RACE)
THEN
  RESPONSE #100
    FaceObject(LastHelp(Myself))
    Continue()
END

IF
  ActionListEmpty()
  NearSavedLocation(12)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  ActionListEmpty()
  !NearSavedLocation(12)
THEN
  RESPONSE #100
    RandomWalk()
    WaitRandom(1,5)
END

