IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    HideCreature(Myself,TRUE)
    Continue()
END

IF
  See([PC])
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastAttackerOf(Myself),75)
END

IF
  Help([PC])
THEN
  RESPONSE #100
    MoveToObject(LastHelp(Myself))
END

IF
  HelpEX(Myself,RACE)
THEN
  RESPONSE #100
    MoveToObject(LastHelp(Myself))
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    Face(N)
  RESPONSE #100
    Face(NE)
  RESPONSE #100
    Face(NW)
END

