IF
  Allegiance(Myself,ENEMY)
  NumberOfTimesTalkedTo(0)
THEN
  RESPONSE #100
    SetNumTimesTalkedTo(1)
    Continue()
END

IF
  !NumberOfTimesTalkedTo(0)
THEN
  RESPONSE #100
    ChangeCurrentScript("D4ELDG")
END

IF
  NumberOfTimesTalkedTo(0)
  See([PC])
  !Allegiance(Myself,ENEMY)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    StartCutSceneMode()
    ClearAllActions()
    SetDialogueRange(300)
    MultiPlayerSync()
    Dialogue([PC])
END

