IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",16,AND)
  HPPercentLT(Myself,50)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,XOR)
    Continue()
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  HPPercentLT(Myself,15)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,XOR)
    Continue()
END

IF
  HaveSpell(TANARI_PARALYZE)
  !Global("YUANTI_INFERNO","GLOBAL",0)
THEN
  RESPONSE #100
    Spell(Myself,TANARI_PARALYZE)
    Wait(2)
    Spell(Myself,TANARI_SILENCE)
    Wait(2)
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,AND)
  HPPercentLT(Myself,75)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,OR)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,OR)
    ForceSpell(Myself,TANARI_SILENCE)
    Wait(2)
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",16,AND)
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  HPPercentLT(Myself,25)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",16,OR)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,OR)
    ForceSpell(Myself,TANARI_SILENCE)
    Wait(2)
    Continue()
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  !Global("HEALER_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,XOR)
    Continue()
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  TargetUnreachable("ELDATHYNHEALER")  // ELDATHYNHEALER
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,XOR)
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",2,AND)
  !Global("YUANTI_INFERNO","GLOBAL",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #75
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",2,OR)
    PlaySequence(Myself,HEAD_TURN)
    Continue()
  RESPONSE #25
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",2,OR)
    Continue()
END

IF
  !Global("YUANTI_INFERNO","GLOBAL",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  !Global("YUANTI_INFERNO","GLOBAL",0)
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  !Global("YUANTI_INFERNO","GLOBAL",0)
  ActionListEmpty()
  !See([PC])
THEN
  RESPONSE #100
    MoveToObject([PC][0.0.10000.10000])
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  !HPPercentLT(Myself,75)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,XOR)
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  !See("ELDATHYNHEALER")  // ELDATHYNHEALER
THEN
  RESPONSE #100
    MoveToObject("ELDATHYNHEALER")
END

