IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",2,AND)
  !Global("YUANTI_INFERNO","GLOBAL",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #75
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",2,OR)
    PlaySequence(Myself,HEAD_TURN)
    Continue()
  RESPONSE #25
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",2,OR)
    Continue()
END

IF
  HaveSpell(TANARI_SILENCE)
  See(NearestEnemyOf(Myself))
  !Global("YUANTI_INFERNO","GLOBAL",0)
THEN
  RESPONSE #100
    Spell(Myself,TANARI_SILENCE)
    Wait(2)
END

IF
  !Global("YUANTI_INFERNO","GLOBAL",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  !Global("YUANTI_INFERNO","GLOBAL",0)
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetGlobal("YUANTI_INFERNO","GLOBAL",1)
    Enemy()
    Continue()
END

