IF
  Entered([PC])
THEN
  RESPONSE #100
    SetGlobal("D5_DEATH_FOG_TRAP_SET","MYAREA",1)
    DisplayString(Myself,14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastTrigger,TRAP_DEATH_FOG)
    Wait(2)
END

IF
  Opened([PC])
THEN
  RESPONSE #100
    SetGlobal("D5_DEATH_FOG_TRAP_SET","MYAREA",1)
    DisplayString(Myself,14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastTrigger,TRAP_DEATH_FOG)
    Wait(2)
END

