IF
  !BitGlobal("MYAREA:AREA_VAR","",2,AND)
THEN
  RESPONSE #100
    BitGlobal("MYAREA:AREA_VAR","",2,OR)
    SetGlobal("YXUN_ATTACK","MYAREA",1)
    SetSavedLocationPoint(3260,530,SW)
    SetStartPos([3260.530])
    Enemy()
    Continue()
END

IF
  HaveSpell(WIZARD_CLOUDKILL)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_CLOUDKILL)
    Wait(2)
END

IF
  HaveSpell(WIZARD_ANIMATE_DEAD)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_ANIMATE_DEAD)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  !See([PC])
  ActionListEmpty()
  !See([PC])
THEN
  RESPONSE #100
    MoveToObject([PC][0.0.10000.10000])
END

