IF
  !TimerActive(25)
THEN
  RESPONSE #100
    StartRandomTimer(25,9,27)
    ForceSpellPoint([917.1098],INNATE_INFERNAL_CONVEYANCE)
    Wait(4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,OR)
    FaceObject([PC][0.0.10000.10000])
    ChangeCurrentScript("eeBelW1")
  RESPONSE #100
    StartRandomTimer(25,9,27)
    ForceSpellPoint([386.573],INNATE_INFERNAL_CONVEYANCE)
    Wait(4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,OR)
    FaceObject([PC][0.0.10000.10000])
    ChangeCurrentScript("eeBelW3")
  RESPONSE #100
    StartRandomTimer(25,9,27)
    ForceSpellPoint([956.509],INNATE_INFERNAL_CONVEYANCE)
    Wait(4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,OR)
    FaceObject([PC][0.0.10000.10000])
    ChangeCurrentScript("eeBelW4")
  RESPONSE #100
    StartRandomTimer(25,9,27)
    ForceSpellPoint([572.1035],INNATE_INFERNAL_CONVEYANCE)
    Wait(4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,OR)
    FaceObject([PC][0.0.10000.10000])
    ChangeCurrentScript("eeBelW5")
  RESPONSE #100
    StartRandomTimer(25,9,27)
    ForceSpellPoint([263.842],INNATE_INFERNAL_CONVEYANCE)
    Wait(4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,OR)
    FaceObject([PC][0.0.10000.10000])
    ChangeCurrentScript("eeBelW6")
END

