IF
  True()
THEN
  RESPONSE #100
    CutSceneId("POQUELIN")  // 
    StartCutSceneMode()
    HideGUI()
    MultiPlayerSync()
    SetGlobal("END_PORTAL","GLOBAL",2)
    ActionOverride("EVERARD",ForceSpellPoint([603.414],INNATE_EVERARDS_PORTAL_CLOSING))
    Wait(2)
    Deactivate("GATEWAY")
    Wait(2)
    StartCutScene("EECRNMVE")
    Wait(3)
    FaceObject([PC])
    SetDialogueRange(300)
    MultiPlayerSync()
    Wait(1)
    Dialogue(Protagonist)
END

