IF
  True()
THEN
  RESPONSE #100
    CutSceneId("POQUELIN")  // 
    StartCutSceneMode()
    StopJoinRequests()
    MultiPlayerSync()
    ExportParty("IWD")
    Wait(1)
    MultiPlayerSync()
    HideGUI()
    MultiPlayerSync()
    ClearAllActions()
    Explore()
    SetVisualRange(30)
    SetDialogueRange(250)
    Wait(1)
    MoveViewObject(Myself,VERY_FAST)
    Wait(3)
    Dialogue(Protagonist)
END

