IF
  Global("CHILDREN_FLOAT","MYAREA",2)
  GlobalTimerExpired("CHILDREN_FLOAT_TIMER","MYAREA")
THEN
  RESPONSE #100
    FloatMessage(Myself,16212)  // ~"Are the giants gonna kill us?"~
    SetGlobalTimer("CHILDREN_FLOAT_TIMER","MYAREA",1)
    SetGlobal("CHILDREN_FLOAT","MYAREA",0)
    Continue()
END

IF
  See([PC])
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastAttackerOf(Myself),45)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  ActionListEmpty()
THEN
  RESPONSE #100
    MoveToObject("MOMMY")
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",0)
END

