IF
  Allegiance(Myself,ENEMY)
  See([PC])
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastAttackerOf(Myself),45)
END

IF
  ActionListEmpty()
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    RandomWalk()
    WaitRandom(5,8)
END

