IF
  IsWeaponRanged(Myself)
THEN
  RESPONSE #50
    ChangeCurrentScript("EFATKCR")
  RESPONSE #50
    ChangeCurrentScript("EFATKHR")
  RESPONSE #50
    ChangeCurrentScript("EFATKTR")
  RESPONSE #150
    ChangeCurrentScript("EFATKRNG")
END

IF
  True()
THEN
  RESPONSE #50
    ChangeCurrentScript("EFATKCM")
  RESPONSE #50
    ChangeCurrentScript("EFATKHM")
  RESPONSE #50
    ChangeCurrentScript("EFATKTM")
  RESPONSE #150
    ChangeCurrentScript("EFATKMEL")
END

