IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",16384,AND)
  Opened([PC])
  See([PC])
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,AND)
  PickPocketFailed([PC])
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,18056)  // ~"I wouldn't try that again.  Thieves are not welcome in these parts."~
    Continue()
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,18057)  // ~"That better not have been your hand I felt in my pocket."~
    Continue()
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,18058)  // ~"You thieving scoundrel.  I'll let you off this time with a warning, but next time..."~
    Continue()
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,18059)  // ~"Watch yourself, stranger.  Pickpocketing is risky business -- especially when your as clumsy as you seem to be."~
    Continue()
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,17990)  // ~"Hey, watch it!  Keep your hands to yourself, friend."~
    Continue()
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,17992)  // ~"I don't appreciate the attempt at theft.  You'd better behave yourself."~
    Continue()
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,17993)  // ~"You're lucky I'm a forgiving person.  Don't try to steal from me again."~
    Continue()
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,17994)  // ~"Keep your distance.  You think I can't tell what you were doing just now?"~
    Continue()
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,OR)
    FloatMessage(Myself,17995)  // ~"What were you just doing?  I'd like to ask that you step away, thank you."~
    Continue()
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",8192,AND)
  PickPocketFailed([PC])
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

