IF
  Dead("YSELF)")  // YSELF)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("AREA_HOSTILE","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  !Global("AREA_HOSTILE","MYAREA",0)
  Allegiance(Myself,ENEMY)
  !See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  !CreatureHidden(Myself)
  !Global("TOWNIE_HOSTILE","MYAREA",0)
  Global("AREA_HOSTILE","MYAREA",0)
  Help([ANYTHING])
THEN
  RESPONSE #100
    SetGlobal("AREA_HOSTILE","MYAREA",1)
    Continue()
    Enemy()
    Continue()
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetGlobal("TOWNIE_HOSTILE","MYAREA",1)
    Help()
    Enemy()
    Continue()
END

