IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastAttackerOf(Myself),75)
END

IF
  Help(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastHelp(Myself),75)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Help([PC])
THEN
  RESPONSE #100
    FaceObject(LastHelp(Myself))
    Continue()
END

IF
  HelpEX(Myself,RACE)
THEN
  RESPONSE #100
    MoveToObject(LastHelp(Myself))
END

