IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  Or(2)
    Allegiance(Myself,ENEMY)
    BitGlobal("MYAREA:AREA_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,OR)
    SetSavedLocationPoint(2202,548,S)
    SetStartPos([2202.548])
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    StartRandomTimer(24,10,20)
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  !TimerActive(24)
THEN
  RESPONSE #100
    FloatMessage(Myself,2964)  // ~"Lets poke him with a stick."~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,2955)  // ~"I'm gonna ask if we can keep him."~
    StartRandomTimer(24,10,20)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,2956)  // ~"Can he do any tricks?"~
    StartRandomTimer(24,10,20)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastAttackerOf(Myself),45)
END

IF
  Help(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastHelp(Myself),45)
END

IF
  BitGlobal("MYAREA:AREA_VAR","",1,AND)
  See([PC])
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  BitGlobal("MYAREA:AREA_VAR","",1,AND)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastAttackerOf(Myself),45)
END

IF
  BitGlobal("MYAREA:AREA_VAR","",1,AND)
  Help([PC])
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastHelp(Myself),45)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Help([ANYTHING])
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastHelp(Myself),45)
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  ActionListEmpty()
  !NearSavedLocation(60)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  ActionListEmpty()
THEN
  RESPONSE #100
    RandomWalk()
    WaitRandom(3,7)
END

IF
  ActionListEmpty()
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

