IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    HideCreature(Myself,TRUE)
    Continue()
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastAttackerOf(Myself),75)
END

IF
  Help(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    MoveToObject(LastHelp(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  ActionListEmpty()
  NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  ActionListEmpty()
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    RandomWalk()
    WaitRandom(3,7)
END

