IF
  !BitGlobal("MYAREA:AREA_VAR","",1,AND)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    BitGlobal("MYAREA:AREA_VAR","",1,OR)
    Continue()
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    BitGlobal("MYAREA:AREA_VAR","",1,OR)
    Enemy()
    Continue()
END

IF
  Help([PC])
THEN
  RESPONSE #100
    BitGlobal("MYAREA:AREA_VAR","",1,OR)
    FaceObject(LastHelp(Myself))
    Continue()
END

IF
  ActionListEmpty()
  NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  ActionListEmpty()
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    RandomWalk()
    WaitRandom(3,7)
END

