IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    ChangeAIScript("EHWLFCRM",AREA)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastAttackerOf(Myself),75)
END

IF
  Help(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    FaceObject(LastHelp(Myself))
    Continue()
END

