IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastAttackerOf(Myself),75)
END

IF
  Help(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastHelp(Myself),75)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Help([PC])
THEN
  RESPONSE #100
    FaceObject(LastHelp(Myself))
    Continue()
END

IF
  Or(2)
    HelpEX(Myself,RACE)
    Help([0.0.DWARF])
THEN
  RESPONSE #100
    FaceObject(LastHelp(Myself))
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  !NearSavedLocation(2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",1)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",1)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(N)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",2)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",7)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",3)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,504,412,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([504.412])
    MoveToPoint([504.412])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",4)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(W)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",5)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",5)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",5)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",6)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",6)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,482,491,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",7)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",6)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([482.491])
    MoveToPoint([482.491])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",7)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(W)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",8)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",8)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",7)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",9)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",9)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,552,619,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",10)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",9)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([552.619])
    MoveToPoint([552.619])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",10)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(SW)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",11)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",11)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",5)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",12)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",12)
  !NearSavedLocation(2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",12)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",0)
    Continue()
END

