IF
  HasItem("POTN08",Myself)  // ~Potion of Healing~
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    UseItem("POTN08",Myself)  // ~Potion of Healing~
    Continue()
END

IF
  HasItem("EXTHEAL",Myself)  // ~Potion of Extra Healing~
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    UseItem("EXTHEAL",Myself)  // ~Potion of Extra Healing~
    Continue()
END

IF
  !BitGlobal("LOCALS:SCRIPT_BIT_VAR","",1,AND)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    BitGlobal("LOCALS:SCRIPT_BIT_VAR","",1,OR)
    StartTimer(0,5)
END

IF
  TimerActive(0)
  BitGlobal("LOCALS:SCRIPT_BIT_VAR","",1,AND)
  AttackedBy(LastSeenBy(Myself),DEFAULT)
THEN
  RESPONSE #100
    StartTimer(0,0)
    Continue()
END

IF
  !TimerActive(0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetBestWeapon(LastSeenBy(Myself),4)
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  HelpEX(Myself,RACE)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(LastHelp(Myself)))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

