IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Protagonist)  // 
    ClearAllActions()
    MultiPlayerSync()
    HideGUI()
    MultiPlayerSync()
    StartCutScene("ILGEMKIL")
    SetVisualRange(50)
    SetGlobal("HOW_COMPLETED","GLOBAL",1)
    MoveViewPoint([943.839],INSTANT)
    MultiPlayerSync()
    Wait(2)
    PlaySound("GEMDEATH")
    PlaySequence("9603MS1",AWAKE)
    Wait(3)
    PlaySequence("9603MS1",CAST)
    Wait(1)
    AddexperienceParty(500000)
    TomsStringDisplayer(26728)  // ~You have saved the northern lands from the threat of Icasaracht.~
    Wait(3)
    MoveViewPoint([2205.1177],INSTANT)
    PlaySound("AM9603F")
    Unlock("AR9604_EXIT")
    Wait(1)
    MultiPlayerSync()
    PlaySound("AM9603D")
    OpenDoor("AR9604_EXIT")
    Wait(1)
    MoveViewObject([PC][0.0.10000.10000],INSTANT)
    SetVisualRange(0)
    MultiPlayerSync()
    UnhideGUI()
    MultiPlayerSync()
    EndCutSceneMode()
END

