IF
  !Global("LYSAN_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    Help()
    RunAwayFromNoLeaveArea(LastAttackerOf(Myself),45)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  !NearSavedLocation(2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",1)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",1)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",3)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",2)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",2)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,345,303,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",3)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([345.303])
    MoveToPoint([345.303])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,345,249,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([345.249])
    MoveToPoint([345.249])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",4)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,374,220,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",5)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",4)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([374.220])
    MoveToPoint([374.220])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",5)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,412,220,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",6)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",5)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([412.220])
    MoveToPoint([412.220])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",6)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(SE)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",7)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",7)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",10)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",8)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",8)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,154,220,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",9)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",8)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([154.220])
    MoveToPoint([154.220])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",9)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(NE)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",10)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",10)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",5)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",11)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",11)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,59,220,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",12)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",11)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([59.220])
    MoveToPoint([59.220])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",12)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,59,184,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",13)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",12)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([59.184])
    MoveToPoint([59.184])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",13)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,113,134,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",14)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",13)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([113.134])
    MoveToPoint([113.134])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",14)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(N)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",15)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",15)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",15)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",16)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",16)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,59,184,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",17)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",16)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([59.184])
    MoveToPoint([59.184])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",17)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,59,220,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",18)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",17)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([59.220])
    MoveToPoint([59.220])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",18)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,154,220,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",19)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",18)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([154.220])
    MoveToPoint([154.220])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",19)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,237,303,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",20)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",19)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([237.303])
    MoveToPoint([237.303])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",20)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,393,303,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",0)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",20)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([393.303])
    MoveToPoint([393.303])
END

