IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastAttackerOf(Myself),45)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,703,2055,8)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",1)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([703.2055])
    MoveToPoint([703.2055])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",1)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,953,2292,8)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",2)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",1)
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([953.2292])
    MoveToPoint([953.2292])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",2)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,2152,2289,8)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",3)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",2)
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([2152.2289])
    MoveToPoint([2152.2289])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,2338,2040,8)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([2338.2040])
    MoveToPoint([2338.2040])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",4)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,2995,1856,8)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",5)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",4)
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([2995.1856])
    MoveToPoint([2995.1856])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",5)
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    DestroySelf()
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",0)
END

