IF
  Global("8001_FENGLA_REMOVE","GLOBAL",0)
  Global("ARROW_MESSAGE","MYAREA",1)
  GlobalTimerExpired("ARROW_TIMER","MYAREA")
THEN
  RESPONSE #100
    FloatMessage(Myself,18610)  // ~"Hey, stupid, get out of here!"~
    SetGlobal("ARROW_MESSAGE","MYAREA",0)
    SetGlobalTimer("ARROW_TIMER","MYAREA",3)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,18611)  // ~"Ha ha!  Idiot!  Take that!"~
    SetGlobal("ARROW_MESSAGE","MYAREA",0)
    SetGlobalTimer("ARROW_TIMER","MYAREA",3)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,19564)  // ~"How'd you like a gut full of arrows, friend?"~
    SetGlobal("ARROW_MESSAGE","MYAREA",0)
    SetGlobalTimer("ARROW_TIMER","MYAREA",3)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,19565)  // ~"Wooo!  Ha ha ha!"~
    SetGlobal("ARROW_MESSAGE","MYAREA",0)
    SetGlobalTimer("ARROW_TIMER","MYAREA",3)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,19605)  // ~"Why don't you try to come storm the tower, moron?"~
    SetGlobal("ARROW_MESSAGE","MYAREA",0)
    SetGlobalTimer("ARROW_TIMER","MYAREA",3)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,19606)  // ~"Hee hee ha ha!"~
    SetGlobal("ARROW_MESSAGE","MYAREA",0)
    SetGlobalTimer("ARROW_TIMER","MYAREA",3)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,19607)  // ~"This is easier than shooting deep gnomes in a cattle pen!"~
    SetGlobal("ARROW_MESSAGE","MYAREA",0)
    SetGlobalTimer("ARROW_TIMER","MYAREA",3)
    Continue()
END

IF
  Global("8001_FENGLA_REMOVE","GLOBAL",0)
  !CreatureHidden(LastTrigger)
  Entered([PC])
THEN
  RESPONSE #100
    ReallyForceSpell(LastTrigger,TRAP_ARROW)
    SetGlobal("ARROW_MESSAGE","MYAREA",1)
END

IF
  Global("8001_FENGLA_REMOVE","GLOBAL",0)
  !CreatureHidden(LastTrigger)
  Opened([PC])
THEN
  RESPONSE #100
    ReallyForceSpell(LastTrigger,TRAP_ARROW)
    SetGlobal("ARROW_MESSAGE","MYAREA",1)
END

IF
  Global("8001_FENGLA_REMOVE","GLOBAL",0)
  !CreatureHidden(LastTrigger)
  Entered([0.0.SVIRFNEBLIN])
THEN
  RESPONSE #100
    ReallyForceSpell(LastTrigger,TRAP_ARROW)
    SetGlobal("ARROW_MESSAGE","MYAREA",1)
END

IF
  Global("8001_FENGLA_REMOVE","GLOBAL",0)
  !CreatureHidden(LastTrigger)
  Opened([0.0.SVIRFNEBLIN])
THEN
  RESPONSE #100
    ReallyForceSpell(LastTrigger,TRAP_ARROW)
    SetGlobal("ARROW_MESSAGE","MYAREA",1)
END

