IF
  GlobalGT("POQUELIN_HOSTILE","GLOBAL",1)
THEN
  RESPONSE #100
    Kill(Myself)
END

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  Allegiance(Myself,ENEMY)
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  ActionListEmpty()
  !NearSavedLocation(36)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    RandomWalk()
    WaitRandom(1,4)
END

