IF
  OnCreation()
  !Global("FLEEZ_MOVED","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  !Global("FLEEZUM_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  NearSavedLocation(0)
  !Allegiance(Myself,ENEMY)
  !TimerActive(26)
THEN
  RESPONSE #100
    StartTimer(26,3)
    PlaySequence(Myself,ATTACK_SLASH)
  RESPONSE #100
    StartTimer(26,3)
    PlaySequence(Myself,ATTACK_BACKSLASH)
  RESPONSE #100
    StartTimer(26,3)
  RESPONSE #100
    StartTimer(26,2)
  RESPONSE #100
    StartTimer(26,1)
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",256,AND)
  !Global("FLOZUM_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",256,OR)
    FloatMessage(Myself,15404)  // ~"You killed my brother!  You'll pay for that!"~
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  Global("MAP_GROUP_HOSTILE1","MYAREA",0)
  !CreatureHidden(Myself)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("MAP_GROUP_HOSTILE1","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1)
    FloatMessage(Myself,15403)  // ~"Flozem!  Get over here!"~
    Enemy()
    SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !TargetUnreachable([PC])
THEN
  RESPONSE #100
    MoveToObject([PC])
END

IF
  ActionListEmpty()
  !NearSavedLocation(12)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

