IF
  !Global("FLOZ_MOVED","GLOBAL",0)
THEN
  RESPONSE #100
    HideCreature(Myself,TRUE)
    DestroySelf()
END

IF
  OnCreation()
  !Global("FLOZEM_GONE","GLOBAL",0)
THEN
  RESPONSE #100
    HideCreature(Myself,TRUE)
    DestroySelf()
END

IF
  !Global("FLOZEM_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    HideCreature(Myself,TRUE)
    DestroySelf()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",256,AND)
  !Global("FLEEZUM_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",256,OR)
    FloatMessage(Myself,15404)  // ~"You killed my brother!  You'll pay for that!"~
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  Global("MAP_GROUP_HOSTILE1","MYAREA",0)
  !CreatureHidden(Myself)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("MAP_GROUP_HOSTILE1","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    FloatMessage(Myself,15405)  // ~"Fleezum!  Your assistance, please!"~
    Enemy()
    SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    MoveToObject([PC][0.0.10000.10000])
END

IF
  Global("FLOZEM_GONE","GLOBAL",0)
  ActionListEmpty()
  !NearSavedLocation(48)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  Global("FLOZEM_GONE","GLOBAL",0)
  ActionListEmpty()
THEN
  RESPONSE #100
    RandomWalk()
    WaitRandom(3,10)
END

