IF
  !Global("BEORN_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  OnCreation()
  !Global("GUELLO_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("MAP_GROUP_HOSTILE1","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  CreatureHidden(Myself)
  Global("BEORN_QUEST","GLOBAL",4)
  Global("8004_HULKS_DEAD","GLOBAL",15)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  CreatureHidden(Myself)
  Global("BEORN_QUEST","GLOBAL",3)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    HideCreature(Myself,TRUE)
    Continue()
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1)
    Enemy()
    Continue()
END

IF
  Allegiance([0.0.GNOME],ENEMY)
  HelpEX(Myself,RACE)
THEN
  RESPONSE #100
    MoveToObject(LastHelp(Myself))
END

