IF
  HaveSpell(WIZARD_STONESKIN)
  !CreatureHidden(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_STONESKIN)
    Wait(2)
END

IF
  HaveSpell(WIZARD_TROLLISH_FORTITUDE)
  !CreatureHidden(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_TROLLISH_FORTITUDE)
    Wait(2)
END

IF
  HaveSpell(WIZARD_SHIELD)
  !CreatureHidden(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHIELD)
    Wait(2)
END

IF
  !HaveSpell(WIZARD_CONFUSION)
  !HaveSpell(WIZARD_LIGHTNING_BOLT)
  !HaveSpell(WIZARD_MONSTER_SUMMONING_V)
  !HaveSpell(WIZARD_PRISMATIC_SPRAY)
  !HaveSpell(CLERIC_WALL_OF_MOONLIGHT)
  !HaveSpell(WIZARD_OTILUKES_FREEZING_SPHERE)
THEN
  RESPONSE #100
    ChangeCurrentScript("LDILAIR2")
END

IF
  !Global("Y_TEAM_HOSTILE","LOCALM",0)
  Global("MAP_GROUP_HOSTILE0","MYAREA",0)
  Global("MAP_GROUP_HOSTILE1","MYAREA",0)
  Global("MAP_GROUP_HOSTILE2","MYAREA",0)
  Global("MAP_GROUP_HOSTILE3","MYAREA",0)
  Global("MAP_GROUP_HOSTILE4","MYAREA",0)
  Global("MAP_GROUP_HOSTILE5","MYAREA",0)
  Global("MAP_GROUP_HOSTILE6","MYAREA",0)
  Global("MAP_GROUP_HOSTILE7","MYAREA",0)
  Global("MAP_GROUP_HOSTILE8","MYAREA",0)
  Global("MAP_GROUP_HOSTILE9","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("Y_TEAM_HOSTILE","LOCALM",0)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("MAP_GROUP_HOSTILE0","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  CreatureHidden(Myself)
  Or(2)
    !Global("MAP_GROUP_HOSTILE0","MYAREA",0)
    !Global("MAP_GROUP_HOSTILE5","MYAREA",0)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  ActionListEmpty()
  Or(2)
    !Global("MAP_GROUP_HOSTILE0","MYAREA",0)
    !Global("MAP_GROUP_HOSTILE5","MYAREA",0)
  Allegiance(Myself,ENEMY)
  !See([PC])
THEN
  RESPONSE #100
    MoveToObject([PC][0.0.10000.10000])
  RESPONSE #100
    NoAction()
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

IF
  True()
THEN
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",0)
    Continue()
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",1)
    Continue()
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",2)
    Continue()
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",3)
    Continue()
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",4)
    Continue()
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",5)
    Continue()
END

IF
  HaveSpell(WIZARD_CONFUSION)
  GlobalLT("LOCAL_CAST_SPELL","LOCALS",1)
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
    Wait(2)
END

IF
  HaveSpell(WIZARD_LIGHTNING_BOLT)
  GlobalLT("LOCAL_CAST_SPELL","LOCALS",2)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
    Wait(2)
END

IF
  HaveSpell(WIZARD_MONSTER_SUMMONING_V)
  GlobalLT("LOCAL_CAST_SPELL","LOCALS",3)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_MONSTER_SUMMONING_V)
    Wait(2)
END

IF
  HaveSpell(WIZARD_PRISMATIC_SPRAY)
  GlobalLT("LOCAL_CAST_SPELL","LOCALS",4)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)
    Wait(2)
END

IF
  HaveSpell(CLERIC_WALL_OF_MOONLIGHT)
  GlobalLT("LOCAL_CAST_SPELL","LOCALS",5)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_WALL_OF_MOONLIGHT)
    Wait(2)
END

IF
  HaveSpell(WIZARD_OTILUKES_FREEZING_SPHERE)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_OTILUKES_FREEZING_SPHERE)
    Wait(2)
END

