IF
  !Allegiance(Myself,ENEMY)
  !Global("MAP_GROUP_HOSTILE5","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Or(2)
    !HaveSpell(WIZARD_TENSERS_TRANSFORMATION)
    IsWeaponRanged(Myself)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  HaveSpell(WIZARD_MORDENKAINENS_SWORD)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MORDENKAINENS_SWORD)
    Wait(2)
END

IF
  HaveSpell(WIZARD_HASTE)
  !StateCheck(NearestEnemyOf(Myself),STATE_HASTED)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_HASTE)
    Wait(2)
END

IF
  HaveSpell(WIZARD_TENSERS_TRANSFORMATION)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_TENSERS_TRANSFORMATION)
    Wait(2)
END

