IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",256,AND)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",256,OR)
    FloatMessage(Myself,15474)  // ~"To the dust with you, Prime!"~
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  NumberOfTimesTalkedTo(0)
  See([PC])
  !Allegiance(Myself,ENEMY)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    StartCutSceneMode()
    ClearAllActions()
    SetDialogueRange(300)
    MultiPlayerSync()
    Dialogue([PC])
END

