IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    LeaveAreaLUA("AR2000","LOAD2000",[137.1252],12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    LeaveAreaLUA("AR2000","LOAD2000",[137.1242],12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    LeaveAreaLUA("AR2000","LOAD2000",[137.1252],12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    LeaveAreaLUA("AR2000","LOAD2000",[147.1252],12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    LeaveAreaLUA("AR2000","LOAD2000",[127.1242],12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    LeaveAreaLUA("AR2000","LOAD2000",[127.1262],12)
END

