IF
  HaveSpell(WIZARD_DIMENSION_DOOR)
  Global("DID_WARP","LOCALS",0)
THEN
  RESPONSE #100
    SpellPoint([2176.1333],WIZARD_DIMENSION_DOOR)
    Wait(2)
    FaceObject(NearestEnemyOf(Myself))
    SetGlobal("DID_WARP","LOCALS",1)
    ChangeCurrentScript("LWAALPW1")
  RESPONSE #100
    SpellPoint([2262.1590],WIZARD_DIMENSION_DOOR)
    Wait(2)
    FaceObject(NearestEnemyOf(Myself))
    SetGlobal("DID_WARP","LOCALS",1)
    ChangeCurrentScript("LWAALPW3")
END

