IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    StartRandomTimer(24,5,10)
    Continue()
END

IF
  GlobalGT("BODY_COUNT","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  !TimerActive(24)
THEN
  RESPONSE #50
    FloatMessage(Myself,17914)  // ~"Yeah, this looks like a good place..."~
    StartRandomTimer(24,5,10)
    Continue()
  RESPONSE #50
    FloatMessage(Myself,17915)  // ~"Ought to tell Doogal 'bout these tracks."~
    StartRandomTimer(24,5,10)
    Continue()
  RESPONSE #50
    FloatMessage(Myself,17916)  // ~"I need a drink."~
    StartRandomTimer(24,5,10)
    Continue()
  RESPONSE #50
    FloatMessage(Myself,17917)  // ~"Emmerich better mind his own business."~
    StartRandomTimer(24,5,10)
    Continue()
  RESPONSE #50
    FloatMessage(Myself,17918)  // ~"Wonder how the boys are doin'."~
    StartRandomTimer(24,5,10)
    Continue()
  RESPONSE #300
    StartRandomTimer(24,5,10)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  See([ENEMY])
THEN
  RESPONSE #100
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),45)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",5)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",1)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",1)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,783,504,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",2)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",1)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([783.504])
    MoveToPoint([783.504])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(SE)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",3)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",5)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",4)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",4)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,853,504,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",5)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",4)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([853.504])
    MoveToPoint([853.504])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",5)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(E)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",6)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",6)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,750,401,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",7)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",6)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([750.401])
    MoveToPoint([750.401])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",7)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(NW)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",8)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",8)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",5)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",9)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",9)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,783,378,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",10)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",9)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([783.378])
    MoveToPoint([783.378])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",10)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(S)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",0)
END

