IF
  !CreatureHidden(Myself)
  IsWeaponRanged(Myself)
  Range(NearestEnemyOf(Myself),2)
THEN
  RESPONSE #100
    ForceHide(Myself)
    RunAwayFrom(NearestEnemyOf(Myself),5)
END

IF
  !Global("EMMERICH_DEAD","GLOBAL",0)
  !Dead("YSELF)")  // YSELF)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  CreatureHidden(Myself)
  Global("WEREWOLF_ACTIVE","GLOBAL",0)
  Or(2)
    !Global("LONELYWOOD_ALARM","GLOBAL",0)
    !Global("EMMERICH_OUTSIDE","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("EMMERICH_OUTSIDE","GLOBAL",1)
    Enemy()
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

IF
  HasItem("EXTHEAL",Myself)  // ~Potion of Extra Healing~
  HPPercentLT(Myself,25)
THEN
  RESPONSE #100
    UseItem("EXTHEAL",Myself)  // ~Potion of Extra Healing~
    Continue()
END

IF
  ActionListEmpty()
  !See([PC])
THEN
  RESPONSE #100
    MoveToObject([PC][0.0.10000.10000])
END

