IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    Face(NW)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    Face(N)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    Face(NW)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    Face(N)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    Face(NW)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    Face(N)
END

