IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    WaitRandom(0,1)
    FaceObject(Player2)
  RESPONSE #100
    CutSceneId(Player1)  // 
    WaitRandom(0,1)
    FaceObject(Player3)
  RESPONSE #100
    CutSceneId(Player1)  // 
    WaitRandom(0,1)
    FaceObject(Player4)
  RESPONSE #100
    CutSceneId(Player1)  // 
    WaitRandom(0,1)
    FaceObject(Player5)
  RESPONSE #100
    CutSceneId(Player1)  // 
    WaitRandom(0,1)
    FaceObject(Player6)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    WaitRandom(0,1)
    FaceObject(Player3)
  RESPONSE #100
    CutSceneId(Player2)  // 
    WaitRandom(0,1)
    FaceObject(Player4)
  RESPONSE #100
    CutSceneId(Player2)  // 
    WaitRandom(0,1)
    FaceObject(Player5)
  RESPONSE #100
    CutSceneId(Player2)  // 
    WaitRandom(0,1)
    FaceObject(Player6)
  RESPONSE #100
    CutSceneId(Player2)  // 
    WaitRandom(0,1)
    FaceObject(Player1)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    WaitRandom(0,1)
    FaceObject(Player4)
  RESPONSE #100
    CutSceneId(Player3)  // 
    WaitRandom(0,1)
    FaceObject(Player5)
  RESPONSE #100
    CutSceneId(Player3)  // 
    WaitRandom(0,1)
    FaceObject(Player6)
  RESPONSE #100
    CutSceneId(Player3)  // 
    WaitRandom(0,1)
    FaceObject(Player1)
  RESPONSE #100
    CutSceneId(Player3)  // 
    WaitRandom(0,1)
    FaceObject(Player2)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    WaitRandom(0,1)
    FaceObject(Player5)
  RESPONSE #100
    CutSceneId(Player4)  // 
    WaitRandom(0,1)
    FaceObject(Player6)
  RESPONSE #100
    CutSceneId(Player4)  // 
    WaitRandom(0,1)
    FaceObject(Player1)
  RESPONSE #100
    CutSceneId(Player4)  // 
    WaitRandom(0,1)
    FaceObject(Player2)
  RESPONSE #100
    CutSceneId(Player4)  // 
    WaitRandom(0,1)
    FaceObject(Player3)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    WaitRandom(0,1)
    FaceObject(Player6)
  RESPONSE #100
    CutSceneId(Player5)  // 
    WaitRandom(0,1)
    FaceObject(Player1)
  RESPONSE #100
    CutSceneId(Player5)  // 
    WaitRandom(0,1)
    FaceObject(Player2)
  RESPONSE #100
    CutSceneId(Player5)  // 
    WaitRandom(0,1)
    FaceObject(Player3)
  RESPONSE #100
    CutSceneId(Player5)  // 
    WaitRandom(0,1)
    FaceObject(Player4)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    WaitRandom(0,1)
    FaceObject(Player1)
  RESPONSE #100
    CutSceneId(Player6)  // 
    WaitRandom(0,1)
    FaceObject(Player2)
  RESPONSE #100
    CutSceneId(Player6)  // 
    WaitRandom(0,1)
    FaceObject(Player3)
  RESPONSE #100
    CutSceneId(Player6)  // 
    WaitRandom(0,1)
    FaceObject(Player4)
  RESPONSE #100
    CutSceneId(Player6)  // 
    WaitRandom(0,1)
    FaceObject(Player5)
END

