IF
  HaveSpell(CLERIC_HEAL)
  !Dead("YSELF)")  // YSELF)
  HPPercentLT(Myself,47)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_HEAL)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  !Dead("YSELF)")  // YSELF)
  HPPercentLT(Myself,47)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_CRITICAL_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_BLADE_BARRIER)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    ForceSpell(Myself,CLERIC_BLADE_BARRIER)
    RemoveSpell(CLERIC_BLADE_BARRIER)
    Wait(2)
END

IF
  HaveSpell(CLERIC_SLAY_LIVING)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),CLERIC_SLAY_LIVING)
    RemoveSpell(CLERIC_SLAY_LIVING)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

