IF
  !HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
THEN
  RESPONSE #100
    IncrementGlobal("ATTACK_STATE","GLOBAL",1)
    ChangeCurrentScript("")
END

IF
  !Global("FRIENDS_DEAD","LOCALS",0)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  !Dead("YSELF)")  // YSELF)
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_CRITICAL_WOUNDS)
    Wait(3)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("VAARGLAN")  // ~Robed Man~
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),50)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    Wait(3)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("ALPHEUS")  // ~Mage~
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),50)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    Wait(3)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("MERCWAR1")  // ~Mercenary Warrior~
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),50)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    Wait(3)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("MERCWAR2")  // ~Mercenary Warrior~
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),50)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    Wait(3)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("MERCTHF")  // ~Mercenary Thief~
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),50)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    Wait(3)
    Continue()
END

