IF
  Global("SET_ATTACK_PC","LOCALS",0)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetGlobal("SET_ATTACK_PC","LOCALS",1)
    Continue()
END

IF
  !Global("SET_ATTACK_PC","LOCALS",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  !Global("GIANT_1_VS_WOLVES","MYAREA",0)
  See([0.0.WOLF])
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  Global("GIANT_1_VS_WOLVES","MYAREA",0)
  See([PC])
THEN
  RESPONSE #100
    SetGlobal("GIANT_1_VS_WOLVES","MYAREA",1)
END

IF
  Global("SET_ATTACK_PC","LOCALS",0)
  !Global("GIANT_1_VS_WOLVES","MYAREA",0)
  !See([0.0.WOLF])
THEN
  RESPONSE #100
    SetGlobal("SET_ATTACK_PC","LOCALS",1)
END

