IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    StartCutSceneMode()
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    MultiPlayerSync()
    SmallWait(8)
    TakePartyItem("DNTSHD1")
    MultiPlayerSync()
    DestroyItem("DNTSHD1")  // ~Tiernon's Sundered Shield~
    MoveToPoint([3426.452])
    FadeToColor([0.0],0)
    Face(N)
    Wait(2)
    FadeFromColor([0.0],0)
    MoveToPoint([3284.614])
    Face(NW)
    SmallWait(8)
    DestroyItem("DNTSHD1")  // ~Tiernon's Sundered Shield~
    GiveItemCreate("DNTSHD2",LastTalkedToBy(Myself),1,1,1)  // ~Sundered Shield of Tiernon~
    SetGlobal("TIERNON_MAKES_SHIELD","GLOBAL",2)
    MultiPlayerSync()
    Dialogue(LastTalkedToBy(Myself))
END

