IF
  Global("MAP_GROUP_HOSTILE2","MYAREA",0)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetGlobal("MAP_GROUP_HOSTILE2","MYAREA",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  !Global("MAP_GROUP_HOSTILE2","MYAREA",0)
  GlobalTimerExpired("WOLF_BREATH","LOCALS")
  RandomNum(3,1)
  Range(NearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
    SetGlobalTimer("WOLF_BREATH","LOCALS",70)
    ForceSpell(LastSeenBy(Myself),INNATE_WINTER_WOLF_BREATH)
    Wait(2)
END

IF
  !Global("MAP_GROUP_HOSTILE2","MYAREA",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  See([0.0.GIANT])
  !Global("GIANT_1_VS_WOLVES","MYAREA",0)
  GlobalTimerExpired("WOLF_BREATH","LOCALS")
  RandomNum(5,1)
THEN
  RESPONSE #100
    SetGlobalTimer("WOLF_BREATH","LOCALS",70)
    ForceSpell(LastSeenBy(Myself),INNATE_WINTER_WOLF_BREATH)
    Wait(2)
END

IF
  !Global("GIANT_1_VS_WOLVES","MYAREA",0)
  See([0.0.GIANT])
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  Global("MAP_GROUP_HOSTILE2","MYAREA",0)
  !Global("GIANT_1_VS_WOLVES","MYAREA",0)
  !See([0.0.GIANT])
THEN
  RESPONSE #100
    SetGlobal("MAP_GROUP_HOSTILE2","MYAREA",1)
END

