IF
  Clicked([ANYTHING])
  PartyHasItem("PIECE1")  // ~Piece of broken machinery~
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    TakePartyItem("PIECE1")
    IncrementGlobal("ASTROLAB","GLOBAL",1)
    AddXPVar("LEVEL_6_AVERAGE",9236)  // ~You combine your piece of machinery with this part of the astrolabe.~
    Deactivate(Myself)
END

IF
  Unlocked([ANYTHING])
  PartyHasItem("PIECE1")  // ~Piece of broken machinery~
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    TakePartyItem("PIECE1")
    IncrementGlobal("ASTROLAB","GLOBAL",1)
    AddXPVar("LEVEL_6_AVERAGE",9236)  // ~You combine your piece of machinery with this part of the astrolabe.~
    Deactivate(Myself)
END

