IF
  BitGlobal("MYAREA:AREA_GROUP_VAR","",1,AND)
THEN
  RESPONSE #100
    FloatMessage(Myself,17227)  // ~"Invaders!"~
    ChangeCurrentScript("")
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    StartTimer(24,4)
    Continue()
END

IF
  !TimerActive(24)
THEN
  RESPONSE #100
    FloatMessage(Myself,17223)  // ~"The teachings show us the way."~
    StartTimer(24,4)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,17225)  // ~"Offer praise."~
    StartTimer(24,4)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,17226)  // ~"Let us pray."~
    StartTimer(24,4)
    Continue()
END

