IF
  CreatureHidden(Myself)
  BitGlobal("MYAREA:AREA_VAR","",32,AND)
THEN
  RESPONSE #100
    Enemy()
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    HideCreature(Myself,TRUE)
    Continue()
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  ActionListEmpty()
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  ActionListEmpty()
  !TargetUnreachable([PC])
THEN
  RESPONSE #100
    MoveToObject([PC])
END

