IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",256,AND)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",256,OR)
    BitGlobal("MYAREA:AREA_VAR","",32,OR)
    FloatMessage(Myself,11733)  // ~"You will not make it past here, invaders!"~
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  !Dead("YSELF)")  // YSELF)
  HPPercentLT(Myself,60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(NearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(SecondNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(ThirdNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(FourthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(FifthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(SixthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(SeventhNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(EigthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(NinthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(TenthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See([ENEMY])
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  !Dead("YSELF)")  // YSELF)
  HPPercentLT(Myself,60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(NearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(SecondNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(ThirdNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(FourthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(FifthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(SixthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(SeventhNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(EigthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(NinthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(TenthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See([ENEMY])
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",1)
    Spell(Myself,CLERIC_CLOAK_OF_FEAR)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",1)
    Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",1)
    Spell(Myself,CLERIC_RECITATION)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",2)
    Spell(Myself,CLERIC_PRAYER)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",2)
    Spell(Myself,CLERIC_STRENGTH_OF_ONE)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",2)
    Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",3)
    Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",3)
    Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",3)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",4)
    Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_RADIUS)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",4)
    Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",4)
    Spell(LastSeenBy(Myself),CLERIC_CHANT)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",4)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",5)
    Spell(LastSeenBy(Myself),CLERIC_ENTANGLE)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",5)
    Spell(LastSeenBy(Myself),CLERIC_CURSE)
    Wait(2)
END

IF
  Global("SPELL_PHASE","LOCALS",5)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    FaceObject(LastAttackerOf(Myself))
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

