IF
  BitGlobal("MYAREA:AREA_VAR","",2,AND)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  BitGlobal("MYAREA:AREA_VAR","",2,AND)
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,XOR)
  !BitGlobal("MYAREA:AREA_VAR","",2,AND)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetSavedLocationPoint(973,1141,S)
    SetStartPos([973.1141])
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,OR)
    FloatMessage(Myself,14334)  // ~"HELP!"~
    ReturnToSavedLocation()
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,XOR)
  !BitGlobal("MYAREA:AREA_VAR","",2,AND)
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    SetSavedLocationPoint(973,1141,S)
    SetStartPos([973.1141])
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,OR)
    FloatMessage(Myself,14334)  // ~"HELP!"~
    ReturnToSavedLocation()
END

IF
  BitGlobal("MYAREA:AREA_VAR","",2,AND)
  ActionListEmpty()
  !See([PC])
  !TargetUnreachable([PC])
THEN
  RESPONSE #100
    MoveToObject([PC])
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
  NearSavedLocation(0)
THEN
  RESPONSE #100
    BitGlobal("MYAREA:AREA_VAR","",2,OR)
END

IF
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",4,AND)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

