IF
  IsWeaponRanged(Myself)
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),5)
THEN
  RESPONSE #100
    RunAwayFrom(LastSeenBy(Myself),45)
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",0)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",10)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",1)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",1)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,553,542,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",2)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",1)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([553.542])
    MoveToPoint([553.542])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(NW)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",3)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,333,375,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",4)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",3)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([333.375])
    MoveToPoint([333.375])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",4)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(W)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",5)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",5)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,258,376,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",6)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",5)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([258.376])
    MoveToPoint([258.376])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",6)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(NW)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",7)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",7)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",10)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",8)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",8)
  !NearSavedLocation(2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",8)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",9)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",9)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",10)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",10)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",10)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",11)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",11)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(E)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",12)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",12)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,750,541,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",13)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",12)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([750.541])
    MoveToPoint([750.541])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",13)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(NE)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",14)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",14)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,807,489,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",15)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",14)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([807.489])
    MoveToPoint([807.489])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",15)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(S)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",16)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",16)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,808,710,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",17)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",16)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([808.710])
    MoveToPoint([808.710])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",17)
  !NearSavedLocation(2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",17)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",18)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",18)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",19)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",19)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MOVEMENT_LIST_0_TIMER","LOCALS",10)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",20)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",20)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(W)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",21)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",21)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,350,562,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",22)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",21)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([350.562])
    MoveToPoint([350.562])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",22)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    Face(SE)
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",23)
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",23)
  BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,AND)
  NearLocation(Myself,610,827,8)
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",24)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,XOR)
    Continue()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",23)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",524288,OR)
    SetStartPos([610.827])
    MoveToPoint([610.827])
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",24)
  !NearSavedLocation(2)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  Global("MOVEMENT_LIST_0_LOC","LOCALS",24)
  ActionListEmpty()
  GlobalTimerExpired("MOVEMENT_LIST_0_TIMER","LOCALS")
THEN
  RESPONSE #100
    SetGlobal("MOVEMENT_LIST_0_LOC","LOCALS",0)
    Continue()
END

