IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    LeaveAreaLUA("AR2100","LOAD2100",[2328.1816],12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    LeaveAreaLUA("AR2100","LOAD2100",[2393.1889],10)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    LeaveAreaLUA("AR2100","LOAD2100",[2232.1848],12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    LeaveAreaLUA("AR2100","LOAD2100",[2352.1953],10)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    LeaveAreaLUA("AR2100","LOAD2100",[2249.1916],10)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    LeaveAreaLUA("AR2100","LOAD2100",[2294.1955],10)
END

