IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    StartCutSceneMode()
    MultiPlayerSync()
    ClearAllActions()
    MultiPlayerSync()
    HideGUI()
    MultiPlayerSync()
    MoveViewPoint([705.451],VERY_FAST)
    Wait(3)
    SetVisualRange(30)
    MoveToPoint([751.523])
    Wait(3)
    FloatMessage(Myself,18268)  // ~"A dwarf dares to set foot here!"~
    Wait(4)
    FloatMessage(Myself,18269)  // ~"Have you come to push the dagger further into our backs!"~
    Wait(3)
    FloatMessage(Myself,18271)  // ~"Speak for yourself!"~
    Wait(2)
    FloatMessage("SQUIRREL",18270)  // ~...~
    Wait(2)
    FloatMessage(Myself,18272)  // ~"Do you deny the destruction wrought by your treacherous kind!"~
    Wait(2)
    FloatMessage("SQUIRREL",18270)  // ~...~
    Wait(3)
    FloatMessage(Myself,18276)  // ~"I will not tolerate your filthy presence anymore!"~
    ActionOverride("SQUIRREL",MoveToPoint([1223.599]))
    MoveViewObject("SQUIRREL",VERY_FAST)
    Wait(2)
    ForceSpellPoint([1033.582],WIZARD_FIREBALL)
    MoveViewObject("SQUIRREL",VERY_FAST)
    Wait(2)
    ActionOverride("SQUIRREL",MoveToPoint([1223.599]))
    Wait(2)
    MoveViewObject(Myself,VERY_FAST)
    Wait(2)
    FloatMessage(Myself,18277)  // ~"Wretched thing."~
    MoveToPoint([610.333])
    SetVisualRange(0)
    Wait(2)
    ActionOverride("SQUIRREL",MoveToPoint([1223.599]))
    Wait(1)
    MoveViewPoint([969.785],FAST)
    MoveToPoint([471.339])
    HideCreature("SQUIRREL",TRUE)
    MultiPlayerSync()
    HideCreature(Myself,TRUE)
    UnhideGUI()
    MultiPlayerSync()
    EndCutSceneMode()
    DestroySelf()
END

