IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    Continue()
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,AND)
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #90
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,OR)
    FloatMessage(Myself,17998)  // ~"Zug Zug."~
    Continue()
  RESPONSE #90
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,OR)
    FloatMessage(Myself,18045)  // ~*Rrraaaarrrrr*~
    Continue()
  RESPONSE #90
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,OR)
    FloatMessage(Myself,18046)  // ~"Smash!"~
    Continue()
  RESPONSE #90
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,OR)
    FloatMessage(Myself,18047)  // ~"Crush!"~
    Continue()
  RESPONSE #90
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,OR)
    FloatMessage(Myself,18048)  // ~"Kill dem!"~
    Continue()
  RESPONSE #60
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,OR)
    Continue()
END

