IF
  BitGlobal("MYAREA:AREA_GROUP_VAR","",1,AND)
THEN
  RESPONSE #100
    FloatMessage(Myself,17228)  // ~"We are under attack!"~
    ChangeCurrentScript("")
END

IF
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",1,OR)
    StartTimer(24,4)
    Continue()
END

IF
  !TimerActive(24)
THEN
  RESPONSE #100
    FloatMessage(Myself,17347)  // ~"The attack will commence here."~
    StartTimer(24,4)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,17349)  // ~"Our forces will lie in wait here."~
    StartTimer(24,4)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,17350)  // ~"They will charge from this point."~
    StartTimer(24,4)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,17351)  // ~"They will come from the rear here."~
    StartTimer(24,4)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,17353)  // ~"The archers will support from this point."~
    StartTimer(24,4)
    Continue()
END

