IF
  HaveSpell(WIZARD_LARLOCHS_MINOR_DRAIN)
  See(NearestEnemyOf(Myself))
  HPPercentLT(Myself,100)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_LARLOCHS_MINOR_DRAIN)
    Wait(2)
END

IF
  HPPercentLT(Myself,100)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  HPPercentLT(Myself,100)
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  ActionListEmpty()
  !NearSavedLocation(36)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    RandomWalk()
END

IF
  True()
THEN
  RESPONSE #100
    MoveToObject([ENEMY])
END

