IF
  Global("SPELL_PHASE","LOCALS",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",1)
    Spell(NearestEnemyOf(Myself),WIZARD_SLOW)
    Wait(2)
    Continue()
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",1)
    Spell([ENEMY],WIZARD_HASTE)
    Wait(2)
    Continue()
END

IF
  Global("SPELL_PHASE","LOCALS",2)
  Global("PRE_BUFF","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",3)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  !Dead("YSELF)")  // YSELF)
  HPPercentLT(Myself,60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(NearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(SecondNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(ThirdNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(FourthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(FifthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(SixthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(SeventhNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(EigthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(NinthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See(TenthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See([ENEMY])
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  !Dead("YSELF)")  // YSELF)
  HPPercentLT(Myself,60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(NearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(SecondNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(ThirdNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(FourthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(FifthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(SixthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(SeventhNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(EigthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(NinthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See(TenthNearestEnemyOf(NearestEnemyOf(Myself)))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  See([ENEMY])
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  HPPercentLT(LastSeenBy(Myself),60)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    Wait(2)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",2)
    Spell(LastSeenBy(Myself),WIZARD_ICE_STORM)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",2)
    Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",2)
    Spell(LastSeenBy(Myself),WIZARD_BELTYNS_BURNING_BLOOD)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",3)
    Spell(Myself,WIZARD_ARMOR)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",3)
    Spell(Myself,WIZARD_SHIELD)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",3)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",4)
    Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",4)
    Spell(LastSeenBy(Myself),WIZARD_WEB)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",4)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",5)
    Spell(LastSeenBy(Myself),WIZARD_ICELANCE)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",5)
    Spell(LastSeenBy(Myself),WIZARD_DIRE_CHARM)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",5)
    Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",5)
    Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",5)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_GREASE)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_CHARM_PERSON)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",6)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",7)
    Spell(LastSeenBy(Myself),WIZARD_GHOUL_TOUCH)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",7)
    Spell(LastSeenBy(Myself),WIZARD_HORROR)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",7)
    Spell(LastSeenBy(Myself),WIZARD_MELFS_ACID_ARROW)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",7)
    Spell(LastSeenBy(Myself),WIZARD_SNILLOCS_SNOWBALL_SWARM)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",7)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",8)
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",8)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",9)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SPELL_PHASE","LOCALS",9)
THEN
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",10)
    Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
    Wait(2)
  RESPONSE #100
    SetGlobal("SPELL_PHASE","LOCALS",10)
    Spell(LastSeenBy(Myself),WIZARD_LARLOCHS_MINOR_DRAIN)
    Wait(2)
END

IF
  Global("SPELL_PHASE","LOCALS",10)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  ActionListEmpty()
  NearSavedLocation(60)
THEN
  RESPONSE #100
    ReturnToSavedLocation()
END

IF
  ActionListEmpty()
  !NearSavedLocation(60)
THEN
  RESPONSE #100
    RandomWalk()
    WaitRandom(5,15)
END

