IF
  CreatureHidden(Myself)
  PartyHasItem("FKEY")  // ~Forge Key~
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

