IF
  HaveSpell(WIZARD_MIRROR_IMAGE)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    Wait(2)
END

IF
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
    Wait(2)
END

IF
  HaveSpell(WIZARD_EMOTION_COURAGE)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SpellPoint([2125.1863],WIZARD_EMOTION_COURAGE)
END

IF
  HaveSpell(WIZARD_DIMENSION_DOOR)
  Or(5)
    See(SixthNearestEnemyOf(Myself))
    See(FifthNearestEnemyOf(Myself))
    See(FourthNearestEnemyOf(Myself))
    See(ThirdNearestEnemyOf(Myself))
    See(SecondNearestEnemyOf(Myself))
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,AND)
  RandomNum(6,1)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,OR)
    Spell(LastSeenBy(Myself),WIZARD_DIMENSION_DOOR)
    Wait(2)
END

IF
  HaveSpell(WIZARD_DIMENSION_DOOR)
  See(NearestEnemyOf(Myself))
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,OR)
    Spell(LastSeenBy(Myself),WIZARD_DIMENSION_DOOR)
    Wait(2)
END

IF
  HaveSpell(WIZARD_BELTYNS_BURNING_BLOOD)
  Or(10)
    See(NearestEnemyOf(Myself))
    See([PC.0.0.CLERIC_RANGER])
    See([PC.0.0.FIGHTER_MAGE_CLERIC])
    See([PC.0.0.DRUID])
    See([PC.0.0.FIGHTER_MAGE_THIEF])
    See([PC.0.0.FIGHTER_CLERIC])
    See([PC.0.0.FIGHTER_MAGE])
    See([PC.0.0.CLERIC_MAGE])
    See([PC.0.0.CLERIC])
    See([PC.0.0.MAGE])
  !BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,AND)
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",512,OR)
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,XOR)
    Spell(LastSeenBy(Myself),WIZARD_BELTYNS_BURNING_BLOOD)
    Wait(2)
END

IF
  True()
THEN
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",0)
    Continue()
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",1)
    Continue()
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",2)
    Continue()
  RESPONSE #100
    SetGlobal("LOCAL_CAST_SPELL","LOCALS",3)
    Continue()
END

IF
  HaveSpell(WIZARD_MELFS_ACID_ARROW)
  GlobalLT("LOCAL_CAST_SPELL","LOCALS",1)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,XOR)
    Spell(LastSeenBy(Myself),WIZARD_MELFS_ACID_ARROW)
    Wait(2)
END

IF
  HaveSpell(WIZARD_BELTYNS_BURNING_BLOOD)
  GlobalLT("LOCAL_CAST_SPELL","LOCALS",2)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,XOR)
    Spell(LastSeenBy(Myself),WIZARD_BELTYNS_BURNING_BLOOD)
    Wait(2)
END

IF
  HaveSpell(WIZARD_MAGIC_MISSILE)
  GlobalLT("LOCAL_CAST_SPELL","LOCALS",3)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,XOR)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    Wait(2)
END

IF
  HaveSpell(WIZARD_FLAME_ARROW)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,XOR)
    Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    Wait(2)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    BitGlobal("LOCALS:CREATURE_STATE_VAR","",8,XOR)
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    FaceObject(LastAttackerOf(Myself))
    Continue()
END

