IF
  Global("UD_SCOUT_2_MOVED","GLOBAL",0)
  See([PC])
THEN
  RESPONSE #100
    IncrementGlobal("UD_SCOUT_2_MOVED","GLOBAL",1)
    MoveToPoint([1981.1754])
    Face(SE)
END

IF
  Global("UD_SCOUT_2_MOVED","GLOBAL",0)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    IncrementGlobal("UD_SCOUT_2_MOVED","GLOBAL",1)
    MoveToPoint([1981.1754])
    Face(SE)
END

IF
  See([PC])
THEN
  RESPONSE #100
    SetBestWeapon(LastSeenBy(Myself),4)
    Help()
    Attack(LastSeenBy(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetBestWeapon(LastAttackerOf(Myself),4)
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Internal(Myself,0,1)
  Help([ANYONE])
THEN
  RESPONSE #100
END

