IF
  See([PC])
THEN
  RESPONSE #100
    SetBestWeapon(LastSeenBy(Myself),4)
    Help()
    Attack(LastSeenBy(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetBestWeapon(LastAttackerOf(Myself),4)
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Or(2)
    See([ANYONE])
    See([ANYONE])
THEN
  RESPONSE #100
    SetBestWeapon(LastSeenBy(Myself),4)
    Help()
    Attack(LastSeenBy(Myself))
END

IF
  Or(2)
    AttackedBy([ANYONE],DEFAULT)
    AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    SetBestWeapon(LastAttackerOf(Myself),4)
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([ANYONE])
THEN
  RESPONSE #100
END

