IF
  !Global("SLAVES_FREE_1","GLOBAL",0)
THEN
  RESPONSE #100
    Unlock(Myself)
    Continue()
END

IF
  Global("SLAVE_DOOR_STATE","MYAREA",0)
  Global("7002_7005_DOOR_STATE","GLOBAL",1)
THEN
  RESPONSE #100
    Unlock(Myself)
    OpenDoor(Myself)
    SetGlobal("SLAVE_DOOR_STATE","MYAREA",1)
    Continue()
END

IF
  Global("SLAVE_DOOR_STATE","MYAREA",1)
  Global("7002_7005_DOOR_STATE","GLOBAL",0)
THEN
  RESPONSE #100
    CloseDoor(Myself)
    SetGlobal("SLAVE_DOOR_STATE","MYAREA",0)
    Continue()
END

IF
  Opened([ANYTHING])
THEN
  RESPONSE #100
    SetGlobal("7002_7005_DOOR_STATE","GLOBAL",1)
    SetGlobal("SLAVE_DOOR_STATE","MYAREA",1)
END

IF
  Unlocked([ANYTHING])
THEN
  RESPONSE #100
    SetGlobal("7002_7005_DOOR_STATE","GLOBAL",1)
    SetGlobal("SLAVE_DOOR_STATE","MYAREA",1)
END

IF
  True()
THEN
  RESPONSE #100
    NoAction()
END

