IF
  Opened([ANYTHING])
  Global("7002_7005_DOOR_STATE","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("7002_7005_DOOR_STATE","GLOBAL",1)
END

IF
  Unlocked([ANYTHING])
  Global("7002_7005_DOOR_STATE","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("7002_7005_DOOR_STATE","GLOBAL",1)
END

IF
  Global("7002_7005_DOOR_STATE","GLOBAL",1)
THEN
  RESPONSE #100
    Unlock(Myself)
    OpenDoor(Myself)
    Continue()
END

IF
  True()
THEN
  RESPONSE #100
    NoAction()
END

