IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    LeaveAreaLUA("AR7005","LOAD7000",[1981.1550],0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    LeaveAreaLUA("AR7005","LOAD7000",[1895.1568],0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    LeaveAreaLUA("AR7005","LOAD7000",[2068.1556],0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    LeaveAreaLUA("AR7005","LOAD7000",[2068.1486],0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    LeaveAreaLUA("AR7005","LOAD7000",[1979.1486],0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    LeaveAreaLUA("AR7005","LOAD7000",[1901.1494],0)
END

