IF
  Or(2)
    See(NearestEnemyOf(Myself))
    See([ALLY])
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),75)
END

IF
  Or(2)
    AttackedBy(NearestEnemyOf(Myself),DEFAULT)
    AttackedBy([ALLY],DEFAULT)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
END

IF
  See([PC])
THEN
  RESPONSE #100
    BitGlobal("MYAREA:AREA_VAR","",32,OR)
    Enemy()
    Continue()
END

IF
  BitGlobal("MYAREA:AREA_VAR","",32,AND)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

