IF
  Global("Current_Area","GLOBAL",100)
THEN
  RESPONSE #100
    ChangeAIScript("0100nt",GENERAL)
END

IF
  Global("Current_Area","GLOBAL",200)
THEN
  RESPONSE #100
    ChangeAIScript("0200nt",GENERAL)
END

IF
  Global("Current_Area","GLOBAL",300)
THEN
  RESPONSE #100
    ChangeAIScript("0300nt",GENERAL)
END

IF
  Global("Current_Area","GLOBAL",300)
THEN
  RESPONSE #100
    ChangeAIScript("0400nt",GENERAL)
END

