IF
  OnCreation()
  Allegiance(Myself,FAMILIAR)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,FAMILIAR)
    StartTimer(1,120)
END

IF
  !TimerActive(1)
THEN
  RESPONSE #100
    StickySinisterPoof("S113SMOK",Myself,1)
    Wait(1)
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  Help([PC])
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    ProtectObject([PC],60)
END

