IF
  GlobalLT("Collective_Rats_Spawned","AR1601",30)
  Specifics(Myself,MRAT_1)
  BitCheck("Collective_Status","AR1601",BIT1)
THEN
  RESPONSE #100
    CreateCreature("Rat",[861.1174])  // ~Cranium Rat~
    IncrementGlobal("Collective_Rats_Spawned","AR1601",1)
END

IF
  GlobalLT("Collective_Rats_Spawned","AR1601",30)
  Specifics(Myself,MRAT_1)
  BitCheck("Collective_Status","AR1601",BIT2)
THEN
  RESPONSE #100
    CreateCreature("Rat",[861.1174])  // ~Cranium Rat~
    IncrementGlobal("Collective_Rats_Spawned","AR1601",1)
END

IF
  GlobalLT("Collective_Rats_Spawned","AR1601",30)
  Specifics(Myself,MRAT_1)
  BitCheck("Collective_Status","AR1601",BIT3)
THEN
  RESPONSE #100
    CreateCreature("Rat",[861.1174])  // ~Cranium Rat~
    IncrementGlobal("Collective_Rats_Spawned","AR1601",1)
END

IF
  GlobalLT("Collective_Rats_Spawned","AR1601",30)
  Specifics(Myself,MRAT_1)
  BitCheck("Collective_Status","AR1601",BIT4)
THEN
  RESPONSE #100
    CreateCreature("Rat",[861.1174])  // ~Cranium Rat~
    IncrementGlobal("Collective_Rats_Spawned","AR1601",1)
END

