IF
  Die()
THEN
  RESPONSE #100
    GlobalSet("DemonBox","GLOBAL",3)
END

IF
  OnCreation()
THEN
  RESPONSE #100
    Face(2)
END

IF
  See([PC])
  Global("Demon_Gate","AR0800",0)
THEN
  RESPONSE #100
    Enemy()
    MoveToObjectEx([PC],0)
    GlobalSet("Demon_Gate","AR0800",1)
    Attack([PC])
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  See([PC])
THEN
  RESPONSE #100
    Enemy()
    Attack([PC])
END

