IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.DUSTMAN])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(30,40)
    MoveToPoint([658.1688])
    MoveToPoint([838.1508])
    MoveToPoint([1605.1508])
    MoveToPoint([1730.1384])
    MoveToPoint([2078.1384])
    MoveToPoint([2360.1103])
    Face(4)
    ChangeAIScript("0100dm1a",GENERAL)
END

