IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(30,40)
    MoveToPoint([565.1395])
    MoveToPoint([950.1012])
    MoveToPoint([1229.1012])
    MoveToPoint([1421.819])
    MoveToPoint([1506.819])
    MoveToPoint([1708.617])
    MoveToPoint([1805.617])
    MoveToPoint([2132.943])
    MoveToPoint([2560.943])
    Face(4)
    ChangeAIScript("0100tm3a",GENERAL)
END

