IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(30,40)
    Face(4)
    MoveToPoint([2169.1708])
    MoveToPoint([2061.1821])
    MoveToPoint([1895.1821])
    MoveToPoint([1764.1954])
    MoveToPoint([1764.2199])
    MoveToPoint([1565.2398])
    MoveToPoint([777.2398])
    MoveToPoint([562.2296])
    MoveToPoint([469.2055])
    MoveToPoint([365.1737])
    MoveToPoint([302.1483])
    MoveToPoint([468.1324])
    MoveToPoint([676.1177])
    MoveToPoint([873.1059])
    MoveToPoint([1089.952])
    MoveToPoint([1319.859])
    MoveToPoint([1395.846])
    MoveToPoint([1432.828])
    MoveToPoint([1451.796])
    MoveToPoint([1451.764])
    MoveToPoint([1355.668])
    MoveToPoint([1309.715])
    Face(4)
    WaitRandom(10,12)
    Face(2)
    WaitRandom(10,12)
    MoveToPoint([1424.631])
    Face(12)
    WaitRandom(10,12)
    MoveToPoint([1355.668])
    MoveToPoint([1451.764])
    MoveToPoint([1451.796])
    MoveToPoint([1432.828])
    MoveToPoint([1395.846])
    MoveToPoint([1319.859])
    MoveToPoint([1089.952])
    MoveToPoint([873.1059])
    MoveToPoint([676.1177])
    MoveToPoint([468.1324])
    MoveToPoint([302.1483])
    MoveToPoint([365.1737])
    MoveToPoint([469.2055])
    MoveToPoint([562.2296])
    MoveToPoint([777.2398])
    MoveToPoint([1565.2398])
    MoveToPoint([1764.2199])
    MoveToPoint([1764.1954])
    MoveToPoint([1895.1821])
    MoveToPoint([2061.1821])
    MoveToPoint([2169.1708])
    MoveToPoint([2687.1590])
END

