IF
  HarmlessEntered("Nordom")  // ~Modron~
THEN
  RESPONSE #100
    VerbalConstant("Nordom",NORDOM_PORTAL)
    Continue()
END

IF
  HarmlessOpened([PC])
  !Dead("Vlask")  // ~Vlask~
THEN
  RESPONSE #100
    ActivatePortalCursor("to3006a",1)
    EnablePortalTravel("to3006a",1)
END

IF
  HarmlessClosed([PC])
THEN
  RESPONSE #100
    ActivatePortalCursor("to3006a",0)
    EnablePortalTravel("to3006a",0)
END

