IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Nameless")  // 
    Wait(3)
    FloatMessage(Myself,51408)  // ~"I'd better break the lock."~
    Wait(1)
    TimedMoveToPoint([1653.1469],45)
    Face(6)
    PlaySequence(ANIM_ATTACK)
    ActivatePortalCursor("to3006a",0)
    EnablePortalTravel("to3006a",0)
    SetDoorLocked("AR0101d2",TRUE)
    Wait(1)
    FloatMessage(Myself,51407)  // ~"That should keep anyone else from entering."~
    EndCutSceneMode()
END

