IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    Face(4)
    WaitRandom(10,12)
    Face(2)
    WaitRandom(10,12)
    Face(4)
    WaitRandom(10,12)
    Face(6)
    WaitRandom(10,12)
    MoveToPoint([957.1707])
    Face(10)
    WaitRandom(10,12)
    MoveToPoint([957.1759])
    MoveToPoint([1024.1825])
    MoveToPoint([1092.1825])
    MoveToPoint([1159.1758])
    Face(10)
    WaitRandom(10,12)
    Face(8)
    WaitRandom(10,12)
    Face(10)
    WaitRandom(10,12)
    Face(12)
    WaitRandom(10,12)
    MoveToPoint([1092.1825])
    MoveToPoint([1092.2008])
    Face(0)
    WaitRandom(10,12)
    Face(14)
    WaitRandom(10,12)
    Face(0)
    WaitRandom(10,12)
    Face(2)
    WaitRandom(10,12)
    MoveToPoint([1092.1825])
    MoveToPoint([1159.1758])
    Face(10)
    WaitRandom(10,12)
    Face(8)
    WaitRandom(10,12)
    Face(10)
    WaitRandom(10,12)
    Face(12)
    WaitRandom(10,12)
    MoveToPoint([1092.1825])
    MoveToPoint([1024.1825])
    MoveToPoint([957.1759])
    MoveToPoint([899.1707])
END

