IF
  Die()
THEN
  RESPONSE #100
END

IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  See([PC])
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack([PC])
END

IF
  Help([ANYONE])
THEN
  RESPONSE #100
    Enemy()
    Attack(NearestEnemyOf(LastHelp))
END

