IF
  Die()
THEN
  RESPONSE #100
END

IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Global("Bum_Rushd","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
    Attack(Protagonist)
END

IF
  Help([ANYONE])
THEN
  RESPONSE #100
    Enemy()
    Attack(NearestEnemyOf(LastHelp))
END

