IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,HOSTILE_THUG)
END

IF
  Allegiance(Myself,ENEMY)
  Internal(Myself,INTERNAL_0,0)
THEN
  RESPONSE #100
    SetInternal(Myself,INTERNAL_0,1)
    Continue()
END

IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("Buried_Attack","GLOBAL",1)
    Enemy()
    SetInternal(Myself,INTERNAL_0,1)
    Attack(LastAttackerOf(Myself))
END

IF
  Internal([0.0.0.0.0.0.HOSTILE_THUG][0.0.10000.10000],INTERNAL_0,1)
THEN
  RESPONSE #100
    Enemy()
    SetInternal(Myself,INTERNAL_0,1)
    Attack(NearestEnemyOf(Myself))
END

