IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    Help()
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("Buried_Attack","GLOBAL",1)
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.0.0.0.0.THUG_2])
THEN
  RESPONSE #100
    Enemy()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  Help([0.0.0.0.0.0.THUG_3])
THEN
  RESPONSE #100
    Enemy()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  !Allegiance(Myself,ENEMY)
  Global("Thug1_Move","AR0109",1)
THEN
  RESPONSE #100
    GlobalSet("Thug1_Move","AR0109",0)
    Face(12)
    RunToPoint([2021.1151])
    Face(10)
    Wait(3)
    Face(4)
    MoveToPoint([1895.1226])
    Face(14)
END

IF
  !Allegiance(Myself,ENEMY)
  Global("Thug1_Move","AR0109",0)
  Global("Thug2_Move","AR0109",0)
  Global("Thug3_Move","AR0109",0)
THEN
  RESPONSE #100
    FloatMessage(Myself,27426)  // ~"Still have enough copper on ya?"~
    Wait(2)
    KillFloatMessage(Myself)
    FloatMessage([0.0.0.0.0.0.THUG_2],27425)  // ~"I have enough jink to take all of yours!"~
    Wait(2)
    KillFloatMessage([0.0.0.0.0.0.THUG_2])
    FloatMessage([0.0.0.0.0.0.THUG_3],27437)  // ~"Shut yer traps and roll the bleedin' dice!"~
    Wait(3)
    GlobalSet("Thug2_Move","AR0109",1)
    GlobalSet("Thug3_Move","AR0109",1)
    GlobalSet("Thug1_Move","AR0109",1)
  RESPONSE #100
    FloatMessage(Myself,27427)  // ~"An unbelievable roll!  I think our friend might have something else involved here..."~
    Wait(2)
    KillFloatMessage(Myself)
    FloatMessage([0.0.0.0.0.0.THUG_2],27448)  // ~"Are you inferring that I cheat?  You're just jealous because of your continued bad luck!"~
    Wait(2)
    KillFloatMessage([0.0.0.0.0.0.THUG_2])
    FloatMessage([0.0.0.0.0.0.THUG_3],27437)  // ~"Shut yer traps and roll the bleedin' dice!"~
    Wait(3)
    GlobalSet("Thug2_Move","AR0109",1)
    GlobalSet("Thug3_Move","AR0109",1)
    GlobalSet("Thug1_Move","AR0109",1)
  RESPONSE #100
    FloatMessage(Myself,27429)  // ~"See?  Now THAT'S a roll my friend!"~
    Wait(2)
    KillFloatMessage(Myself)
    FloatMessage([0.0.0.0.0.0.THUG_2],27611)  // ~"Oh come on now!  I could have rolled that nine times in my sleep!"~
    Wait(2)
    KillFloatMessage([0.0.0.0.0.0.THUG_2])
    FloatMessage([0.0.0.0.0.0.THUG_3],27437)  // ~"Shut yer traps and roll the bleedin' dice!"~
    Wait(3)
    GlobalSet("Thug2_Move","AR0109",1)
    GlobalSet("Thug3_Move","AR0109",1)
    GlobalSet("Thug1_Move","AR0109",1)
  RESPONSE #100
    FloatMessage(Myself,27442)  // ~"Amazing."~
    Wait(2)
    KillFloatMessage(Myself)
    FloatMessage([0.0.0.0.0.0.THUG_2],27430)  // ~"What incredible luck!"~
    Wait(2)
    KillFloatMessage([0.0.0.0.0.0.THUG_2])
    FloatMessage([0.0.0.0.0.0.THUG_3],27446)  // ~"Luck is merely ONE of my skills!"~
    Wait(2)
    KillFloatMessage([0.0.0.0.0.0.THUG_3])
    FloatMessage(Myself,27449)  // ~"Will ya just roll the damn dice?!"~
    Wait(3)
    GlobalSet("Thug2_Move","AR0109",1)
    GlobalSet("Thug3_Move","AR0109",1)
    GlobalSet("Thug1_Move","AR0109",1)
  RESPONSE #100
    FloatMessage(Myself,27424)  // ~"Ummm...I...well...errr double or nothing!"~
    Wait(2)
    KillFloatMessage(Myself)
    FloatMessage([0.0.0.0.0.0.THUG_2],27618)  // ~"Well now!  Are you sure that YOU have enough copper?  Hahaha!"~
    Wait(2)
    KillFloatMessage([0.0.0.0.0.0.THUG_2])
    FloatMessage([0.0.0.0.0.0.THUG_3],27437)  // ~"Shut yer traps and roll the bleedin' dice!"~
    Wait(3)
    GlobalSet("Thug2_Move","AR0109",1)
    GlobalSet("Thug3_Move","AR0109",1)
    GlobalSet("Thug1_Move","AR0109",1)
END

