IF
  Die()
THEN
  RESPONSE #100
END

IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("BV_Enemy","GLOBAL",1)
    Enemy()
END

IF
  Global("Pharod_talk","GLOBAL",1)
THEN
  RESPONSE #33
    WaitRandom(3,5)
    FloatMessage(Myself,19237)  // ~"Aye...what am I gonna do with Annah?"~
    GlobalSet("Pharod_talk","GLOBAL",0)
  RESPONSE #33
    WaitRandom(3,5)
    FloatMessage(Myself,19236)  // ~"The Dusties be paying a pretty piece of jink for this delivery."~
    GlobalSet("Pharod_talk","GLOBAL",0)
  RESPONSE #33
    WaitRandom(3,5)
    FloatMessage(Myself,19235)  // ~"Gotta get more bodies from the catacombs."~
    GlobalSet("Pharod_talk","GLOBAL",0)
  RESPONSE #901
    WaitRandom(3,5)
    GlobalSet("Pharod_talk","GLOBAL",0)
END

IF
  Global("Pharod_pattern","GLOBAL",0)
THEN
  RESPONSE #100
    Face(0)
    MoveToPoint([1635.1189])
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",1)
THEN
  RESPONSE #100
    Face(2)
    MoveToPoint([1554.1260])
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",2)
THEN
  RESPONSE #100
    Face(4)
    MoveToPoint([1266.1260])
    Face(8)
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",3)
THEN
  RESPONSE #100
    MoveToPoint([1257.1081])
    Face(2)
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",4)
THEN
  RESPONSE #100
    Face(0)
    MoveToPoint([1635.1189])
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",5)
THEN
  RESPONSE #100
    MoveToPoint([1118.1216])
    Face(6)
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",6)
THEN
  RESPONSE #100
    MoveToPoint([916.1018])
    Face(10)
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",7)
THEN
  RESPONSE #100
    Face(6)
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",8)
THEN
  RESPONSE #100
    Face(2)
    MoveToPoint([740.1193])
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",9)
THEN
  RESPONSE #100
    Face(10)
    MoveToPoint([916.1018])
    Face(14)
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",10)
THEN
  RESPONSE #100
    MoveToPoint([1118.1216])
    Face(0)
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",11)
THEN
  RESPONSE #100
    MoveToPoint([1118.1470])
    IncrementGlobal("Pharod_pattern","GLOBAL",1)
    GlobalSet("Pharod_talk","GLOBAL",1)
END

IF
  Global("Pharod_pattern","GLOBAL",12)
THEN
  RESPONSE #100
    Face(10)
    MoveToPoint([1635.1120])
    GlobalSet("Pharod_pattern","GLOBAL",0)
END

