IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    Help()
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("Buried_Attack","GLOBAL",1)
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.ALLEY_GANG])
THEN
  RESPONSE #100
    Enemy()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  True()
THEN
  RESPONSE #100
    GlobalSet("Thug3_Move","AR0109",0)
    ChangeAIScript("0109thg3",DEFAULT)
END

