IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    MoveToPoint([1668.2354])
    MoveToPoint([1512.2508])
    MoveToPoint([1512.2800])
    MoveToPoint([1666.2966])
    MoveToPoint([2638.2968])
    MoveToPoint([2830.3156])
    MoveToPoint([2830.3156])
    MoveToPoint([2638.3600])
    Wait(5)
    Face(4)
    Wait(5)
    Face(0)
    Wait(5)
    MoveToPoint([2638.2644])
    MoveToPoint([2334.2354])
    Face(12)
END

