IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("Enemy_Dabus","GLOBAL",1)
    IncrementGlobal("Lady","GLOBAL",5)
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.0.0.DABUS])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  True()
THEN
  RESPONSE #100
    SetAnimState(Myself,ANIM_MISC1)
    SetAnimState(Myself,ANIM_MISC1)
    SetAnimState(Myself,ANIM_MISC1)
    MoveToPoint([3443.3663])
    Face(8)
    SetAnimState(Myself,ANIM_MISC1)
    SetAnimState(Myself,ANIM_MISC1)
    SetAnimState(Myself,ANIM_MISC1)
    MoveToPoint([3362.3730])
    Face(0)
    SetAnimState(Myself,ANIM_MISC1)
    SetAnimState(Myself,ANIM_MISC1)
    SetAnimState(Myself,ANIM_MISC1)
    MoveToPoint([3032.3744])
    Face(0)
    SetAnimState(Myself,ANIM_MISC1)
    SetAnimState(Myself,ANIM_MISC1)
    SetAnimState(Myself,ANIM_MISC1)
    MoveToPoint([3533.3714])
    Face(14)
END

