IF
  Global("AR0108_Visited","GLOBAL",1)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Die()
THEN
  RESPONSE #100
    GlobalSet("Annah_Hive","GLOBAL",1)
END

IF
  InParty(Myself)
THEN
  RESPONSE #100
    ChangeAIScript("pcannah",DEFAULT)
END

IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("Annah_Hive","GLOBAL",1)
    Enemy()
END

IF
  InParty("Annah")  // ~Tiefling~
THEN
  RESPONSE #100
    ChangeAIScript("",GENERAL)
END

IF
  Range([PC],30)
THEN
  RESPONSE #100
    StartSong(CHAR_ANNAH,[0.0],Normal)
    Continue()
END

IF
  See([PC])
THEN
  RESPONSE #100
    FaceObject([PC])
    Continue()
END

IF
  See([PC])
  Range([PC],30)
THEN
  RESPONSE #100
    KillFloatMessage(Myself)
    PlaySound("ANA005")
    PlaySequence(ANIM_TALK1)
    FloatMessage(Myself,17024)  // ~"Ach! Never have I seen something so ugly, I've not..."~
    WaitRandom(25,40)
  RESPONSE #100
    KillFloatMessage(Myself)
    PlaySound("ANA006")
    PlaySequence(ANIM_TALK1)
    FloatMessage(Myself,17023)  // ~"Looks like the Dusties lost one of their deaders..."~
    WaitRandom(25,40)
  RESPONSE #100
    KillFloatMessage(Myself)
    PlaySound("ANA007")
    PlaySequence(ANIM_TALK1)
    FloatMessage(Myself,17022)  // ~"No deaders today 'cept walking ones, looks like..."~
    WaitRandom(25,40)
END

IF
  True()
THEN
  RESPONSE #100
    KillFloatMessage(Myself)
    PlaySound("ANA008")
    PlaySequence(ANIM_TALK1)
    FloatMessage(Myself,17030)  // ~"Slow Sigil day, it is..."~
    WaitRandom(25,40)
  RESPONSE #100
    KillFloatMessage(Myself)
    PlaySound("ANA009")
    PlaySequence(ANIM_TALK1)
    FloatMessage(Myself,17029)  // ~"Ol' stutter crutch be tallying his copper 'bout now..."~
    WaitRandom(25,40)
  RESPONSE #100
    KillFloatMessage(Myself)
    PlaySound("ANA010")
    PlaySequence(ANIM_TALK1)
    FloatMessage(Myself,17028)  // ~"If I can't find any deaders, maybe I can gut a Dustie..."~
    WaitRandom(25,40)
END

