IF
  Global("AR0200_Visited","GLOBAL",1)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Die()
THEN
  RESPONSE #100
    GlobalSet("Soego","GLOBAL",2)
    GlobalSet("Mortuary_Soego_Killed","GLOBAL",1)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Mortuary_Alert_1","GLOBAL",1)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("Mortuary_Alert","GLOBAL",1)
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  Global("Mortuary_Alert","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
    Attack([PC])
END

IF
  True()
THEN
  RESPONSE #100
    Wait(5)
    MoveToPoint([1818.2684])
    Face(4)
    Wait(5)
    MoveToPoint([1326.2536])
    Face(2)
    Wait(5)
    MoveToPoint([1050.2318])
    Face(14)
    Wait(5)
    MoveToPoint([1326.2536])
    Face(2)
END

