IF
  Allegiance(Myself,ENEMY)
  Global("Mortuary_Alert_3","GLOBAL",1)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  Global("Mortuary_Alert","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
    Attack([PC])
END

IF
  True()
THEN
  RESPONSE #100
    Wait(12)
    MoveToPoint([3034.2126])
    Face(12)
    Wait(12)
    MoveToPoint([2427.1701])
    Face(8)
END

