IF
  Allegiance(Myself,ENEMY)
  Global("Mortuary_Alert_3","GLOBAL",1)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  Global("Mortuary_Alert","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
    Attack([PC])
END

IF
  True()
THEN
  RESPONSE #100
    Wait(14)
    MoveToPoint([1202.1591])
    Face(4)
    Wait(16)
    MoveToPoint([1499.1163])
    Face(8)
END

