IF
  Global("0205_Angry","AR0205",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    GlobalSet("0205_Angry","AR0205",1)
    Help()
    RunAwayFromEx([PC],50,FALSE)
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  Global("Mortai","GLOBAL",0)
  LOS([PC],20)
THEN
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,9732)  // ~"You, stranger... speak with me for a moment."~
    Wait(25)
END

IF
  True()
THEN
  RESPONSE #100
    MoveToPoint([1055.654])
    Face(2)
    WaitRandom(10,15)
    FloatMessage(Myself,9729)  // ~"What *use* is a body after death, though?"~
  RESPONSE #100
    MoveToPoint([1055.654])
    Face(2)
    WaitRandom(10,15)
    FloatMessage(Myself,9730)  // ~"Perhaps another will be here soon..."~
  RESPONSE #100
    MoveToPoint([1055.654])
    Face(2)
    WaitRandom(10,15)
    FloatMessage(Myself,9731)  // ~"Heard the Mortuary keeps misplacing bodies..."~
END

