IF
  Die()
THEN
  RESPONSE #100
    IncrementGlobal("ServantsKilled","AR0205",1)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    ChangeAIScript("0205made",OVERRIDE)
END

IF
  Global("DisturbanceLevel","AR0205",1)
THEN
  RESPONSE #100
    Enemy()
    ChangeAIScript("0205made",OVERRIDE)
END

IF
  Help([ANYONE])
THEN
  RESPONSE #100
    Enemy()
    GlobalSet("DisturbanceLevel","AR0205",1)
    ChangeAIScript("0205made",OVERRIDE)
END

IF
  Died([ANYONE])
THEN
  RESPONSE #100
    Enemy()
    Help()
    ChangeAIScript("0205made",OVERRIDE)
END

IF
  Exists([PC][1268.374.1537.587])
THEN
  RESPONSE #100
    GlobalSet("PlayerBehindBar","AR0205",1)
    Enemy()
    ChangeAIScript("0205cntr",AREA)
END

