IF
  Global("0205_Angry","AR0205",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    GlobalSet("0205_Angry","AR0205",1)
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(5,8)
    MoveToPoint([1169.569])
    MoveToPoint([1081.654])
    Face(4)
    WaitRandom(5,8)
    MoveToPoint([1169.654])
    MoveToPoint([1169.735])
    MoveToPoint([1136.767])
    MoveToPoint([1113.767])
    Face(6)
    WaitRandom(5,8)
    MoveToPoint([1169.823])
    MoveToPoint([1169.868])
    Face(4)
    WaitRandom(5,8)
    MoveToPoint([1169.569])
    MoveToPoint([1190.474])
    Face(12)
END

