IF
  True()
THEN
  RESPONSE #100
    PlaySequence(ANIM_ATTACK)
    MoveToPoint([455.201])
    Face(4)
    PlaySequence(ANIM_ATTACK)
    MoveToPoint([455.206])
    MoveToPoint([365.206])
    MoveToPoint([281.201])
    Face(10)
    PlaySequence(ANIM_ATTACK)
    MoveToPoint([365.206])
    MoveToPoint([455.206])
    MoveToPoint([455.201])
    Face(4)
    PlaySequence(ANIM_ATTACK)
    MoveToPoint([345.1955])
    Face(0)
END

