IF
  True()
THEN
  RESPONSE #100
    Wait(3)
    PlaySequenceTimed(ANIM_STANCEFIDGET1,6)
    Wait(3)
    MoveToPoint([3173.1112])
    Face(2)
    Wait(3)
    PlaySequenceTimed(ANIM_STANCEFIDGET1,6)
    Wait(5)
    MoveToPoint([3173.1165])
    MoveToPoint([3136.1184])
    Face(8)
    Wait(4)
    PlaySequenceTimed(ANIM_STANCEFIDGET1,10)
    MoveToPoint([3173.1165])
    MoveToPoint([3173.1112])
    Face(2)
    Wait(3)
    PlaySequenceTimed(ANIM_STANCEFIDGET1,6)
    Wait(5)
    MoveToPoint([3091.1112])
    Face(14)
END

