IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
END

IF
  True()
THEN
  RESPONSE #100
    Face(0)
    Wait(3)
    Face(2)
    Wait(3)
    Face(0)
    Wait(3)
    MoveToPoint([669.2280])
    Face(4)
    Wait(3)
    Face(2)
    WaitRandom(5,10)
    MoveToPoint([835.2462])
    MoveToPoint([950.2462])
    MoveToPoint([991.2502])
    MoveToPoint([991.2650])
    Face(0)
    Wait(3)
    Face(2)
    Wait(3)
    Face(0)
    Wait(1)
    Face(14)
    Wait(3)
    MoveToPoint([1066.2649])
    Face(12)
    Wait(3)
    Face(14)
    Wait(3)
    Face(0)
    Wait(3)
    Face(2)
    Wait(3)
    MoveToPoint([1065.2576])
    MoveToPoint([950.2462])
    MoveToPoint([853.2462])
    MoveToPoint([669.2280])
    Face(4)
    Wait(3)
    Face(2)
    WaitRandom(5,10)
    MoveToPoint([669.2405])
    Face(0)
END

