IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(15,20)
    MoveToPoint([854.655])
    MoveToPoint([741.768])
    MoveToPoint([741.1115])
    MoveToPoint([946.1322])
    MoveToPoint([1485.1322])
    MoveToPoint([1884.1397])
    MoveToPoint([1994.1508])
    MoveToPoint([1994.1648])
    MoveToPoint([2134.1790])
    MoveToPoint([2245.1790])
    MoveToPoint([2296.1843])
    MoveToPoint([2296.1905])
    MoveToPoint([2865.2474])
    MoveToPoint([2865.2751])
    Face(4)
    ChangeAIScript("0300tm1b",GENERAL)
END

