IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  !NearLocation(Myself,[840.2279],146)
THEN
  RESPONSE #100
    MoveToPoint([840.2279])
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

