IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
END

IF
  True()
THEN
  RESPONSE #100
    Face(2)
    FloatMessage(Myself,6334)  // ~"That's three tails, at three coppers a rat..."~
    WaitRandom(6,10)
    Face(4)
    FloatMessage(Myself,6337)  // ~"It's a wonder the Hive isn't overrun with vermin!"~
    WaitRandom(6,10)
    Face(0)
    FloatMessage(Myself,6335)  // ~"Another rat-catcher dead... those vermin are getting smarter..."~
    WaitRandom(6,10)
    Face(6)
    FloatMessage(Myself,7092)  // ~"Those little blighters have seen their last days...!"~
    WaitRandom(6,10)
    Face(2)
    FloatMessage(Myself,6336)  // ~"Inspector Phineas T. Lort XXXIX is at the helm, yessir..."~
    WaitRandom(6,10)
    Face(14)
    FloatMessage(Myself,7086)  // ~"Need to send another report to the Hall of Records..."~
    WaitRandom(6,10)
END

