IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    Face(12)
    Wait(10)
    MoveToPoint([2808.706])
    MoveToPoint([2776.674])
    MoveToPoint([1884.674])
    MoveToPoint([1826.615])
    Face(8)
    Wait(10)
    MoveToPoint([1884.674])
    MoveToPoint([2776.674])
    MoveToPoint([2808.706])
    MoveToPoint([3697.1097])
END

