IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(10,25)
    Face(8)
    MoveToPoint([204.2013])
    MoveToPoint([502.1716])
    MoveToPoint([571.1716])
    MoveToPoint([870.1416])
    MoveToPoint([870.1227])
    MoveToPoint([2097.0])
    ChangeAIScript("0400tm2b",GENERAL)
END

