IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
END

IF
  True()
THEN
  RESPONSE #100
    Face(8)
    WaitRandom(10,12)
    MoveToPoint([2500.2000])
    MoveToPoint([2500.2142])
    Face(12)
    WaitRandom(3,5)
    Face(14)
    WaitRandom(3,5)
    Face(0)
    WaitRandom(3,5)
    Face(2)
    WaitRandom(3,5)
    Face(4)
    WaitRandom(3,5)
    MoveToPoint([2092.2142])
    MoveToPoint([1977.2027])
    MoveToPoint([1977.1636])
    Face(8)
    WaitRandom(10,12)
    MoveToPoint([1977.2027])
    MoveToPoint([2092.2142])
    MoveToPoint([2500.2142])
    Face(12)
    WaitRandom(3,5)
    Face(14)
    WaitRandom(3,5)
    Face(0)
    WaitRandom(3,5)
    Face(14)
    WaitRandom(3,5)
    Face(12)
    WaitRandom(3,5)
    MoveToPoint([2500.2000])
    MoveToPoint([2767.1732])
END

