IF
  Help([0.0.0.0.GITHZERAI])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(20,30)
    Face(0)
    MoveToPoint([1151.698])
    MoveToPoint([115.1734])
    MoveToPoint([0.1734])
    ChangeAIScript("0400gt1a",GENERAL)
END

