IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    Face(8)
    MoveToPoint([1347.1743])
    MoveToPoint([1607.1743])
    MoveToPoint([1643.1781])
    MoveToPoint([1903.1781])
    MoveToPoint([2111.1990])
    MoveToPoint([2382.1990])
    MoveToPoint([2415.1957])
    MoveToPoint([2637.1957])
    Face(14)
    WaitRandom(5,10)
    MoveToPoint([2415.1957])
    MoveToPoint([2382.1990])
    MoveToPoint([2111.1990])
    MoveToPoint([1903.1781])
    MoveToPoint([1643.1781])
    MoveToPoint([1607.1743])
    MoveToPoint([1347.1743])
    MoveToPoint([1241.1637])
END

