IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  !NearLocation(Myself,[1778.1923],158)
THEN
  RESPONSE #100
    MoveToPoint([1778.1923])
END

IF
  TimerExpired(1)
THEN
  RESPONSE #25
    Wait(3)
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

