IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(30,40)
    Face(2)
    MoveToPoint([2273.1655])
    MoveToPoint([2273.1750])
    MoveToPoint([2366.1844])
    MoveToPoint([3070.1844])
    MoveToPoint([3108.1882])
    MoveToPoint([3685.1882])
    MoveToPoint([3722.1845])
    MoveToPoint([3722.1322])
    MoveToPoint([3623.1221])
    MoveToPoint([3623.1039])
    MoveToPoint([3469.885])
    MoveToPoint([3200.885])
    MoveToPoint([3025.738])
    MoveToPoint([1724.738])
    MoveToPoint([1237.251])
    MoveToPoint([1237.0])
    ChangeAIScript("0400tf3a",GENERAL)
END

