IF
  HPPercentLT(Myself,50)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  !NearLocation(Myself,[1088.855],171)
THEN
  RESPONSE #100
    MoveToPoint([1088.855])
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

