IF
  Global("SC_Mercy_3_At_Table","AR0402",0)
THEN
  RESPONSE #100
    ChangeAIScript("0402mkr3",DEFAULT)
END

IF
  Global("SC_Mercy_Turn_Talk","AR0402",0)
THEN
  RESPONSE #100
    Wait(20)
    FloatMessage(Myself,8152)  // ~"I'm going to go look for that berk again."~
    Wait(3)
    IncrementGlobal("SC_Mercy_Turn_Talk","AR0402",1)
END

IF
  Global("SC_Mercy_Turn_Talk","AR0402",3)
THEN
  RESPONSE #100
    MoveToPoint([959.915])
    Face(2)
    Wait(5)
    MoveToPoint([685.974])
    Face(3)
    Wait(6)
    Face(7)
    Wait(4)
    MoveToPoint([1029.889])
    Face(12)
    MoveToPoint([1301.706])
    Face(11)
    Wait(6)
    Face(12)
    Wait(4)
    MoveToPoint([1096.650])
    Face(6)
    FloatMessage(Myself,9324)  // ~"I feel like I keep doing this."~
    Wait(4)
    IncrementGlobal("SC_Mercy_Turn_Talk","AR0402",2)
END

IF
  Global("SC_Mercy_Turn_Talk","AR0402",7)
THEN
  RESPONSE #100
    FloatMessage(Myself,9327)  // ~"I know, I know. I don't want to miss him."~
    Wait(4)
    IncrementGlobal("SC_Mercy_Turn_Talk","AR0402",1)
END

