IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromEx(NearestEnemyOf(Myself),50,FALSE)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    GlobalSet("SC_Hostile","AR0402",1)
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  Global("SC_Hostile","AR0402",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Range(Protagonist,5)
THEN
  RESPONSE #100
    Dialogue(Protagonist)
END

IF
  See(Protagonist)
THEN
  RESPONSE #100
    MoveToObjectEx(Protagonist,0)
END

