IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    GlobalSet("SC_Hostile","AR0402",1)
    Attack(LastAttackerOf(Myself))
END

IF
  Global("SC_Hostile","AR0402",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Global("Mochai","GLOBAL",2)
  Global("SC_Mochai_Talked_Barkis","AR0402",0)
THEN
  RESPONSE #100
    MoveToPoint([559.859])
END

IF
  Global("Mochai","GLOBAL",2)
  Global("SC_Mochai_Talked_Barkis","AR0402",1)
THEN
  RESPONSE #100
    FloatMessage(Myself,9725)  // ~"You'd better. Or I'll send him after you again."~
    Wait(5)
    MoveToPoint([573.851])
    GlobalSet("SC_Mochai_Talked_Barkis","AR0402",2)
END

IF
  Global("Alais_At_Bar","AR0402",1)
THEN
  RESPONSE #100
    MoveToPoint([511.881])
    Face(0)
    GlobalSet("Barkis_Ready_Serve_Alais","AR0402",1)
END

IF
  Global("Barkis_Ready_Serve_Alais","AR0402",1)
  Global("Alais_At_Bar","AR0402",0)
THEN
  RESPONSE #100
    MoveToPoint([573.851])
    Face(14)
    GlobalSet("Barkis_Ready_Serve_Alais","AR0402",0)
END

IF
  Global("Ilquix_At_Bar","AR0402",1)
THEN
  RESPONSE #100
    MoveToPoint([601.789])
    Face(12)
    PlaySequence(ANIM_STANDFIDGET1)
    GlobalSet("Barkis_Ready_Serve_Ilquix","AR0402",1)
END

IF
  Global("Barkis_Ready_Serve_Ilquix","AR0402",1)
  Global("Ilquix_At_Bar","AR0402",0)
THEN
  RESPONSE #100
    PlaySequence(ANIM_STANDFIDGET2)
    MoveToPoint([573.851])
    Face(14)
    GlobalSet("Barkis_Ready_Serve_Ilquix","AR0402",0)
END

