IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    GlobalSet("SC_Hostile","AR0402",1)
    Attack(LastAttackerOf(Myself))
END

IF
  Global("SC_Hostile","AR0402",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See([PC])
  Global("Mooch","GLOBAL",0)
THEN
  RESPONSE #100
    Dialogue([PC])
    GlobalSet("Mooch","GLOBAL",1)
END

IF
  Global("Mochai","GLOBAL",2)
  Global("SC_Mochai_Talked_Barkis","AR0402",0)
THEN
  RESPONSE #100
    MoveToPoint([612.920])
    Face(6)
    FloatMessage(Myself,9724)  // ~"Here's... umm... some money. I'll bring in more ... umm... later."~
    Wait(5)
    GlobalSet("SC_Mochai_Talked_Barkis","AR0402",1)
END

IF
  NearLocation(Myself,[1219.1840],0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("SC_Mochai_Talked_Barkis","AR0402",2)
THEN
  RESPONSE #100
    MoveToPoint([1219.1840])
END

