IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([ANYONE],DEFAULT)
  Global("Tenement_Alarm","AR0403",0)
THEN
  RESPONSE #100
    Enemy()
    GlobalSet("Tenement_Alarm","AR0403",1)
    Attack(LastAttackerOf(Myself))
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

