IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(5,10)
    PlaySequence(ANIM_STANDTOSTANCE)
    PlaySequence(ANIM_ATTACK1)
    PlaySequence(ANIM_ATTACK2)
    PlaySequence(ANIM_STANCETOSTAND)
    WaitRandom(5,10)
    Face(-1)
    Continue()
END

