IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(5,10)
    MoveToPoint([801.1800])
    Face(4)
    WaitRandom(5,10)
    MoveToPoint([1200.1950])
    Face(10)
    WaitRandom(5,10)
    MoveToPoint([801.2195])
    Face(4)
    Continue()
END

