IF
  Die()
THEN
  RESPONSE #100
    Help()
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  Help("Giltspur")  // Giltspur
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(LastHelp),50,FALSE)
END

IF
  Help("0500cusm1")  // 0500cusm1
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(LastHelp),50,FALSE)
END

IF
  Help("0500cusm2")  // 0500cusm2
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(LastHelp),50,FALSE)
END

IF
  Help("0500cusm3")  // 0500cusm3
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(LastHelp),50,FALSE)
END

IF
  Help("0500cusf1")  // 0500cusf1
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(LastHelp),50,FALSE)
END

IF
  Help("0500cusf2")  // 0500cusf2
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(LastHelp),50,FALSE)
END

IF
  Help("0500cusf3")  // 0500cusf3
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(LastHelp),50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    RunAwayFromEx(NearestEnemyOf(Myself),50,FALSE)
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

