IF
  Die()
THEN
  RESPONSE #100
    Help()
END

IF
  Help([0.0.0.0.0.0.SPAWNER])
  Race(Myself,ABISHAI_BLACK)
THEN
  RESPONSE #100
    Enemy()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([ANYONE],DEFAULT)
  Race(Myself,ABISHAI_BLACK)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  See(NearestEnemyOf(Myself))
  Race(Myself,ABISHAI_BLACK)
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  Help([0.0.0.0.0.0.SPAWNER])
  !Race(Myself,ABISHAI_BLACK)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(Myself),50,FALSE)
END

IF
  AttackedBy([ANYONE],DEFAULT)
  !Race(Myself,ABISHAI_BLACK)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
  !Race(Myself,ABISHAI_BLACK)
THEN
  RESPONSE #100
    Help()
    RunAwayFromEx(NearestEnemyOf(Myself),50,FALSE)
END

