IF
  Global("Guard_Drill","AR0500",0)
THEN
  RESPONSE #100
    Wait(1)
    RunToPoint([1313.713])
    Face(10)
    IncrementGlobal("Guards_Arrived","AR0500",1)
    ChangeAIScript("0500noop",DEFAULT)
END

IF
  Global("Guard_Drill","AR0500",1)
THEN
  RESPONSE #100
    Wait(1)
    RunToPoint([993.905])
    Face(2)
    IncrementGlobal("Guards_Arrived","AR0500",1)
    ChangeAIScript("0500noop",DEFAULT)
END

IF
  Global("Guard_Drill","AR0500",2)
THEN
  RESPONSE #100
    Wait(2)
    Face(10)
    RunToPoint([1233.987])
    Face(14)
    IncrementGlobal("Guards_Arrived","AR0500",1)
    ChangeAIScript("0500noop",DEFAULT)
END

