IF
  True()
THEN
  RESPONSE #100
    WaitRandom(3,5)
    PlaySequence(ANIM_MISC1)
    WaitRandom(3,5)
    MoveToPoint([1470.1798])
    Face(2)
    WaitRandom(3,5)
    PlaySequence(ANIM_MISC1)
    WaitRandom(3,5)
    MoveToPoint([1298.1711])
    Face(4)
    WaitRandom(3,5)
    PlaySequence(ANIM_MISC1)
    WaitRandom(3,5)
    MoveToPoint([1470.1798])
    Face(2)
    WaitRandom(3,5)
    PlaySequence(ANIM_MISC1)
    WaitRandom(3,5)
    MoveToPoint([1505.1934])
    Face(4)
END

