IF
  True()
THEN
  RESPONSE #100
    WaitRandom(3,5)
    PlaySequence(ANIM_MISC1)
    WaitRandom(3,5)
    MoveToPoint([1046.1722])
    Face(14)
    WaitRandom(3,5)
    PlaySequence(ANIM_MISC1)
    WaitRandom(3,5)
    MoveToPoint([1195.1696])
    Face(0)
    WaitRandom(3,5)
    PlaySequence(ANIM_MISC1)
    WaitRandom(3,5)
    MoveToPoint([1046.1722])
    Face(14)
    WaitRandom(3,5)
    PlaySequence(ANIM_MISC1)
    WaitRandom(3,5)
    MoveToPoint([967.1828])
    Face(12)
END

