IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  !NearbyDialog("DDimTree")
THEN
  RESPONSE #100
    FaceObject([PC])
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(10,15)
    FloatMessage(Myself,41270)  // ~"You're the best friend a man could ever have, Dimtree."~
    PlaySequence(ANIM_TALK1)
    WaitRandom(10,15)
    FloatMessage(Myself,41269)  // ~"That has to be one of the finest coffins I've ever put together, eh Dimtree?"~
    PlaySequence(ANIM_TALK1)
    WaitRandom(10,15)
    FloatMessage(Myself,41268)  // ~"Ya sure are a quiet one today, Dimtree!"~
    PlaySequence(ANIM_TALK1)
    WaitRandom(10,15)
    FloatMessage(Myself,41249)  // ~"Dimtree, ya hear me talkin' at ya?"~
    PlaySequence(ANIM_TALK1)
    Continue()
END

