IF
  Die()
THEN
  RESPONSE #100
    GlobalSet("Foundry_GR_Status","AR0511",7)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #0
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    IncrementGlobal("Lady","GLOBAL",1)
    Help()
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    GlobalSet("0511_Talked_Guards","AR0511",1)
END

IF
  See([PC])
  Global("G_Test3","GLOBAL",1)
  Global("0511_Talked_Guards","AR0511",0)
THEN
  RESPONSE #100
    Dialogue([PC])
END

IF
  !NearLocation(Myself,[679.506],0)
THEN
  RESPONSE #100
    MoveToPoint([679.506])
    Face(10)
END

IF
  !Dead("Sandoz")  // ~Godsman Factor~
THEN
  RESPONSE #100
    BitSet("Foundry_GR_Status","AR0511",BIT1)
    WaitRandom(3,15)
    FloatMessage(Myself,25981)  // ~"I can't wait until my shift is done."~
  RESPONSE #100
    BitSet("Foundry_GR_Status","AR0511",BIT1)
    WaitRandom(3,15)
    FloatMessage(Myself,25979)  // ~"Heard it's going to rain tonight."~
  RESPONSE #100
    WaitRandom(3,5)
    FloatMessage(Myself,25978)  // ~"He's been in there for a long time!"~
    WaitRandom(3,5)
    FloatMessage([0.0.0.0.0.0.PERSON_1],25977)  // ~"I know.  I wonder what he's doing?"~
    GlobalSet("Foundry_GR_Status","AR0511",0)
  RESPONSE #100
    WaitRandom(3,5)
    FloatMessage([0.0.0.0.0.0.PERSON_1],25976)  // ~"Have you been in the armory lately?"~
    WaitRandom(3,5)
    FloatMessage(Myself,25983)  // ~"No, but I've heard they're working on a machine in there."~
    GlobalSet("Foundry_GR_Status","AR0511",0)
  RESPONSE #100
    WaitRandom(3,5)
    FloatMessage(Myself,25984)  // ~::Yawn:: " Maybe I should take a nap."~
    WaitRandom(3,5)
    FloatMessage([0.0.0.0.0.0.PERSON_1],25985)  // ~"Don't let the factor see you doing it."~
    GlobalSet("Foundry_GR_Status","AR0511",0)
  RESPONSE #100
    WaitRandom(3,5)
    FloatMessage([0.0.0.0.0.0.PERSON_1],25986)  // ~"Sandoz seemed very preoccupied when he arrived."~
    WaitRandom(3,5)
    FloatMessage(Myself,25982)  // ~"I wonder what he's worried about?"~
    GlobalSet("Foundry_GR_Status","AR0511",0)
END

