IF
  True()
THEN
  RESPONSE #100
    Face(4)
    MoveToPoint([662.636])
    Face(2)
    MoveToPoint([522.77])
    Face(6)
    MoveToPoint([501.753])
    Continue()
END

IF
  True()
THEN
  RESPONSE #100
    PlaySequence(ANIM_STANDFIDGET1)
    Continue()
  RESPONSE #100
    PlaySequence(ANIM_STANDFIDGET2)
    Continue()
  RESPONSE #100
    PlaySequence(ANIM_STANCETOSTAND)
    Continue()
END

IF
  True()
THEN
  RESPONSE #100
    FloatMessage(Myself,16977)  // ~"Now where did that tool go?"~
    Continue()
  RESPONSE #100
    FloatMessage(Myself,16976)  // ~"Who took the nails?"~
    Continue()
  RESPONSE #100
    FloatMessage(Myself,16975)  // ~"Whose got the hammer?"~
    Continue()
END

IF
  True()
THEN
  RESPONSE #100
    Face(14)
    MoveToPoint([522.771])
    Face(10)
    MoveToPoint([662.636])
    Face(12)
    MoveToPoint([910.633])
    Face(14)
    GlobalSet("Foundry_Area_Return","AR0512",0)
    ChangeAIScript("0512work",DEFAULT)
END

