IF
  True()
THEN
  RESPONSE #100
    PlaySequence(ANIM_STANDFIDGET1)
    Continue()
  RESPONSE #100
    PlaySequence(ANIM_STANDFIDGET2)
    Continue()
  RESPONSE #100
    PlaySequence(ANIM_STANCETOSTAND)
    Continue()
END

IF
  True()
THEN
  RESPONSE #100
    FloatMessage(Myself,0)  // ~"I shall wait for you in death's halls, my Love." She smiles, but there is only sadness in it. She closes her eyes, and with an ethereal whisper, she fades.~ [DEN008B]
    Wait(3)
  RESPONSE #100
    FloatMessage(Myself,0)  // ~"I shall wait for you in death's halls, my Love." She smiles, but there is only sadness in it. She closes her eyes, and with an ethereal whisper, she fades.~ [DEN008B]
    Wait(3)
  RESPONSE #100
    FloatMessage(Myself,0)  // ~"I shall wait for you in death's halls, my Love." She smiles, but there is only sadness in it. She closes her eyes, and with an ethereal whisper, she fades.~ [DEN008B]
    Wait(3)
END

