IF
  NearLocation(Myself,[437.802],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,FWORKER_1)
    ChangeAIScript("0512ft1b",DEFAULT)
END

IF
  NearLocation(Myself,[534.719],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,FWORKER_2)
    ChangeAIScript("0512ft2b",DEFAULT)
END

IF
  NearLocation(Myself,[782.722],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,FWORKER_3)
    ChangeAIScript("0512work",DEFAULT)
END

IF
  NearLocation(Myself,[853.933],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,FWORKER_4)
    ChangeAIScript("0512work",DEFAULT)
END

IF
  NearLocation(Myself,[910.633],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,FWORKER_5)
    ChangeAIScript("0512work",DEFAULT)
END

IF
  NearLocation(Myself,[1019.604],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,FWORKER_6)
    ChangeAIScript("0512work",DEFAULT)
END

IF
  NearLocation(Myself,[1014.694],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,FWORKER_7)
    ChangeAIScript("0512work",DEFAULT)
END

IF
  NearLocation(Myself,[937.770],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,FWORKER_8)
    ChangeAIScript("0512work",DEFAULT)
END

