IF
  Help([0.0.FOUNDRY_GUARD])
THEN
  RESPONSE #100
    Help()
    Enemy()
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("Alarm2","GLOBAL",1)
    IncrementGlobal("Lady","GLOBAL",1)
    Help()
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  !TimerActive(1)
THEN
  RESPONSE #100
    FloatMessage(Myself,28846)  // ~"Why am I guarding a broken machine?"~
    StartRandomTimer(1,15,30)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,28848)  // ~"Hmmm, such a waste."~
    StartRandomTimer(1,15,30)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,28849)  // ~"So much for the weapon."~
    StartRandomTimer(1,15,30)
    Continue()
END

