IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  Help([0.0.POET])
THEN
  RESPONSE #100
    Help()
    Enemy()
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    GlobalSet("Call_MK","GLOBAL",1)
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(10,15)
    FloatMessage(Myself,50756)  // ~"Are you familiar with the language?"~
    Wait(3)
    FloatMessage([0.0.0.0.0.0.POET_WATCHER_2],50757)  // ~"No, I am not... but the sound of it sound is not so bad."~
    Wait(3)
    FloatMessage(Myself,50758)  // ~"Hmmm..."~
END

