IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  Help([0.0.BAR_CROWD_1])
THEN
  RESPONSE #100
    Enemy()
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack(NearestEnemyOf(Myself))
END

IF
  !NearLocation(Myself,[3906.2594],0)
THEN
  RESPONSE #100
    MoveToPoint([3906.2594])
    Face(2)
END

