IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    FloatMessage(Myself,27433)  // ~"Aelwyn became angered, and they fled in terror at the sound of her voice."~
    GlobalSet("Attack_Nemelle","AR0600",1)
    Dialogue("Nameless")
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  !TimerActive(1)
THEN
  RESPONSE #100
    PlaySequence(ANIM_TALK1)
    StartRandomTimer(1,5,10)
  RESPONSE #100
    PlaySequence(ANIM_TALK2)
    StartRandomTimer(1,5,10)
  RESPONSE #100
    PlaySequence(ANIM_TALK3)
    StartRandomTimer(1,5,10)
END

