IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,MERCHANT_1)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromEx(NearestEnemyOf(Myself),TWO_AI_SECONDS,FALSE)
END

IF
  Help([0.0.BAR_CROWD_1])
THEN
  RESPONSE #100
    Enemy()
    RunAwayFromEx(NearestEnemyOf(Myself),TWO_AI_SECONDS,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    GlobalSet("Call_MK","GLOBAL",1)
    RunAwayFromEx(NearestEnemyOf(Myself),TWO_AI_SECONDS,FALSE)
END

IF
  !NearLocation(Myself,[3769.2488],0)
THEN
  RESPONSE #100
    MoveToPoint([3769.2488])
    Face(0)
END

