IF
  OnCreation()
THEN
  RESPONSE #100
    Enemy()
    SetInternal(Myself,INTERNAL_1,0)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
    SetInternal(Myself,INTERNAL_1,1)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  Internal(Myself,INTERNAL_1,0)
THEN
  RESPONSE #100
    RunToObject([PC][0.0.10000.10000])
    RunningAttack(NearestEnemyOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

