IF
  HPPercentLT(Myself,10)
THEN
  RESPONSE #100
    RunAwayFromEx(LastAttackerOf(Myself),TEN_AI_SECONDS,TRUE)
END

IF
  !HaveAnySpells()
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromEx(LastAttackerOf(Myself),TEN_AI_SECONDS,TRUE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_ARMOR)
    Wait(1)
    Spell([PC],WIZARD_SWARM_CURSE)
    Wait(3)
    Spell([PC],WIZARD_CHROMATIC_ORB)
    Wait(1)
    Spell([PC],WIZARD_CHROMATIC_ORB)
    Wait(1)
    Spell([PC],WIZARD_CHROMATIC_ORB)
    Wait(1)
    Spell([PC],WIZARD_SWARM_CURSE)
    Wait(3)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(5,10)
    FloatMessage(Myself,50745)  // ~"Fortunes told... get yer fortunes told fer a paltry five coppers!"~
  RESPONSE #100
    WaitRandom(5,10)
    FloatMessage(Myself,50746)  // ~"Come to Elobrande and learn yer fortune! Only five coins..."~
END

