IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeTeam(Myself,THUGB)
END

IF
  Die()
  !Global("YoBoy","AR0600",3)
THEN
  RESPONSE #100
    CreateItem("Mertwyn",0,0,0)  // ~Steel Box~
    DropInventory()
    Continue()
END

IF
  Die()
THEN
  RESPONSE #100
    GlobalSet("0600_Thug_Respawn","GLOBAL",0)
END

IF
  HPLT(Myself,10)
THEN
  RESPONSE #100
    Enemy()
    RunAwayFromEx([PC],TEN_AI_SECONDS,FALSE)
END

IF
  NumCreature([0.0.THUG],0)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],TEN_AI_SECONDS,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.THUG])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  Range([PC],25)
  !TimerActive(1)
THEN
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,50476)  // ~"You'll 'pike off' quick if you know what's good for you. Get out of here!"~
    StartRandomTimer(1,5,10)
END

