IF
  Die()
THEN
  RESPONSE #100
    GlobalSet("Montague_Problem","GLOBAL",1)
    GlobalSet("Call_MK","GLOBAL",1)
    Help()
END

IF
  Allegiance(Myself,ENEMY)
  !Global("Montague_Problem","GLOBAL",1)
THEN
  RESPONSE #100
    GlobalSet("Montague_Problem","GLOBAL",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    GlobalSet("Call_MK","GLOBAL",1)
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.TEAM_1])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  Help([0.0.TEAM_2])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  Help([0.0.TEAM_4])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  Internal(Myself,INTERNAL_0,1)
THEN
  RESPONSE #100
    Wait(300)
    SetInternal(Myself,INTERNAL_0,0)
END

IF
  Internal(Myself,INTERNAL_0,0)
  Internal(Myself,INTERNAL_1,0)
THEN
  RESPONSE #100
    Face(10)
    SetInternal(Myself,INTERNAL_1,1)
    SetInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,0)
  Internal(Myself,INTERNAL_1,1)
THEN
  RESPONSE #100
    MoveToPoint([1813.596])
    OpenDoor("ar601d07")
    MoveToPoint([1403.606])
    MoveToPoint([1385.777])
    OpenDoor("ar601d06")
    MoveToPoint([1680.856])
    SetInternal(Myself,INTERNAL_1,2)
    SetInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,0)
  Internal(Myself,INTERNAL_1,2)
THEN
  RESPONSE #100
    MoveToPoint([1490.932])
    OpenDoor("ar601d06")
    MoveToPoint([1403.606])
    MoveToPoint([1661.531])
    OpenDoor("ar601d07")
    MoveToPoint([1813.596])
    CloseDoor("ar601d07")
    MoveToPoint([1890.600])
    SetInternal(Myself,INTERNAL_1,0)
END

