IF
  Die()
THEN
  RESPONSE #100
    Enemy()
    Help()
    GlobalSet("Call_MK","GLOBAL",1)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    GlobalSet("Call_MK","GLOBAL",1)
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.TEAM_7])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  TimerExpired(1)
THEN
  RESPONSE #10
    ChangeAIScript("0601qs1",GENERAL)
  RESPONSE #10
    ChangeAIScript("0601qs2",GENERAL)
  RESPONSE #10
    ChangeAIScript("0601qs3",GENERAL)
  RESPONSE #10
    ChangeAIScript("0601qs4",GENERAL)
  RESPONSE #10
    ChangeAIScript("0601qs5",GENERAL)
  RESPONSE #10
    ChangeAIScript("0601qs6",GENERAL)
END

IF
  !TimerActive(1)
THEN
  RESPONSE #100
    StartRandomTimer(1,30,60)
END

IF
  True()
THEN
  RESPONSE #100
    Face(14)
    Wait(5)
    MoveToPoint([1944.1575])
    Face(12)
    Wait(5)
    Face(6)
    Wait(5)
    MoveToPoint([1848.1673])
    Face(6)
    Wait(5)
    Face(2)
    Wait(5)
    MoveToPoint([1906.1673])
    Face(14)
    Wait(5)
    Face(12)
    Wait(5)
    MoveToPoint([1944.1634])
END

