IF
  Die()
THEN
  RESPONSE #100
    Enemy()
    Help()
    GlobalSet("Call_MK","GLOBAL",1)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    GlobalSet("Call_MK","GLOBAL",1)
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.TEAM_8])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
    Continue()
END

IF
  !NearLocation(Myself,[2778.1811],0)
THEN
  RESPONSE #100
    MoveToPoint([2778.1811])
    Face(12)
END

