IF
  Die()
THEN
  RESPONSE #100
    Enemy()
    Help()
    GlobalSet("Call_MK","GLOBAL",1)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    GlobalSet("Call_MK","GLOBAL",1)
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.TEAM_8])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  True()
THEN
  RESPONSE #100
    MoveToPoint([2608.1925])
    Face(12)
    FloatMessage(Myself,26789)  // ~"Remember, a mark is most vulnerable when distracted."~
    ChangeAIScript("0601eli0",GENERAL)
  RESPONSE #100
    MoveToPoint([2608.1925])
    Face(12)
    FloatMessage(Myself,26793)  // ~"Your hands must move faster. In and out of the pockets quickly... or you're sure to get scragged."~
    ChangeAIScript("0601eli0",GENERAL)
  RESPONSE #100
    MoveToPoint([2608.1925])
    Face(12)
    FloatMessage(Myself,26802)  // ~"Slice through the purse strings gently. Softly, but swiftly."~
    ChangeAIScript("0601eli0",GENERAL)
END

