IF
  OnCreation()
THEN
  RESPONSE #100
    SavePlace()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromEx(NearestEnemyOf(Myself),50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(LastHelp),50,FALSE)
END

IF
  See([PC])
THEN
  RESPONSE #100
    FaceObject([PC])
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

