IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,SENSATES)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromEx(NearestEnemyOf(Myself),50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(LastHelp),50,FALSE)
END

IF
  Global("0602_Sen_8","AR0602",1)
THEN
  RESPONSE #100
    Wait(20)
    MoveToPoint([1599.1418])
    MoveToPoint([1599.1631])
    StartTimer(1,30)
    DestroySelf()
    GlobalSet("0602_Sen_8","AR0602",0)
    SetGlobalTimer("0602_Timer_1","AR0602",30)
END

IF
  Global("0602_Sen_8","AR0602",2)
THEN
  RESPONSE #100
    MoveToPoint([1599.1418])
    MoveToPoint([1456.1274])
    GlobalSet("0602_Sen_8","AR0602",1)
END

