IF
  HPPercentLT(Myself,10)
THEN
  RESPONSE #100
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    RunAwayFromEx(LastAttackerOf(LastHelp),TEN_AI_SECONDS,FALSE)
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

