IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    RunAwayFromEx(LastAttackerOf(LastHelp),TEN_AI_SECONDS,FALSE)
END

IF
  !BitCheck("0604_Status","AR0604",BIT1)
THEN
  RESPONSE #100
    Wait(30)
    MoveToPoint([560.603])
    MoveToPoint([560.790])
    MoveToPoint([274.1116])
    SetGlobalTimer("Sen4","AR0604",30)
    BitSet("0604_Status","AR0604",3)
    DestroySelf()
END

IF
  BitCheck("0604_Status","AR0604",BIT1)
THEN
  RESPONSE #100
    MoveToPoint([560.790])
    MoveToPoint([560.603])
    MoveToPoint([664.501])
    BitClear("0604_Status","AR0604",BIT1)
END

