IF
  Die()
THEN
  RESPONSE #100
    GlobalSet("Brothel_Alarm","GLOBAL",1)
    GlobalSet("Brothel_Guards","GLOBAL",1)
    Help()
    CreateItem("BHanky",0,0,0)  // ~Bloody Handkerchief~
    DropInventory()
END

IF
  Global("Brothel_Alarm","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(Myself),50,FALSE)
END

IF
  AttackedBy([ANYONE],DEFAULT)
  Global("Brothel_Alarm","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("Brothel_Alarm","GLOBAL",1)
    GlobalSet("Brothel_Guards","GLOBAL",1)
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  !Internal(Myself,INTERNAL_3,2)
THEN
  RESPONSE #100
    SetInternal(Myself,INTERNAL_3,2)
    Continue()
END

IF
  !Internal(Myself,INTERNAL_1,0)
THEN
  RESPONSE #100
    SetInternal(Myself,INTERNAL_1,0)
END

IF
  Internal(Myself,INTERNAL_2,4)
THEN
  RESPONSE #100
    MoveToPoint([2104.785])
    Face(10)
    Wait(1)
    OpenDoor("AR605d05")
    MoveToPoint([2254.631])
    MoveToPoint([2254.549])
    Face(2)
    CloseDoor("AR605d05")
    Face(0)
    ChangeAIScript("0605kes1",DEFAULT)
END

IF
  See([PC])
THEN
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,48073)  // ~"Mmm... hello there."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,48074)  // ~"I like what I see."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,48075)  // ~"Is there something you'd like to share with me?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,48076)  // ~"Are you alone?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,48077)  // ~"My my, what have we here?"~
    Wait(5)
    Continue()
  RESPONSE #1000
    Continue()
END

IF
  See("BPatron1")  // ~Brothel Patron~
THEN
  RESPONSE #100
    FaceObject("BPatron1")
    FloatMessage(Myself,48073)  // ~"Mmm... hello there."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron1")
    FloatMessage(Myself,48074)  // ~"I like what I see."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron1")
    FloatMessage(Myself,48075)  // ~"Is there something you'd like to share with me?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron1")
    FloatMessage(Myself,48076)  // ~"Are you alone?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron1")
    FloatMessage(Myself,48077)  // ~"My my, what have we here?"~
    Wait(5)
    Continue()
  RESPONSE #500
    SendTrigger("BPatron1",3)
    FaceObject("BPatron1")
    ChangeAIScript("0605kes3",DEFAULT)
    Continue()
  RESPONSE #1000
    Continue()
END

IF
  See("BPatron2")  // ~Brothel Patron~
THEN
  RESPONSE #100
    FaceObject("BPatron2")
    FloatMessage(Myself,48073)  // ~"Mmm... hello there."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron2")
    FloatMessage(Myself,48074)  // ~"I like what I see."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron2")
    FloatMessage(Myself,48075)  // ~"Is there something you'd like to share with me?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron2")
    FloatMessage(Myself,48076)  // ~"Are you alone?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron2")
    FloatMessage(Myself,48077)  // ~"My my, what have we here?"~
    Wait(5)
    Continue()
  RESPONSE #500
    SendTrigger("BPatron2",3)
    FaceObject("BPatron2")
    ChangeAIScript("0605kes3",DEFAULT)
    Continue()
  RESPONSE #1000
    Continue()
END

IF
  See("BPatron3")  // ~Brothel Patron~
THEN
  RESPONSE #100
    FaceObject("BPatron3")
    FloatMessage(Myself,48073)  // ~"Mmm... hello there."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron3")
    FloatMessage(Myself,48074)  // ~"I like what I see."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron3")
    FloatMessage(Myself,48075)  // ~"Is there something you'd like to share with me?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron3")
    FloatMessage(Myself,48076)  // ~"Are you alone?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron3")
    FloatMessage(Myself,48077)  // ~"My my, what have we here?"~
    Wait(5)
    Continue()
  RESPONSE #500
    SendTrigger("BPatron3",3)
    FaceObject("BPatron3")
    ChangeAIScript("0605kes3",DEFAULT)
    Continue()
  RESPONSE #1000
    Continue()
END

IF
  See("BPatron5")  // ~Brothel Patron~
THEN
  RESPONSE #100
    FaceObject("BPatron5")
    FloatMessage(Myself,48073)  // ~"Mmm... hello there."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron5")
    FloatMessage(Myself,48074)  // ~"I like what I see."~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron5")
    FloatMessage(Myself,48075)  // ~"Is there something you'd like to share with me?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron5")
    FloatMessage(Myself,48076)  // ~"Are you alone?"~
    Wait(5)
    Continue()
  RESPONSE #100
    FaceObject("BPatron5")
    FloatMessage(Myself,48077)  // ~"My my, what have we here?"~
    Wait(5)
    Continue()
  RESPONSE #500
    SendTrigger("BPatron5",3)
    FaceObject("BPatron5")
    ChangeAIScript("0605kes3",DEFAULT)
    Continue()
  RESPONSE #1000
    Continue()
END

IF
  Internal(Myself,INTERNAL_0,0)
  !TimerActive(1)
THEN
  RESPONSE #100
    MoveToPoint([2101.1176])
    Face(2)
    StartRandomTimer(1,5,10)
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,1)
  !TimerActive(1)
THEN
  RESPONSE #100
    MoveToPoint([1939.1340])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,2)
THEN
  RESPONSE #100
    MoveToPoint([1854.1340])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,3)
THEN
  RESPONSE #100
    MoveToPoint([1793.1402])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,4)
THEN
  RESPONSE #100
    MoveToPoint([1693.1402])
    Face(0)
    StartRandomTimer(1,5,10)
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,5)
  !TimerActive(1)
THEN
  RESPONSE #100
    MoveToPoint([1585.1491])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,6)
THEN
  RESPONSE #100
    MoveToPoint([1286.1491])
    Face(0)
    StartRandomTimer(1,5,10)
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,7)
  !TimerActive(1)
THEN
  RESPONSE #100
    MoveToPoint([1222.1427])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,8)
THEN
  RESPONSE #100
    MoveToPoint([1079.1427])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,9)
THEN
  RESPONSE #100
    MoveToPoint([815.1162])
    Face(2)
    StartRandomTimer(1,5,10)
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,10)
  !TimerActive(1)
THEN
  RESPONSE #100
    MoveToPoint([815.742])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,11)
THEN
  RESPONSE #100
    MoveToPoint([993.568])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,12)
THEN
  RESPONSE #100
    MoveToPoint([1213.570])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,13)
THEN
  RESPONSE #100
    MoveToPoint([1257.534])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,14)
THEN
  RESPONSE #100
    MoveToPoint([1536.534])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,15)
THEN
  RESPONSE #100
    MoveToPoint([1596.591])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,16)
THEN
  RESPONSE #100
    MoveToPoint([1688.591])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,17)
THEN
  RESPONSE #100
    MoveToPoint([1971.785])
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  InternalGT(Myself,INTERNAL_0,17)
THEN
  RESPONSE #100
    MoveToPoint([2104.785])
    Face(2)
    StartRandomTimer(1,5,10)
    SetInternal(Myself,INTERNAL_0,0)
    IncInternal(Myself,INTERNAL_2,1)
END

