IF
  TimerExpired(3)
THEN
  RESPONSE #100
    StartTimer(2,20)
    SetInternal(Myself,INTERNAL_0,0)
    ChangeAIScript("0605pat1",DEFAULT)
END

IF
  TimerActive(3)
  !TimerActive(4)
THEN
  RESPONSE #100
    FaceObject(Nearest)
    PlaySequence(ANIM_TALK1)
    StartRandomTimer(4,2,6)
END

IF
  Internal(Myself,INTERNAL_0,1)
  !TimerActive(3)
THEN
  RESPONSE #100
    MoveToObjectEx("Grace",0)
    FaceObject("Grace")
    SendTrigger("Grace",1)
    StartTimer(3,45)
END

IF
  Internal(Myself,INTERNAL_0,2)
  !TimerActive(3)
THEN
  RESPONSE #100
    MoveToObjectEx("Vivian",0)
    FaceObject("Vivian")
    SendTrigger("Vivian",1)
    StartTimer(3,45)
END

IF
  Internal(Myself,INTERNAL_0,3)
  !TimerActive(3)
THEN
  RESPONSE #100
    MoveToObjectEx("Kesai",0)
    FaceObject("Kesai")
    SendTrigger("Kesai",1)
    StartTimer(3,45)
END

IF
  Internal(Myself,INTERNAL_0,4)
  !TimerActive(3)
THEN
  RESPONSE #100
    MoveToObjectEx("Nenny",0)
    FaceObject("Nenny")
    SendTrigger("Nenny",1)
    StartTimer(3,45)
END

IF
  Internal(Myself,INTERNAL_0,5)
  !TimerActive(3)
THEN
  RESPONSE #100
    MoveToObjectEx("Ecco",0)
    FaceObject("Ecco")
    SendTrigger("Ecco",1)
    StartTimer(3,45)
END

IF
  Internal(Myself,INTERNAL_0,6)
  !TimerActive(3)
THEN
  RESPONSE #100
    MoveToObjectEx("Dolora",0)
    FaceObject("Dolora")
    SendTrigger("Dolora",1)
    StartTimer(3,45)
END

