IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    RunAwayFromEx(LastAttackerOf(LastHelp),TEN_AI_SECONDS,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    Wait(25)
    MoveToPoint([709.438])
    MoveToPoint([665.482])
    MoveToPoint([736.552])
    MoveToPoint([852.429])
    Face(6)
    Wait(10)
    MoveToPoint([921.423])
    Face(10)
    Wait(10)
    MoveToPoint([1034.499])
    Face(10)
    Wait(10)
    MoveToPoint([1034.499])
    Face(10)
    Wait(10)
    MoveToPoint([921.423])
    Face(10)
    Wait(10)
    MoveToPoint([709.291])
    Face(10)
END

