IF
  True()
THEN
  RESPONSE #100
    CutSceneId("trigit5")  // 
    MoveViewPoint([2085.3028],INSTANT)
    Activate(Myself)
    PlaySoundNotRanged("ABYSS02")
    PlaySequence(ANIM_MISC1)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("trigit6")  // 
    Activate(Myself)
    PlaySoundNotRanged("ABYSS02")
    PlaySequence(ANIM_MISC1)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Nameless")  // 
    GlobalSet("Trigit_Attack","GLOBAL",1)
    EndCutSceneMode()
END

