IF
  True()
THEN
  RESPONSE #100
    CutSceneId("trigit5")  // 
    DeactivateEx(Myself,FALSE)
    GlobalSet("Spawn_Trigit","GLOBAL",0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("trigit6")  // 
    DeactivateEx(Myself,FALSE)
    MoveViewPoint([2085.3028],VERY_FAST)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Nameless")  // 
    TimedMoveToPoint([1944.3055],75)
    Face(12)
    StartCutScene("0610in3c")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    MoveToPoint([1944.3090])
    Face(12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    MoveToPoint([1944.3131])
    Face(12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    MoveToPoint([1900.3032])
    Face(12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    MoveToPoint([1900.3066])
    Face(12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    MoveToPoint([1900.3097])
    Face(12)
END

