IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Ravel")  // 
    SetInternal(Myself,INTERNAL_0,1)
    PlaySequence(ANIM_SPELL2)
    StickySinisterPoof("S113SMOK",Myself,1)
    PolymorphEx(Fall From Grace,0)
    FaceObject("Nameless")
    Wait(3)
    PlaySequence(ANIM_STANDTOSTANCE)
    PlaySequence(ANIM_DEFEND)
    PlaySequence(ANIM_STANCEFIDGET1)
    PlaySequence(ANIM_STANCETOSTAND)
    Dialogue([PC])
    SetInternal(Myself,INTERNAL_0,0)
    EndCutSceneMode()
END

