IF
  True()
THEN
  RESPONSE #100
    Wait(5)
    MoveToPoint([3182.2450])
    MoveToPoint([3182.2236])
    Face(4)
    Wait(3)
    MoveToPoint([3474.2234])
    MoveToPoint([3668.2034])
    MoveToPoint([4026.2034])
    Face(12)
    Wait(5)
    MoveToPoint([3668.2034])
    MoveToPoint([3474.2234])
    MoveToPoint([3182.2236])
    Face(4)
    Wait(3)
    MoveToPoint([3182.2450])
    MoveToPoint([2994.2644])
    Face(6)
END

