IF
  True()
THEN
  RESPONSE #100
    CutSceneId("RavelCut")  // 
    Face(2)
    SetAnimState(Myself,ANIM_MIMEDIE)
    Wait(2)
    FadeFromBlack()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("TransCut")  // 
    StartSong(CHAR_TRANSCENDENT,[0.0],Normal)
    Face(14)
    Wait(6)
    TimedMoveToPoint([434.3543],75)
    StartSong(CHAR_TRANSCENDENT,[0.0],Normal)
    StartCutScene("0610ct3c")
END

