IF
  Global("Patron_Arrived","AR0611",1)
THEN
  RESPONSE #100
    Face(14)
    Wait(6)
    FloatMessage(Myself,27440)  // ~"It looks... well... a bit like the last one you tried on."~
    Wait(5)
END

IF
  Global("Patron_Arrived","AR0611",2)
THEN
  RESPONSE #100
    Face(14)
    Wait(6)
    FloatMessage(Myself,27439)  // ~::Sigh:: "No fatter than the others you've tried on today."~
    Wait(5)
END

IF
  Global("Patron_Arrived","AR0611",0)
THEN
  RESPONSE #100
    Face(12)
END

