IF
  NearLocation(Myself,[1725.1437],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,PERSON_30)
    ChangeAIScript("0700cthg",DEFAULT)
END

IF
  NearLocation(Myself,[1925.1468],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,PERSON_31)
    ChangeAIScript("0700cthg",DEFAULT)
END

IF
  NearLocation(Myself,[1819.1452],0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,PERSON_32)
    ChangeAIScript("0700cthg",DEFAULT)
END

