IF
  Die()
THEN
  RESPONSE #100
    IncrementGlobal("Murder","GLOBAL",1)
    IncrementGlobal("Good","GLOBAL",-1)
    IncrementGlobal("Law","GLOBAL",-1)
END

IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  Help("CrstFem")  // ~Curst Citizen~
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  Help("Crstmal")  // ~Curst Citizen~
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  Help("CrstMch")  // <Invalid Strref -1>
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  True()
THEN
  RESPONSE #100
    MoveToPoint([1838.1503])
    Face(10)
    Wait(45)
    MoveToPoint([1716.2415])
    Face(2)
    Wait(15)
    MoveToPoint([917.1079])
    Face(14)
END

