IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,PERSON_6)
    Continue()
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
    Continue()
END

IF
  Internal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,10)
THEN
  RESPONSE #100
    FloatMessage(Myself,68020)  // ~"I wouldn't be too sure of that."~
    Wait(3)
    SetInternal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,11)
END

