IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,PERSON_5)
    Continue()
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
    Continue()
END

IF
  Internal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,5)
THEN
  RESPONSE #100
    FloatMessage(Myself,68016)  // ~"That bird's goin' down in feathers, mark my words."~
    Wait(3)
    SetInternal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,6)
END

IF
  Internal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,15)
THEN
  RESPONSE #100
    MoveToObjectEx([0.0.0.0.0.0.DUELER_2],0)
END

IF
  Internal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,16)
THEN
  RESPONSE #100
    MoveToPoint([1340.3368])
    Face(10)
END

IF
  Internal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,18)
THEN
  RESPONSE #100
    FloatMessage(Myself,68025)  // ~"I got a lot o' money ridin' on you, bird!"~
    Wait(10)
END

