IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,PERSON_2)
    Continue()
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
    Continue()
END

IF
  Internal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,3)
THEN
  RESPONSE #100
    FloatMessage(Myself,68009)  // ~"Go on, boy! Nail 'im!"~
    Wait(3)
    SetInternal([0.0.0.0.0.0.DUELER_1][0.0.10000.10000],INTERNAL_0,4)
END

