IF
  Global("C_Off","GLOBAL",8)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("C_Off","GLOBAL",7)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFromEx(NearestEnemyOf(Myself),TEN_AI_SECONDS,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx([PC],TEN_AI_SECONDS,FALSE)
END

IF
  Help([ANYONE])
  !Help([PC])
  !Help([0.0.0.BAD])
  !Help([0.0.0.DEAD])
  !Help([0.HATMONIUM])
  !Help("Jasilya")  // ~Jasilya~
THEN
  RESPONSE #100
    Enemy()
    RunAwayFromEx([PC],TEN_AI_SECONDS,FALSE)
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(15,20)
    Face(14)
    WaitRandom(10,15)
    Face(2)
END

