IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeTeam(Myself,TEAM_NONGUARD)
END

IF
  Global("Cassius","GLOBAL",10)
  Internal(Myself,INTERNAL_0,0)
THEN
  RESPONSE #100
    Enemy()
    JumpToPoint([745.1505])
    Face(-1)
    SetInternal(Myself,INTERNAL_0,1)
    Continue()
  RESPONSE #200
    Enemy()
    JumpToPoint([580.2214])
    Face(-1)
    SetInternal(Myself,INTERNAL_0,1)
    Continue()
END

IF
  Global("Cassius","GLOBAL",10)
  Exists([0.0.TEAM_1])
THEN
  RESPONSE #100
    Attack([0.0.TEAM_1])
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  Help([0.0.TEAM_NONGUARD])
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

