IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    PolymorphEx(Vhailor,0)
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  Range([PC],30)
THEN
  RESPONSE #100
    StartSong(CHAR_VHAILOR,[0.0],Normal)
    Continue()
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

