IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
END

IF
  True()
THEN
  RESPONSE #100
    Wait(17)
    MoveToPoint([1004.787])
    Face(2)
    Wait(15)
    MoveToPoint([964.219])
    Face(10)
    Wait(5)
    MoveToPoint([1004.787])
    Face(2)
    Wait(15)
    MoveToPoint([778.656])
    Face(4)
    Continue()
END

