IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
END

IF
  True()
THEN
  RESPONSE #100
    Wait(10)
    MoveToPoint([300.616])
    Face(4)
    Wait(15)
    MoveToPoint([399.709])
    Face(0)
    Wait(5)
    MoveToPoint([300.616])
    Face(4)
    Wait(15)
    MoveToPoint([592.575])
    Face(14)
    Continue()
END

