IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeTeam(Myself,TEAM_1)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.TEAM_1])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  True()
THEN
  RESPONSE #100
    Face(12)
    Wait(10)
    MoveToPoint([535.980])
    Face(14)
    Wait(10)
    MoveToPoint([931.1287])
    Face(0)
    Wait(10)
    MoveToPoint([1264.1135])
    Face(12)
    Wait(10)
    MoveToPoint([855.912])
    Face(8)
    Wait(10)
    MoveToPoint([654.632])
    Face(8)
    Wait(10)
    MoveToPoint([2091.601])
    Face(0)
    Wait(30)
END

