IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    GlobalSet("0706_Make_Enemy","AR0706",1)
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  Global("0706_Make_Enemy","AR0706",1)
THEN
  RESPONSE #100
    FaceObject([PC][0.0.10000.10000])
    Enemy()
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

