IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
END

IF
  Allegiance(Myself,ENEMY)
  Internal(Myself,INTERNAL_0,0)
THEN
  RESPONSE #100
    SetInternal([0.0.TEAM_1][0.0.10000.10000],INTERNAL_1,1)
    SetInternal([0.0.TEAM_2][0.0.10000.10000],INTERNAL_1,1)
    SetInternal(Myself,INTERNAL_0,1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

