IF
  Die()
  GlobalGT("Curst_Murder","GLOBAL",14)
THEN
  RESPONSE #100
    GlobalSet("Curst_Force_Spawn","GLOBAL",1)
    Continue()
END

IF
  Die()
  GlobalLT("Curst_Murder","GLOBAL",15)
THEN
  RESPONSE #100
    IncrementGlobal("Curst_Murder","GLOBAL",1)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,GANGER_1)
    Continue()
END

IF
  Global("Lynch_Mob","GLOBAL",1)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  GlobalGT("Lynch_Mob","GLOBAL",1)
THEN
  RESPONSE #100
    Kill(Myself)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    RunAwayFromEx(NearestEnemyOf(Myself),50,FALSE)
END

IF
  Help([0.0.0.0.0.0.GANGER_1])
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(NearestEnemyOf(LastHelp),50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

