IF
  Die()
  GlobalGT("Curst_Murder","GLOBAL",14)
THEN
  RESPONSE #100
    GlobalSet("Curst_Force_Spawn","GLOBAL",1)
    Continue()
END

IF
  Die()
  GlobalLT("Curst_Murder","GLOBAL",15)
THEN
  RESPONSE #100
    IncrementGlobal("Curst_Murder","GLOBAL",1)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  See([PC])
  !TimerActive(1)
THEN
  RESPONSE #100
    StartTimer(1,10)
    FaceObject([PC])
    PlaySequence(ANIM_CAST)
    ReallyForceSpellLevel([PC],WIZARD_MAGIC_MISSILE,7)
  RESPONSE #100
    StartTimer(1,10)
    FaceObject([PC])
    PlaySequence(ANIM_CAST)
    ReallyForceSpellLevel([PC],WIZARD_ICE_KNIFE,7)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    FaceObject(LastAttackerOf(Myself))
END

