IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,PERSON_3)
    Continue()
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    ReturnToSavedPlace()
    Continue()
END

IF
  Global("Curst_Execution_One","GLOBAL",2)
THEN
  RESPONSE #100
    FloatMessage(Myself,52850)  // ~"Do you understand the charges put forth against you?"~
    Wait(2)
    GlobalSet("Curst_Execution_One","GLOBAL",3)
END

IF
  Global("Curst_Execution_One","GLOBAL",4)
THEN
  RESPONSE #100
    FloatMessage(Myself,52848)  // ~"And do you have anything to say in your defense?"~
    Wait(2)
    GlobalSet("Curst_Execution_One","GLOBAL",5)
END

IF
  Global("Curst_Execution_One","GLOBAL",6)
THEN
  RESPONSE #100
    FloatMessage(Myself,52846)  // ~"Right then.  Citizens of Curst, do you understand the charges put forth against our respectable official?"~
    Wait(2)
    GlobalSet("Curst_Execution_One","GLOBAL",7)
END

IF
  Global("Curst_Execution_One","GLOBAL",10)
THEN
  RESPONSE #100
    FloatMessage(Myself,52842)  // ~"And having understood those charges and having the opportunity to hear the statement of the defense, how do you rule?"~
    Wait(5)
    GlobalSet("Curst_Execution_One","GLOBAL",11)
END

IF
  Global("Curst_Execution_One","GLOBAL",15)
THEN
  RESPONSE #100
    FloatMessage(Myself,52855)  // ~"Then we have a verdict.  Executioner, please be about your business."~
    Wait(3)
    GlobalSet("Curst_Execution_One","GLOBAL",16)
END

IF
  Global("Curst_Execution_Two","GLOBAL",2)
THEN
  RESPONSE #100
    FloatMessage(Myself,52850)  // ~"Do you understand the charges put forth against you?"~
    Wait(2)
    GlobalSet("Curst_Execution_Two","GLOBAL",3)
END

IF
  Global("Curst_Execution_Two","GLOBAL",4)
THEN
  RESPONSE #100
    FloatMessage(Myself,52848)  // ~"And do you have anything to say in your defense?"~
    Wait(2)
    GlobalSet("Curst_Execution_Two","GLOBAL",5)
END

IF
  Global("Curst_Execution_Two","GLOBAL",7)
THEN
  RESPONSE #100
    FloatMessage(Myself,52852)  // ~"What th..."~
    Wait(2)
    GlobalSet("Curst_Execution_Two","GLOBAL",8)
END

IF
  Global("Curst_Execution_Two","GLOBAL",9)
THEN
  RESPONSE #100
    GlobalSet("Curst_Execution_Two","GLOBAL",0)
    GlobalSet("Execution_Chaos","AR0900",1)
    Kill(Myself)
END

