IF
  Die()
  GlobalGT("Curst_Murder","GLOBAL",14)
THEN
  RESPONSE #100
    GlobalSet("Curst_Force_Spawn","GLOBAL",1)
    Continue()
END

IF
  Die()
  GlobalLT("Curst_Murder","GLOBAL",15)
THEN
  RESPONSE #100
    IncrementGlobal("Curst_Murder","GLOBAL",1)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  !Global("Curst_Execution_Two","GLOBAL",0)
  Global("Execution_Chaos","AR0900",0)
THEN
  RESPONSE #100
    GlobalSet("Curst_Execution_Two","GLOBAL",0)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  !Global("Curst_Execution_One","GLOBAL",0)
  Global("Execution_Chaos","AR0900",0)
THEN
  RESPONSE #100
    GlobalSet("Curst_Execution_One","GLOBAL",0)
    Continue()
END

IF
  Global("Good_Judge_1","GLOBAL",1)
THEN
  RESPONSE #100
    GlobalSet("Curst_Execution_One","GLOBAL",0)
    GlobalSet("Curst_Execution_Two","GLOBAL",0)
    EscapeArea()
END

IF
  See(NearestEnemyOf(Myself))
  Global("Execution_Chaos","AR0900",0)
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  Help([0.0.0.0.0.0.PERSON_1])
  Global("Execution_Chaos","AR0900",0)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  Help([0.0.0.0.0.0.PERSON_3])
  Global("Execution_Chaos","AR0900",0)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  Help([0.0.0.0.0.0.GUARD_1])
  Global("Execution_Chaos","AR0900",0)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  AttackedBy([ANYONE],DEFAULT)
  !Global("Curst_Execution_One","GLOBAL",0)
  !Global("Curst_Execution_Two","GLOBAL",0)
  Global("Execution_Chaos","AR0900",0)
THEN
  RESPONSE #100
    GlobalSet("Curst_Execution_One","GLOBAL",0)
    GlobalSet("Curst_Execution_Two","GLOBAL",0)
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  AttackedBy([ANYONE],DEFAULT)
  Global("Execution_Chaos","AR0900",0)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
  Global("Execution_Chaos","AR0900",1)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

