IF
  OnCreation()
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  See([PC])
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack([PC])
END

IF
  See([0.0.0.0.0.0.GUARD_1])
  !See([PC])
THEN
  RESPONSE #100
    Enemy()
    Attack([0.0.0.0.0.0.GUARD_1])
END

IF
  Help([0.0.0.0.GEHRELETH])
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

