IF
  See([PC])
THEN
  RESPONSE #100
    Help()
    RunToObject([PC])
    Attack([PC])
END

IF
  Help([0.0.0.0.SOHMIEN])
  Global("Sohmien_Pack_Three","AR0901",1)
THEN
  RESPONSE #100
    Help()
    RunToObject(Protagonist)
    Attack(NearestEnemyOf(LastHelp))
END

IF
  Global("Sohmien_Pack_Three","AR0901",1)
THEN
  RESPONSE #100
    RunToPoint([3952.479])
    RunToPoint([3853.610])
    Face(2)
END

IF
  Global("Sohmien_Pack_Three","AR0901",0)
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

