IF
  See([PC])
  Global("Sohmien_Pack_One","AR0901",1)
THEN
  RESPONSE #100
    Help()
    RunToObject([PC])
    Attack([PC])
END

IF
  Help([0.0.0.0.SOHMIEN])
  Global("Sohmien_Pack_One","AR0901",1)
THEN
  RESPONSE #100
    Help()
    RunToObject(Protagonist)
    Attack(NearestEnemyOf(LastHelp))
END

IF
  Global("Sohmien_Pack_One","AR0901",1)
THEN
  RESPONSE #100
    RunToPoint([3394.1135])
    RunToPoint([3321.1147])
    Face(2)
END

IF
  Global("Sohmien_Pack_One","AR0901",0)
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

