IF
  OnCreation()
THEN
  RESPONSE #100
    GlobalSet("Damsel_Abishai","GLOBAL",0)
END

IF
  See([PC])
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(NearestEnemyOf(LastHelp))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack(LastAttackerOf(Myself))
END

