IF
  OnCreation()
THEN
  RESPONSE #100
    SetInternal(Myself,INTERNAL_1,0)
    GlobalSet("0104C_Spawn","GLOBAL",0)
END

IF
  HPPercentLT(Myself,51)
THEN
  RESPONSE #100
    RunAwayFromEx(NearestEnemyOf(Myself),5,FALSE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  Global("0104C_Angry","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

IF
  Internal(Myself,INTERNAL_1,0)
  NearLocation([PC][658.215.400.-1],[658.215],15)
THEN
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,64212)  // ~"Hey berk, don't be taking anything that's not yours!"~
    SetInternal(Myself,INTERNAL_1,1)
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(5,10)
    Face(14)
    WaitRandom(5,10)
    Face(12)
END

