IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
    Continue()
END

IF
  True()
THEN
  RESPONSE #100
    WaitRandom(5,10)
    Continue()
END

IF
  NearLocation(Myself,[786.1096],0)
THEN
  RESPONSE #100
    Face(10)
END

IF
  NearLocation(Myself,[842.1064],0)
THEN
  RESPONSE #100
    Face(0)
END

IF
  NearLocation(Myself,[801.1152],0)
THEN
  RESPONSE #100
    Face(10)
END

IF
  NearLocation(Myself,[898.1110],0)
THEN
  RESPONSE #100
    Face(2)
END

