IF
  OnCreation()
THEN
  RESPONSE #100
    SetInternal(Myself,INTERNAL_1,0)
END

IF
  Die()
THEN
  RESPONSE #100
    IncrementGlobal("1101_Cutscene","AR1101",-1)
END

IF
  See(NearestEnemyOf(Myself))
  Internal(Myself,INTERNAL_1,1)
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  See(NearestEnemyOf(Myself))
  Global("1101_Demons_Hostile","AR1101",1)
  Dead("Fhjull")  // ~Crippled Cornugon~
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("1101_Demons_Hostile","AR1101",1)
    SetInternal(Myself,INTERNAL_1,1)
    FaceObject(LastAttackerOf(Myself))
    Attack(LastAttackerOf(Myself))
END

IF
  See("Fhjull")  // ~Crippled Cornugon~
THEN
  RESPONSE #100
    Attack("Fhjull")
END

IF
  Dead("Fhjull")  // ~Crippled Cornugon~
  Global("1101_Demons_Hostile","AR1101",0)
THEN
  RESPONSE #100
    EscapeArea()
END

