IF
  HarmlessEntered([PC])
  !Dead("Fhjull")  // ~Crippled Cornugon~
  Global("1101_CutScene_2","AR1101",0)
  Global("Curst_Portal","GLOBAL",1)
THEN
  RESPONSE #100
    GlobalSet("1101_CutScene_2","AR1101",1)
    StartCutSceneMode()
    ClearAllActions()
    KillFloatMessage("Fhjull")
    DisableFogDither()
    DisableSpriteDither()
    MoveViewObject("Fhjull",INSTANT)
    StartCutScene("1101cut5")
END

