IF
  OnCreation()
THEN
  RESPONSE #100
    SetInternal(Myself,INTERNAL_1,0)
END

IF
  WasInDialog()
THEN
  RESPONSE #100
    StartCutSceneMode()
    StartCutScene("1200cut2")
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    PlaySequence(ANIM_DIE)
    Wait(3)
    GlobalSet("Game_Over","GLOBAL",3)
    DestroySelf()
END

IF
  Range([PC],32)
THEN
  RESPONSE #100
    StartSong(CHAR_DEIONARRA,[0.0],Normal)
END

