IF
  True()
THEN
  RESPONSE #100
    CutSceneId("VhailF")  // 
    SetAnimState(Myself,ANIM_TWITCH)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Trans")  // 
    Wait(1)
    StartSong(CHAR_VHAILOR,[0.0],Normal)
    FadeFromBlack()
    Wait(4)
    MoveToPoint([4561.1028])
    FaceObject("VhailF")
    Wait(2)
    StartSong(CHAR_VHAILOR,[0.0],Normal)
    PlaySoundNotRanged("Tra040")
    PlaySequence(ANIM_MISC1)
    Wait(3)
    StartCutScene("1201CV12")
END

