IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Trans")  // 
    DestroySelf()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("NordomF")  // 
    DestroySelf()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Nameless")  // 
    EnableFogDither()
    EnableSpriteDither()
    ExploreMapChunk([4493.1095],0,600)
    MoveViewPoint([3889.2933],INSTANT)
    FadeFromBlack()
    Wait(3)
    SinisterPoof("EF02TPR2",[3889.2933],1)
    EndCutSceneMode()
    JumpToPoint([3889.2933])
END

