IF
  True()
THEN
  RESPONSE #100
    CutSceneId("DakkonF")  // 
    Wait(1)
    Face(6)
    Wait(1)
    StartSong(CHAR_DAKKON,[0.0],Normal)
    Face(14)
    Wait(1)
    StartCutScene("1201csD3")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("D_Shadow_2")  // 
    MoveToPoint([4402.999])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("D_Shadow_3")  // 
    StartSong(CHAR_DAKKON,[0.0],Normal)
    MoveToPoint([4588.1182])
END

