IF
  True()
THEN
  RESPONSE #100
    CutSceneId("VhailF")  // 
    Face(2)
    PolymorphEx("""""(cl 1) Vhailor Still""""",0)
    FadeFromBlack()
    StickySinisterPoof("S113SMOK","VhailF",1)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Trans")  // 
    Wait(4)
    StartSong(CHAR_VHAILOR,[0.0],Normal)
    MoveToPoint([4561.1028])
    FaceObject("VhailF")
    Wait(2)
    StickySinisterPoof("S113SMOK","VhailF",1)
    StartCutScene("1201CV22")
END

