IF
  HPPercentLT(Myself,100)
THEN
  RESPONSE #100
    Attack([PC])
END

IF
  !LOS(NearestEnemyOf(Myself),32)
THEN
  RESPONSE #100
    ClearActions()
END

IF
  LOS(NearestEnemyOf(Myself),32)
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

