IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Nameless")  // 
    FadeToBlack()
    StartSong(CHAR_DAKKON,[0.0],Normal)
    Wait(3)
    DisableFogDither()
    DisableSpriteDither()
    ExploreMapChunk([4493.1095],0,600)
    MoveViewPoint([4493.1095],INSTANT)
    StartSong(CHAR_DAKKON,[0.0],Normal)
    GlobalSet("Spawn_Dakkon_Shadow","GLOBAL",1)
    CreateCreature("DakkonF",[4124.1426])  // ~Githzerai~
    FadeFromBlack()
    Wait(2)
    StartCutScene("1201csD1")
END

