IF
  True()
THEN
  RESPONSE #100
    CutSceneId("IgnusF")  // 
    SetAnimState(Myself,ANIM_TWITCH)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Trans")  // 
    Wait(1)
    StartSong(CHAR_IGNUS,[0.0],Normal)
    FadeFromBlack()
    Wait(2)
    MoveToPoint([4561.1028])
    FaceObject("IgnusF")
    Wait(2)
    StartSong(CHAR_IGNUS,[0.0],Normal)
    PlaySoundNotRanged("Tra038")
    PlaySequence(ANIM_MISC1)
    Wait(3)
    StartCutScene("1201CI12")
END

