IF
  See([PC])
THEN
  RESPONSE #100
    Help()
    Attack([PC])
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([ANYONE])
THEN
  RESPONSE #100
    Attack(LastAttackerOf(LastHelp))
END

IF
  HPPercentLT(Myself,33)
THEN
  RESPONSE #100
    RunAwayFromEx([PC],TWO_AI_SECONDS,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    Wait(1)
    Face(14)
    WaitRandom(3,5)
    Face(8)
    MoveToPoint([3480.943])
    WaitRandom(3,5)
    Face(14)
    MoveToPoint([3582.1039])
    WaitRandom(3,5)
    Face(12)
    MoveToPoint([3834.1039])
    WaitRandom(3,5)
    Face(4)
    MoveToPoint([3237.1132])
    MoveToPoint([3486.1137])
    Face(2)
END

