IF
  Die()
THEN
  RESPONSE #100
    GlobalSet("1400_Area_A","GLOBAL",0)
    GlobalSet("1400_Area_B","GLOBAL",0)
    BitSet("1400_Status","AR1400",BIT6)
END

IF
  BitCheck("1400_Status","AR1400",BIT6)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  !HaveAnySpells()
THEN
  RESPONSE #100
    BitSet("1400_Status","AR1400",BIT6)
END

IF
  HaveAnySpells()
THEN
  RESPONSE #100
    FaceObject([PC])
    Spell([PC],WIZARD_BALL_LIGHTNING)
    Wait(5)
    Spell([PC],WIZARD_BALL_LIGHTNING)
    Wait(5)
    Spell([PC],WIZARD_SWARM_CURSE)
    Wait(5)
    Spell([PC],WIZARD_ICE_KNIFE)
    Wait(5)
    Spell([PC],WIZARD_ICE_KNIFE)
    Wait(5)
    Spell([PC],WIZARD_BLINDNESS)
    Wait(5)
    Spell([PC],WIZARD_MAGIC_MISSILE)
    Wait(5)
    Spell([PC],WIZARD_MAGIC_MISSILE)
    Wait(5)
    Spell([PC],WIZARD_CHROMATIC_ORB)
END

