IF
  See([PC])
THEN
  RESPONSE #100
    Attack([PC])
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Attack(LastAttackerOf(Myself))
END

IF
  Help([0.0.TEAM_2])
THEN
  RESPONSE #100
    Attack(LastAttackerOf(LastHelp))
END

IF
  True()
THEN
  RESPONSE #100
    MoveToPoint([1079.1822])
    Wait(2)
    MoveToPoint([1593.1648])
    Wait(2)
    MoveToPoint([1176.1687])
    Wait(2)
END

