IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeTeam(Myself,TEAM_NONGHOUL)
    SetInternal(Myself,INTERNAL_1,0)
END

IF
  Global("Undead_Alert","AR1500",1)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Global("Ghoul_Attack","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
    SetInternal(Myself,INTERNAL_1,2)
    ChangeAIScript("1500bdz",DEFAULT)
END

IF
  !Internal(Myself,INTERNAL_1,1)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    GlobalSet("Undead_Alert","AR1500",1)
    Enemy()
    SetInternal(Myself,INTERNAL_1,2)
    Attack(LastAttackerOf(Myself))
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

IF
  Internal(Myself,INTERNAL_1,0)
  StealFailed([PC])
THEN
  RESPONSE #100
    Enemy()
    SetInternal(Myself,INTERNAL_1,1)
END

IF
  Internal(Myself,INTERNAL_1,1)
  !TimerActive(1)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,66554)  // ~"You wanna pick something? Try picking your head up off the floor! HA!"~
    StartRandomTimer(1,20,40)
  RESPONSE #100
    FaceObject([PC])
    FloatMessage(Myself,66553)  // ~"Wanna steal something? Go ahead. I'll just collect it from your carcass later! HA!"~
    StartRandomTimer(1,20,40)
END

IF
  Global("Nap_Time","AR1500",1)
THEN
  RESPONSE #100
    ChangeAIScript("1500sk8b",DEFAULT)
END

IF
  !NearSavedLocation(0)
  Global("Nap_Time","AR1500",0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
    Continue()
END

IF
  Global("Nap_Time","AR1500",0)
THEN
  RESPONSE #100
    WaitRandom(4,6)
    FloatMessage(Myself,48282)  // ~::Whistles Merrily::~
END

