IF
  !Allegiance(Myself,ENEMY)
  Global("1501_Undead_Alert","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    GlobalSet("1501_Undead_Alert","GLOBAL",1)
    Attack(LastAttackerOf(Myself))
END

IF
  Help([ANYONE])
  !Help([PC])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

