IF
  BitCheck("1600_Status","AR1600",BIT3)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("AR1601_Visited","GLOBAL",1)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    StartCutSceneMode()
    StartCutScene("Zap")
END

IF
  See([PC])
  !BitCheck("1600_Status","AR1600",BIT2)
THEN
  RESPONSE #100
    Dialogue([PC])
    BitSet("1600_Status","AR1600",BIT2)
END

