IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Help()
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

IF
  See([0.0.0.0.VARGOUILLE])
THEN
  RESPONSE #100
    Attack([0.0.0.0.VARGOUILLE])
END

IF
  Help([0.0.0.0.GHOUL])
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(LastHelp))
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Help()
    Attack(NearestEnemyOf(Myself))
END

IF
  See([PC])
  Global("Ghoul_Attack","GLOBAL",1)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack([PC])
END

IF
  See([PC])
  Global("CR_Vic","GLOBAL",3)
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack([PC])
END

IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,GHOUL7)
END

IF
  Die()
  GlobalLT("Troco_Calm","AR1700",2)
THEN
  RESPONSE #100
    GlobalSet("Ghoul_Pissed_B","AR1700",1)
    GlobalSet("Troco_Calm","AR1700",1)
END

IF
  See([PC])
  Global("Ghoul_Pissed_B","AR1700",1)
THEN
  RESPONSE #100
    Enemy()
    Attack([PC])
END

IF
  Global("Troco_Calm","AR1700",2)
THEN
  RESPONSE #100
    MoveToPoint([1999.467])
    Face(10)
    PlaySequence(ANIM_STANDFIDGET1)
    WaitRandom(2,5)
    PlaySequence(ANIM_STANDFIDGET2)
    WaitRandom(2,5)
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

