IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    RunAwayFromEx(LastAttackerOf(Myself),50,FALSE)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Attack(LastAttackerOf(Myself))
END

IF
  See([0.0.0.0.GHOUL])
THEN
  RESPONSE #100
    Attack([0.0.0.0.GHOUL])
END

IF
  See([PC])
THEN
  RESPONSE #100
    Enemy()
    Help()
    Attack([PC])
END

IF
  !NearSavedLocation(0)
THEN
  RESPONSE #100
    ReturnToSavedPlace()
END

