IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Vlask")  // 
    TimedMoveToPoint([647.481],75)
    DestroySelf()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("3006Athug1")  // 
    Wait(2)
    TimedMoveToPoint([647.481],75)
    DestroySelf()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("3006Athug2")  // 
    Wait(4)
    TimedMoveToPoint([647.481],75)
    EndCutSceneMode()
    DestroySelf()
END

