IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Vlask")  // 
    TimedMoveToPoint([482.468],120)
    Face(8)
    Wait(8)
    Dialogue([PC])
    EndCutSceneMode()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("3006Athug1")  // 
    Wait(2)
    MoveToPoint([442.497])
    Face(8)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("3006Athug2")  // 
    Wait(4)
    MoveToPoint([524.497])
    Face(8)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    TimedMoveToPoint([482.418],120)
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    MoveToPoint([446.397])
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    MoveToPoint([519.397])
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    MoveToPoint([548.367])
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    MoveToPoint([465.367])
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    MoveToPoint([505.367])
    Face(0)
END

