IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Rauk")  // 
    MoveViewPoint([589.518],VERY_FAST)
    TimedMoveToPoint([573.597],75)
    Face(8)
    FloatMessage(Myself,48674)  // ~"Masters, Rauk has the rings."~
    Wait(2)
    TimedMoveToPoint([628.657],75)
    Face(6)
    StartCutScene("3012cut2")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Nameless")  // 
    TimedMoveToPoint([720.628],75)
    Face(6)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_1][0.0.10000.10000])  // 
    Face(14)
    Wait(2)
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_2][0.0.10000.10000])  // 
    Face(14)
    Wait(2)
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_3][0.0.10000.10000])  // 
    Face(14)
    Wait(2)
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_4][0.0.10000.10000])  // 
    Face(14)
    Wait(2)
    Face(0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_5][0.0.10000.10000])  // 
    Face(14)
    Wait(2)
    Face(0)
END

