IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_1][0.0.10000.10000])  // 
    FloatMessage(Myself,48675)  // ~"Aaaaaah..."~
    Wait(5)
    FloatMessage(Myself,48682)  // ~"Ahem!"~
    Wait(1)
    TimedMoveToPoint([599.497],45)
    Face(4)
    Wait(3)
    StartCutScene("3012cut4")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_2][0.0.10000.10000])  // 
    Wait(2)
    FloatMessage(Myself,48676)  // ~"Braaaaa..."~
    Wait(5)
    TimedMoveToPoint([594.523],45)
    Face(6)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_3][0.0.10000.10000])  // 
    Wait(3)
    FloatMessage(Myself,48677)  // ~"Caaaaaa..."~
    Wait(4)
    TimedMoveToPoint([557.523],45)
    Face(10)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_4][0.0.10000.10000])  // 
    Wait(4)
    FloatMessage(Myself,48678)  // ~"Daaaaa..."~
    Wait(3)
    TimedMoveToPoint([545.497],45)
    Face(12)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId([0.0.0.0.0.0.PERSON_5][0.0.10000.10000])  // 
    Wait(6)
    FloatMessage(Myself,48683)  // ~"Oops!  Braaaaa..."~
    Wait(1)
    TimedMoveToPoint([572.478],45)
    Face(0)
END

