IF
  Help([ANYONE])
  !Help([PC])
  Internal(Myself,INTERNAL_0,0)
THEN
  RESPONSE #100
    Enemy()
    Help()
    SetInternal(Myself,INTERNAL_0,1)
END

IF
  See(NearestEnemyOf(Myself))
  Internal(Myself,INTERNAL_0,0)
THEN
  RESPONSE #100
    Help()
    SetInternal(Myself,INTERNAL_0,1)
END

IF
  AttackedBy([ANYONE],DEFAULT)
  Internal(Myself,INTERNAL_0,0)
THEN
  RESPONSE #100
    Enemy()
    Help()
    SetInternal(Myself,INTERNAL_0,1)
END

IF
  OnCreation()
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,PERSON_5)
END

IF
  Internal(Myself,INTERNAL_0,1)
  See([PC])
THEN
  RESPONSE #100
    FaceObject([PC])
    ForceSpell([PC],WIZARD_MAGIC_MISSILE)
    Wait(1)
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  Internal(Myself,INTERNAL_0,2)
  See([PC])
THEN
  RESPONSE #100
    ForceSpell([PC],WIZARD_MAGIC_MISSILE)
    Wait(1)
    IncInternal(Myself,INTERNAL_0,1)
END

IF
  InternalGT(Myself,INTERNAL_0,2)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  Global("Summon_Dance","AR3012",0)
  !NearLocation(Myself,[572.451],0)
THEN
  RESPONSE #100
    MoveToPoint([572.451])
    Face(0)
    Wait(6)
    FloatMessage(Myself,48679)  // ~"Oh!  Braaaaa..."~
    Wait(1)
    GlobalSet("Summon_Dance","AR3012",1)
END

IF
  Global("Summon_Dance","AR3012",1)
  !NearLocation(Myself,[516.497],0)
THEN
  RESPONSE #100
    MoveToPoint([516.497])
    Face(14)
    Wait(6)
    FloatMessage(Myself,48680)  // ~"Um...Braaaaa..."~
    Wait(1)
    GlobalSet("Summon_Dance","AR3012",0)
END

