IF
  Exists("Nameless")  // ~Nameless One~
  !GlobalGT("AR0200_Visited","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("AR0200_Visited","GLOBAL",1)
    Continue()
END

IF
  InParty("Morte")  // ~Talking Skull~
  !BitCheck("0200_Status","AR0200",BIT1)
THEN
  RESPONSE #100
    BitSet("0200_Status","AR0200",BIT1)
    ChangeDialog("Morte","DMorte")
    Continue()
END

IF
  BitCheck("0200_Status","AR0200",BIT2)
  !NearLocation([PC][622.1034.400.-1],[622.1034],20)
THEN
  RESPONSE #100
    BitClear("0200_Status","AR0200",BIT2)
    ActivatePortalCursor("TravelTrigger1",0)
    EnablePortalTravel("TravelTrigger1",0)
END

IF
  !Global("Current_Area","GLOBAL",200)
THEN
  RESPONSE #100
    GlobalSet("Modron_Cube","GLOBAL",1)
    GlobalSet("Mortuary_Alert_1","GLOBAL",1)
    GlobalSet("Mortuary_Alert_2","GLOBAL",1)
    GlobalSet("Mortuary_Alert_3","GLOBAL",1)
    GlobalSet("Current_Area","GLOBAL",200)
    Continue()
END

IF
  Global("Mortuary_Alert","GLOBAL",1)
THEN
  RESPONSE #100
    GlobalSet("Mortuary_Alert","GLOBAL",0)
END

IF
  Global("Escape_Mortuary","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("Escape_Mortuary","GLOBAL",1)
END

