IF
  !Global("Current_Area","GLOBAL",602)
THEN
  RESPONSE #100
    GlobalSet("Current_Area","GLOBAL",602)
    Continue()
END

IF
  Exists("Nameless")  // ~Nameless One~
  !GlobalGT("AR0602_Visited","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("AR0602_Visited","GLOBAL",1)
    Continue()
END

IF
  GlobalTimerExpired("0602_Timer_1","AR0602")
  Global("0602_Sen_8","AR0602",0)
THEN
  RESPONSE #100
    CreateCreature("SensF3",[1599.1631])  // ~Sensate~
    GlobalSet("0602_Sen_8","AR0602",2)
END

