IF
  !Global("Current_Area","GLOBAL",611)
THEN
  RESPONSE #100
    GlobalSet("Current_Area","GLOBAL",611)
    Continue()
END

IF
  Exists("Nameless")  // ~Nameless One~
  !GlobalGT("AR0611_Visited","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("AR0611_Visited","GLOBAL",1)
    Continue()
END

IF
  Global("Wandering_Patron","AR0611",0)
THEN
  RESPONSE #100
    Wait(60)
    CreateCreature("Patron7",[807.960])  // ~Sensate~
    GlobalSet("Wandering_Patron","AR0611",1)
END

