IF
  Exists("Nameless")  // ~Nameless One~
  Global("AR1100_Visited","GLOBAL",0)
THEN
  RESPONSE #100
    StartMovie("Outlands")
    StickySinisterPoof("EF02TPR2",Player1,1)
    StickySinisterPoof("EF02TPR2",Player2,1)
    StickySinisterPoof("EF02TPR2",Player3,1)
    StickySinisterPoof("EF02TPR2",Player4,1)
    StickySinisterPoof("EF02TPR2",Player5,1)
    StickySinisterPoof("EF02TPR2",Player6,1)
    GlobalSet("AR1100_Visited","GLOBAL",1)
    Continue()
END

IF
  !Global("Current_Area","GLOBAL",1100)
THEN
  RESPONSE #100
    GlobalSet("Current_Area","GLOBAL",1100)
    Continue()
END

IF
  Global("AR1000_Visited","GLOBAL",1)
  Global("Portal_Open","GLOBAL",1)
THEN
  RESPONSE #100
    ActivatePortalCursor("to1000",0)
    EnablePortalTravel("to1000",0)
    GlobalSet("Portal_Open","GLOBAL",2)
END

IF
  Exists("1100pack1")  // 1100pack1
  Exists("1100pack2")  // 1100pack2
  Exists("1100pack3")  // 1100pack3
  Exists("1100bait3")  // 1100bait3
  Global("1100_Spawn_Once","GLOBAL",1)
THEN
  RESPONSE #100
    GlobalSet("1100_Spawn_Once","GLOBAL",0)
    Continue()
END

IF
  !Exists("1100pack1")  // 1100pack1
  !Exists("1100lead1")  // 1100lead1
  !Exists("1100foll1")  // 1100foll1
  Global("Gronk_Pack1_Respawn","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("Gronk_Pack1_Respawn","GLOBAL",1)
    Continue()
END

IF
  !Exists("1100pack2")  // 1100pack2
  !Exists("1100lead2")  // 1100lead2
  !Exists("1100foll2")  // 1100foll2
  Global("Gronk_Pack2_Respawn","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("Gronk_Pack2_Respawn","GLOBAL",1)
    Continue()
END

IF
  !Exists("1100pack3")  // 1100pack3
  !Exists("1100bait3")  // 1100bait3
  !Exists("1100lead3")  // 1100lead3
  !Exists("1100foll3")  // 1100foll3
  Global("Grillig_Pack_Respawn","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("Grillig_Pack_Respawn","GLOBAL",1)
    Continue()
END

