IF
  Global("AR0508_Visited","GLOBAL",0)
  !BitCheck("1600_Status","AR1600",BIT1)
  !Dead("Mantuok")  // ~Wererat~
THEN
  RESPONSE #100
    BitSet("1600_Status","AR1600",BIT1)
    CreateCreature("Mantuok",[1390.2354])  // ~Wererat~
    ForceAIScript("1600mant","Mantuok",DEFAULT)
    ForceFacing("Mantuok",2)
END

IF
  Global("CR_Vic","GLOBAL",1)
  Global("1600_PC_Enemy","AR1600",1)
THEN
  RESPONSE #100
    GlobalSet("1600_PC_Enemy","AR1600",0)
END

IF
  GlobalGT("CR_Vic","GLOBAL",2)
  !BitCheck("1600_Status","AR1600",BIT4)
THEN
  RESPONSE #100
    SetDoorLocked("a1600d08",FALSE)
    OpenDoor("a1600d08")
    BitSet("1600_Status","AR1600",BIT4)
END

IF
  !Global("Current_Area","GLOBAL",1600)
THEN
  RESPONSE #100
    GlobalSet("Current_Area","GLOBAL",1600)
    Continue()
END

IF
  Exists("Nameless")  // ~Nameless One~
  !GlobalGT("AR1600_Visited","GLOBAL",0)
THEN
  RESPONSE #100
    GlobalSet("AR1600_Visited","GLOBAL",1)
    Continue()
END

IF
  Global("1600_Guards_Spawn","GLOBAL",1)
  Exists("Shad")  // ~Wererat~
  Exists("Raimon")  // ~Wererat~
THEN
  RESPONSE #100
    GlobalSet("1600_Guards_Spawn","GLOBAL",0)
END

