IF
  Detected([ANYONE])
  Global("Switch2Detection5014","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Switch2Detection5014","GLOBAL",1)
    DisplayString("Switch2",72518)  // ~You have found a small hidden switch behind a trap. You shall have to disarm the trap if you wish to flick the switch.~
END

IF
  Disarmed([ANYONE])
  Global("Switch2Disarmed5014","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Switch2Disarmed5014","GLOBAL",1)
    IncrementGlobal("DoorSwitch5014","GLOBAL",1)
    DisplayString("Switch2",72519)  // ~You flick the switch and hear the muffled turning of gears.~
END

