IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  OR(2)
    GlobalLT("SolaufeinJob","GLOBAL",5)
    Global("DrowCityHostile","GLOBAL",1)
THEN
  RESPONSE #100
    DisplayString(Myself,57503)  // ~A loathsome fishlike creature floats within the tank. Long leathery tentacles grow from its head and the smell of rancid grease hangs about the tank. For the moment, the creature is motionless, as if sleeping.~
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("UsedAlboleth","AR2200",0)
THEN
  RESPONSE #100
    SetGlobal("UsedAlboleth","AR2200",1)
    CreateCreature("DAABOL",[805.3068],0)  // ~Aboleth~
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("UsedAlboleth","AR2200",1)
THEN
  RESPONSE #100
    ActionOverride("DAABOL",StartDialogNoSet([PC]))
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,12)
THEN
  RESPONSE #100
    DisplayString(Myself,42372)  // ~You must move closer to the creature in the tank to converse with it.~
END

