IF
  Opened([ANYONE])
  See([NOTGOOD])
  !StateCheck(LastTrigger,STATE_INVISIBLE)
  !StateCheck(LastTrigger,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    DisplayString(LastTrigger,9896)  // ~Someone has noticed you! You hear the guards being summoned!~ [AMB_D05A]
    Wait(3)
    CreateCreature("AMNISE",[-1.-1],0)  // AMNISE
    CreateCreature("AMNISE2",[-1.-1],0)  // AMNISE2
    CreateCreature("AMNISE2",[-1.-1],0)  // AMNISE2
END

