IF
  Delay(10)
  Entered([ANYONE])
  ReputationLT(LastTrigger,3)
  !StateCheck(LastTrigger,STATE_INVISIBLE)
  !StateCheck(LastTrigger,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #60
    Wait(3)
    CreateCreature("FLAMPUN",[-1.-1],0)  // FLAMPUN
    CreateCreature("FLAMPUN2",[-1.-1],0)  // FLAMPUN2
    CreateCreature("FLAMPUN2",[-1.-1],0)  // FLAMPUN2
    CreateCreature("FLAMSCO",[-1.-1],0)  // FLAMSCO
    CreateCreature("FLAMWIZ",[-1.-1],0)  // FLAMWIZ
  RESPONSE #40
    Wait(2)
END

