IF
  HasItem("POTN08",Myself)  // ~Potion of Healing~
  HPPercentLT(Myself,80)
THEN
  RESPONSE #100
    UseItem("POTN08",Myself)  // ~Potion of Healing~
END

IF
  HasItem("POTN52",Myself)  // ~Potion of Extra Healing~
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    UseItem("POTN52",Myself)  // ~Potion of Extra Healing~
END

IF
  HPPercentLT(Myself,10)
  HaveSpell(CLERIC_HEAL)
THEN
  RESPONSE #100
    Spell(Myself,0)
END

IF
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),4)
  HPPercentLT(Myself,20)
THEN
  RESPONSE #100
    RunAwayFrom(LastSeenBy(Myself),10)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),4)
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  HPPercentLT(Myself,20)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),4)
  HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
  HPPercentLT(Myself,20)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_SERIOUS_WOUNDS)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),5)
  HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
  HPPercentLT(Myself,40)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_MEDIUM_WOUNDS)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),10)
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),4)
  StateCheck(Myself,STATE_POISONED)
  HaveSpell(CLERIC_NEUTRALIZE_POISON)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_NEUTRALIZE_POISON)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),4)
  StateCheck(Myself,STATE_POISONED)
  HaveSpell(CLERIC_SLOW_POISON)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_SLOW_POISON)
END

IF
  See(NearestEnemyOf(Myself))
  StateCheck(Myself,STATE_SILENCED)
  HaveSpell(WIZARD_VOCALIZE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_VOCALIZE)
END

IF
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
  !HasBounceEffects(Myself)
  !HasImmunityEffects(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END

IF
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
  HaveSpell(WIZARD_MINOR_SPELL_TURNING)
  !HasBounceEffects(Myself)
  !HasImmunityEffects(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MINOR_SPELL_TURNING)
END

IF
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
  HaveSpell(WIZARD_SPELL_SHIELD)
  !HasBounceEffects(Myself)
  !HasImmunityEffects(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_SHIELD)
END

IF
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
  HaveSpell(WIZARD_SPELL_TURNING)
  !HasBounceEffects(Myself)
  !HasImmunityEffects(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TURNING)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_STONE_SKIN)
  CheckStatLT(Myself,1,STONESKINS)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_STONE_SKIN)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_IRONSKIN)
  CheckStatLT(Myself,1,STONESKINS)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_IRONSKIN)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_BLADE_BARRIER)
  Global("blade","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("blade","LOCALS",1)
    Spell(Myself,CLERIC_BLADE_BARRIER)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_ARMOR_OF_FAITH)
  CheckStatGT(Myself,1,ARMORCLASS)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_ARMOR_OF_FAITH)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SPIRIT_ARMOR)
  CheckStatGT(Myself,1,ARMORCLASS)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPIRIT_ARMOR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_GHOST_ARMOR)
  CheckStatGT(Myself,2,ARMORCLASS)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_GHOST_ARMOR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SHIELD)
  CheckStatGT(Myself,4,ARMORCLASS)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHIELD)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_ARMOR)
  CheckStatGT(Myself,6,ARMORCLASS)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_ARMOR)
END

IF
  Detect(NearestEnemyOf(Myself))
  !See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_TRUE_SIGHT)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_TRUE_SIGHT)
END

IF
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  HaveSpell(WIZARD_SPELL_THRUST)
  Global("pscript_SpellThrust","LOCALS",0)
  OR(2)
    HasBounceEffects(LastSeenBy(Myself))
    HasImmunityEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
    Wait(2)
    SetGlobal("pscript_SpellThrust","LOCALS",1)
END

IF
  Global("pscript_SpellThrust","LOCALS",1)
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  OR(2)
    HasBounceEffects(LastSeenBy(Myself))
    HasImmunityEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobal("pscript_SpellThrust","LOCALS",2)
END

IF
  Global("pscript_SpellThrust","LOCALS",1)
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  !HasBounceEffects(LastSeenBy(Myself))
  !HasImmunityEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobal("pscript_SpellThrust","LOCALS",0)
END

IF
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  HaveSpell(WIZARD_WARDING_WHIP)
  Global("pscript_WHIP","LOCALS",0)
  OR(2)
    HasBounceEffects(LastSeenBy(Myself))
    HasImmunityEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)
    Wait(2)
    SetGlobal("pscript_WHIP","LOCALS",1)
END

IF
  Global("pscript_WHIP","LOCALS",1)
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  OR(2)
    HasBounceEffects(LastSeenBy(Myself))
    HasImmunityEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobal("pscript_WHIP","LOCALS",2)
END

IF
  Global("pscript_WHIP","LOCALS",1)
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  !HasBounceEffects(LastSeenBy(Myself))
  !HasImmunityEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobal("pscript_WHIP","LOCALS",0)
END

IF
  HasItem("WAND11",Myself)  // ~Wand of the Heavens~
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    UseItem("WAND11",NearestEnemyOf(Myself))  // ~Wand of the Heavens~
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  HPGT(LastSeenBy(Myself),30)
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_MAZE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MAZE)
END

IF
  HaveSpell(CLERIC_SILENCE_15_FOOT)
  OR(2)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
  !Range(LastSeenBy(Myself),15)
  Range(LastSeenBy(Myself),50)
  !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_FLAME_STRIKE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_FLAME_STRIKE)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_CONE_OF_COLD)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),30)
  HaveSpell(WIZARD_ICE_STORM)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_ICE_STORM)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),30)
  HaveSpell(WIZARD_CLOUDKILL)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),20)
  HaveSpell(WIZARD_FIREBALL)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_FIREBALL)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),30)
  HaveSpell(WIZARD_DEATH_FOG)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !General(LastSeenBy(Myself),HUMANOID)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  HaveSpell(WIZARD_HOLD_MONSTER)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_HOLD_MONSTER)
END

IF
  HaveSpell(WIZARD_DEATH_SPELL)
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  NumCreatureVsPartyGT([ENEMY],4)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END

IF
  HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  NumCreatureVsPartyGT([ENEMY],3)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_ANIMAL_SUMMONING_3)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),0)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_MENTAL_DOMINATION)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !HasBounceEffects(LastSeenBy(Myself))
  HPGT(LastSeenBy(Myself),20)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
  See(NearestEnemyOf(Myself))
  HPGT(LastSeenBy(Myself),20)
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_DISINTEGRATE)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_DISINTEGRATE)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_BURNING_HANDS)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_COLOR_SPRAY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_COLOR_SPRAY)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_MAGIC_MISSILE)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_SLEEP)
  ActionListEmpty()
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_SLEEP)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_CHROMATIC_ORB)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_BLINDNESS)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_BLINDNESS)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_CLOAK_OF_FEAR)
  HPGT(LastSeenBy(Myself),20)
  Range(LastSeenBy(Myself),10)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CLOAK_OF_FEAR)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  General(LastSeenBy(Myself),HUMANOID)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  HaveSpell(WIZARD_CHARM_PERSON)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_CHARM_PERSON)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_MELF_ACID_ARROW)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_RAY_OF_ENFEEBLEMENT)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_RAY_OF_ENFEEBLEMENT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_STRENGTH)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_STRENGTH)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_FLAME_ARROW)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_POLYMORPH_OTHER)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_POLYMORPH_OTHER)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  HaveSpell(WIZARD_FLESH_TO_STONE)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_FLESH_TO_STONE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_IMPROVED_HASTE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_IMPROVED_HASTE)
END

IF
  OR(2)
    HPLT(Myself,5)
    StateCheck(Myself,STATE_PANIC)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastAttackerOf(Myself),30)
END

IF
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  Delay(10)
  See(NearestEnemyOfType([0.UNDEAD]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
THEN
  RESPONSE #100
    Turn()
    Continue()
END

IF
  !Detect(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Range(NearestEnemyOf(Myself),50)
THEN
  RESPONSE #100
    EscapeArea()
END

