IF
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("Effect","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Effect","LOCALS",8)
    ReallyForceSpell(Myself,AIR_ELEMENTAL_EFFECT)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),5)
END

IF
  !See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

