IF
  OR(3)
    Global("Alphonse","GLOBAL",1)
    Global("Alphonse","GLOBAL",2)
    Global("Alphonse","GLOBAL",3)
  !See([PC])
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  OR(3)
    Global("Alphonse","GLOBAL",1)
    Global("Alphonse","GLOBAL",2)
    Global("Alphonse","GLOBAL",3)
  See([PC])
  !Range([PC],5)
THEN
  RESPONSE #100
    MoveToObject([PC])
END

IF
  Global("Alphonse","GLOBAL",1)
  See([PC])
  Range([PC],5)
THEN
  RESPONSE #100
    SetGlobal("Alphonse","GLOBAL",4)
    GiveItemCreate("RING22",[PC],0,0,0)  // ~Ring of Holiness~
END

IF
  Global("Alphonse","GLOBAL",2)
  See([PC])
  Range([PC],5)
THEN
  RESPONSE #100
    SetGlobal("Alphonse","GLOBAL",4)
    GiveItemCreate("CHAN18",[PC],0,0,0)  // ~Armor of Faith +3~
END

IF
  Global("Alphonse","GLOBAL",3)
  See([PC])
  Range([PC],5)
THEN
  RESPONSE #100
    SetGlobal("Alphonse","GLOBAL",4)
    GiveItemCreate("STAF07",[PC],0,0,0)  // ~Staff Spear +2~
END

IF
  Global("Alphonse","GLOBAL",4)
THEN
  RESPONSE #100
    EscapeArea()
END

