IF
  Global("Enclave","GLOBAL",2)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("MayorCutscene","AR5500",0)
  OR(7)
    Allegiance("amasana",ENEMY)  // ~Asana Haraad~
    Allegiance("ammerc03",ENEMY)  // ~Mercenary~
    Allegiance("ammayor",ENEMY)  // ~Omar Haraad~
    Allegiance(Myself,ENEMY)
    Dead("amasana")  // ~Asana Haraad~
    Dead("ammerc03")  // ~Mercenary~
    Dead("ammayor")  // ~Omar Haraad~
THEN
  RESPONSE #100
    SetGlobal("MayorCutscene","AR5500",1)
    SetGlobal("AsanaPlot","GLOBAL",10)
END

IF
  Global("AsanaPlot","GLOBAL",10)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Detect([PC])
  Range(LastSeenBy(Myself),10)
  Global("MayorCutscene","AR5500",0)
THEN
  RESPONSE #100
    ClearAllActions()
    StartCutSceneMode()
    StartCutScene("cut212a")
END

