IF
  !GlobalTimerNotExpired("amtalk2","LOCALS")
  RandomNum(10,1)
  !Global("notalk","LOCALS",1)
  OnScreen(Myself)
  Range([0.0.0.INNOCENT],10)
THEN
  RESPONSE #100
    SetGlobalTimer("amtalk2","LOCALS",22)
  RESPONSE #10
    SetGlobalTimer("amtalk2","LOCALS",10)
    Wait(1)
    FaceObject([0.0.0.INNOCENT])
    DisplayStringHead(Myself,71533)  // ~Something must be done, don't you think?~
  RESPONSE #10
    SetGlobalTimer("amtalk2","LOCALS",10)
    Wait(1)
    FaceObject([0.0.0.INNOCENT])
    DisplayStringHead(Myself,71534)  // ~We should demand to see Balthazar!~
  RESPONSE #10
    SetGlobalTimer("amtalk2","LOCALS",10)
    Wait(1)
    FaceObject([0.0.0.INNOCENT])
    DisplayStringHead(Myself,71535)  // ~Let's be reasonable about this...~
  RESPONSE #10
    SetGlobalTimer("amtalk2","LOCALS",10)
    Wait(1)
    FaceObject([0.0.0.INNOCENT])
    DisplayStringHead(Myself,71536)  // ~Nothing is being done about the cave of the dead!~
  RESPONSE #10
    SetGlobalTimer("amtalk2","LOCALS",10)
    Wait(1)
    FaceObject([0.0.0.INNOCENT])
    DisplayStringHead(Myself,71537)  // ~We have no supplies, except what the smugglers can get for us.~
  RESPONSE #10
    SetGlobalTimer("amtalk2","LOCALS",10)
    Wait(1)
    FaceObject([0.0.0.INNOCENT])
    DisplayStringHead(Myself,71538)  // ~All these mercenaries concern me greatly...~
END

IF
  See([0.0.LEATHER])
  !Range([0.0.LEATHER],6)
THEN
  RESPONSE #100
    MoveToObject([0.0.LEATHER])
END

