IF
  Detect([PC])
  Allegiance(Myself,NEUTRAL)
  ActionListEmpty()
THEN
  RESPONSE #100
    Wait(1)
    ActionOverride("AMCST04",DisplayStringHead(Myself,4592))  // ~Where's me ale woman?~
    Wait(1)
    DisplayStringHead(Myself,4604)  // ~Wait 'cha turn.~
    Wait(2)
    MoveToObject("Way2")
    Wait(2)
    MoveToObject("AMCST04")
    DisplayStringHead(Myself,4611)  // ~Here ya go.~
    Wait(2)
    MoveToObject("WAY2")
    Wait(3)
  RESPONSE #100
    Wait(1)
    ActionOverride("AMCST03",DisplayStringHead(Myself,4592))  // ~Where's me ale woman?~
    Wait(1)
    DisplayStringHead(Myself,4604)  // ~Wait 'cha turn.~
    Wait(2)
    MoveToObject("Way2")
    Wait(2)
    MoveToObject("AMCST03")
    DisplayStringHead(Myself,4611)  // ~Here ya go.~
    Wait(2)
    MoveToObject("WAY2")
    Wait(3)
  RESPONSE #100
    Wait(1)
    ActionOverride("AMCST02",DisplayStringHead(Myself,4592))  // ~Where's me ale woman?~
    Wait(1)
    DisplayStringHead(Myself,4604)  // ~Wait 'cha turn.~
    Wait(2)
    MoveToObject("Way2")
    Wait(2)
    MoveToObject("AMCST02")
    DisplayStringHead(Myself,4611)  // ~Here ya go.~
    Wait(2)
    MoveToObject("WAY2")
    Wait(3)
  RESPONSE #100
    Wait(1)
    ActionOverride("AMSEAT01",DisplayStringHead(Myself,4592))  // ~Where's me ale woman?~
    Wait(1)
    DisplayStringHead(Myself,4604)  // ~Wait 'cha turn.~
    Wait(2)
    MoveToObject("Way2")
    Wait(2)
    MoveToObject("AMSEAT01")
    DisplayStringHead(Myself,4611)  // ~Here ya go.~
    Wait(2)
    MoveToObject("WAY2")
    Wait(3)
  RESPONSE #100
    Wait(1)
    ActionOverride("AMCST01",DisplayStringHead(Myself,4592))  // ~Where's me ale woman?~
    Wait(2)
    MoveToObject("AMCST01")
    DisplayStringHead(Myself,4590)  // ~No more for you~
    Wait(2)
    MoveToObject("WAY2")
    Wait(3)
  RESPONSE #100
    Wait(1)
    MoveToObject([PC])
    Wait(5)
    MoveToObject("WAY2")
    Wait(3)
  RESPONSE #100
    Wait(1)
    MoveToObject("WAY1")
    Wait(5)
  RESPONSE #100
    Wait(1)
    MoveToObject("WAY2")
    Wait(5)
  RESPONSE #100
    Wait(1)
    MoveToObject("WAY3")
    Wait(5)
  RESPONSE #100
    Wait(1)
    MoveToObject("WAY4")
    Wait(5)
  RESPONSE #100
    Wait(1)
    MoveToObject("WAY5")
    Wait(5)
END

