IF
  Global("DeathMatch","GLOBAL",0)
THEN
  RESPONSE #100
    ActionOverride(Player1,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player2,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player3,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player4,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player5,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player6,ChangeAIScript("Deathm",OVERRIDE))
    DeathMatchPositionGlobal("AR0060",[1437.926],1)
    DeathMatchPositionGlobal("AR0060",[1437.926],2)
    DeathMatchPositionGlobal("AR0060",[1437.926],3)
    DeathMatchPositionGlobal("AR0060",[1437.926],4)
    DeathMatchPositionGlobal("AR0060",[1437.926],5)
    DeathMatchPositionGlobal("AR0060",[1437.926],6)
    SetGlobal("DeathMatch","GLOBAL",1)
END

