IF
  True()
THEN
  RESPONSE #100
    ActionOverride(Player1,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player2,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player3,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player4,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player5,ChangeAIScript("Deathm",OVERRIDE))
    ActionOverride(Player6,ChangeAIScript("Deathm",OVERRIDE))
END

