IF
  Global("EnteredArea","AR0020",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredArea","AR0020",1)
    SetGlobalTimer("SpawnMerch","AR0020",FIVE_DAYS)
END

IF
  Global("EnteredArea","AR0020",1)
  GlobalTimerExpired("SpawnMerch","AR0020")
THEN
  RESPONSE #100
    SetGlobal("EnteredArea","AR0020",2)
    CreateCreature("AEMERCH",[390.550],14)  // ~Merchant~
    CreateCreature("AEEXTORT",[473.590],6)  // ~Hanj~
END

IF
  TimeGT(20)
  TimeLT(8)
  Exists("aemerch")  // ~Merchant~
  Exists("aeextort")  // ~Hanj~
  Global("DeactivateMerchants","AR0020",0)
THEN
  RESPONSE #100
    SetGlobal("DeactivateMerchants","AR0020",1)
    Deactivate("aemerch")
    Deactivate("aeextort")
END

IF
  TimeLT(DUSK_START)
  TimeGT(DAWN_END)
  Exists("aemerch")  // ~Merchant~
  Exists("aeextort")  // ~Hanj~
  Global("DeactivateMerchants","AR0020",1)
THEN
  RESPONSE #100
    SetGlobal("DeactivateMerchants","AR0020",0)
    Activate("aemerch")
    Activate("aeextort")
END

IF
  SpellCast([PC],0)
  !GlobalTimerNotExpired("SpellsBad","GLOBAL")
  Global("BribedCowled","GLOBAL",0)
  GlobalLT("CowledWarning","GLOBAL",7)
THEN
  RESPONSE #100
    CreateCreatureObjectDoor("COWENF2",LastTrigger,0,0,0)  // ~Cowled Enforcer~
    SetGlobalTimer("SpellsBad","GLOBAL",300)
END

IF
  SpellCast([PC],0)
  Global("BribedCowled","GLOBAL",0)
  GlobalTimerNotExpired("SpellsBad","GLOBAL")
THEN
  RESPONSE #100
    Wait(1)
END

