IF
  Global("EnteredArea","AR0329",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredArea","AR0329",1)
    MoveGlobalsTo("AR0307","AR0329",[0.0])
    AmbientActivate("AM307TT2",FALSE)
    AmbientActivate("AM307TT3",FALSE)
    TriggerActivation("Guillotine1",FALSE)
    TriggerActivation("Guillotine2",FALSE)
END

IF
  Dead("aran02")  // ~Aran Linvail~
  Global("DearAranJournal","AR0329",0)
THEN
  RESPONSE #100
    SetGlobal("DearAranJournal","AR0329",1)
    AddJournalEntry(5819,QUEST)
END

