IF
  GlobalLT("GoSeeEdwin","GLOBAL",2)
  !Dead("MaeVar")  // ~Mae'Var~
THEN
  RESPONSE #100
    ActionOverride("Edwin",Deactivate(Myself))
END

IF
  Global("GoSeeEdwin","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("GoSeeEdwin","GLOBAL",3)
    ActionOverride("Edwin",Activate(Myself))
END

IF
  GlobalLT("GoSeeEdwin","GLOBAL",2)
  Dead("MaeVar")  // ~Mae'Var~
THEN
  RESPONSE #100
    SetGlobal("GoSeeEdwin","GLOBAL",3)
    ActionOverride("Edwin",Activate(Myself))
END

