IF
  OnCreation()
  Global("NewGame","AR0602",0)
THEN
  RESPONSE #100
    HideGUI()
    FadeToColor([1.0],0)
    SetGlobal("NewGame","AR0602",1)
    Continue()
END

IF
  Global("RielevDisable","AR0602",0)
THEN
  RESPONSE #100
    SetGlobal("RielevDisable","AR0602",1)
    TriggerActivation("Rielevdeadtrigger",FALSE)
END

IF
  Global("IrenTeleport","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("IrenTeleport","GLOBAL",1)
    SmallWait(8)
    PlaySound("EFF_M29")
    FadeFromColor([30.0],0)
    CreateVisualEffect("SPCLOUD1",[3075.644])
    CreateVisualEffect("SPCLOUD1",[3029.652])
    CreateVisualEffect("SPCLOUD1",[2975.670])
    CreateVisualEffect("SPCLOUD1",[3114.665])
    CreateVisualEffect("SPCLOUD1",[3068.681])
    CreateVisualEffect("SPCLOUD1",[3004.704])
END

IF
  Global("BG1Pantaloons","GLOBAL",0)
  PartyHasItem("MISC47")  // ~Golden Pantaloons~
THEN
  RESPONSE #100
    SetGlobal("BG1Pantaloons","GLOBAL",1)
    ActionOverride("Picture1",CreateItem("MISC47",0,0,0))  // ~Golden Pantaloons~
    Continue()
END

IF
  Global("BG1DrizztItem","GLOBAL",0)
  OR(3)
    PartyHasItem("CHAN06")  // ~Mithril Chain Mail +4~
    PartyHasItem("SW1H15")  // ~Scimitar +3, Frostbrand~
    PartyHasItem("SW1H16")  // ~Scimitar +5, Defender~
THEN
  RESPONSE #100
    SetGlobal("BG1DrizztItem","GLOBAL",1)
    Continue()
END

IF
  Global("TakeImportItems","AR0602",0)
THEN
  RESPONSE #100
    SetGlobal("TakeImportItems","AR0602",1)
    SetGlobal("Chapter","GLOBAL",1)
    ActionOverride("Malaaq",MoveBetweenAreas("AR0601",[345.591],14))
    ActionOverride("DuegarClanChief",TakeItemListPartyNum("IMPORT01",1))
    ActionOverride("Shelf1",TakeItemListPartyNum("IMPORT03",1))
    SmallWait(4)
    TakePartyGold(2147483647)
    ActionOverride(Player1,DestroyAllEquipment())
    ActionOverride(Player2,DestroyAllEquipment())
    ActionOverride(Player3,DestroyAllEquipment())
    ActionOverride(Player4,DestroyAllEquipment())
    ActionOverride(Player5,DestroyAllEquipment())
    ActionOverride(Player6,DestroyAllEquipment())
    CreateCreature("CSJON",[3210.3304],10)  // ~Mage~
    ActionOverride(Player1,PlayDead(165))
    Wait(1)
    FadeFromColor([30.0],0)
    StartCutSceneMode()
    StartCutScene("NewGame")
END

IF
  InParty("Imoen")  // ~Imoen~
  Global("MoveScreen","AR0602",0)
THEN
  RESPONSE #100
    SetGlobal("MoveScreen","AR0602",1)
    SaveGame(0)
    MoveViewPoint([3802.2769],VERY_FAST)
END

IF
  Global("AataqahFight","AR0602",1)
  Dead("AataqahOgre")  // AataqahOgre
THEN
  RESPONSE #100
    SetGlobal("AataqahFight","AR0602",2)
    Wait(1)
    CreateCreatureObjectEffect("AATAQAH","SPCLOUD3",Player1)
    ActionOverride("Aataqah",Wait(2))
END

IF
  Global("AataqahFight","AR0602",1)
  NumDead("AataqahGibber",4)
THEN
  RESPONSE #100
    SetGlobal("AataqahFight","AR0602",2)
    Wait(1)
    CreateCreatureObjectEffect("AATAQAH","SPCLOUD3",Player1)
    ActionOverride("Aataqah",Wait(2))
END

IF
  Global("AataqahFight","AR0602",1)
  HPPercentLT(MostDamagedOf(Myself),25)
THEN
  RESPONSE #100
    SetGlobal("AataqahFight","AR0602",2)
    Wait(1)
    CreateCreatureObjectEffect("AATAQAH","SPCLOUD3",Player1)
    ActionOverride("Aataqah",Wait(2))
END

IF
  Global("Ellsime","AR0602",1)
  OpenState("DOOR08",FALSE)  // DOOR08
THEN
  RESPONSE #100
    OpenDoor("DOOR08")
END

