IF
  PartyHasItem("BOOK94")  // ~The Vapiricus Omnibus: Unabridged~
  Global("GotBook94","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("GotBook94","GLOBAL",1)
END

IF
  Global("DrizztFightBodhi","GLOBAL",1)
  Global("AttackedDrizzt","GLOBAL",0)
  !Dead("C6Drizz2")  // ~Drizzt~
  Global("SpawnDrizz","AR0809",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnDrizz","AR0809",1)
    CreateCreatureObject("C6DRIZZ3",Player1,0,0,0)  // ~Drizzt~
END

IF
  Global("ShadowFightBodhi","GLOBAL",1)
  Global("AttackedShadow","GLOBAL",0)
  !Dead("C6Arkan")  // ~Arkanis~
  Global("SpawnArkan","AR0809",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnArkan","AR0809",1)
    CreateCreatureObject("C6ARKAN3",Player1,0,0,0)  // ~Arkanis~
END

IF
  Global("OrderFightBodhi","GLOBAL",1)
  Global("AttackedOrder","GLOBAL",0)
  !Dead("C6Eric")  // ~Eric Vanstraaten~
  Global("SpawnEric","AR0809",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnEric","AR0809",1)
    CreateCreatureObject("C6ERIC3",Player1,0,0,0)  // ~Eric Vanstraaten~
END

IF
  Dead("C6Bodhi")  // ~Bodhi~
  GlobalLT("udMind","GLOBAL",41)
THEN
  RESPONSE #100
    EraseJournalEntry(16351)  // ~The Final Battle with Bodhi.Bodhi has revealed herself to me, letting me know that she is aware of my pursuit... and in an attempt to dissuade me from entering her lair unleashed yet more of her undead creations upon me.  She swears I will lose much more than my life if I continue to pursue her... although, in truth, I have little choice.~
    EraseJournalEntry(7002)  // ~The Final Battle with Bodhi.Bodhi appeared in an ambush shortly before I reached her haven, warning me that she was aware of my pursuit and stealing from me the one person that is dearest to my heart: Jaheira.  Before she vanished and unleashed more of her undead creations upon me, Bodhi warned me that if I continue I will lose even more than I thought possible.  I cannot give up on the Rhynn Lanthorn... but now the life and immortal soul of the one I love is at stake, as well!~
    EraseJournalEntry(3716)  // ~The Final Battle with Bodhi.Bodhi appeared in an ambush shortly before I reached her haven, warning me that she was aware of my pursuit and stealing from me the one person that is dearest to my heart: Viconia.  Before she vanished and unleashed more of her undead creations upon me, Bodhi warned me that if I continue I will lose even more than I thought possible.  I cannot give up on the Rhynn Lanthorn... but now the life and immortal soul of the one I love is at stake, as well!~
    EraseJournalEntry(5814)  // ~The Final Battle with Bodhi.Bodhi appeared in an ambush shortly before I reached her haven, warning me that she was aware of my pursuit and stealing from me the one person that is dearest to my heart: Aerie.  Before she vanished and unleashed more of her undead creations upon me, Bodhi warned me that if I continue I will lose even more than I thought possible.  I cannot give up on the Rhynn Lanthorn... but now the life and immortal soul of the one I love is at stake, as well!~
    EraseJournalEntry(16331)  // ~The Final Battle with Bodhi.Bodhi appeared in an ambush shortly before I reached her haven, warning me that she was aware of my pursuit and stealing from me the one person that is dearest to my heart: Anomen.  Before she vanished and unleashed more of her undead creations upon me, Bodhi warned me that if I continue I will lose even more than I thought possible.  I cannot give up on the Rhynn Lanthorn... but now the life and immortal soul of the one I love is at stake, as well!~
    EraseJournalEntry(15710)  // ~The Final Battle with Bodhi.I have finally encountered Bodhi within her lair!  I must be careful to use every advantage I have at my disposal, including the holy water that Elhan gave me.  I doubt it will do much to her personally... but perhaps there is some way to pollute the power she draws from this place, use the holy water to dim the blood she draws...And if I survive, I will have many questions for Elhan.  He knows more than he has said about Irenicus and Bodhi.~
    SetGlobal("udMind","GLOBAL",41)
END

IF
  Global("Entered","AR0809",0)
THEN
  RESPONSE #100
    SetGlobal("Entered","AR0809",1)
    MoveGlobalsTo("AR0803","AR0809",[0.0])
    TriggerActivation("Coffin",FALSE)
END

IF
  Global("AerieVampire","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("AerieVampire","GLOBAL",2)
    CreateCreature("Vampaer",[1473.332],2)  // ~Aerie~
END

IF
  Global("AnomenVampire","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("AnomenVampire","GLOBAL",2)
    CreateCreature("Vampano",[1473.332],2)  // ~Anomen~
END

IF
  Global("JaheiraVampire","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("JaheiraVampire","GLOBAL",2)
    CreateCreature("Vampjah",[1473.332],2)  // ~Jaheira~
END

IF
  Global("ViconiaVampire","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ViconiaVampire","GLOBAL",2)
    CreateCreature("Vampvic",[1473.332],2)  // ~Viconia~
END

IF
  PartyHasItem("c6lantho")  // ~Lanthorn~
  Global("LanthornExp","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("LanthornExp","GLOBAL",1)
    AddXPObject(Player1,55000)
    AddXPObject(Player2,55000)
    AddXPObject(Player3,55000)
    AddXPObject(Player4,55000)
    AddXPObject(Player5,55000)
    AddXPObject(Player6,55000)
END

IF
  PartyHasItem("book94")  // ~The Vapiricus Omnibus: Unabridged~
  Global("RevealUmar","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("RevealUmar","GLOBAL",1)
    RevealAreaOnMap("AR1100")
END

IF
  Global("C6BodhiFight","AR0809",1)
  Global("DrizztFightBodhi","GLOBAL",1)
  Global("ArtemisSpawn","AR0809",0)
THEN
  RESPONSE #100
    CreateCreature("BODFGT01",[1430.362],0)  // ~Grimwarder~
    SetGlobal("ArtemisSpawn","AR0809",1)
END

IF
  Global("C6BodhiFight","AR0809",1)
  Global("OrderFightBodhi","GLOBAL",1)
  Global("PaliVampSpawn","AR0809",0)
THEN
  RESPONSE #100
    CreateCreature("VAMPIM01",[1198.381],0)  // ~Vampire~
    SetGlobal("PaliVampSpawn","AR0809",1)
END

IF
  Global("C6BodhiFight","AR0809",1)
  Global("ArkanisFightBodhi","GLOBAL",1)
  Global("GrimSpawn","AR0809",0)
THEN
  RESPONSE #100
    CreateCreature("BODFGT01",[1387.560],0)  // ~Grimwarder~
    SetGlobal("GrimSpawn","AR0809",1)
END

