IF
  Global("TelwynSpawn","GLOBAL",0)
  OR(5)
    Class(Player1,CLERIC)
    Class(Player1,FIGHTER_CLERIC)
    Class(Player1,CLERIC_MAGE)
    Class(Player1,CLERIC_THIEF)
    Class(Player1,FIGHTER_MAGE_CLERIC)
  Alignment(Player1,MASK_GENEUTRAL)
THEN
  RESPONSE #100
    SetGlobal("TelwynSpawn","GLOBAL",1)
    CreateCreature("SCTELWYN",[705.711],4)  // ~Guardian Telwyn~
END

IF
  Global("TelwynSpawn","GLOBAL",0)
  !Class(Player1,CLERIC)
  !Class(Player1,FIGHTER_CLERIC)
  !Class(Player1,CLERIC_MAGE)
  !Class(Player1,CLERIC_THIEF)
  !Class(Player1,FIGHTER_MAGE_CLERIC)
THEN
  RESPONSE #100
    SetGlobal("TelwynSpawn","GLOBAL",1)
    CreateCreature("SCTELWYN",[705.711],4)  // ~Guardian Telwyn~
END

IF
  GlobalTimerExpired("HelmbyrReturn","GLOBAL")
  Global("HelmbyrEnd","GLOBAL",0)
  !Exists("helmbyr")  // ~Acolyte Byron~
  !Dead("helmbyr")  // ~Acolyte Byron~
THEN
  RESPONSE #100
    CreateCreature("HELMBYR",[1066.774],4)  // ~Acolyte Byron~
    ActionOverride("helmbyr",SetNumTimesTalkedTo(1))
END

IF
  Global("HelmbyrEnd","GLOBAL",1)
  Dead("clcoti01")  // ~Cotirso~
  !Exists("helmbyr")  // ~Acolyte Byron~
  !Dead("helmbyr")  // ~Acolyte Byron~
THEN
  RESPONSE #100
    SetGlobal("HelmbyrEnd","GLOBAL",2)
    CreateCreature("HELMBYR",[1066.774],4)  // ~Acolyte Byron~
    ActionOverride("helmbyr",SetNumTimesTalkedTo(1))
END

IF
  GlobalTimerExpired("Clglin01Return","GLOBAL")
  Global("Clglin01Spawn","GLOBAL",0)
  Global("JoinHelm","GLOBAL",1)
THEN
  RESPONSE #100
    ClearAllActions()
    SetGlobal("Clglin01Spawn","GLOBAL",1)
    StartCutSceneMode()
    StartCutScene("Cut80f")
END

IF
  GlobalTimerExpired("Cltiva01Return","GLOBAL")
  Global("Cltiva01Spawn","GLOBAL",0)
  Global("JoinHelm","GLOBAL",1)
THEN
  RESPONSE #100
    ClearAllActions()
    SetGlobal("Cltiva01Spawn","GLOBAL",1)
    StartCutSceneMode()
    StartCutScene("Cut80e")
END

IF
  Global("JoinHelm","GLOBAL",1)
  !Global("Stripped","GLOBAL",2)
  Global("SetRest","AR0901",0)
THEN
  RESPONSE #100
    SetGlobal("SetRest","AR0901",1)
    SetAreaRestFlag(1)
END

IF
  Global("Stripped","GLOBAL",2)
  Global("SetRest","AR0902",1)
THEN
  RESPONSE #100
    SetGlobal("SetRest","AR0902",2)
    SetAreaRestFlag(0)
END

