IF
  Global("DerilEscape","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("DerilEscape","GLOBAL",1)
    ActionOverride("CeDeril",ForceSpell(Myself,DRYAD_TELEPORT))
END

IF
  Global("TalkedToCerndNanny","GLOBAL",1)
  InParty("Cernd")  // Cernd
  !Dead("Cernd")  // Cernd
  Global("SpawnGlut","AR1004",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnGlut","AR1004",1)
    CreateCreature("CeGlut",[707.583],13)  // ~Glut~
    Wait(1)
    ActionOverride("CeGlut",StartDialogNoSet([PC]))
END

