IF
  Global("PaladinPlot","GLOBAL",8)
  Global("BaronSpawn","AR1105",0)
THEN
  RESPONSE #100
    SetGlobal("BaronSpawn","AR1105",1)
    CreateCreature("PLMETR01",[915.281],12)  // ~Baron Metrich~
    CreateCreature("PLMETG01",[941.210],10)  // ~Metrich Footman~
    CreateCreature("PLFARM01",[999.351],13)  // ~Lette~
    CreateCreature("PLFARM02",[885.352],0)  // ~Lanka~
    CreateCreature("PLMETW01",[958.394],0)  // ~Sorcerous Amin ~
    CreateCreature("PLMETG02",[981.182],0)  // ~Metrich Yeoman~
END

