IF
  Global("DeactivateCabin","AR1100",0)
THEN
  RESPONSE #100
    SetGlobal("DeactivateCabin","AR1100",1)
    TriggerActivation("Tran1107",FALSE)
    TriggerActivation("LostCabin",FALSE)
END

IF
  Global("RangerProtector","GLOBAL",1)
  Global("DeactivateCabin","AR1100",1)
THEN
  RESPONSE #100
    SetGlobal("DeactivateCabin","AR1100",2)
    TriggerActivation("Tran1107",TRUE)
    TriggerActivation("Tran1102",FALSE)
END

IF
  Global("RangerProtector","GLOBAL",6)
  Global("DeactivateCabin","AR1100",2)
THEN
  RESPONSE #100
    SetGlobal("DeactivateCabin","AR1100",3)
    TriggerActivation("Tran1107",FALSE)
    TriggerActivation("LostCabin",TRUE)
    EraseJournalEntry(2939)  // ~Ranger-Protector of the Umar HillsWhether I wish to assume the position or not, Mayor Wainwright has offered me the use of the cabin occupied by Merella, the former ranger-protector of Imnesvale and the area, who is now dead.  The cabin lies just west of the village and I may use it as much or as little as I wish.~
    EraseJournalEntry(2957)  // ~Ranger-Protector of the Umar HillsA forest spirit named Mairyn has implored me to aid her against humans who are tearing down her forest in the west, in the area where the Shadow altar once was.  She says the humans will not listen to her  and I have agreed to go and do what I can to help.~
    EraseJournalEntry(2965)  // ~Ranger-Protector of the Umar HillsLord Igen has agreed to hold off his excavations so long as I search for the mithril cache his ancestor has hidden in the area.  He only has half of his ancestor's journal, and finding the other half might be my only clue to locating the cache.  Likely the other half is also in the area, perhaps in the old dungeon, itself.~
    EraseJournalEntry(2966)  // ~Ranger-Protector of the Umar HillsThe disappointed Lord Igen has taken the mithril medallion and agreed to leave the area, as promised.  I can now return to Mairyn and tell her that the forest is safe.~
    EraseJournalEntry(2971)  // ~Ranger-Protector of the Umar HillsDelon of Imnesvale came and told me that the village was under assault by orcs coming down from the hills.  I told him I would go and help out as soon as possible.  I should go within three days at most or it will be too late.~
    EraseJournalEntry(2972)  // ~Ranger-Protector of the Umar HillsDelon of Imnevale came and told me of a group of orcs that seems to have come down from the hills and attacked the village.  I have other things to do, so the boy left.  If I change my mind, I should go to the village within three days or it will be too late.~
    EraseJournalEntry(3013)  // ~Ranger-Protector of the Umar HillsApparently, the witch Umar has returned to the Imnesvale area and has threatened the village.  Delon came and told me of the danger, and I have agreed to go and speak to the mayor immediately.~
    EraseJournalEntry(3017)  // ~Ranger-Protector of the Umar HillsDelon has come to find me again and has told me some tale about the witch Umar returning and Imnesvale being threatened by her.  I told him I haven't time to go and deal with their situation.~
    EraseJournalEntry(3024)  // ~Ranger-Protector of the Umar HillsThe mayor of Imnesvale told me that Umar, or whoever is claiming to be her, has set up in the Shadow Portal dungeon to the west and threatens to detroy the village uless the inhabitants leave.~
    EraseJournalEntry(3028)  // ~Ranger-Protector of the Umar HillsMairyn, the forest spirit, appeared again and told me of the sorceress that has been poisoning her forest with infernal magic.  The sorceress, claiming to be Umar, has set herself up in the now-empty Shadow Portal dungeon.~
END

IF
  Global("PaladinPlot","GLOBAL",9)
  !Dead("PLFARM04")  // ~Brunson~
  !Dead("PLFARM05")  // ~Pardo~
  !Dead("PLFARM06")  // ~Moreno~
  Global("FarmerSpawn","AR1100",1)
THEN
  RESPONSE #100
    SetGlobal("FarmerSpawn","AR1100",2)
    ActionOverride("PLFARM04",DestroySelf())
    ActionOverride("PLFARM05",DestroySelf())
    ActionOverride("PLFARM06",DestroySelf())
END

IF
  GlobalGT("PaladinPlot","GLOBAL",9)
  GlobalLT("PaladinPlot","GLOBAL",13)
  !Dead("PLFARM04")  // ~Brunson~
  !Dead("PLFARM05")  // ~Pardo~
  !Dead("PLFARM06")  // ~Moreno~
  Global("FarmerSpawn","AR1100",1)
THEN
  RESPONSE #100
    SetGlobal("FarmerSpawn","AR1100",2)
    ActionOverride("PLFARM04",DestroySelf())
    ActionOverride("PLFARM05",DestroySelf())
    ActionOverride("PLFARM06",DestroySelf())
    CreateCreature("PLFARM04",[4020.2688],14)  // ~Brunson~
    CreateCreature("PLFARM05",[3957.2722],2)  // ~Pardo~
    CreateCreature("PLFARM06",[4068.2770],0)  // ~Moreno~
END

IF
  !GlobalTimerExpired("KnightsDeath","GLOBAL")
  OR(2)
    Global("PaladinPlot","GLOBAL",2)
    Global("PaladinPlot","GLOBAL",1)
  Global("EnteredKnightArea","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredKnightArea","GLOBAL",1)
END

IF
  Global("PaladinPlot","GLOBAL",1)
  !GlobalTimerExpired("KnightsDeath","GLOBAL")
  Global("PaladinSpawn","AR1100",0)
THEN
  RESPONSE #100
    SetGlobal("PaladinSpawn","AR1100",1)
    CreateCreature("elotte",[1701.2100],7)  // ~Squire Elotte~
    CreateCreature("plshkn01",[1595.1937],10)  // ~Knight of the Order~
    CreateCreature("plshkn02",[1708.1949],13)  // ~Knight of the Order~
    CreateCreature("plshom01",[1576.1701],0)  // ~Ogre Mage~
    CreateCreature("plshfg01",[1669.1726],0)  // ~Ettin~
    CreateCreature("plshfg02",[1733.1790],0)  // ~Ettin~
    CreateCreature("ORC01",[1745.1800],0)  // ~Orc~
    CreateCreature("ORC01",[1690.1740],0)  // ~Orc~
    CreateCreature("ORC01",[1550.1920],0)  // ~Orc~
    CreateCreature("ORC02",[1700.1940],0)  // ~Orc Archer~
    CreateCreature("ORC02",[1760.1616],2)  // ~Orc Archer~
    CreateCreature("plshom01",[1635.1522],0)  // ~Ogre Mage~
    CreateCreature("orcded",[1526.1941],10)  // <Invalid Strref -1>
    CreateCreature("orcded",[1644.2031],0)  // <Invalid Strref -1>
END

IF
  Global("PaladinPlot","GLOBAL",1)
  !GlobalTimerExpired("KnightsDeath","GLOBAL")
  !Exists("ALYNAR")  // ~Sir Alynar~
  Global("SpawnAlynar","AR1100",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnAlynar","AR1100",1)
    CreateCreatureObjectOffScreen("ALYNAR",Player1,0,0,0)  // ~Sir Alynar~
END

IF
  Global("PaladinPlot","GLOBAL",8)
  AreaCheck("AR1100")
  Global("FarmerSpawn","AR1100",0)
THEN
  RESPONSE #100
    SetGlobal("FarmerSpawn","AR1100",1)
    CreateCreatureObjectOffScreen("CROLUS",Player1,0,0,0)  // ~Crolus~
    CreateCreature("PLFARM04",[3957.2715],1)  // ~Brunson~
    CreateCreature("PLFARM05",[3889.2917],4)  // ~Pardo~
    CreateCreature("PLFARM06",[4173.2625],2)  // ~Moreno~
END

IF
  Global("RangerProtector","GLOBAL",1)
  GlobalTimerExpired("MairynAppear","GLOBAL")
  Global("MairynSpawn","AR1100",0)
  AreaCheck("AR1100")
  CombatCounter(0)
THEN
  RESPONSE #100
    SetGlobal("MairynSpawn","AR1100",1)
    SetGlobal("IgenPlot","GLOBAL",1)
    CreateCreatureObjectOffScreen("RSPIRIT1",Player1,0,0,0)  // ~Mairyn~
END

IF
  Global("IgenPlot","GLOBAL",1)
  Dead("rigen01")  // ~Lord Igen Tombelthen~
THEN
  RESPONSE #100
    SetGlobal("IgenPlot","GLOBAL",2)
END

IF
  Global("MairynMoves","AR1100",1)
THEN
  RESPONSE #100
    SetGlobal("MairynMoves","AR1100",2)
    CreateCreature("RSPIRIT1",[661.3002],12)  // ~Mairyn~
    ActionOverride("RSPIRIT01",SetNumTimesTalkedTo(1))
END

IF
  GlobalTimerNotExpired("OgronAssault","GLOBAL")
  Global("OgronAttack","GLOBAL",1)
  Global("OgronAttackStarted","AR1100",0)
THEN
  RESPONSE #100
    SetGlobal("OgronAttackStarted","AR1100",1)
    CreateCreature("RORCL01",[1854.1387],14)  // ~Orog Leader~
    CreateCreature("RORCA01",[1758.1453],14)  // ~Orc Archer~
    CreateCreature("RORCA01",[1822.1481],14)  // ~Orc Archer~
    CreateCreature("RORCS01",[1750.1534],14)  // ~Orog~
    CreateCreature("RORCS01",[1663.1536],14)  // ~Orog~
    CreateCreature("RORCS01",[1613.1450],14)  // ~Orog~
END

IF
  GlobalTimerExpired("OgronAssault","GLOBAL")
  Global("OgronAttack","GLOBAL",1)
  CombatCounter(0)
  NumDeadLT("rogron",6)
THEN
  RESPONSE #100
    SetGlobal("OgronAttack","GLOBAL",5)
    SetGlobal("RangerProtector","GLOBAL",6)
END

IF
  Global("ShadowLordDead","GLOBAL",1)
  Global("ChangeSpawns","AR1100",0)
THEN
  RESPONSE #100
    SetGlobal("ChangeSpawns","AR1100",1)
    SpawnPtActivate("SpawnPoint4")
    SpawnPtActivate("SpawnPoint6")
    SpawnPtActivate("SpawnPoint7")
    SpawnPtDeactivate("SpawnPoint1")
    SpawnPtDeactivate("SpawnPoint5")
    SpawnPtDeactivate("SpawnPoint8")
END

IF
  Global("CreateFaelMerchant","GLOBAL",1)
  Global("PlaceFaelOnce","AR1100",0)
THEN
  RESPONSE #100
    CreateCreature("TANALLY1",[3496.2860],0)  // ~Fael~
    SetGlobal("PlaceFaelOnce","AR1100",1)
END

IF
  Global("AdventureTime","AR1100",1)
THEN
  RESPONSE #100
    SetGlobal("AdventureTime","AR1100",2)
    ActionOverride("uhkid01",EscapeArea())
    ActionOverride("uhkid02",MoveToObjectFollow("uhkid01"))
    ActionOverride("uhkid03",MoveToObjectFollow("uhkid02"))
END

IF
  Global("AdventureTime","AR1100",2)
  !Exists("uhkid01")  // ~Dirbert~
THEN
  RESPONSE #100
    SetGlobal("AdventureTime","AR1100",3)
    ActionOverride("uhkid02",EscapeArea())
    ActionOverride("uhkid03",EscapeArea())
END

IF
  Global("villagesaved","GLOBAL",1)
  Global("EveryoneGoesHome","AR1100",0)
THEN
  RESPONSE #100
    SetGlobal("EveryoneGoesHome","AR1100",1)
    ActionOverride("uhfarm01",EscapeArea())
    ActionOverride("uhfarm02",EscapeArea())
    ActionOverride("uhfarm03",EscapeArea())
    ActionOverride("gemfar01",EscapeArea())
    ActionOverride("gemfar02",EscapeArea())
    ActionOverride("gemjeb01",EscapeArea())
    ActionOverride("uhgirl01",EscapeArea())
END

IF
  Global("villagesaved","GLOBAL",1)
  Global("TalkedToMadulf","GLOBAL",0)
  Global("MadulfGroupLeaves","AR1100",0)
THEN
  RESPONSE #100
    SetGlobal("MadulfLeft","GLOBAL",1)
    SetGlobal("MadulfGroupLeaves","AR1100",1)
END

IF
  NumDeadGT("rogron",5)
  Global("OgronAttack","GLOBAL",1)
  !Dead("madulf")  // madulf
  Global("OgreAlliance","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("OgronAttack","GLOBAL",2)
END

IF
  NumDeadGT("rogron",5)
  Global("OgronAttack","GLOBAL",1)
  !Dead("madulf")  // madulf
  !Global("MadulfGroupLeaves","AR1100",1)
  !Global("OgreAlliance","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("OgronAttack","GLOBAL",3)
END

IF
  NumDeadGT("rogron",5)
  Global("OgronAttack","GLOBAL",1)
  OR(2)
    Dead("madulf")  // madulf
    Global("MadulfGroupLeaves","AR1100",1)
THEN
  RESPONSE #100
    SetGlobal("OgronAttack","GLOBAL",4)
END

IF
  Dead("Madulf")  // Madulf
  OR(2)
    Global("MadulfJob","GLOBAL",1)
    Global("ogrealliance","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("MadulfJob","GLOBAL",0)
    SetGlobal("ogrealliance","GLOBAL",0)
END

