IF
  StateCheck("kpglai01",STATE_CHARMED)  // ~Glaicas~
  Global("KPGlai01Talked","AR1303",0)
THEN
  RESPONSE #100
    SetGlobal("KPGlai01Talked","AR1303",1)
    ApplySpell("kpglai01",WIZARD_TRUE_DISPEL_MAGIC)
    Wait(1)
    ChangeEnemyAlly("kpglai01",NEUTRAL)
    ActionOverride("kpglai01",StartDialogNoSet([PC]))
END

IF
  Global("NaliaMove","GLOBAL",3)
  Global("DeadNalia","AR1303",0)
THEN
  RESPONSE #100
    SetGlobal("DeadNalia","AR1303",1)
    CreateCreature("NALDEAD",[1855.1546],0)  // ~Nalia~
END

IF
  Global("BridgeOpen","GLOBAL",1)
THEN
  RESPONSE #100
    SpawnPtDeactivate("SpawnPoint5")
    SpawnPtDeactivate("SpawnPoint6")
    SpawnPtDeactivate("SpawnPoint7")
    SpawnPtDeactivate("SpawnPoint8")
END

