IF
  GlobalTimerExpired("BodhiHunts","GLOBAL")
  !Global("AsylumPlot","GLOBAL",100)
  !Exists("ppbodhi4")  // ~Bodhi~
THEN
  RESPONSE #100
    FadeToColor([20.0],0)
    CreateCreatureObject("ppbodhi4",Player1,0,0,0)  // ~Bodhi~
    CreateCreatureObject("vammat01",Player1,0,0,0)  // ~Vampire~
    CreateCreatureObject("vammat01",Player1,0,0,0)  // ~Vampire~
    FadeFromColor([20.0],0)
    ActionOverride("ppbodhi4",StartDialogNoSet(Player1))
END

IF
  Contains("MISCA9","Asysta01")  // Asysta01
  Contains("MISCAA","Asysta02")  // Asysta02
  Contains("MISCAI","Asysta03")  // Asysta03
  Contains("MISCAB","Asysta04")  // Asysta04
  Contains("MISCAC","Asysta05")  // Asysta05
  Contains("MISCAD","Asysta06")  // Asysta06
  Contains("MISCAE","Asysta07")  // Asysta07
  Contains("MISCAF","Asysta08")  // Asysta08
  Contains("MISCAG","Asysta09")  // Asysta09
  Contains("MISCAH","Asysta10")  // Asysta10
  Contains("MISCAJ","Asysta11")  // Asysta11
  Global("PlantedItems","AR1512",0)
THEN
  RESPONSE #100
    SetGlobal("PlantedItems","AR1512",1)
END

IF
  Global("FaceOn","AR1512",1)
THEN
  RESPONSE #100
    TriggerActivation("Face1",TRUE)
    TriggerActivation("Face2",TRUE)
    TriggerActivation("Face3",TRUE)
    TriggerActivation("Face4",TRUE)
    TriggerActivation("Face5",TRUE)
    TriggerActivation("Face6",TRUE)
    TriggerActivation("Face7",TRUE)
    TriggerActivation("Face8",TRUE)
    TriggerActivation("Face9",TRUE)
    TriggerActivation("Face10",TRUE)
    TriggerActivation("Face11",TRUE)
    TriggerActivation("Face12",TRUE)
    SetGlobal("FaceOn","AR1512",0)
END

IF
  Global("FaceOn","AR1512",2)
THEN
  RESPONSE #100
    TriggerActivation("Face1",FALSE)
    TriggerActivation("Face2",FALSE)
    TriggerActivation("Face3",FALSE)
    TriggerActivation("Face4",FALSE)
    TriggerActivation("Face5",FALSE)
    TriggerActivation("Face6",FALSE)
    TriggerActivation("Face7",FALSE)
    TriggerActivation("Face8",FALSE)
    TriggerActivation("Face9",FALSE)
    TriggerActivation("Face10",FALSE)
    TriggerActivation("Face11",FALSE)
    TriggerActivation("Face12",FALSE)
    SetGlobal("FaceOn","AR1512",0)
END

