IF
  OnCreation()
THEN
  RESPONSE #100
    Weather(RAIN)
END

IF
  GlobalTimerExpired("GithTimer1","GLOBAL")
  Global("sah","AR1607",0)
THEN
  RESPONSE #100
    SetGlobalTimer("GithTimer1","GLOBAL",100)
    DisplayStringHead(Player1,31879)  // ~The ship shakes and sounds as if it is about to break apart.~
    ScreenShake([5.5],5)
    SetGlobal("sah","AR1607",1)
    CreateCreature("ppsailor",[699.1467],0)  // ~Sailor~
END

IF
  Global("AsylumPlot","GLOBAL",200)
THEN
  RESPONSE #100
    SetGlobal("AsylumPlot","GLOBAL",201)
    Wait(1)
    ClearAllActions()
    StartCutSceneMode()
    StartCutScene("Cut41zg")
END

IF
  GlobalTimerExpired("GithTimer1","GLOBAL")
  Global("lastcut","AR1607",0)
THEN
  RESPONSE #100
    SetGlobal("lastcut","AR1607",1)
    ScreenShake([100.100],100)
    ClearAllActions()
    StartCutSceneMode()
    StartCutScene("Cut41r")
END

