IF
  Global("GalvenaDoor","GLOBAL",1)
  Global("OpenedDoor","AR1611",0)
THEN
  RESPONSE #100
    SetGlobal("OpenedDoor","AR1611",1)
    Unlock("Secret1")
    OpenDoor("Secret1")
END

IF
  Global("OpenedDoor","AR1611",0)
  Global("PlayerOpenedDoor","AR1611",0)
  Global("GuardSleep","GLOBAL",0)
  OpenState("Secret1",TRUE)  // Secret1
THEN
  RESPONSE #100
    ActionOverride("pirmur03",StartDialogNoSet([PC]))
    SetGlobal("PlayerOpenedDoor","AR1611",1)
END

IF
  Dead("pirmur01")  // ~Galvena~
THEN
  RESPONSE #100
    ActionOverride("pirmur03",Enemy())
END

