IF
  Dead("pirmur02")  // ~Assassin ~
  Global("AssasinAttacks","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("AssasinAttacks","GLOBAL",2)
    ActionOverride("ppinn01",StartDialogNoSet([PC]))
END

IF
  Global("AsylumPlot","GLOBAL",60)
  Global("create","AR1602",0)
THEN
  RESPONSE #100
    SetGlobal("create","AR1602",1)
    CreateCreature("ppsaem3",[779.372],0)  // ~Saemon Havarian~
    ActionOverride("ppsanik",DestroySelf())
END

