IF
  Global("DeactivateTran3019","AR3024",0)
THEN
  RESPONSE #100
    SetGlobal("DeactivateTran3019","AR3024",1)
    TriggerActivation("Tran3019",FALSE)
END

IF
  Dead("fsdragon")  // ~Dragon~
  Global("SpawnSpirit","AR3024",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnSpirit","AR3024",1)
    CreateCreatureObjectEffect("FSSPIRB","SPFLESHS",Player1)
    TriggerActivation("Tran3019",TRUE)
    Wait(1)
    ActionOverride("fsspirb",StartDialogNoSet(Player1))
END

