IF
  PartyHasItem("PLOT02A")  // ~Scepter of Radiance~
  PartyHasItem("PLOT02C")  // ~Scepter Gem~
  PartyHasItem("PLOT02D")  // ~Scepter Gem~
  PartyHasItem("PLOT02E")  // ~Scepter Gem~
  Global("GorCambScepterComplete","GLOBAL",0)
THEN
  RESPONSE #100
    StartCutSceneMode()
    SetGlobal("GorCambScepterComplete","GLOBAL",1)
    DisplayStringHead(Player1,70786)  // ~The scepter of radiance suddenly glows brightly...it is obviously back in one piece and ready to be used.~
    GiveItemCreate("PLOT02B",Player1,0,0,0)  // ~Scepter of Radiance~
    TakePartyItem("PLOT02A")
    TakePartyItem("PLOT02C")
    TakePartyItem("PLOT02D")
    TakePartyItem("PLOT02E")
    AddXP2DA("PLOT3B")
    EndCutSceneMode()
END

IF
  Global("Demon1TimerSet","AR3012",0)
  Dead("GorTan2")  // ~Succubus~
THEN
  RESPONSE #100
    SetGlobalTimer("DemonSpawn1","AR3012",ONE_DAY)
    SetGlobal("Demon1TimerSet","AR3012",1)
END

IF
  Global("Demon1TimerSet","AR3012",1)
  GlobalTimerExpired("DemonSpawn1","AR3012")
  Dead("GorTan2")  // ~Succubus~
THEN
  RESPONSE #100
    SetGlobal("Demon1TimerSet","AR3012",0)
    SetGlobal("SPRITE_IS_DEADGorTan2","GLOBAL",0)
    CreateVisualEffect("SPPLANAR",[494.840])
    Wait(3)
    CreateCreature("GORTAN2",[494.840],6)  // ~Succubus~
END

IF
  Global("Demon2TimerSet","AR3012",0)
  Dead("GorTan3")  // ~Yochlol~
THEN
  RESPONSE #100
    SetGlobalTimer("DemonSpawn2","AR3012",ONE_DAY)
    SetGlobal("Demon2TimerSet","AR3012",1)
END

IF
  GlobalTimerExpired("DemonSpawn2","AR3012")
  Dead("GorTan3")  // ~Yochlol~
THEN
  RESPONSE #100
    SetGlobal("Demon2TimerSet","AR3012",0)
    SetGlobal("SPRITE_IS_DEADGorTan3","GLOBAL",0)
    CreateVisualEffect("SPPLANAR",[955.551])
    Wait(3)
    CreateCreature("GORTAN3",[955.551],6)  // ~Yochlol~
END

IF
  Global("Demon3TimerSet","AR3012",0)
  Dead("GorTan4")  // ~Glabrezu~
THEN
  RESPONSE #100
    SetGlobalTimer("DemonSpawn3","AR3012",ONE_DAY)
    SetGlobal("Demon3TimerSet","AR3012",1)
END

IF
  GlobalTimerExpired("DemonSpawn3","AR3012")
  Dead("GorTan4")  // ~Glabrezu~
THEN
  RESPONSE #100
    SetGlobal("Demon3TimerSet","AR3012",0)
    SetGlobal("SPRITE_IS_DEADGorTan4","GLOBAL",0)
    CreateVisualEffect("SPPLANAR",[352.631])
    Wait(3)
    CreateCreature("GORTAN4",[352.631],6)  // ~Glabrezu~
END

IF
  Global("Demon4TimerSet","AR3012",0)
  Dead("GorTan5")  // ~Quasit~
THEN
  RESPONSE #100
    SetGlobalTimer("DemonSpawn4","AR3012",ONE_DAY)
    SetGlobal("Demon4TimerSet","AR3012",1)
END

IF
  GlobalTimerExpired("DemonSpawn4","AR3012")
  Dead("GorTan5")  // ~Quasit~
THEN
  RESPONSE #100
    SetGlobal("Demon4TimerSet","AR3012",0)
    SetGlobal("SPRITE_IS_DEADGorTan5","GLOBAL",0)
    CreateVisualEffect("SPPLANAR",[737.348])
    Wait(3)
    CreateCreature("GORTAN5",[737.348],6)  // ~Quasit~
END

IF
  OnCreation()
  Global("ReduceDemons","AR3012",0)
  OR(2)
    DifficultyLT(NORMAL)
    !LevelPartyGT(16)
THEN
  RESPONSE #100
    SetGlobal("ReduceDemons","AR3012",1)
END

