









IF
  OnCreation()
  Global("TurnDay","AR4000",0)
THEN
    SetGlobal("TurnDay","AR4000",1)
    DayNight(DAWN_END)
    StartRainNow()
    Explore()
    AmbientActivate("AMB_Head1L",FALSE)
    AmbientActivate("AMB_Head1R",FALSE)
    AmbientActivate("AMB_Head2L",FALSE)
    AmbientActivate("AMB_Head2R",FALSE)
    AmbientActivate("AMB_Head3L",FALSE)
    AmbientActivate("AMB_Head3R",FALSE)
    AmbientActivate("AMB_Head4L",FALSE)
    AmbientActivate("AMB_Head4R",FALSE)
    AmbientActivate("AMB_Head5L",FALSE)
    AmbientActivate("AMB_Head5R",FALSE)
    TriggerActivation("HeadInfo1",FALSE)
    TriggerActivation("HeadInfo2",FALSE)
    TriggerActivation("HeadInfo3",FALSE)
    TriggerActivation("HeadInfo4",FALSE)
    TriggerActivation("HeadInfo5",FALSE)
    TriggerActivation("HeadInfo6",FALSE)
    TriggerActivation("HeadInfo7",FALSE)
    TriggerActivation("HeadInfo8",FALSE)
    TriggerActivation("HeadInfo9",FALSE)
    TriggerActivation("HeadInfo10",FALSE)
    FadeFromColor([20.0],0)
    SetGlobal("Chapter","GLOBAL",8)
    AddJournalEntry(73256,INFO)
    Wait(2)
    SaveGame(0)
END

IF
  OR(2)
    OnCreation()
    PartyRested()
THEN
    StartRainNow()
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    MultiPlayerSync()
    SetInterrupt(FALSE)
    Wait(1)
    Continue()
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN02",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN02",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN02",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN02",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN02",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCHAN02",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCSW1H01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H02",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H02",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H02",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H02",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H02",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSW1H02",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBLUN01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBLUN01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBLUN01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBLUN01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBLUN01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBLUN01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWHALB01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWHALB01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWHALB01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWHALB01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWHALB01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWHALB01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSPER01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSPER01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSPER01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSPER01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSPER01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSPER01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWXBOW01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWXBOW01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWXBOW01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWXBOW01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWXBOW01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWXBOW01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSHLD01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSHLD01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSHLD01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSHLD01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSHLD01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWSHLD01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCLCK01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCLCK01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCLCK01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCLCK01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCLCK01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWCLCK01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT02",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT02",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT02",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT02",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT02",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT02",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT03",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT03",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT03",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT03",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT03",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWBOLT03",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWPLAT01",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWPLAT01",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWPLAT01",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWPLAT01",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWPLAT01",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","DWPLAT01",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","MISC9W",Player1)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","MISC9W",Player2)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","MISC9W",Player3)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","MISC9W",Player4)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","MISC9W",Player5)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    TakeItemReplace("DWDUST","MISC9W",Player6)
END

IF
  Global("DrowItemCheck","AR4000",0)
THEN
    SetInterrupt(TRUE)
    SetGlobal("DrowItemCheck","AR4000",1)
END

IF
  Global("AerieSummoned","GLOBAL",0)
THEN
    SetGlobal("AerieSummoned","GLOBAL",2)
END

IF
  Global("AnomenSummoned","GLOBAL",0)
THEN
    SetGlobal("AnomenSummoned","GLOBAL",2)
END

IF
  Global("CerndSummoned","GLOBAL",0)
THEN
    SetGlobal("CerndSummoned","GLOBAL",2)
END

IF
  Global("EdwinSummoned","GLOBAL",0)
THEN
    SetGlobal("EdwinSummoned","GLOBAL",2)
END

IF
  Global("HaerDalisSummoned","GLOBAL",0)
THEN
    SetGlobal("HaerDalisSummoned","GLOBAL",2)
END

IF
  Global("ImoenSummoned","GLOBAL",0)
THEN
    SetGlobal("ImoenSummoned","GLOBAL",2)
END

IF
  Global("JaheiraSummoned","GLOBAL",0)
THEN
    SetGlobal("JaheiraSummoned","GLOBAL",2)
END

IF
  Global("JanSummoned","GLOBAL",0)
THEN
    SetGlobal("JanSummoned","GLOBAL",2)
END

IF
  Global("KeldornSummoned","GLOBAL",0)
THEN
    SetGlobal("KeldornSummoned","GLOBAL",2)
END

IF
  Global("KorganSummoned","GLOBAL",0)
THEN
    SetGlobal("KorganSummoned","GLOBAL",2)
END

IF
  Global("MazzySummoned","GLOBAL",0)
THEN
    SetGlobal("MazzySummoned","GLOBAL",2)
END

IF
  Global("MinscSummoned","GLOBAL",0)
THEN
    SetGlobal("MinscSummoned","GLOBAL",2)
END

IF
  Global("NaliaSummoned","GLOBAL",0)
THEN
    SetGlobal("NaliaSummoned","GLOBAL",2)
END

IF
  Global("ValygarSummoned","GLOBAL",0)
THEN
    SetGlobal("ValygarSummoned","GLOBAL",2)
END

IF
  Global("ViconiaSummoned","GLOBAL",0)
THEN
    SetGlobal("ViconiaSummoned","GLOBAL",2)
END

IF
  Global("YoshimoSummoned","GLOBAL",0)
THEN
    SetGlobal("YoshimoSummoned","GLOBAL",2)
END

IF
  Global("EnteredAR4000","AR4000",0)
THEN
    SetGlobal("EnteredAR4000","AR4000",1)
    TriggerActivation("HeadInfo1",TRUE)
    TriggerActivation("HeadInfo2",TRUE)
    TriggerActivation("HeadInfo3",TRUE)
    TriggerActivation("HeadInfo4",TRUE)
    TriggerActivation("HeadInfo5",TRUE)
    TriggerActivation("HeadInfo6",TRUE)
    TriggerActivation("HeadInfo7",TRUE)
    TriggerActivation("HeadInfo8",TRUE)
    TriggerActivation("HeadInfo9",TRUE)
    TriggerActivation("HeadInfo10",TRUE)
END

IF
  GlobalTimerExpired("IllaseraSpawnTimer","GLOBAL")
  Global("IllaseraSpawn","GLOBAL",0)
  OR(2)
    NumInParty(1)
    LevelPartyLT(10)
THEN
    ClearAllActions()
    SetGlobal("IllaseraSpawn","GLOBAL",1)
    StartCutSceneMode()
    StartCutScene("cut204f2")
END

IF
  GlobalTimerExpired("IllaseraSpawnTimer","GLOBAL")
  Global("IllaseraSpawn","GLOBAL",0)
  LevelPartyGT(19)
  NumInPartyLT(4)
THEN
    ClearAllActions()
    SetGlobal("IllaseraSpawn","GLOBAL",1)
    StartCutSceneMode()
    StartCutScene("cut204f3")
END

IF
  GlobalTimerExpired("IllaseraSpawnTimer","GLOBAL")
  Global("IllaseraSpawn","GLOBAL",0)
  LevelPartyLT(20)
  NumInPartyGT(1)
THEN
    ClearAllActions()
    SetGlobal("IllaseraSpawn","GLOBAL",1)
    StartCutSceneMode()
    StartCutScene("cut204f3")
END

IF
  GlobalTimerExpired("IllaseraSpawnTimer","GLOBAL")
  Global("IllaseraSpawn","GLOBAL",0)
  LevelPartyGT(19)
  NumInPartyGT(3)
THEN
    ClearAllActions()
    SetGlobal("IllaseraSpawn","GLOBAL",1)
    StartCutSceneMode()
    StartCutScene("cut204f")
END

IF
  Global("SetSolarDreamTimer","AR4000",0)
THEN
    SetGlobal("SetSolarDreamTimer","AR4000",1)
    SetGlobalTimer("DreamSolarTimer","GLOBAL",15)
END

IF
  Global("HeadsSave","AR4000",1)
THEN
    SetGlobal("HeadsSave","AR4000",2)
    SaveGame(0)
END

IF
  Global("HeadsSave","AR4000",2)
THEN
    SetGlobal("HeadsSave","AR4000",3)
    Wait(1)
END

IF
  Global("SolarDream","GLOBAL",0)
  GlobalTimerExpired("DreamSolarTimer","GLOBAL")
THEN
    ClearAllActions()
    SetGlobal("SolarDream","GLOBAL",1)
    StartCutSceneMode()
    StartCutScene("Cut205a")
END


END
