IF
  Global("UnlockAR5006","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("UnlockAR5006","GLOBAL",1)
END

IF
  GlobalTimerExpired("SaradushSiegeTimer","GLOBAL")
THEN
  RESPONSE #50
    SetGlobalTimer("SaradushSiegeTimer","GLOBAL",50)
  RESPONSE #50
    ScreenShake([20.20],3)
    PlaySound("AM5004S1")
    SetGlobalTimer("SaradushSiegeTimer","GLOBAL",50)
  RESPONSE #50
    ScreenShake([20.20],3)
    PlaySound("AM5004S2")
    SetGlobalTimer("SaradushSiegeTimer","GLOBAL",50)
END

