IF
  Global("EnteredArea","AR5002",0)
THEN
  RESPONSE #100
    ClearAllActions()
    SetGlobal("EnteredArea","AR5002",1)
    StartCutSceneMode()
    StartCutScene("cut225a")
END

IF
  Dead("Gromnir")  // ~Gromnir Il-Khan~
  Global("AddXP","AR5002",0)
THEN
  RESPONSE #100
    SetGlobal("AddXP","AR5002",1)
    AddXP2DA("Gromnir")
END

IF
  GlobalTimerExpired("SaradushSiegeTimer","GLOBAL")
THEN
  RESPONSE #50
    SetGlobalTimer("SaradushSiegeTimer","GLOBAL",50)
  RESPONSE #50
    ScreenShake([20.20],3)
    PlaySound("AM5004S1")
    SetGlobalTimer("SaradushSiegeTimer","GLOBAL",50)
  RESPONSE #50
    ScreenShake([20.20],3)
    PlaySound("AM5004S2")
    SetGlobalTimer("SaradushSiegeTimer","GLOBAL",50)
END

