IF
  Global("OpenDoor1","AR6001",0)
  OR(2)
    Dead("bazeye01")  // ~Iycanth the Mad~
    PartyHasItem("bazplo06")  // ~Reversal Scroll~
THEN
  RESPONSE #100
    SetGlobal("OpenDoor1","AR6001",1)
END

IF
  OpenState("DOOR01",FALSE)  // DOOR01
  Global("OpenDoor1","AR6001",1)
THEN
  RESPONSE #100
    Unlock("DOOR01")
    OpenDoor("DOOR01")
END

IF
  Global("OpenDoor2","AR6001",0)
  PartyHasItem("bazplo05")  // ~Rope~
THEN
  RESPONSE #100
    SetGlobal("OpenDoor2","AR6001",1)
END

IF
  OpenState("DOOR02",FALSE)  // DOOR02
  Global("OpenDoor2","AR6001",1)
THEN
  RESPONSE #100
    Unlock("DOOR02")
    OpenDoor("DOOR02")
END

IF
  Global("OpenDoor3","AR6001",0)
  Global("AbazigalLairOpen","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("OpenDoor3","AR6001",1)
END

IF
  OpenState("DOOR03",FALSE)  // DOOR03
  Global("OpenDoor3","AR6001",1)
THEN
  RESPONSE #100
    Unlock("DOOR03")
    OpenDoor("DOOR03")
END

