IF
  Global("EnteredAR6104","GLOBAL",1)
  !Dead("Sengua04")  // ~Slavemaster~
THEN
  RESPONSE #100
    ActionOverride("SenGua04",DestroySelf())
    SetGlobal("SPRITE_IS_DEADSenGua04","GLOBAL",1)
END

IF
  GlobalTimerExpired("HordeTimer","AR6102")
  GlobalLT("SendaiSlaveFight","GLOBAL",3)
  !Dead("Sengua04")  // ~Slavemaster~
THEN
  RESPONSE #100
    SetGlobalTimer("HordeTimer","AR6102",12)
    CreateCreature("senorc01",[2448.1536],8)  // ~Derro Berserker~
    CreateCreature("senorc02",[2572.1534],8)  // ~Derro~
    CreateCreature("senorc01",[182.1538],8)  // ~Derro Berserker~
    CreateCreature("senorc02",[296.1539],8)  // ~Derro~
END

IF
  GlobalTimerExpired("HordeTimer","AR6102")
  GlobalGT("SendaiSlaveFight","GLOBAL",2)
  !Dead("Sengua04")  // ~Slavemaster~
THEN
  RESPONSE #100
    SetGlobalTimer("HordeTimer","AR6102",14)
    CreateCreature("sensmsp2",[2448.1536],8)  // ~Orog~
    CreateCreature("sensmsp2",[2572.1534],8)  // ~Orog~
    CreateCreature("sensmsp2",[182.1538],8)  // ~Orog~
    CreateCreature("sensmsp2",[296.1539],8)  // ~Orog~
END

IF
  Global("SendaiSlaveFight","GLOBAL",4)
THEN
  RESPONSE #100
    SetGlobal("SendaiSlaveFight","GLOBAL",5)
    CreateVisualEffect("SPFLESHS",[2456.867])
    CreateVisualEffect("SPFLESHS",[2389.1047])
    CreateVisualEffect("SPFLESHS",[2220.1153])
    Wait(1)
    CreateCreature("umbhul02",[2456.867],4)  // ~Umber Hulk Elder~
    CreateCreature("umbhul01",[2389.1047],4)  // ~Umber Hulk~
    CreateCreature("umbhul02",[2220.1153],6)  // ~Umber Hulk Elder~
END

