IF
  Die()
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Detect([PC])
  Global("StartMoving","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("StartMoving","LOCALS",1)
    MoveToPointNoInterrupt([3513.352])
    Face(10)
END

IF
  Detect([PC])
  Range([PC],25)
  Global("StartMoving","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("StartMoving","LOCALS",2)
    Wait(1)
    ChangeAIScript("",CLASS)
    StartDialogNoSet([PC])
END

