IF
  Heard([ANYONE],151)
  InMyGroup(LastHeardBy(Myself))
  StateCheck(Myself,STATE_STONE_DEATH)
THEN
  RESPONSE #100
    ReallyForceSpellDeadRES("jwonehit",Myself)
END

IF
  Global("MakeFlesh","AR6003",0)
  !StateCheck(Myself,STATE_STONE_DEATH)
  !StateCheck(Myself,STATE_DEAD)
  See("bazpat01")  // ~Bondari~
  See("bazpat03")  // ~Tim Goldenhand~
THEN
  RESPONSE #100
    ClearAllActions()
    StartCutSceneMode()
    SetGlobal("MakeFlesh","AR6003",1)
    ApplySpell("bazpat01",WIZARD_STONE_TO_FLESH)
    ApplySpell("bazpat03",WIZARD_STONE_TO_FLESH)
    Wait(1)
    ActionOverride("bazpat01",StartDialogNoSet(Player1))
END

IF
  StateCheck(Myself,STATE_STONE_DEATH)
THEN
  RESPONSE #100
    NoAction()
END

