IF
  Global("BeholderBehavior","LOCALS",0)
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
THEN
  RESPONSE #100
    FaceObject(LastSeenBy(Myself))
    ForceSpell(LastSeenBy(Myself),WIZARD_ICE_STORM)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  HPGT(Myself,65)
THEN
  RESPONSE #100
    FaceObject([PC])
    ForceSpell([PC],WIZARD_MAGIC_MISSILE)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  HPGT(Myself,55)
THEN
  RESPONSE #100
    FaceObject(SecondNearest([PC]))
    ForceSpell(SecondNearest([PC]),WIZARD_BURNING_HANDS)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See(LeastDamagedOf(Myself))
  HPGT(Myself,45)
THEN
  RESPONSE #100
    FaceObject(LeastDamagedOf(Myself))
    ForceSpell(LeastDamagedOf(Myself),WIZARD_ICE_STORM)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  !See(LeastDamagedOf(Myself))
  HPGT(Myself,45)
THEN
  RESPONSE #100
    FaceObject([PC])
    ForceSpell([PC],WIZARD_MAGIC_MISSILE)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  !See([PC.0.0.MAGE])
THEN
  RESPONSE #100
    FaceObject([PC])
    ForceSpell([PC],BEHOLDER_SLOW)
    SetGlobal("BeholderBehavior","LOCALS",1)
    Wait(2)
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  HPGT(Myself,15)
THEN
  RESPONSE #100
    FaceObject([PC])
    ForceSpell([PC],WIZARD_BURNING_HANDS)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  HPGT(Myself,35)
THEN
  RESPONSE #100
    FaceObject(SecondNearest([PC]))
    ForceSpell(SecondNearest([PC]),BEHOLDER_SLOW)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  HPGT(Myself,5)
THEN
  RESPONSE #100
    FaceObject(ThirdNearest([PC]))
    ForceSpell(ThirdNearest([PC]),WIZARD_ICE_STORM)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See(LeastDamagedOf(Myself))
THEN
  RESPONSE #100
    FaceObject(LeastDamagedOf(Myself))
    ForceSpell(LeastDamagedOf(Myself),WIZARD_MAGIC_MISSILE)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  !See(LeastDamagedOf(Myself))
THEN
  RESPONSE #100
    FaceObject([PC])
    ForceSpell([PC],WIZARD_MAGIC_MISSILE)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  See([PC.0.0.MAGE])
THEN
  RESPONSE #100
    FaceObject(LastSeenBy(Myself))
    ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetGlobal("BeholderBehavior","LOCALS",0)
    Wait(2)
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  !See([PC.0.0.MAGE])
THEN
  RESPONSE #100
    FaceObject([PC])
    ForceSpell([PC],WIZARD_BURNING_HANDS)
    SetGlobal("BeholderBehavior","LOCALS",0)
    Wait(2)
END

