IF
  Global("ItemMaker","GLOBAL",1)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sw1h59",Player1,0,0,0)  // ~Short Sword of Mask +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",2)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sw1h61",Player1,0,0,0)  // ~Angurvadal +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",3)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sw1h63",Player1,0,0,0)  // ~Foebane +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",4)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sw1h65",Player1,0,1,2)  // ~Purifier +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",5)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sw2h18",Player1,0,0,0)  // ~Gram the Sword of Grief +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",6)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sw2h19",Player1,0,3,0)  // ~Carsomyr +6~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",7)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("dagg22",Player1,0,0,0)  // ~Dagger of the Star +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",8)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sper12",Player1,0,0,0)  // ~Ixil's Spike +6~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",9)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("ax1h15",Player1,0,0,0)  // ~Axe of the Unyielding +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",10)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("staf22",Player1,0,0,0)  // ~Staff of the Ram +6~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",11)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("halb11",Player1,0,3,0)  // ~Ravager +6~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",12)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sw1h69",Player1,0,0,0)  // ~Spectral Brand +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",13)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("sw1h71",Player1,0,1,0)  // ~Hindo's Doom +4~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",14)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("blun27",Player1,0,0,0)  // ~Club of Detonation +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",15)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("blun29",Player1,0,0,0)  // ~Storm Star +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",16)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("blun30c",Player1,0,0,0)  // ~Flail of Ages +4~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",17)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("blun30",Player1,0,0,0)  // ~Flail of Ages +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",18)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("hamm11",Player1,0,1,1)  // ~Runehammer +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",19)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("bow21",Player1,0,1,0)  // ~Darkfire Bow +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",20)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("bow23",Player1,0,0,0)  // ~Taralash +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",21)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("quiver03",Player1,0,0,0)  // ~Quiver of Plenty +2~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",22)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("xbow16",Player1,0,0,0)  // ~Firetooth +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",23)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("slng09",Player1,0,1,0)  // ~Erinne Sling +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",24)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("quiver06",Player1,0,0,0)  // ~Bag of Plenty +2~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",25)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("chan19",Player1,0,0,0)  // ~Aslyferund Elven Chain +5~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",26)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("chan20",Player1,3,0,0)  // ~White Dragon Scale~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",27)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("plat20",Player1,0,0,0)  // ~Blue Dragon Plate~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",28)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("clck31",Player1,0,0,0)  // ~Improved Cloak of Protection +2~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",29)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("tome02",Player1,1,0,0)  // ~Clay Golem Manual~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",30)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("tome03",Player1,1,0,0)  // ~Stone Golem Manual~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",31)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("tome04",Player1,1,0,0)  // ~Juggernaut Golem Manual~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",32)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("helm28",Player1,0,0,0)  // ~Circlet of Netheril~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",33)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("brac23",Player1,1,1,0)  // ~Blessed Bracers~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",34)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("brac25",Player1,0,0,0)  // ~Wondrous Gloves~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",35)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("clck32",Player1,0,0,0)  // ~Montolio's Cloak~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",36)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("helm32",Player1,3,0,0)  // ~Helm of the Rock~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",37)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("helm30",Player1,3,0,0)  // ~Thieves' Hood~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",38)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("ring44",Player1,0,0,0)  // ~Heartwood Ring~
    StartDialogNoSet(Player1)
END

IF
  Global("ItemMaker","GLOBAL",39)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("quiver04",Player1,0,0,0)  // ~Case of Plenty +2~
    StartDialogNoSet(Player1)
END

