IF
  Dead("HaerDalis")  // HaerDalis
  InPartyAllowDead("HaerDalis")  // HaerDalis
  Global("BounHaHD","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("BounHaHD","LOCALS",1)
    ForceSpell(Myself,DO_NOTHING)
    ApplySpell("HaerDalis",CLERIC_RESURRECTION)
END

IF
  OR(2)
    !Dead("HaerDalis")  // HaerDalis
    !InPartyAllowDead("HaerDalis")  // HaerDalis
  Detect([ENEMY])
  NumTimesTalkedToGT(0)
THEN
  RESPONSE #100
    CreateVisualEffectObject("SPFIREPI",LastSeenBy(Myself))
    Kill(LastSeenBy(Myself))
END

IF
  OR(2)
    !Dead("HaerDalis")  // HaerDalis
    !InPartyAllowDead("HaerDalis")  // HaerDalis
  !Detect([ENEMY])
  Detect([PC])
  NumTimesTalkedToGT(0)
THEN
  RESPONSE #100
    StartDialogNoSet(LastSeenBy(Myself))
END

