IF
  Global("ImTooSexyForThisBrus","GLOBAL",1)
  See([GOODCUTOFF])
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Global("ImTooSexyForThisBrus","GLOBAL",1)
  !See([GOODCUTOFF])
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  OR(2)
    !See(Player1)
    !Range(Player1,7)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  See(Player1)
  Range(Player1,7)
THEN
  RESPONSE #100
    StartDialogNoSet(Player1)
END

