IF
  Die()
THEN
  RESPONSE #100
    CreateCreatureObjectEffect("c6elven2","spportal",Player1)
END

IF
  NumberOfTimesTalkedTo(0)
  See([PC])
THEN
  RESPONSE #100
    Wait(1)
    StartDialogNoSet([PC])
END

IF
  See(NearestEnemyOf(Myself))
  Global("KillPlayer","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("KillPlayer","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_TIME_STOP)
    Kill(Player1)
END

