IF
  Die()
THEN
  RESPONSE #100
    ReallyForceSpellDead(Myself,VALEN_MIST_FORM_CHANGE)
END

IF
  See([PC])
  Global("ValenFight","AR0808",0)
THEN
  RESPONSE #100
    SetGlobal("ValenFight","AR0808",1)
    DisplayStringHead(Myself,53710)  // ~My mistress bids you welcome, <CHARNAME>.~
    CreateVisualEffect("SPCLOUD3",[599.1867])
    CreateCreature("C6VFLM01",[599.1867],10)  // ~Fledgling Vampire~
END

