IF
  Opened([ANYONE])
THEN
  RESPONSE #100
    StartMovie("MINEFLOD")
    ActionOverride(Player1,LeaveAreaLUA("AR1800","",[3099.718],12))
    ActionOverride(Player2,LeaveAreaLUA("AR1800","",[3088.686],12))
    ActionOverride(Player3,LeaveAreaLUA("AR1800","",[3087.649],12))
    ActionOverride(Player4,LeaveAreaLUA("AR1800","",[3090.588],12))
    ActionOverride(Player5,LeaveAreaLUA("AR1800","",[2998.680],12))
    ActionOverride(Player6,LeaveAreaLUA("AR1800","",[2936.699],12))
    DisplayString(Player1,19717)  // ~Undoubtedly. I would do as such again without hesitation. <CHARNAME> is proven decent and others are all the more fools for not seeing so.~ [JAHEIRD9]
    SetGlobal("FLOODED","GLOBAL",1)
    SetGlobal("NashkellAdventures","GLOBAL",2)
END

