









IF
  Die()
THEN
    CreateVisualEffectObject("ICRMPARI",Myself)
    DestroySelf()
END

IF
  Global("GetAwayNPC","LOCALS",1)
  Range(Player2,10)
THEN
    Continue()
END

IF
  Global("GetAwayNPC","LOCALS",1)
  Range(Player3,10)
THEN
    Continue()
END

IF
  Global("GetAwayNPC","LOCALS",1)
  Range(Player4,10)
THEN
    Continue()
END

IF
  Global("GetAwayNPC","LOCALS",1)
  Range(Player5,10)
THEN
    Continue()
END

IF
  Global("GetAwayNPC","LOCALS",1)
  Range(Player6,10)
THEN
    Continue()
END

IF
  Global("GetAwayNPC","LOCALS",1)
THEN
    SetGlobal("GetAwayNPC","LOCALS",0)
END

IF
  See(Player1)
  InPartySlot([GOODCUTOFF],0)
  Allegiance(Myself,ENEMY)
THEN
    AttackReevaluate(Player1,15)
END

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  Gender(LastSeenBy(Myself),SUMMONED)
  !LevelGT(LastSeenBy(Myself),9)
THEN
    CreateVisualEffectObject("SPGFLSH1",NearestEnemyOf(Myself))
    ActionOverride(NearestEnemyOf(Myself),DestroySelf())
END

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  InPartySlot(LastSeenBy(Myself),0)
  Global("GetAwayNPC","LOCALS",0)
THEN
    AttackReevaluate(Player1,30)
END

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  !InPartySlot(LastSeenBy(Myself),0)
  Global("GetAwayNPC","LOCALS",0)
  Allegiance(NearestEnemyOf(Myself),PC)
  !GlobalTimerNotExpired("ThrowBackTimer","LOCALS")
THEN
    SetGlobalTimer("ThrowBackTimer","LOCALS",10)
    SetGlobal("GetAwayNPC","LOCALS",1)
    SwingOnce()
END

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  !InPartySlot(LastSeenBy(Myself),0)
  Allegiance(NearestEnemyOf(Myself),GOODCUTOFF)
THEN
    AttackReevaluate(NearestEnemyOf(Myself),15)
END


END
