IF
  Entered([ANYONE])
  Global("Chase","GLOBAL",1)
THEN
  RESPONSE #20
    CreateCreature("DOPDOP",[725.814],0)  // DOPDOP
    CreateCreature("DOPKIE",[725.814],0)  // DOPKIE
    Wait(300)
  RESPONSE #20
    CreateCreature("DOPDUR",[725.814],0)  // DOPDUR
    CreateCreature("DOPDOP",[725.814],0)  // DOPDOP
    Wait(300)
  RESPONSE #20
    CreateCreature("DOPISL",[725.814],0)  // DOPISL
    CreateCreature("DOPDUR",[725.814],0)  // DOPDUR
    Wait(300)
  RESPONSE #20
    CreateCreature("DOPFUE",[725.814],0)  // DOPFUE
    CreateCreature("DOPISL",[725.814],0)  // DOPISL
    Wait(300)
  RESPONSE #20
    CreateCreature("DOPKIE",[725.814],0)  // DOPKIE
    CreateCreature("DOPFUE",[725.814],0)  // DOPFUE
    Wait(300)
END

IF
  Entered([ANYONE])
THEN
  RESPONSE #100
    Wait(1)
END

