IF
  Global("StoneFormPotion","LOCALS",0)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN46",Myself)  // ~Potion of Stone Form~
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    SetGlobal("StoneFormPotion","LOCALS",1)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN46",Myself)  // ~Potion of Stone Form~
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN55",Myself)  // ~Potion of Superior Healing~
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN55",Myself)  // ~Potion of Superior Healing~
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN52",Myself)  // ~Potion of Extra Healing~
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN52",Myself)  // ~Potion of Extra Healing~
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN08",Myself)  // ~Potion of Healing~
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN08",Myself)  // ~Potion of Healing~
END

IF
  HitBy([ANYONE],CRUSHING)
  Global("GiantStrengthPotion","LOCALS",0)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN05",Myself)  // ~Potion of Fire Giant Strength~
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    SetGlobal("GiantStrengthPotion","LOCALS",1)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN05",Myself)  // ~Potion of Fire Giant Strength~
END

IF
  HitBy([ANYONE],CRUSHING)
  Global("GiantStrengthPotion","LOCALS",0)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN07",Myself)  // ~Potion of Storm Giant Strength~
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    SetGlobal("GiantStrengthPotion","LOCALS",1)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN07",Myself)  // ~Potion of Storm Giant Strength~
END

IF
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  Global("HastePotion","LOCALS",0)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN14",Myself)  // ~Oil of Speed~
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    SetGlobal("HastePotion","LOCALS",1)
    SetGlobalTimer("SawEnemy","LOCALS",3)
END

IF
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  Global("HastePotion","LOCALS",1)
  GlobalTimerExpired("SawEnemy","LOCALS")
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN14",Myself)  // ~Oil of Speed~
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    SetGlobal("HastePotion","LOCALS",2)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN14",Myself)  // ~Oil of Speed~
END

IF
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN10",Myself)  // ~Potion of Invisibility~
  HaveSpell(KENSAI_KIA)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    Spell(Myself,KENSAI_KIA)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN10",Myself)  // ~Potion of Invisibility~
END

IF
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN10",Myself)  // ~Potion of Invisibility~
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN10",Myself)  // ~Potion of Invisibility~
END

IF
  HPPercentLT(Myself,25)
  HPGT(Myself,1)
  !Dead("yself)")  // yself)
  Global("Whined","LOCALS",0)
  See(NearestMyGroupOfType)
  Allegiance(Myself,ENEMY)
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobal("Whined","LOCALS",1)
    DisplayStringHead(Myself,46151)  // ~help!~
END

IF
  Heard([ANYONE],153)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),45)
END

IF
  Heard([ANYONE],154)
THEN
  RESPONSE #100
    AttackReevaluate([PC.0.0.MAGE],45)
END

IF
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),7)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

