IF
  Clicked([ANYONE])
  Global("UsePress","GLOBAL",0)
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    SetGlobal("UsePress","GLOBAL",1)
    DisplayString(Myself,23175)  // ~The winepress appears to be in working order but it needs power to begin pressing.~
END

IF
  Clicked([ANYONE])
  !Global("UseEngine","GLOBAL",2)
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    DisplayString(Myself,23175)  // ~The winepress appears to be in working order but it needs power to begin pressing.~
END

IF
  Clicked([ANYONE])
  PartyHasItem("MISC91")  // ~Grapes~
  Global("UsePress","GLOBAL",1)
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    SetGlobal("UsePress","GLOBAL",2)
    TakePartyItem("MISC91")
    GiveItemCreate("MISC1A",LastTrigger,0,0,0)  // ~Bottle of Wine~
    DisplayString(Myself,23179)  // ~You place the grapes in the press and gather their juice in a bottle.~
END

IF
  Clicked([ANYONE])
  Global("UsePress","GLOBAL",1)
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    DisplayString(Myself,23176)  // ~The press is ready but you have no fruit to place in it.~
END

IF
  Clicked([ANYONE])
  Global("UsePress","GLOBAL",2)
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    DisplayString(Myself,23182)  // ~You have no further use for the winepress.~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,9)
THEN
  RESPONSE #100
    DisplayString(Myself,23565)  // ~You are too far away to operate that device.~
END

