IF
  Heard([ANYONE],24)
  Detect([PC])
  HaveSpell(WIZARD_DETECT_INVISIBILITY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)
END

IF
  Heard([ANYONE],24)
  !Detect([PC])
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
END

IF
  Heard([ANYONE],99)
  !See([PC])
  Detect([PC])
  HaveSpell(WIZARD_DETECT_INVISIBILITY)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,EVILBUTBLUE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)
END

