IF
  Global("TalkedToBaronMetrich","GLOBAL",0)
  !See(Player1)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  Global("TalkedToBaronMetrich","GLOBAL",0)
  Global("TalkedCrolus","LOCALS",0)
  See(Player1)
THEN
  RESPONSE #100
    SetGlobal("TalkedCrolus","LOCALS",1)
    StartDialogNoSet(Player1)
END

IF
  Global("TalkedToBaronMetrich","GLOBAL",1)
THEN
  RESPONSE #100
    EscapeArea()
END

