IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("UsedCrypt0331","GLOBAL",0)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,37451)  // ~The lid of the sarcophagus moves easily aside despite the dour warnings and guardian runes written on the side. Within rests a golden skull. As you reach for it, it seems to move.~
    SetGlobal("UsedCrypt0331","GLOBAL",1)
    CreateCreature("HLSKULL",[681.465],0)  // ~Golden Skull~
END

IF
  Clicked([ANYONE])
  Exists("HLSKULL")  // ~Golden Skull~
  Range(LastTrigger,12)
  Global("UsedCrypt0331","GLOBAL",1)
THEN
  RESPONSE #100
    ActionOverride("HLSKULL",StartDialogNoSet(Player1))
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("UsedCrypt0331","GLOBAL",2)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,35864)  // ~The sarcophagus is now empty.~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,12)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

