IF
  Contains("PLOT01H",Myself)
  Global("PlacedBell","AR3001",0)
THEN
  RESPONSE #100
    PlaySound("chr_bell")
    SetGlobal("PlacedBell","AR3001",1)
END

IF
  !Contains("PLOT01H",Myself)
  Global("PlacedBell","AR3001",1)
THEN
  RESPONSE #100
    SetGlobal("PlacedBell","AR3001",0)
END

IF
  Contains("PLOT01F",Myself)
  Contains("PLOT01G",Myself)
  Contains("PLOT01H",Myself)
  Global("SpawnGorAlt1","AR3001",0)
  Global("ReturnRitualItems","AR3001",0)
  Global("SetDifficulty","AR3001",0)
  Dead("gorsta01")  // ~Statue~
  Dead("gorsta02")  // ~Statue~
  Dead("gorsta03")  // ~Statue~
  Dead("gorsta04")  // ~Statue~
THEN
  RESPONSE #100
    SetGlobal("SpawnGorAlt1","AR3001",1)
    CreateCreatureImpassable("GorAlt1",[819.781],14)
END

IF
  Contains("PLOT01F",Myself)
  Contains("PLOT01G",Myself)
  Contains("PLOT01H",Myself)
  Global("SpawnGorAlt1","AR3001",0)
  Global("ReturnRitualItems","AR3001",0)
  Global("SetDifficulty","AR3001",1)
  Dead("gorsta01")  // ~Statue~
  Dead("gorsta02")  // ~Statue~
THEN
  RESPONSE #100
    SetGlobal("SpawnGorAlt1","AR3001",1)
    CreateCreatureImpassable("GorAlt1",[819.781],14)
END

IF
  Global("ReturnRitualItems","AR3001",1)
  OR(3)
    !Contains("PLOT01F",Myself)
    !Contains("PLOT01G",Myself)
    !Contains("PLOT01H",Myself)
THEN
  RESPONSE #100
    SetGlobal("ReturnRitualItems","AR3001",0)
END

IF
  Global("ReturnRitualItems","AR3001",1)
  Contains("PLOT01F",Myself)
  Contains("PLOT01G",Myself)
  Contains("PLOT01H",Myself)
THEN
  RESPONSE #100
    DestroyItem("PLOT01F")  // ~Candle~
    DestroyItem("PLOT01G")  // ~Holy Book~
    DestroyItem("PLOT01H")  // ~Bell~
    GiveItemCreate("PLOT01F",Player1,0,0,0)  // ~Candle~
    GiveItemCreate("PLOT01G",Player1,0,0,0)  // ~Holy Book~
    GiveItemCreate("PLOT01H",Player1,0,0,0)  // ~Bell~
    SetGlobal("ReturnRitualItems","AR3001",0)
END

IF
  Global("PortalOpen","GLOBAL",1)
  Global("RitualComplete","AR3001",0)
  Contains("PLOT01F",Myself)
  Contains("PLOT01G",Myself)
  Contains("PLOT01H",Myself)
THEN
  RESPONSE #100
    DestroyItem("PLOT01F")  // ~Candle~
    DestroyItem("PLOT01G")  // ~Holy Book~
    DestroyItem("PLOT01H")  // ~Bell~
    SetGlobal("RitualComplete","AR3001",1)
END

IF
  Global("LivingStatues","AR3001",0)
  OR(3)
    Contains("PLOT01F",Myself)
    !Contains("PLOT01G",Myself)
    Contains("PLOT01H",Myself)
THEN
  RESPONSE #100
    SetGlobal("LivingStatues","AR3001",1)
END

