IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Shout(1)
    Enemy()
END

IF
  HitBy([GOODCUTOFF],CRUSHING)
THEN
  RESPONSE #100
    Shout(1)
    Continue()
END

IF
  Heard("CultWizard",1)  // CultWizard
  Allegiance(Myself,NEUTRAL)
  !Class(Myself,INNOCENT)
THEN
  RESPONSE #100
    Enemy()
    MoveToObject(LastHeardBy(Myself))
END

IF
  Heard("CultWizard",1)  // CultWizard
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Heard("CultWizard",1)  // CultWizard
  !Class(Myself,INNOCENT)
  !See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
    Continue()
END

IF
  Heard("CultGuard",1)  // CultGuard
  Allegiance(Myself,NEUTRAL)
  !Class(Myself,INNOCENT)
THEN
  RESPONSE #100
    Enemy()
    MoveToObject(LastHeardBy(Myself))
END

IF
  Heard("CultGuard",1)  // CultGuard
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Heard("CultGuard",1)  // CultGuard
  !Class(Myself,INNOCENT)
  !See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
    Continue()
END

IF
  Heard("CultAssassin",1)  // CultAssassin
  Allegiance(Myself,NEUTRAL)
  !Class(Myself,INNOCENT)
THEN
  RESPONSE #100
    Enemy()
    MoveToObject(LastHeardBy(Myself))
END

IF
  Heard("CultAssassin",1)  // CultAssassin
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Heard("CultAssassin",1)  // CultAssassin
  !Class(Myself,INNOCENT)
  !See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
    Continue()
END

IF
  Heard("CultArcher",1)  // CultArcher
  Allegiance(Myself,NEUTRAL)
  !Class(Myself,INNOCENT)
THEN
  RESPONSE #100
    Enemy()
    MoveToObject(LastHeardBy(Myself))
END

IF
  Heard("CultArcher",1)  // CultArcher
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Heard("CultArcher",1)  // CultArcher
  !Class(Myself,INNOCENT)
  !See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
    Continue()
END

