IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([20.0],0)
    Wait(1)
    CreateCreature("SPY406",[732.1777],0)  // <Invalid Strref -1>
    Face(4)
    CreateCreature("CPCHICK1",[732.1777],4)  // ~Party's Dog~
    CreateCreature("CPCHICK2",[446.1773],12)  // ~Surly's Dog~
    MoveViewPoint([597.1770],INSTANT)
    FadeFromColor([20.0],0)
    Wait(1)
    StartCutScene("Cut04b")
END

