IF
  True()
THEN
  RESPONSE #100
    CutSceneId("hprelate")  // 
    FadeToColor([0.0],0)
    Wait(2)
    JumpToPoint([1045.982])
    Face(13)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    Wait(2)
    JumpToPoint([863.1285])
    MoveViewPoint([863.1285],INSTANT)
    Face(7)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("kayl2")  // 
    Face(13)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Anomen")  // 
    Wait(2)
    JumpToPoint([919.1230])
    Face(6)
    FadeFromColor([20.0],0)
    Wait(2)
    StartDialogNoSet(Player1)
    JoinParty()
END

