IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    Wait(1)
    ActionOverride("Raelis",ForceSpell(Myself,DO_NOTHING))
    ActionOverride("FFActor1",ForceSpell(Myself,DO_NOTHING))
    ActionOverride("FFActor2",ForceSpell(Myself,DO_NOTHING))
    Wait(3)
    FadeToColor([20.0],0)
    Wait(1)
    LeaveAreaLUAPanic("AR0523","",[884.596],8)
    LeaveAreaLUA("AR0523","",[884.596],8)
    ActionOverride(Player2,LeaveAreaLUA("AR0523","",[796.595],0))
    ActionOverride(Player3,LeaveAreaLUA("AR0523","",[820.628],0))
    ActionOverride(Player4,LeaveAreaLUA("AR0523","",[863.642],0))
    ActionOverride(Player5,LeaveAreaLUA("AR0523","",[919.644],0))
    ActionOverride(Player6,LeaveAreaLUA("AR0523","",[968.632],0))
    ActionOverride("HaerDalis",LeaveAreaLUA("AR0523","",[908.526],0))
    MultiPlayerSync()
    SetMasterArea("AR0500")
    Wait(1)
    FadeFromColor([20.0],0)
    Wait(1)
    ActionOverride("HaerDalis",StartDialogNoSet(Player1))
    EndCutSceneMode()
END

