IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([30.0],0)
    Wait(2)
    MoveViewObject("Head5",INSTANT)
    Explore()
    Wait(1)
    FadeFromColor([30.0],0)
    SmallWait(5)
    ScreenShake([20.20],20)
    PlaySound("EFF_M36B")
    Wait(2)
    AmbientActivate("AMB_Head5L",TRUE)
    AmbientActivate("AMB_Head5R",TRUE)
    SmallWait(5)
    StaticSequence("AMB_Head5L",1)
    StaticSequence("AMB_Head5R",1)
    ActionOverride("Head5",StartDialogNoSet(Player1))
END

