IF
  True()
THEN
  RESPONSE #100
    CutSceneId("arntra03")  // 
    EquipRanged()
    MoveViewPoint([2159.1379],VERY_FAST)
    MoveToPointNoInterrupt([2159.1379])
    CreateCreature("ARNTRA06",[2020.1266],14)  // ~Shadow Thief~
    AttackOneRound("arntra06")
    Wait(1)
    Kill("arntra06")
    Wait(1)
    SetGlobal("arntra03Move","AR0307",1)
    ActionOverride("pelanna",StartDialogNoSet([PC]))
END

