IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    ApplySpell("goriond",SURE_STONE_SHATTER)
    ApplySpell("elmind",SURE_STONE_SHATTER)
    ApplySpell("khalidd",SURE_STONE_SHATTER)
    Wait(2)
    FadeToColor([40.0],0)
    MoveViewPoint([2625.2044],6)
    ActionOverride("Dream1",MoveToPoint([2625.2044]))
    MoveToPoint([2572.2040])
    ActionOverride("Dream1",JumpToPoint([2591.1525]))
    MoveViewPoint([2591.1525],INSTANT)
    Wait(1)
    JumpToPoint([2637.1567])
    FadeFromColor([30.0],0)
    MoveViewPoint([2654.1434],VERY_FAST)
    ActionOverride("Dream1",MoveToPoint([2600.1366]))
    MoveToPoint([2657.1434])
    ActionOverride("Dream1",Wait(2))
    ActionOverride("Dream1",StartDialogNoSet(Player1))
END

