IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([30.0],0)
    Wait(2)
    LeaveAreaLUAPanic("AR3000","",[710.1655],14)
    LeaveAreaLUA("AR3000","",[710.1655],14)
    ActionOverride(Player2,LeaveAreaLUA("AR3000","",[678.1659],14))
    ActionOverride(Player3,LeaveAreaLUA("AR3000","",[691.1627],14))
    ActionOverride(Player4,LeaveAreaLUA("AR3000","",[652.1618],14))
    ActionOverride(Player5,LeaveAreaLUA("AR3000","",[652.1570],14))
    ActionOverride(Player6,LeaveAreaLUA("AR3000","",[614.1568],14))
    Wait(2)
    MultiPlayerSync()
    FadeFromColor([30.0],0)
    EndCutSceneMode()
END

