IF
  True()
THEN
  RESPONSE #100
    CutSceneId("finsol01")  // 
    FaceObject("finmel01")
    MoveViewObject("finmel01",INSTANT)
    Wait(1)
    CreateVisualEffect("SPGRWHRL",[1288.1131])
    PlaySound("EFF_M28")
    Wait(1)
    FadeToColor([30.0],0)
    Wait(2)
    StartMovie("MELISSAN")
    Wait(1)
    StartMovie("ENDMVE2")
    SetGlobal("StartEndBios","AR6200",1)
    ActionOverride("finmel01",DestroySelf())
    SetCutSceneLite(TRUE)
    EndCutSceneMode()
END

