IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([30.0],0)
    Wait(2)
    ActionOverride("Head1",DestroySelf())
    ActionOverride("Head2",DestroySelf())
    ActionOverride("Head3",DestroySelf())
    ActionOverride("Head4",DestroySelf())
    ActionOverride("Head5",DestroySelf())
    SetGlobal("HeadsSave","AR4000",1)
    JumpToPoint([615.489])
    Face(15)
    ActionOverride(Player2,JumpToPoint([683.463]))
    ActionOverride(Player2,Face(15))
    ActionOverride(Player3,JumpToPoint([744.437]))
    ActionOverride(Player3,Face(15))
    ActionOverride(Player4,JumpToPoint([569.430]))
    ActionOverride(Player4,Face(15))
    ActionOverride(Player5,JumpToPoint([637.401]))
    ActionOverride(Player5,Face(15))
    ActionOverride(Player6,JumpToPoint([698.378]))
    ActionOverride(Player6,Face(15))
    SmallWait(2)
    Face(14)
    MoveViewObject(Player1,INSTANT)
    Wait(2)
    FadeFromColor([30.0],0)
    EndCutSceneMode()
END

