IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([30.0],0)
    Wait(2)
    LeaveAreaLUAPanic("AR3000","",[307.1815],14)
    LeaveAreaLUA("AR3000","",[307.1815],14)
    ActionOverride(Player2,LeaveAreaLUA("AR3000","",[268.1840],14))
    ActionOverride(Player3,LeaveAreaLUA("AR3000","",[274.1781],14))
    ActionOverride(Player4,LeaveAreaLUA("AR3000","",[232.1802],14))
    ActionOverride(Player5,LeaveAreaLUA("AR3000","",[236.1748],14))
    ActionOverride(Player6,LeaveAreaLUA("AR3000","",[195.1767],14))
    Wait(2)
    MultiPlayerSync()
    FadeFromColor([30.0],0)
    EndCutSceneMode()
END

