IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([30.0],0)
    Wait(2)
    LeaveAreaLUAPanic("AR3014","",[498.493],14)
    LeaveAreaLUA("AR3014","",[498.493],14)
    ActionOverride(Player2,LeaveAreaLUA("AR3014","",[454.529],14))
    ActionOverride(Player3,LeaveAreaLUA("AR3014","",[475.471],14))
    ActionOverride(Player4,LeaveAreaLUA("AR3014","",[436.479],14))
    ActionOverride(Player5,LeaveAreaLUA("AR3014","",[445.454],14))
    ActionOverride(Player6,LeaveAreaLUA("AR3014","",[402.473],14))
    Wait(2)
    MultiPlayerSync()
    FadeFromColor([30.0],0)
    EndCutSceneMode()
END

