IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    ClearAllActions()
    FadeToColor([30.0],0)
    Wait(2)
    LeaveAreaLUAPanic("AR4500","",[1986.1304],14)
    LeaveAreaLUA("AR4500","",[1986.1304],14)
    ActionOverride(Player2,LeaveAreaLUA("AR4500","",[2032.1256],14))
    ActionOverride(Player3,LeaveAreaLUA("AR4500","",[1939.1231],14))
    ActionOverride(Player4,LeaveAreaLUA("AR4500","",[2004.1202],14))
    ActionOverride(Player5,LeaveAreaLUA("AR4500","",[1986.1130],14))
    ActionOverride(Player6,LeaveAreaLUA("AR4500","",[2030.1087],14))
    Wait(2)
    MultiPlayerSync()
    EndCutSceneMode()
END

