IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    StorePartyLocations()
    FadeToColor([30.0],0)
    Wait(2)
    LeaveAreaLUAPanic("AR4500","",[1657.1284],14)
    LeaveAreaLUA("AR4500","",[1657.1284],14)
    ActionOverride(Player2,LeaveAreaLUA("AR4500","",[1587.1246],10))
    ActionOverride(Player3,LeaveAreaLUA("AR4500","",[1614.1190],2))
    ActionOverride(Player4,LeaveAreaLUA("AR4500","",[1563.1208],8))
    ActionOverride(Player5,LeaveAreaLUA("AR4500","",[1527.1245],12))
    ActionOverride(Player6,LeaveAreaLUA("AR4500","",[1479.1265],4))
    MultiPlayerSync()
    MoveViewPoint([1657.1284],INSTANT)
    ActionOverride(Player2,PlayDeadInterruptible(100000))
    ActionOverride(Player3,PlayDeadInterruptible(100000))
    ActionOverride(Player4,PlayDeadInterruptible(100000))
    ActionOverride(Player5,PlayDeadInterruptible(100000))
    ActionOverride(Player6,PlayDeadInterruptible(100000))
    Explore()
    Wait(2)
    FadeFromColor([30.0],0)
    PlaySong(68)
    Wait(1)
    MoveViewPoint([1870.1438],6)
    MoveToPoint([1870.1438])
    CreateCreature("CUTSPY",[1992.1553],0)  // <Invalid Strref -1>
    CreateVisualEffect("SPPOWRRD",[1992.1553])
    PlaySound("EFF_M18a")
    Wait(1)
    ActionOverride("cutspy",ReallyForceSpell(Myself,HOLY_PILLAR_VISUAL))
    Wait(1)
    SmallWait(7)
    SetGlobal("TalkedToSolar","GLOBAL",3)
    CreateCreature("SOLAR",[1992.1553],6)  // ~Solar~
    SmallWait(7)
    ActionOverride("cutspy",DestroySelf())
    Wait(1)
    ActionOverride("solar",StartDialogNoSet(Player1))
END

