IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([20.0],0)
    MoveViewPoint([844.3245],INSTANT)
    Wait(1)
    JumpToPoint([844.3245])
    Wait(1)
    ActionOverride(Player2,JumpToPoint([890.3218]))
    ActionOverride(Player3,JumpToPoint([966.3177]))
    ActionOverride(Player4,JumpToPoint([862.3281]))
    ActionOverride(Player5,JumpToPoint([934.3249]))
    ActionOverride(Player6,JumpToPoint([991.3196]))
    Wait(1)
    FadeFromColor([20.0],0)
    ActionOverride("garren",MoveBetweenAreas("ar1204",[422.430],0))
    EndCutSceneMode()
END

