IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([30.0],0)
    Wait(1)
    LeaveAreaLUAPanic("AR6104","",[1077.968],14)
    LeaveAreaLUA("AR6104","",[1077.968],14)
    ActionOverride(Player2,LeaveAreaLUA("AR6104","",[1116.939],14))
    ActionOverride(Player3,LeaveAreaLUA("AR6104","",[1034.926],14))
    ActionOverride(Player4,LeaveAreaLUA("AR6104","",[1076.890],14))
    ActionOverride(Player5,LeaveAreaLUA("AR6104","",[998.878],14))
    ActionOverride(Player6,LeaveAreaLUA("AR6104","",[1036.848],14))
    Wait(1)
    MultiPlayerSync()
    FadeFromColor([30.0],0)
    EndCutSceneMode()
END

