









IF
  True()
THEN
    SetGlobal("DruidFight","AR1901",8)
    StorePartyLocations()
    TriggerActivation("THESOURCE",FALSE)
    SetGlobal("SourceReactivate","AR1901",1)
    FadeToColor([20.0],0)
    Wait(2)
    MoveViewPoint([1250.958],INSTANT)
    ActionOverride("cefaldor",DestroySelf())
    ActionOverride(Player6,DropInventory())
    ActionOverride(Player6,JumpToPoint([1332.966]))
    ActionOverride(Player6,Face(4))
    FadeFromColor([20.0],0)
    Wait(2)
    EndCutSceneMode()
END


END
