IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    SetGlobal("DruidFight","AR1901",3)
    StorePartyLocations()
    TriggerActivation("THESOURCE",FALSE)
    SetGlobal("SourceReactivate","AR1901",1)
    FadeToColor([20.0],0)
    Wait(2)
    MoveViewPoint([1250.958],INSTANT)
    ActionOverride("cefaldor",DestroySelf())
    DropInventory()
    JumpToPoint([1332.966])
    Face(4)
    CreateCreature("CEFALD01",[1173.964],12)  // ~Faldorn~
    FadeFromColor([20.0],0)
    Wait(2)
    EndCutSceneMode()
END

