IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([30.0],0)
    Wait(1)
    LeaveAreaLUAPanic("AR1306","",[1082.918],6)
    LeaveAreaLUA("AR1306","",[1082.918],6)
    ActionOverride(Player2,LeaveAreaLUA("AR1306","",[1111.960],6))
    ActionOverride(Player3,LeaveAreaLUA("AR1306","",[1168.945],6))
    ActionOverride(Player4,LeaveAreaLUA("AR1306","",[1099.1005],6))
    ActionOverride(Player5,LeaveAreaLUA("AR1306","",[1166.1007],6))
    ActionOverride(Player6,LeaveAreaLUA("AR1306","",[1228.1005],6))
    MultiPlayerSync()
    MoveGlobal("AR1306","Nalia",[1136.905])
    FadeFromColor([30.0],0)
    Wait(1)
    EndCutSceneMode()
    ActionOverride("kpdomo01",Wait(1))
    ActionOverride("kpdomo01",StartDialogNoSet(Player1))
END

