IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([20.0],0)
    Wait(1)
    ActionOverride("bdhigg01",DestroySelf())
    LeaveAreaLUAPanic("AR0523","",[1071.623],6)
    LeaveAreaLUA("AR0523","",[1071.623],6)
    ActionOverride(Player2,LeaveAreaLUA("AR0523","",[563.729],6))
    ActionOverride(Player3,LeaveAreaLUA("AR0523","",[891.936],6))
    ActionOverride(Player4,LeaveAreaLUA("AR0523","",[939.902],6))
    ActionOverride(Player5,LeaveAreaLUA("AR0523","",[600.679],6))
    ActionOverride(Player6,LeaveAreaLUA("AR0523","",[459.810],6))
    MultiPlayerSync()
    Wait(1)
    CreateCreature("bdaud01",[524.854],10)  // ~Peasant~
    CreateCreature("bdaud02",[834.915],10)  // ~Peasant~
    CreateCreature("bdaud03",[735.908],10)  // ~Commoner~
    CreateCreature("bdcoun01",[596.757],10)  // ~Council Member~
    CreateCreature("bdcoun02",[638.775],10)  // ~Courtier~
    CreateCreature("bdcoun03",[510.671],10)  // ~Bodyguard~
    CreateCreature("bdcoun04",[592.825],10)  // bdcoun04
    ActionOverride("bdhigg01",JumpToPoint([880.844]))
    ActionOverride("bdact06",JumpToPoint([931.707]))
    ActionOverride("bdact06",Face(0))
    SetGlobal("BardPlot1","GLOBAL",52)
    FadeFromColor([20.0],0)
    Wait(2)
    ActionOverride("bdact06",StartDialogNoSet(Player1))
END

