IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([20.0],0)
    Wait(2)
    ActionOverride("ISAEA",EscapeArea())
    ActionOverride("ISAMNG1",EscapeArea())
    ActionOverride("ISAMNG2",EscapeArea())
    ActionOverride("ISAMNG3",EscapeArea())
    ActionOverride("ISAMNG4",EscapeArea())
    ActionOverride("NALIA",SetLeavePartyDialogueFile())
    ActionOverride("NALIA",ChangeAIScript("",DEFAULT))
    ActionOverride("NALIA",GivePartyAllEquipment())
    ActionOverride("NALIA",EscapeArea())
    Wait(1)
    CreateCreatureObjectOffScreen("KHELLOR",Myself,0,0,0)  // ~Khellor Ahmson~
    Wait(2)
    FadeFromColor([20.0],0)
    Wait(2)
    ActionOverride("KHELLOR",Dialog([PC]))
    EndCutSceneMode()
END

