IF
  True()
THEN
  RESPONSE #100
    CutSceneId("c6gener")  // 
    Wait(1)
    FadeToColor([20.0],0)
    Wait(2)
    CreateCreature("c6warsa1",[784.1076],0)  // ~Elven War Sage~
    CreateCreature("c6warsa2",[721.1106],0)  // ~Elven War Sage~
    JumpToPoint([831.1905])
    Wait(1)
    FadeFromColor([20.0],0)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("c6elhan")  // 
    Wait(6)
    StartDialogNoSet([PC])
END

