IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([20.0],0)
    Wait(2)
    JumpToPoint([4377.2827])
    ActionOverride(Player2,JumpToPoint([4450.2838]))
    ActionOverride(Player3,JumpToPoint([4345.2869]))
    ActionOverride(Player4,JumpToPoint([4412.2889]))
    ActionOverride(Player5,JumpToPoint([4318.2814]))
    ActionOverride(Player6,JumpToPoint([4381.2930]))
    ActionOverride("sahkng01",JumpToPoint([4471.2754]))
    Face(10)
    ActionOverride(Player2,Face(10))
    ActionOverride(Player3,Face(10))
    ActionOverride(Player4,Face(10))
    ActionOverride(Player5,Face(10))
    ActionOverride(Player6,Face(10))
    MoveViewPoint([4377.2827],INSTANT)
    FadeFromColor([20.0],0)
    Wait(2)
    ActionOverride("sahkng01",StartDialogNoSet([PC]))
END

