IF
  True()
THEN
  RESPONSE #100
    CutSceneId("UDMASTER")  // 
    FadeToColor([20.0],0)
    Wait(1)
    MoveViewPoint([2445.1635],INSTANT)
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    Wait(1)
    ActionOverride(Player1,JumpToPoint([2445.1635]))
    ActionOverride(Player2,JumpToPoint([2487.1593]))
    ActionOverride(Player3,JumpToPoint([2505.1526]))
    ActionOverride(Player4,JumpToPoint([2531.1615]))
    ActionOverride(Player5,JumpToPoint([2574.1567]))
    ActionOverride(Player6,JumpToPoint([2624.1599]))
    FadeFromColor([20.0],0)
    Wait(1)
    EndCutSceneMode()
END

