IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([20.0],0)
    Wait(1)
    JumpToPoint([2161.1919])
    ActionOverride(Player2,JumpToPoint([2212.1967]))
    ActionOverride(Player3,JumpToPoint([2247.2029]))
    ActionOverride(Player4,JumpToPoint([2103.1899]))
    ActionOverride(Player5,JumpToPoint([2162.1986]))
    ActionOverride(Player6,JumpToPoint([2198.2079]))
    ActionOverride("udogre",JumpToPoint([2779.1684]))
    CreateCreature("udumb02",[1845.2172],12)  // ~Umber Hulk~
    CreateCreature("udumb02",[1817.2080],12)  // ~Umber Hulk~
    CreateCreature("udumb02",[1896.2089],12)  // ~Umber Hulk~
    MoveViewPoint([2198.2079],100)
    FadeFromColor([20.0],0)
    Wait(1)
    EndCutSceneMode()
END

