IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    ActionOverride("sujon",DestroyItem("MINHP1"))  // <Invalid Strref -1>
    CreateVisualEffectObject("SPFLSRIN","sujon")
    Wait(1)
    CreateVisualEffectObject("SPFLSRIN","sujon")
    Wait(1)
    ScreenShake([15.15],45)
    PlaySound("EFF_M87")
    CreateVisualEffectObject("SPDEATH3","sujon")
    SmallWait(7)
    CreateVisualEffectObject("SPFLESHS","sujon")
    Kill("sujon")
    Wait(2)
    StartDialogue("Player1",Player1)
END

