IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    FadeToColor([20.0],0)
    Wait(1)
    ActionOverride("Raelis",DestroySelf())
    ActionOverride("FFactor1",DestroySelf())
    ActionOverride("FFactor2",DestroySelf())
    ActionOverride("HaerDalis",DestroySelf())
    ActionOverride("FFBiff01",DestroySelf())
    JumpToPoint([312.1212])
    ActionOverride(Player2,JumpToPoint([349.1182]))
    ActionOverride(Player3,JumpToPoint([315.1152]))
    ActionOverride(Player4,JumpToPoint([287.1115]))
    ActionOverride(Player5,JumpToPoint([331.1112]))
    ActionOverride(Player6,JumpToPoint([367.1134]))
    MoveViewPoint([312.1212],INSTANT)
    Wait(1)
    FadeFromColor([20.0],0)
    EndCutSceneMode()
END

