IF
  True()
THEN
  RESPONSE #100
    CutSceneId("sujon")  // 
    EraseJournalEntry(23447)  // ~Freeing Queen EllesimeI spoke with the projected image of Queen Ellesime.  She is held near the center of the Tree of Life, caged with corruptive magics.  Irenicus is absorbing the power of the Tree, draining it with three strange parasites that have been attached to the trunk in various places.  Ellesime says that Irenicus is oblivious to everything around him, and may be stopped if we act quickly.I must kill the parasites, reaching them by growing branches using nuts from the palace gardens.  Once this is done, Ellesime will be freed from her cage and she can sever Irenicus' connection to the tree.~
    EraseJournalEntry(16543)  // ~Freeing Queen EllesimeThere is only one more parasite left to kill, and Ellesime says it must be dispatched quickly.  Once it is killed she will begin disconnecting Irenicus from the Tree of Life, and I will have to go to the central area quickly. Irenicus will be disoriented and weak, and that may be my only chance.  She warns caution though; the effect of the mage absorbing the Tree's power is unknown.~
    SetGlobal("EllesimeLeave","AR2806",1)
    ActionOverride("suelle",ReallyForceSpell(Myself,DRYAD_TELEPORT))
    Wait(4)
    SetGlobal("EllesimeLeave","AR2806",2)
    StartDialogNoSet(Player1)
END

