IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    Wait(4)
    SetGlobal("SpawnDeril","GLOBAL",2)
    SetGlobal("DerilArrives","AR1004",1)
    Wait(2)
    CreateCreature("CeDeril",[368.600],10)  // ~Deril~
    EndCutSceneMode()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("ceglut")  // 
    MoveToPointNoInterrupt([268.615])
    Wait(1)
    ReallyForceSpell(Myself,FIREBALL_DEATH)
    SetGlobal("SpawnDeril","GLOBAL",1)
    Kill(Myself)
END

