IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    Wait(1)
    FadeToColor([20.0],0)
    Wait(1)
    JumpToPoint([1112.795])
    ActionOverride(Player2,JumpToPoint([1183.781]))
    ActionOverride(Player3,JumpToPoint([1070.849]))
    ActionOverride(Player4,JumpToPoint([1155.843]))
    ActionOverride(Player5,JumpToPoint([1053.913]))
    ActionOverride(Player6,JumpToPoint([1250.757]))
    Wait(1)
    ActionOverride(Player2,Face(6))
    ActionOverride(Player3,Face(6))
    ActionOverride(Player4,Face(6))
    ActionOverride(Player5,Face(6))
    ActionOverride(Player6,Face(6))
    Face(6)
    AmbientActivate("AMB_DOOR01",TRUE)
    SoundActivate("EnergyBarrier1",TRUE)
    Unlock("Door1")
    CloseDoor("Door1")
    Lock("Door1")
    FadeFromColor([20.0],0)
    MoveViewObject(Player1,5)
    Wait(3)
    CreateVisualEffect("SPPORTAL",[922.672])
    CreateCreature("CHALSP01",[922.672],13)  // ~Gavid~
    Wait(4)
    ActionOverride("chalsp01",StartDialogNoSet(Player1))
END

