IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    Wait(2)
    FadeToColor([20.0],0)
    Wait(1)
    JumpToPoint([1112.795])
    Face(6)
    Wait(1)
    MoveViewObject(Player1,VERY_FAST)
    Wait(1)
    FadeFromColor([20.0],0)
    CreateVisualEffect("SPPORTAL",[922.672])
    CreateCreature("CHALSP01",[922.672],13)  // ~Gavid~
    Wait(3)
    ActionOverride("chalsp01",StartDialogNoSet(Player1))
END

