IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSIren")  // 
    DisplayStringWait("CSCowl1",2866)  // ~This is an unsanctioned use of magical energy!~ [CSCOW102]
    DisplayStringWait("CSCowl2",2868)  // ~All involved will be held!  This disturbance is over!~ [CSCOW501]
    DisplayStringWait(Myself,2869)  // ~Must I be interrupted at every turn!  Enough of this!~ [DPJON137]
    CreateVisualEffectObject("SPPLANAR",Myself)
    ForceSpell("CSCowl5",CUTSCENE_POWERWORD_KILL)
    ForceSpell("CSCowl1",FLASHY_1)
    ForceSpell("CSCowl3",FLASHY_2)
    ForceSpell("CSCowl2",WIZARD_DISINTEGRATE2_IGNORE_RESISTANCE)
    CreateVisualEffectObject("SPSDIMPA","CSCowl2")
    PlaySound("EFF_M28")
    CreateCreatureDoor("CSCOWL6",[549.736],8)
    CreateCreatureDoor("CSCOWL7",[560.543],0)
    ForceSpell("CSCowl1",CUTSCENE_POWERWORD_KILL)
    CreateVisualEffectObject("SPDEATH3","CSCowl1")
    PlaySound("EFF_M28")
    CreateCreatureDoor("CSCOWL8",[662.650],2)
    StartCutScene("CutD1f")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSImoen")  // 
    Wait(9)
    SmallWait(7)
    ForceSpell("CSIren",FLASHY_4)
    Wait(1)
    ForceSpell("CSIren",WIZARD_MAGIC_MISSILE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSCowl1")  // 
    Wait(9)
    ForceSpell("CSIren",FLASHY_1)
    Wait(1)
    ForceSpell("CSIren",FLASHY_2)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSCowl2")  // 
    Wait(9)
    SmallWait(7)
    ForceSpell("CSIren",CUTSCENE_RUBY_RAY_OF_REVERSAL)
    ForceSpell("CSIren",FLASHY_2)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSCowl3")  // 
    Wait(10)
    SmallWait(7)
    ForceSpell("CSIren",CUTSCENE_BREACH)
    Wait(1)
    ForceSpell("CSIren",FLASHY_4)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSCowl4")  // 
    Wait(10)
    ForceSpell("CSIren",CUTSCENE_RUBY_RAY_OF_REVERSAL)
    Wait(1)
    ForceSpell("CSIren",FLASHY_1)
END

