IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
    CreateVisualEffect("SPMETSWA",[381.612])
    CreateVisualEffect("SPMETSWA",[540.722])
    SmallWait(3)
    CreateVisualEffect("SPMETSWA",[725.630])
    CreateVisualEffect("SPMETSWA",[544.463])
    SmallWait(4)
    CreateVisualEffect("SPMETSWA",[719.472])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSIren")  // 
    Wait(1)
    DisplayStringHead(Myself,2844)  // ~You will suffer!  You will all suffer!~ [DPJON132]
    Wait(1)
    Face(0)
    PlaySound("EFF_M23C")
    CreateVisualEffectObject("SPROTECT",Myself)
    ForceSpell("CSThief3",CUTSCENE_POWERWORD_KILL)
    CreateVisualEffectObject("SPFIREPI","CSThief3")
    PlaySound("EFF_M23C")
    CreateVisualEffectObject("SPROTECT",Myself)
    Face(14)
    ForceSpell("CSThief1",CUTSCENE_POWERWORD_KILL)
    CreateVisualEffectObject("SPFLSRIN","CSThief1")
    PlaySound("EFF_M23C")
    CreateVisualEffectObject("SPROTECT",Myself)
    ForceSpell("CSThief4",CUTSCENE_POWERWORD_KILL)
    CreateVisualEffectObject("CALLLIGH","CSThief4")
    ForceSpell("CSThief2",WIZARD_FLAME_ARROW)
    CreateVisualEffectObject("ICFIRSDI",Myself)
    Wait(1)
    StartCutScene("cutD1c")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSThief1")  // 
    Wait(1)
    SmallWait(7)
    Enemy()
    EquipMostDamagingMelee()
    Attack("CSIren")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSThief2")  // 
    Enemy()
    EquipMostDamagingMelee()
    Attack("CSIren")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSThief3")  // 
    Wait(1)
    Enemy()
    EquipMostDamagingMelee()
    Attack("CSIren")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSThief4")  // 
    Wait(2)
    Enemy()
    EquipMostDamagingMelee()
    Attack("CSIren")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("CSGayl")  // 
    Wait(3)
    MoveToPoint([785.1034])
    DestroySelf()
END

