IF
  See(NearestEnemyOf(Myself))
  Global("DaoStoneSkin","LOCALS",0)
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_IMPROVED_HASTE)
    SetGlobal("DaoStoneSkin","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("skins","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(Myself,WIZARD_STONE_SKIN)
    SetGlobal("skins","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("stone","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(NearestEnemyOf(Myself),WIZARD_FLESH_TO_STONE)
    SetGlobal("stone","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("invis","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(Myself,WIZARD_INVISIBILITY)
    SetGlobal("invis","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

