IF
  Global("TalkedDegardan","GLOBAL",3)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  OR(2)
    Allegiance(Myself,NEUTRAL)
    Allegiance(Myself,GOODBUTBLUE)
THEN
  RESPONSE #100
    Enemy()
END

IF
  !See("Edwin")  // Edwin
  InParty("Edwin")  // Edwin
THEN
  RESPONSE #100
    MoveToObject("Edwin")
END

IF
  Allegiance("Edwin",ENEMY)  // Edwin
  !Range("Edwin",20)  // Edwin
THEN
  RESPONSE #100
    MoveToObjectFollow("Edwin")
END

IF
  OR(2)
    Global("TalkedDegardan","GLOBAL",0)
    Global("TalkedDegardan","GLOBAL",1)
  See("Edwin")  // Edwin
  InParty("Edwin")  // Edwin
  Range([PC],25)
  !Allegiance("Edwin",ENEMY)  // Edwin
  !Allegiance(Myself,ENEMY)
  CombatCounter(0)
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
END

IF
  OR(2)
    Global("TalkedDegardan","GLOBAL",0)
    Global("TalkedDegardan","GLOBAL",1)
  !Global("TurnedInEdwin","GLOBAL",1)
  !InParty("Edwin")  // Edwin
  !Allegiance("Edwin",ENEMY)  // Edwin
  !Allegiance(Myself,ENEMY)
  CombatCounter(0)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Global("TurnedInEdwin","GLOBAL",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,GOODBUTBLUE)
END

IF
  Global("TurnedInEdwin","GLOBAL",1)
  Global("DegardanRewards","GLOBAL",0)
  !Allegiance(Myself,ENEMY)
  Dead("Edwin")  // Edwin
  See([PC])
  !Dead("PC])")  // PC])
  !StateCheck([PC],STATE_SLEEPING)
  CombatCounter(0)
THEN
  RESPONSE #100
    SetGlobal("DegardanRewards","GLOBAL",1)
    StartDialogNoSet([PC])
END

