IF
  See([ANYONE])
  Global("hostile","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("hostile","LOCALS",1)
    Enemy()
END

IF
  See([ANYONE])
  StateCheck(LastSeenBy,STATE_HELPLESS)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy)
    AttackOneRound(LastSeenBy)
END

IF
  OR(2)
    See([0.0.0.CLERIC_ALL])
    See([0.0.0.MAGE_ALL])
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy,WIZARD_DISPEL_MAGIC)
    SetGlobal("Prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",1)
THEN
  RESPONSE #100
    ForceSpell(NearestEnemyOf(Myself),WIZARD_POWER_WORD_STUN)
    SetGlobal("Prep","LOCALS",2)
END

IF
  See([ANYONE])
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #70
    AttackReevaluate([ANYONE],30)
  RESPONSE #30
    ForceSpell(NearestEnemyOf(Myself),WIZARD_POWER_WORD_STUN)
END

