IF
  GlobalLT("DemonWheel","AR0602",2)
  See(NearestEnemyOf(Myself))
  Delay(7)
THEN
  RESPONSE #100
    PlaySound("TANAR01")
  RESPONSE #100
    PlaySound("TANAR02")
  RESPONSE #100
    PlaySound("TANAR03")
  RESPONSE #100
    PlaySound("TANAR04")
END

IF
  Global("DemonWheel","AR0602",2)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    PlaySound("EFF_P13")
    PlaySound("OGREM01")
    ChangeAnimation("IDEMON02")
END

