IF
  See([ANYONE])
  Global("PITFEAR","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),DEMON_FEAR)
    SetGlobal("PITFEAR","LOCALS",1)
END

IF
  OR(2)
    See([GOODCUTOFF.0.0.CLERIC_ALL])
    See([GOODCUTOFF.0.0.MAGE_ALL])
  Global("prep","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
    SetGlobal("prep","LOCALS",1)
END

IF
  See([GOODCUTOFF])
THEN
  RESPONSE #15
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)
    AttackOneRound(LastSeenBy(Myself))
  RESPONSE #25
    ReallyForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)
    AttackOneRound(LastSeenBy(Myself))
  RESPONSE #60
    AttackOneRound(LastSeenBy(Myself))
    AttackOneRound(LastSeenBy(Myself))
END

IF
  OR(2)
    See([0.0.0.CLERIC_ALL])
    See([0.0.0.MAGE_ALL])
  Global("prep","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
    SetGlobal("prep","LOCALS",1)
END

IF
  See([ANYONE])
  Global("DeathKnightFireball","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)
    SetGlobal("DeathKnightFireball","LOCALS",1)
END

IF
  See([ANYONE])
THEN
  RESPONSE #10
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)
  RESPONSE #20
    ReallyForceSpell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)
  RESPONSE #70
    AttackReevaluate(LastSeenBy(Myself),30)
END

