IF
  See(NearestEnemyOf(Myself))
  Global("hasted","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("hasted","LOCALS",1)
    DisplayString(Myself,46150)  // ~quaffs a potion~
    ReallyForceSpell(Myself,WIZARD_HASTE)
END

IF
  HasWeaponEquiped(Myself)
  OR(4)
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
THEN
  RESPONSE #100
    Shout(152)
    AttackReevaluate(LastSeenBy(Myself),15)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),15)
END

