IF
  HPPercentLT(Myself,50)
THEN
  RESPONSE #25
    ChangeAnimation("DOPKIE")
  RESPONSE #75
    Continue()
END

IF
  See([0.0.DOPPLEGANGER.FIGHTER])
  HPPercentLT([0.0.DOPPLEGANGER.FIGHTER],50)
THEN
  RESPONSE #25
    ChangeAnimation("DOPKIE")
  RESPONSE #75
    Continue()
END

IF
  See([0.0.DOPPLEGANGER.BARD])
  HPPercentLT([0.0.DOPPLEGANGER.BARD],50)
THEN
  RESPONSE #25
    ChangeAnimation("DOPKIE")
  RESPONSE #75
    Continue()
END

IF
  See([0.0.DOPPLEGANGER.CLERIC])
  HPPercentLT([0.0.DOPPLEGANGER.CLERIC],70)
THEN
  RESPONSE #25
    ChangeAnimation("DOPKIE")
  RESPONSE #75
    Continue()
END

IF
  See([0.0.DOPPLEGANGER.DOPPLEGANGER_GREATER])
  HPPercentLT([0.0.DOPPLEGANGER.DOPPLEGANGER_GREATER],750)
THEN
  RESPONSE #25
    ChangeAnimation("DOPKIE")
  RESPONSE #75
    Continue()
END

IF
  See([0.0.DOPPLEGANGER.MAGE])
  HPPercentLT([0.0.DOPPLEGANGER.MAGE],50)
THEN
  RESPONSE #25
    ChangeAnimation("DOPKIE")
  RESPONSE #75
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),4)
THEN
  RESPONSE #50
    ChangeAnimation("DOPDUR")
  RESPONSE #50
    RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
  Delay(20)
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),4)
  Range(NearestEnemyOf(Myself),8)
THEN
  RESPONSE #100
    ChangeAnimation("DOPFUE")
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),8)
  HaveSpell(WIZARD_SHADOW_DOOR)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHADOW_DOOR)
END

IF
  See(NearestEnemyOf(Myself))
  See([PC.0.0.MAGE])
  !Range(NearestEnemyOf(Myself),8)
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell([PC.0.0.MAGE],WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
  See([PC])
  !Range(NearestEnemyOf(Myself),8)
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell([PC],WIZARD_LIGHTNING_BOLT)
END

IF
  See([PC])
  !Range([PC],8)
  HaveSpell(WIZARD_DISPEL_MAGIC)
THEN
  RESPONSE #100
    Spell([PC],WIZARD_DISPEL_MAGIC)
END

IF
  See([PC])
  !Range([PC],8)
  HaveSpell(WIZARD_CONFUSION)
THEN
  RESPONSE #100
    Spell([PC],WIZARD_CONFUSION)
END

IF
  See([PC])
  !Range([PC],8)
  HaveSpell(WIZARD_DIRE_CHARM)
THEN
  RESPONSE #100
    Spell([PC],WIZARD_DIRE_CHARM)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),8)
  HaveSpell(WIZARD_DETECT_INVISIBILITY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)
END

IF
  See(NearestEnemyOf(Myself))
  See("Dopdur")  // Dopdur
  !Range(NearestEnemyOf(Myself),8)
  HaveSpell(WIZARD_HASTE)
THEN
  RESPONSE #100
    Spell("Dopdur",WIZARD_HASTE)
END

IF
  See([PC])
  !Range([PC],8)
  HaveSpell(WIZARD_HORROR)
THEN
  RESPONSE #100
    Spell([PC],WIZARD_HORROR)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),8)
  HaveSpell(WIZARD_RESIST_FEAR)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_RESIST_FEAR)
END

IF
  See([PC])
  !Range([PC],8)
  HaveSpell(WIZARD_SLEEP)
THEN
  RESPONSE #100
    Spell([PC],WIZARD_SLEEP)
END

IF
  See(NearestEnemyOf(Myself))
  See("Dopkie")  // Dopkie
  !Range(NearestEnemyOf(Myself),8)
  HaveSpell(WIZARD_LUCK)
THEN
  RESPONSE #100
    Spell("Dopkie",WIZARD_LUCK)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),8)
THEN
  RESPONSE #100
    ChangeAnimation("DOPFUE")
END

