IF
  HPLT(Myself,10)
THEN
  RESPONSE #100
    ChangeAnimationNoEffect("DRSHNL02")
END

IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)
    ForceSpell(Myself,CLERIC_DEATH_WARD)
    ForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)
    SetGlobal("Prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("ratSpawn","LOCALS",0)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,8340)  // ~The troll shakes, twitches, and convulses as a dozen sickly rats tear their way from her body and scramble towards you, fangs bared in angry grimaces.~
    ForceSpell(Myself,TROLL_RAT_SPAWN)
    SetGlobal("ratSpawn","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_POISON)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_POISON)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_UNHOLY_BLIGHT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_UNHOLY_BLIGHT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_CAUSE_CRITICAL_WOUNDS)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CAUSE_CRITICAL_WOUNDS)
END

IF
  See(NearestEnemyOf(Myself))
  Global("fight1","LOCALS",0)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
    AttackOneRound(LastSeenBy(Myself))
    AttackOneRound(LastSeenBy(Myself))
    SetGlobal("fight1","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  TookDamage()
  HaveSpell(CLERIC_IRONSKIN)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_IRONSKIN)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_HOLD_PERSON)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)
END

IF
  See(ThirdNearestEnemyOf(Myself))
  HaveSpell(CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),30)
END

