IF
  HitBy([ANYONE],CRUSHING)
  !Exists("DOPDUR1")  // DOPDUR1
  Global("FueDummy","GLOBAL",0)
THEN
  RESPONSE #100
    ClearActions(LastAttackerOf(Myself))
    SetGlobal("FueDummy","GLOBAL",1)
    Unlock("DOOR01")
    Unlock("DOOR04")
    Unlock("DOOR05")
    CloseDoor("DOOR01")
    OpenDoor("DOOR04")
    OpenDoor("DOOR05")
    Lock("DOOR01")
    Lock("DOOR04")
    Lock("DOOR05")
    CreateCreature("DOPDUR1",[929.1127],0)  // DOPDUR1
    PlaySound("AMB_D04A")
END

