IF
  Global("ReadBook1","GLOBAL",1)
  Global("ReadBook2","GLOBAL",1)
  Global("ReadBook3","GLOBAL",1)
  Global("ReadBook4","GLOBAL",1)
  Global("Honor","GLOBAL",0)
THEN
  RESPONSE #100
    ApplySpell(Myself,DURLAG_SWORD)
    SetGlobal("Honor","GLOBAL",1)
END

IF
  Global("Honor","GLOBAL",1)
  Global("Honor2","GLOBAL",0)
  See([PC])
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
    SetGlobal("Honor2","GLOBAL",1)
END

