IF
  Global("BeholderGolem","LOCALS",0)
  See("obsgol01")  // ~Guardian Golem~
  Detect([PC])
THEN
  RESPONSE #100
    FaceObject("obsgol01")
    ReallyForceSpell("obsgol01",BEHOLDER_DISINTEGRATE)
    SetGlobal("BeholderGolem","LOCALS",1)
    Wait(1)
END

IF
  Global("BeholderGolem","LOCALS",1)
  See("obsgol01")  // ~Guardian Golem~
  Detect([PC])
THEN
  RESPONSE #100
    FaceObject("obsgol01")
    ReallyForceSpell("obsgol01",BEHOLDER_ANTIMAGIC_RAY)
    SetGlobal("BeholderGolem","LOCALS",2)
    Wait(2)
END

IF
  Global("BeholderGolem","LOCALS",2)
  See("obsgol01")  // ~Guardian Golem~
  Detect([PC])
THEN
  RESPONSE #100
    FaceObject("obsgol01")
    ReallyForceSpell("obsgol01",BEHOLDER_DEATH_RAY)
    SetGlobal("BeholderGolem","LOCALS",3)
END

IF
  Global("BeholderGolem","LOCALS",3)
  See("obsgol01")  // ~Guardian Golem~
  Detect([PC])
THEN
  RESPONSE #100
    Attack("obsgol01")
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
THEN
  RESPONSE #100
    FaceObject(LastSeenBy(Myself))
    ReallyForceSpell(LastSeenBy(Myself),BEHOLDER_DISINTEGRATE)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  HPGT(Myself,65)
THEN
  RESPONSE #100
    FaceObject([PC])
    ReallyForceSpell([PC],BEHOLDER_CHARM_PERSON)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  HPGT(Myself,55)
THEN
  RESPONSE #100
    FaceObject(SecondNearest([PC]))
    ReallyForceSpell(SecondNearest([PC]),BEHOLDER_FEAR)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See(LeastDamagedOf(Myself))
  HPGT(Myself,45)
THEN
  RESPONSE #100
    FaceObject(LeastDamagedOf(Myself))
    ReallyForceSpell(LeastDamagedOf(Myself),BEHOLDER_DISINTEGRATE)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  !See(LeastDamagedOf(Myself))
  HPGT(Myself,45)
THEN
  RESPONSE #100
    FaceObject([PC])
    ReallyForceSpell([PC],BEHOLDER_DISINTEGRATE)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  HPGT(Myself,25)
THEN
  RESPONSE #100
    FaceObject(ThirdNearest([PC]))
    ReallyForceSpell(ThirdNearest([PC]),BEHOLDER_FLESH_TO_STONE)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  See([PC.0.0.MAGE])
THEN
  RESPONSE #100
    FaceObject(LastSeenBy(Myself))
    ReallyForceSpell(LastSeenBy(Myself),BEHOLDER_ANTIMAGIC_RAY)
    SetGlobal("BeholderBehavior","LOCALS",1)
    Wait(2)
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([PC])
  !See([PC.0.0.MAGE])
THEN
  RESPONSE #100
    FaceObject([PC])
    ReallyForceSpell([PC],BEHOLDER_ANTIMAGIC_RAY)
    SetGlobal("BeholderBehavior","LOCALS",1)
    Wait(2)
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
THEN
  RESPONSE #100
    FaceObject(LastSeenBy(Myself))
    ReallyForceSpell(LastSeenBy(Myself),BEHOLDER_DISINTEGRATE)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  HPGT(Myself,15)
THEN
  RESPONSE #100
    FaceObject([PC])
    ReallyForceSpell([PC],BEHOLDER_DOMINATION)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  HPGT(Myself,35)
THEN
  RESPONSE #100
    FaceObject(SecondNearest([PC]))
    ReallyForceSpell(SecondNearest([PC]),BEHOLDER_SLOW)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  HPGT(Myself,5)
THEN
  RESPONSE #100
    FaceObject(ThirdNearest([PC]))
    ReallyForceSpell(ThirdNearest([PC]),BEHOLDER_CAUSE_SERIOUS_WOUNDS)
    Wait(1)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See(LeastDamagedOf(Myself))
THEN
  RESPONSE #100
    FaceObject(LeastDamagedOf(Myself))
    ReallyForceSpell(LeastDamagedOf(Myself),BEHOLDER_DEATH_RAY)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  !See(LeastDamagedOf(Myself))
THEN
  RESPONSE #100
    FaceObject([PC])
    ReallyForceSpell([PC],BEHOLDER_DEATH_RAY)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  See([PC.0.0.MAGE])
THEN
  RESPONSE #100
    FaceObject(LastSeenBy(Myself))
    ReallyForceSpell(LastSeenBy(Myself),BEHOLDER_ANTIMAGIC_RAY)
    SetGlobal("BeholderBehavior","LOCALS",0)
    Wait(2)
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([PC])
  !See([PC.0.0.MAGE])
THEN
  RESPONSE #100
    FaceObject([PC])
    ReallyForceSpell([PC],BEHOLDER_ANTIMAGIC_RAY)
    SetGlobal("BeholderBehavior","LOCALS",0)
    Wait(2)
END

