IF
  Detect([PC])
  Global("Display","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Display","LOCALS",1)
    DisplayStringHead(Myself,72786)  // ~Who calls Imix, Prince of Fire!~
END

IF
  See(NearestEnemyOf(Myself))
  Global("CastFlamestrike","LOCALS",0)
  !GlobalTimerNotExpired("FlamestrikeTimer","LOCALS")
THEN
  RESPONSE #100
    ForceSpellRES("spimix01",NearestEnemyOf(Myself))  // ~Flame Strike~
    DisplayStringHead(Myself,72787)  // ~Feel the wrath of Imix!~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",SecondNearestEnemyOf(Myself))  // ~Flame Strike~
    DisplayStringHead(Myself,72787)  // ~Feel the wrath of Imix!~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",ThirdNearestEnemyOf(Myself))  // ~Flame Strike~
    DisplayStringHead(Myself,72787)  // ~Feel the wrath of Imix!~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",FourthNearestEnemyOf(Myself))  // ~Flame Strike~
    DisplayStringHead(Myself,72787)  // ~Feel the wrath of Imix!~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",FifthNearestEnemyOf(Myself))  // ~Flame Strike~
    DisplayStringHead(Myself,72787)  // ~Feel the wrath of Imix!~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",SixthNearestEnemyOf(Myself))  // ~Flame Strike~
    DisplayStringHead(Myself,72787)  // ~Feel the wrath of Imix!~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("CastFlamestrike","LOCALS",1)
  !GlobalTimerNotExpired("FlamestrikeTimer","LOCALS")
THEN
  RESPONSE #100
    ForceSpellRES("spimix01",NearestEnemyOf(Myself))  // ~Flame Strike~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",SecondNearestEnemyOf(Myself))  // ~Flame Strike~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",ThirdNearestEnemyOf(Myself))  // ~Flame Strike~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",FourthNearestEnemyOf(Myself))  // ~Flame Strike~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",FifthNearestEnemyOf(Myself))  // ~Flame Strike~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
  RESPONSE #100
    ForceSpellRES("spimix01",SixthNearestEnemyOf(Myself))  // ~Flame Strike~
    IncrementGlobal("CastFlamestrike","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobal("CastFlamestrike","LOCALS",0)
    SetGlobalTimer("FlamestrikeTimer","LOCALS",15)
    AttackReevaluate(NearestEnemyOf(Myself),120)
END

