IF
  GlobalTimerExpired("StopAttaking","GLOBAL")
  Global("AttackedChickens","GLOBAL",1)
  !Dead("gemfar01")  // ~Enna Hendrick~
  !HPPercentLT("gemfar01",100)  // ~Enna Hendrick~
THEN
  RESPONSE #100
    SetGlobal("AttackedChickens","GLOBAL",2)
    StartDialogNoSet([PC])
END

IF
  OR(2)
    Dead("gemfar01")  // ~Enna Hendrick~
    HPPercentLT("gemfar01",100)  // ~Enna Hendrick~
  GlobalGT("AttackedChickens","GLOBAL",0)
THEN
  RESPONSE #100
    ChangeAIScript("SHOUT",RACE)
    Shout(99)
    Enemy()
END

