IF
  Die()
THEN
  RESPONSE #100
    CreateVisualEffectObject("ICRMPARI",Myself)
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),7)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
  See(NearestEnemyOf(Myself))
  Delay(6)
THEN
  RESPONSE #100
    ForceSpell(Myself,WIZARD_MONSTER_SUMMONING_1)
  RESPONSE #100
    ForceSpell(Myself,WIZARD_MONSTER_SUMMONING_2)
  RESPONSE #100
    ForceSpell(Myself,WIZARD_MONSTER_SUMMONING_3)
  RESPONSE #100
    ForceSpell(Myself,CLERIC_ANIMAL_SUMMONING_1)
  RESPONSE #100
    ForceSpell(Myself,CLERIC_ANIMAL_SUMMONING_2)
END

