IF
  Die()
THEN
  RESPONSE #100
    CreateVisualEffectObject("ICRMPARI",Myself)
    DestroySelf()
END

IF
  See([PC])
  Range([PC],5)
THEN
  RESPONSE #50
    CreateVisualEffectObject("spnwchrm",Myself)
    RunAwayFromNoInterrupt([PC],45)
    SetGlobalTimer("RunFromPlayer","LOCALS",5)
END

IF
  See([PC])
  !Range([PC],6)
  !GlobalTimerNotExpired("RunFromPlayer","LOCALS")
THEN
  RESPONSE #100
    MoveToObject([PC])
END

