IF
  Clicked([ANYONE])
  Range(LastTrigger,16)
  Global("Slayer10","GLOBAL",2)
THEN
  RESPONSE #100
    ActionOverride(Player1,ReallyForceSpell(Myself,SLAYER_IMMUNE_TO_DAMAGE))
    DisplayString(Myself,6479)  // ~The god child has come.~
    StartCutSceneMode()
    StartCutScene("Cut72a")
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,16)
  !Global("Slayer10","GLOBAL",2)
THEN
  RESPONSE #100
    DisplayString(Myself,5691)  // ~The stone face does not respond but within your head a voice whispers: 'In mortal form you cannot speak. Reveal the god, the death and hate within you. So shall the test begin...'~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,16)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

