IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HOLD_PERSON)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_HOLD_PERSON)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HASTE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_HASTE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_VAMPIRIC_TOUCH)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_VAMPIRIC_TOUCH)
END

