IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HASTE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_HASTE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_CONJURE_LESSER_FIRE_ELEMENTAL)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_CONJURE_LESSER_FIRE_ELEMENTAL)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_POWER_WORD_SLEEP)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_POWER_WORD_SLEEP)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HOLD_PERSON)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_HOLD_PERSON)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FIRE_SHIELD_RED)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_FIRE_SHIELD_RED)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_POLYMORPH_OTHER)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_POLYMORPH_OTHER)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

