IF
  NumberOfTimesTalkedTo(0)
  Detect(Player1)
  Global("JumBandits","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("JumBandits","GLOBAL",1)
    Wait(3)
    StartDialogNoSet(Player1)
END

IF
  Detect(Player1)
  !See([ENEMY])
  Range(Player1,10)
  CombatCounter(0)
  Global("FirbanFight","GLOBAL",1)
  Global("JumGivesChallenge","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("JumGivesChallenge","LOCALS",1)
    StartDialogNoSet(Player1)
END

IF
  Global("FirbanFight","GLOBAL",1)
  !See([ENEMY])
  CombatCounter(0)
  OR(2)
    !See(Player1)
    !Range(Player1,10)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

