IF
  Global("GasChamber","AR0202",1)
  Detect([PC])
  Range(LastSeenBy,20)
THEN
  RESPONSE #100
    ForceSpellPoint([2943.1919],WIZARD_CLOUDKILL)
    Wait(50)
    SetGlobal("GasChamber","AR0202",2)
END

IF
  Global("GasChamber","AR0202",4)
  Detect([PC])
  Range(LastSeenBy,20)
THEN
  RESPONSE #100
    ForceSpellPoint([2943.1919],WIZARD_CLOUDKILL)
    Wait(50)
    SetGlobal("GasChamber","AR0202",2)
END

