IF
  HPPercentLT(Myself,40)
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
END

IF
  Allegiance(Myself,ENEMY)
  See([PC.0.0.MAGE])
  HaveSpell(CLERIC_DISPEL_MAGIC)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_HOLD_PERSON)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_COMMAND)
THEN
  RESPONSE #50
    Spell(NearestEnemyOf(Myself),CLERIC_COMMAND)
  RESPONSE #50
    Spell(SecondNearestEnemyOf(Myself),CLERIC_COMMAND)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_ANIMATE_DEAD)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_ANIMATE_DEAD)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

