IF
  Global("prepspells","LOCALS",0)
  See(NearestMyGroupOfType)
  !StateCheck(LastSeenBy(Myself),STATE_HASTED)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_HASTE)
    SetGlobal("prepspells","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Delay(6)
THEN
  RESPONSE #33
    ForceSpell(LastSeenBy(Myself),PSIONIC_MIND_BLAST)
  RESPONSE #77
    Continue()
END

