IF
  See([PC])
  NumberOfTimesTalkedTo(0)
THEN
  RESPONSE #100
    Dialog([PC])
END

IF
  HPLT(Myself,5)
  Global("GnollFightOver","GLOBAL",0)
THEN
  RESPONSE #100
    SmallWait(1)
    ActionOverride(StrongestOf,SmallWait(1))
    Dialog([PC])
    SetGlobal("GnollFightOver","GLOBAL",2)
    EscapeArea()
END

IF
  HPLT(StrongestOf,5)
  Global("GnollFightOver","GLOBAL",0)
THEN
  RESPONSE #100
    SmallWait(1)
    ActionOverride(StrongestOf,SmallWait(1))
    Dialog([PC])
END

