IF
  NumberOfTimesTalkedTo(0)
  !Allegiance(Myself,ENEMY)
  CombatCounter(0)
  Detect(Player1)
THEN
  RESPONSE #100
    DialogueInterrupt(TRUE)
    StartDialogNoSet(Player1)
END

IF
  Global("PostCombatReinit","GLOBAL",1)
  Dead("GorDeck5")  // ~Assassin ~
  Dead("GorDeck6")  // ~Assassin ~
  Dead("GorDeck7")  // ~Assassin ~
  Dead("GorDeck8")  // ~Assassin ~
  Dead("GorDeck9")  // ~Assassin ~
  Dead("GorDeckA")  // ~Assassin ~
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    SetGlobal("PostCombatReinit","GLOBAL",0)
    DialogueInterrupt(TRUE)
    StartDialogNoSet(LastTalkedToBy)
END

IF
  Global("PostCombatReinit","GLOBAL",2)
  Dead("GorDeck1")  // ~Fighter~
  Dead("GorDeck2")  // ~Fighter~
  Dead("GorDeck3")  // ~Fighter~
  Dead("GorDeck4")  // ~Fighter~
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    SetGlobal("Prepare","LOCALS",0)
    SetGlobal("PostCombatReinit","GLOBAL",4)
    ReallyForceSpell(Myself,CLERIC_HEAL)
END

IF
  Global("PostCombatReinit","GLOBAL",3)
  Dead("GorDeckB")  // ~Adamantite Golem~
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    SetGlobal("Prepare","LOCALS",0)
    SetGlobal("PostCombatReinit","GLOBAL",4)
    ReallyForceSpell(Myself,CLERIC_HEAL)
END

IF
  Global("PostCombatReinit","GLOBAL",4)
  !HPPercentLT(Myself,100)
THEN
  RESPONSE #100
    SetGlobal("PostCombatReinit","GLOBAL",0)
    DialogueInterrupt(TRUE)
    StartDialogNoSet(LastTalkedToBy)
END

