IF
  Dead("GorCamb")  // ~Aesgareth~
  OR(3)
    !See([0.WEAPON])
    Global("PostCombatReinit","GLOBAL",3)
    Global("PostCombatReinit","GLOBAL",2)
  Global("AesTiefAttack","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("AesTiefAttack","GLOBAL",1)
    DisplayStringHead(Myself,70984)  // ~The cambion's dead!  Let's get the way out of this bloody place from the berks, come on!~
    Shout(151)
    Enemy()
END

IF
  OR(3)
    See([0.WEAPON])
    Global("PostCombatReinit","GLOBAL",1)
    Global("PostCombatReinit","GLOBAL",2)
  Global("shutup","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("shutup","LOCALS",1)
    DialogueInterrupt(FALSE)
END

IF
  Global("PostCombatReinit","GLOBAL",4)
  Global("shutup","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("shutup","LOCALS",0)
    DialogueInterrupt(TRUE)
END

IF
  OR(2)
    See([0.WEAPON])
    See(NearestEnemyOf(Myself))
  Global("Prepare","LOCALS",0)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_IMPROVED_MANTLE)
    ApplySpell(Myself,WIZARD_STONE_SKIN)
    SetGlobal("Prepare","LOCALS",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Global("SpellTrigger","LOCALS",0)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    DisplayString(Myself,43046)  // ~Spell Trigger - Mislead~
    ReallyForceSpell(Myself,WIZARD_MISLEAD)
    DisplayString(Myself,43047)  // ~Spell Trigger - Fire Shield Red~
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
    SetGlobal("SpellTrigger","LOCALS",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  StateCheck(Myself,STATE_SILENCED)
  HaveSpell(WIZARD_VOCALIZE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_VOCALIZE)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  Detect([PC])
  !See(LastSeenBy(Myself))
  HaveSpell(WIZARD_TRUE_SIGHT)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_TRUE_SIGHT)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  Detect([PC])
  !See(LastSeenBy(Myself))
  !HaveSpell(WIZARD_TRUE_SIGHT)
  Delay(10)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Global("Prepare","LOCALS",1)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TURNING)
    SetGlobal("Prepare","LOCALS",2)
    Continue()
END

IF
  !HasBounceEffects(Myself)
  !HasImmunityEffects(Myself)
  HaveSpell(WIZARD_SPELL_TURNING)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TURNING)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  TookDamage()
  Global("Prepare2","LOCALS",0)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    DisplayString(Myself,43050)  // ~Chain Contingency - Improved Mantle~
    ApplySpell(Myself,WIZARD_IMPROVED_MANTLE)
    DisplayString(Myself,3302)  // ~Chain Contingency - Spell Turning~
    ApplySpell(Myself,WIZARD_SPELL_TURNING)
    DisplayString(Myself,40240)  // ~Chain Contingency - Mislead~
    ApplySpell(Myself,WIZARD_MISLEAD)
    SetGlobal("Prepare2","LOCALS",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  TookDamage()
  Global("Prepare2","LOCALS",1)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    DisplayString(Myself,40252)  // ~Contingency - Protection from Magical Weapons~
    ApplySpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    SetGlobal("Prepare2","LOCALS",2)
    Continue()
END

IF
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
  Allegiance(LastSeenBy(Myself),ENEMY)
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  Global("Summon","LOCALS",0)
THEN
  RESPONSE #100
    FaceObject(LastSeenBy(Myself))
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetGlobal("Summon","LOCALS",1)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_TIME_STOP)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_TIME_STOP)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_NPC_SYMBOL_STUN)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_NPC_SYMBOL_STUN)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SUN_FIRE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_SUN_FIRE)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FINGER_OF_DEATH)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FINGER_OF_DEATH)
    Continue()
END

IF
  OR(2)
    See([0.WEAPON])
    See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_PRISMATIC_SPRAY)
  !CheckStatGT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)
    Continue()
END

IF
  OR(2)
    See([0.WEAPON])
    See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MAZE)
  !CheckStatGT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_DOMINATION)
  !CheckStatGT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_DOMINATION)
    Continue()
END

IF
  OR(2)
    See([0.WEAPON])
    See(NearestEnemyOf(Myself))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),75,RESISTMAGIC)
THEN
  RESPONSE #50
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    Continue()
  RESPONSE #20
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
    Continue()
  RESPONSE #30
    SpellNoDec(LastSeenBy(Myself),WIZARD_FIREBALL)
    Continue()
  RESPONSE #30
    SpellNoDec(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
    Continue()
  RESPONSE #20
    SpellNoDec(LastSeenBy(Myself),WIZARD_DIRE_CHARM)
    Continue()
  RESPONSE #30
    SpellNoDec(LastSeenBy(Myself),WIZARD_CONFUSION)
    Continue()
END

IF
  OR(2)
    See([0.WEAPON])
    See(NearestEnemyOf(Myself))
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),15)
    Continue()
END

IF
  Dead("GorDeckB")  // ~Adamantite Golem~
  Allegiance(Myself,NEUTRAL)
  Global("reset","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("reset","LOCALS",1)
    SetGlobal("Prepare","LOCALS",0)
END

IF
  Dead("GorDeck1")  // ~Fighter~
  Dead("GorDeck2")  // ~Fighter~
  Dead("GorDeck3")  // ~Fighter~
  Dead("GorDeck4")  // ~Fighter~
  Allegiance(Myself,NEUTRAL)
  Global("reset2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("reset2","LOCALS",1)
    SetGlobal("Prepare","LOCALS",0)
END

