IF
  HitBy([ANYONE],ELECTRICITY)
  Global("NoFusion","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("NoFusion","LOCALS",1)
END

IF
  Die()
  Global("NoFusion","LOCALS",0)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,71108)  // ~Rather than dying, the creature splits into two.~
    CreateCreatureObjectEffect("GORJELF2","TRGOOYAA",Myself)
    CreateCreatureObjectEffect("GORJELF2","TRGOOYAA",Myself)
END

