IF
  Global("aura","LOCALS",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobal("aura","LOCALS",1)
    ReallyForceSpell(LastSeenBy(Myself),LICH_FEAR)
END

IF
  Delay(24)
  See(NearestEnemyOf(Myself))
  Global("aura","LOCALS",1)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),LICH_FEAR)
END

IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",0)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_STONE_SKIN)
    ApplySpell(Myself,WIZARD_IMPROVED_MANTLE)
    ApplySpell(Myself,WIZARD_MIRROR_IMAGE)
    SetGlobal("Prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  !Dead("yself)")  // yself)
  CheckStatLT(Myself,1,STONESKINS)
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_STONE_SKIN)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Global("SpellTrigger","LOCALS",0)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    DisplayString(Myself,44901)  // ~~
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)
    DisplayString(Myself,40245)  // ~Spell Trigger - Globe of Invulnerability~
    ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
    SetGlobal("SpellTrigger","LOCALS",1)
END

IF
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
  Global("summon","LOCALS",0)
THEN
  RESPONSE #100
    FaceObject(LastSeenBy(Myself))
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetGlobal("summon","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_TIME_STOP)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_TIME_STOP)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_METEOR_SWARM)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_METEOR_SWARM)
END

IF
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),20)
  HaveSpell(WIZARD_IMPRISONMENT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_IMPRISONMENT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  See(NearestEnemyOf(Myself))
  StateCheck(Myself,STATE_SILENCED)
  HaveSpell(WIZARD_VOCALIZE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_VOCALIZE)
END

IF
  Allegiance(Myself,ENEMY)
  Detect([PC])
  !See(LastSeenBy(Myself))
  HaveSpell(WIZARD_TRUE_SIGHT)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  Detect([PC])
  !See(LastSeenBy(Myself))
  !HaveSpell(WIZARD_TRUE_SIGHT)
  Delay(10)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)
END

IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",1)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TURNING)
    SetGlobal("Prep","LOCALS",2)
END

IF
  !HasBounceEffects(Myself)
  !HasImmunityEffects(Myself)
  HaveSpell(WIZARD_SPELL_TURNING)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TURNING)
END

IF
  See(NearestEnemyOf(Myself))
  TookDamage()
  Global("Prep2","LOCALS",0)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    DisplayString(Myself,43050)  // ~Chain Contingency - Improved Mantle~
    ApplySpell(Myself,WIZARD_IMPROVED_MANTLE)
    DisplayString(Myself,3302)  // ~Chain Contingency - Spell Turning~
    ApplySpell(Myself,WIZARD_SPELL_TURNING)
    DisplayString(Myself,40240)  // ~Chain Contingency - Mislead~
    ApplySpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
    SetGlobal("Prep2","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  TookDamage()
  Global("Prep2","LOCALS",1)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    DisplayString(Myself,40252)  // ~Contingency - Protection from Magical Weapons~
    ApplySpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    SetGlobal("Prep2","LOCALS",2)
END

IF
  Allegiance(Myself,ENEMY)
  !HasBounceEffects(Myself)
  !HasImmunityEffects(Myself)
  HaveSpell(WIZARD_SPELL_TURNING)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TURNING)
END

IF
  See(NearestEnemyOf(Myself))
  Global("SpellTrigger","LOCALS",0)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    DisplayString(Myself,39969)  // ~Spell Sequencer - Fired~
    DisplayString(Myself,44899)  // ~Spell Sequencer - Confusion~
    ReallyForceSpell(SecondNearestEnemyOf(Myself),WIZARD_CONFUSION)
    DisplayString(Myself,362)  // ~Spell Sequencer - Fireball~
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_FIREBALL)
    DisplayString(Myself,44871)  // ~Spell Sequencer - Protection From Evil~
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_EVIL)
    SetGlobal("SpellTrigger","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MAZE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MAZE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_NPC_SYMBOL_STUN)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_NPC_SYMBOL_STUN)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_NPC_SYMBOL_FEAR)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_NPC_SYMBOL_FEAR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_NPC_SYMBOL_DEATH)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_NPC_SYMBOL_DEATH)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SUN_FIRE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_SUN_FIRE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_WAIL_OF_THE_BANSHEE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_WAIL_OF_THE_BANSHEE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SHADOW_DOOR)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHADOW_DOOR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FINGER_OF_DEATH)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SUMMON_EFREET)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SUMMON_EFREET)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FLESH_TO_STONE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FLESH_TO_STONE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_DISINTEGRATE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_DISINTEGRATE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_DOMINATION)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_DOMINATION)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SLOW)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_SLOW)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FLAME_ARROW)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MELF_ACID_ARROW)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_POLYMORPH_OTHER)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_POLYMORPH_OTHER)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

