IF
  Die()
THEN
  RESPONSE #100
    Unlock("Mimic4")
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Shout(89)
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(MIMIC_WEB)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),MIMIC_WEB)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    ForceSpell(NearestEnemyOf(Myself),MIMIC_ACID)
END

