IF
  NumberOfTimesTalkedTo(0)
  Detect([PC])
THEN
  RESPONSE #100
    StartDialogNoSet(Player1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("Preparation","LOCALS",0)
THEN
  RESPONSE #100
    ApplySpell(Myself,CLERIC_REGENERATE)
    ApplySpell(Myself,CLERIC_DEATH_WARD)
    ApplySpell(Myself,NPC_BLADE_BARRIER)
    SetGlobal("Preparation","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  HitBy([ANYONE],CRUSHING)
  HaveSpell(CLERIC_IRONSKIN)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_IRONSKIN)
END

IF
  See(NearestEnemyOf(Myself))
  RandomNum(2,1)
  HaveSpell(CLERIC_CREEPING_DOOM)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_CREEPING_DOOM)
END

IF
  See(NearestEnemyOf(Myself))
  RandomNum(2,2)
  HaveSpell(CLERIC_FINGER_OF_DEATH)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_FINGER_OF_DEATH)
END

IF
  See(NearestEnemyOf(Myself))
  RandomNum(2,2)
  HaveSpell(CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_INSECT_PLAGUE)
END

IF
  See(NearestEnemyOf(Myself))
  RandomNum(2,1)
  HaveSpell(CLERIC_CONFUSION)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CONFUSION)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(LastSeenBy(Myself),4)
  HPPercentLT(Myself,20)
  HaveSpell(CLERIC_HEAL)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_HEAL)
END

IF
  See(NearestEnemyOf(Myself))
  RandomNum(2,1)
  HaveSpell(CLERIC_CONJURE_FIRE_ELEMENTAL)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_CONJURE_FIRE_ELEMENTAL)
END

IF
  See(NearestEnemyOf(Myself))
  RandomNum(2,2)
  HaveSpell(CLERIC_CONJURE_EARTH_ELEMENTAL)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_CONJURE_EARTH_ELEMENTAL)
END

IF
  See(NearestEnemyOf(Myself))
  RandomNum(2,1)
  HaveSpell(CLERIC_AERIAL_SERVANT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_AERIAL_SERVANT)
END

IF
  HaveSpell(CLERIC_SILENCE_15_FOOT)
  OR(2)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_FLAME_STRIKE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_FLAME_STRIKE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_HOLD_PERSON)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_CLOAK_OF_FEAR)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CLOAK_OF_FEAR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_PHYSICAL_MIRROR)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_PHYSICAL_MIRROR)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),7)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),7)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

