IF
  Die()
THEN
  RESPONSE #50
    ReallyForceSpellDead(Myself,SKULL_EXPLODE)
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("resetprep","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("resetprep","LOCALS",15)
    ApplySpell(Myself,WIZARD_FIRE_SHIELD_RED)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),10)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),15)
    Continue()
END

IF
  !AreaCheck("AR5201")
  See(NearestEnemyOf(Myself))
  !Range(LastSeenBy(Myself),10)
  Global("belch","LOCALS",0)
  RandomNum(4,1)
THEN
  RESPONSE #100
    SetGlobal("belch","LOCALS",1)
    SpellNoDec(NearestEnemyOf(Myself),WIZARD_INCENDIARY_CLOUD)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  !Range(LastSeenBy(Myself),10)
  !GlobalTimerNotExpired("renewflame","LOCALS")
THEN
  RESPONSE #15
    SetGlobalTimer("renewflame","LOCALS",4)
    SpellNoDec(NearestEnemyOf(Myself),WIZARD_FIREBALL)
    Continue()
  RESPONSE #40
    SetGlobalTimer("renewflame","LOCALS",4)
    SpellNoDec(NearestEnemyOf(Myself),FLAMING_SKULL_BOLT)
    Continue()
  RESPONSE #50
    SetGlobalTimer("renewflame","LOCALS",4)
    SpellNoDec(NearestEnemyOf(Myself),WIZARD_AGANNAZAR_SCORCHER)
    Continue()
  RESPONSE #100
    SetGlobalTimer("renewflame","LOCALS",4)
    SpellNoDec(NearestEnemyOf(Myself),WIZARD_BURNING_HANDS)
    Continue()
END

