IF
  Range([PC],10)
  Global("Spawn2","AR6400",0)
THEN
  RESPONSE #100
    SetGlobal("Spawn2","AR6400",1)
    SetGlobal("6400limit","AR6400",0)
    CreateCreature("YSSOLD13",[2019.882],0)  // ~Yaga-Shura Soldier~
    CreateCreature("YSSOLD13",[2000.880],0)  // ~Yaga-Shura Soldier~
    CreateCreature("YSSOLD12",[2151.907],0)  // ~Yaga-Shura Soldier~
    CreateCreature("YSSOLD13",[2344.793],0)  // ~Yaga-Shura Soldier~
    CreateCreature("YSSOLD13",[2350.790],0)  // ~Yaga-Shura Soldier~
    CreateCreature("YSSOLD12",[2450.333],0)  // ~Yaga-Shura Soldier~
    CreateCreature("YSSOLD15",[2261.360],0)  // ~Yaga-Shura Officer~
    CreateCreature("YSSOLD16",[2211.319],0)  // ~Cleric Of Talos~
    CreateCreature("YSSOLD15",[1795.521],0)  // ~Yaga-Shura Officer~
    CreateCreature("YSSOLD16",[1757.465],0)  // ~Cleric Of Talos~
    CreateCreature("YSSOLD13",[1689.428],0)  // ~Yaga-Shura Soldier~
    CreateCreature("YSSOLD10",[1619.498],12)  // ~Fire Giant~
    CreateCreature("YSSOLD10",[1626.505],12)  // ~Fire Giant~
END

