IF
  HPLT(Myself,2)
  Global("OKGoBoom","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("OKGoBoom","LOCALS",1)
    ReallyForceSpell(Myself,QUICK_INVISIBLE)
    ReallyForceSpell(Myself,SPORE_DEATH)
    CreateVisualEffectObject("SPFIREPI",Myself)
    Wait(5)
    DestroyItem("minhp1")  // <Invalid Strref -1>
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(Myself))
END

