IF
  See([PC])
  Allegiance(Myself,NEUTRAL)
  Global("point","LOCALS",0)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,60853)  // ~Come to the Adventurer's Mart!~
    StartTimer(101,5)
    SetGlobal("point","LOCALS",1)
END

IF
  See([PC])
  TimerExpired(101)
  Allegiance(Myself,NEUTRAL)
  Global("point","LOCALS",1)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,60854)  // ~We have all the equipment you need!~
    StartTimer(101,10)
    SetGlobal("point","LOCALS",2)
END

IF
  See([PC])
  TimerExpired(101)
  Allegiance(Myself,NEUTRAL)
  Global("point","LOCALS",2)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,60853)  // ~Come to the Adventurer's Mart!~
    StartTimer(101,5)
    SetGlobal("point","LOCALS",1)
END

