IF
  Global("HellSwap","GLOBAL",1)
  Range([PC],20)
  Global("Player1Fear","GLOBAL",1)
  Global("RoomFear","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("RoomFear","GLOBAL",1)
    SetGlobal("HellSwap","GLOBAL",0)
    ForceSpell(Myself,HELL_FEAR_GOOD)
    TriggerActivation("FearRoom",FALSE)
END

IF
  Global("HellSwap","GLOBAL",1)
  Range([PC],20)
  Global("Player1Fear","GLOBAL",2)
  Global("RoomFear","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("RoomFear","GLOBAL",2)
    SetGlobal("HellSwap","GLOBAL",0)
    ForceSpell(Myself,HELL_FEAR_EVIL)
    TriggerActivation("FearRoom",FALSE)
END

IF
  Global("RoomFear","GLOBAL",3)
THEN
  RESPONSE #100
    SetGlobal("RoomFear","GLOBAL",2)
    SetGlobal("HellSwap","GLOBAL",0)
    ForceSpell(Myself,HELL_FEAR_EVIL)
    TriggerActivation("FearRoom",FALSE)
END

