IF
  See(NearestEnemyOf(Myself))
  General(LastSeenBy(Myself),UNDEAD)
  Global("spells","LOCALS",0)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CONTROL_UNDEAD)
    SetGlobal("spells","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  General(LastSeenBy(Myself),UNDEAD)
  Global("spells","LOCALS",1)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_HOLD_UNDEAD)
    SetGlobal("spells","LOCALS",2)
END

