IF
  See(NearestEnemyOf(Myself))
  HPLT(Myself,30)
  Global("coward","AR1201",0)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
    DisplayStringHead(Myself,313)  // ~I do not want to die...please have mercy!~
    SetGlobal("coward","AR1201",1)
    ChangeAIScript("",RACE)
    ChangeAIScript("",DEFAULT)
    ChangeAIScript("",OVERRIDE)
    MoveToPointNoInterrupt([1457.2124])
    EscapeAreaMove("ar1200",4274,731,0)
END

IF
  See([PC])
  Allegiance(Myself,NEUTRAL)
  AreaCheck("AR1200")
THEN
  RESPONSE #100
    ChangeAIScript("hgsham01",RACE)
    ChangeAIScript("wtasight",DEFAULT)
    ChangeAIScript("gensht01",OVERRIDE)
    StartDialogNoSet(LastSeenBy(Myself))
END

