IF
  See([0.0.HOBGOBLIN.PALADIN])
  HaveSpell(WIZARD_HASTE)
THEN
  RESPONSE #100
    Spell([0.0.HOBGOBLIN.PALADIN],WIZARD_HASTE)
END

IF
  HaveSpell(WIZARD_MIRROR_IMAGE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(0)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),0)
END

IF
  HPPercentLT(Myself,10)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Dead("HobgoblinLeader")  // HobgoblinLeader
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

