IF
  HasItem("MINHP1",Myself)  // <Invalid Strref -1>
  AreaCheck("AR0907")
THEN
  RESPONSE #100
    DestroyItem("MINHP1")  // <Invalid Strref -1>
END

IF
  Global("TalkedToHlketta","GLOBAL",2)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Global("EnteredAR0907","GLOBAL",1)
  See(NearestEnemyOf(Myself))
  OR(2)
    StateCheck(Myself,STATE_INVISIBLE)
    StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
  Global("EnteredAR0907","GLOBAL",1)
  See(NearestEnemyOf(Myself))
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  HasItemSlot(Myself,SLOT_MISC0)
THEN
  RESPONSE #100
    UseItemSlot(Myself,SLOT_MISC0)
END

IF
  Global("EnteredAR0907","GLOBAL",1)
  See(NearestEnemyOf(Myself))
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !HasItemSlot(Myself,SLOT_MISC0)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),70)
    Hide()
END

