IF
  Allegiance(Myself,ENEMY)
  !Global("HusamMove","GLOBAL",100)
THEN
  RESPONSE #100
    SetGlobal("HusamMove","GLOBAL",100)
END

IF
  Global("HusamMove","GLOBAL",100)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Allegiance(Myself,NEUTRAL)
  NumberOfTimesTalkedTo(0)
  GlobalGT("HusamMove","GLOBAL",0)
  GlobalLT("HusamMove","GLOBAL",5)
  See([PC])
THEN
  RESPONSE #100
    Dialog([PC])
END

