IF
  Clicked([ANYONE])
  PartyHasItem("HGWARD03")  // ~Hammer Wardstone~
  Range(LastTrigger,10)
THEN
  RESPONSE #100
    DisplayStringHead(LastTrigger,71178)  // ~The symbol of the hammer upon the golden sphere fades away as you touch its blisteringly hot surface.  In the distance, a faint humming sound abruptly ceases.~
    ApplySpell(LastTrigger,FIRE_GIANT_LAVA)
    OpenDoor("IceWall01")
    AmbientActivate("ICEWALL1A",FALSE)
    AmbientActivate("ICEWALL1B",FALSE)
    AmbientActivate("ICEWALL1C",FALSE)
    SoundActivate("Icebarrier1",FALSE)
    AddXP2DA("PLOT11F")
    CreateCreature("HGSAL01",[750.1349],12)  // ~Fire Salamander~
    CreateCreature("HGSAL01",[497.1334],12)  // ~Fire Salamander~
    CreateCreature("HGSAL01",[471.1437],12)  // ~Fire Salamander~
    CreateCreature("HGSKU01",[580.1261],12)  // ~Flaming Skull~
    CreateCreature("HGFEL01",[582.1349],12)  // ~Fell Cat~
    CreateCreature("HGFEL01",[363.1430],12)  // ~Fell Cat~
    CreateCreature("GOLBUR01",[418.1659],12)  // ~Burning Man~
    TriggerActivation(Myself,FALSE)
END

IF
  Clicked([ANYONE])
  !PartyHasItem("HGWARD03")  // ~Hammer Wardstone~
  Global("TouchedPanel1","GLOBAL",0)
  Range(LastTrigger,10)
THEN
  RESPONSE #100
    SetGlobal("TouchedPanel1","GLOBAL",1)
    DisplayStringHead(LastTrigger,71180)  // ~The golden sphere glows with heat and is inscribed on its surface with the symbol of a hammer.  You could touch it if you wish to, although it would likely burn.~
END

IF
  Clicked([ANYONE])
  !PartyHasItem("HGWARD03")  // ~Hammer Wardstone~
  Global("TouchedPanel1","GLOBAL",1)
  Range(LastTrigger,10)
THEN
  RESPONSE #100
    DisplayStringHead(LastTrigger,71179)  // ~As you touch the incredibly hot surface of the sphere, a symbol of a hammer is displayed brightly...almost in a demanding fashion.  The symbol then flashes and then falls silent.~
    CreateVisualEffect("FIRECOLD",[425.2004])
    ApplySpell(LastTrigger,FIRE_GIANT_LAVA)
    Wait(1)
    ApplySpell(LastTrigger,WIZARD_ENERGY_DRAIN)
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,10)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

