IF
  Global("Torches","GLOBAL",6)
THEN
  RESPONSE #100
    TriggerActivation(Myself,FALSE)
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,15)
THEN
  RESPONSE #100
    StartCutSceneMode()
    CreateCreatureObject("GORTOR5",Myself,0,0,0)  // ~Torch~
    ActionOverride("gortor5",StartDialogNoSet(LastTrigger("Torch5")))
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,15)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

