IF
  !Global("JaheiraRomanceActive","GLOBAL",0)
  !Global("JaheiraRomanceActive","GLOBAL",3)
  OR(2)
    Global("JaheiraMatch","GLOBAL",1)
    Global("JaheiraMatch","GLOBAL",2)
  See(Player1)
  CombatCounter(0)
  OR(2)
    Global("LoveTalk","LOCALS",67)
    Global("LoveTalk","LOCALS",57)
THEN
  RESPONSE #100
    IncrementGlobal("LoveTalk","LOCALS",1)
    RealSetGlobalTimer("JaheiraRomance","GLOBAL",1)
    PlaySong(36)
    Interact(Player1)
END

