IF
  Global("JanMove","GLOBAL",1)
  Global("JanFree","GLOBAL",0)
  See("Trax")  // ~Trax~
THEN
  RESPONSE #100
    DialogueInterrupt(FALSE)
    MoveToObjectFollow("Trax")
END

IF
  Global("JanMove","GLOBAL",1)
  Global("JanFree","GLOBAL",0)
  !See("Trax")  // ~Trax~
THEN
  RESPONSE #100
    DialogueInterrupt(TRUE)
    MoveGlobal("AR1005",Myself,[664.499])
END

IF
  GlobalTimerExpired("JanJoined","GLOBAL")
  Global("JanLissaPlot","GLOBAL",0)
  !Global("Chapter","GLOBAL",4)
  !Global("Chapter","GLOBAL",5)
  !Global("Chapter","GLOBAL",7)
  !AreaCheck("AR1900")
  !AreaCheck("AR1100")
  !AreaCheck("AR1400")
  !AreaCheck("AR1300")
  !AreaCheck("AR2500")
  !AreaCheck("AR2600")
  AreaType(OUTDOOR)
  CombatCounter(0)
  InParty(Myself)
THEN
  RESPONSE #100
    SetGlobal("JanLissaPlot","GLOBAL",1)
    CreateCreatureObjectOffScreen("BEELOO",Myself,0,0,0)  // ~Beeloo Jansen~
END

IF
  OR(4)
    Global("JanLissaPlot","GLOBAL",2)
    Global("JanLissaPlot","GLOBAL",10)
    Global("JanLissaPlot","GLOBAL",11)
    Global("JanLissaPlot","GLOBAL",14)
  CombatCounter(0)
  Detect(Player1)
THEN
  RESPONSE #100
    Wait(2)
    StartDialogNoSet(Player1)
END

IF
  Global("JanLissaPlot","GLOBAL",3)
  GlobalTimerExpired("JanLissa","GLOBAL")
  !Global("Chapter","GLOBAL",4)
  !Global("Chapter","GLOBAL",5)
  !Global("Chapter","GLOBAL",7)
  CombatCounter(0)
  See(Player1)
THEN
  RESPONSE #100
    IncrementGlobal("JanLissaPlot","GLOBAL",1)
    StartDialogNoSet(Player1)
END

IF
  InParty(Myself)
  OR(10)
    Allegiance("majan",ENEMY)  // ~Ma Jansen~
    Allegiance("gerhardt",ENEMY)  // ~Uncle Gerhardt~
    Allegiance("lissa",ENEMY)  // ~Lissa~
    Allegiance("jaella",ENEMY)  // ~Jaella~
    Dead("lissa")  // ~Lissa~
    Dead("jaella")  // ~Jaella~
    Dead("majan")  // ~Ma Jansen~
    Dead("gerhardt")  // ~Uncle Gerhardt~
    Dead("tat")  // ~Tat~
    Dead("tot")  // ~Tot~
  Global("JanFamily","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("JanFamily","LOCALS",1)
    DisplayStringHead(Myself,56235)  // ~No! What are you doing?!~
    LeaveParty()
    Enemy()
END

IF
  !InParty(Myself)
  OR(10)
    Allegiance("majan",ENEMY)  // ~Ma Jansen~
    Allegiance("gerhardt",ENEMY)  // ~Uncle Gerhardt~
    Allegiance("lissa",ENEMY)  // ~Lissa~
    Allegiance("jaella",ENEMY)  // ~Jaella~
    Dead("lissa")  // ~Lissa~
    Dead("jaella")  // ~Jaella~
    Dead("majan")  // ~Ma Jansen~
    Dead("gerhardt")  // ~Uncle Gerhardt~
    Dead("tat")  // ~Tat~
    Dead("tot")  // ~Tot~
  Allegiance(Myself,NEUTRAL)
  Global("JanFamily","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("JanFamily","LOCALS",1)
    DisplayStringHead(Myself,56235)  // ~No! What are you doing?!~
    Enemy()
END

IF
  Allegiance(Myself,ENEMY)
  !InParty(Myself)
  Global("NPCFight","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("NPCFight","LOCALS",1)
    ChangeAIScript("janx",SPECIFICS)
    ChangeAIScript("useitem",GENERAL)
    ChangeAIScript("",DEFAULT)
    SetDialogue("")
    Continue()
END

IF
  Allegiance(Myself,NEUTRAL)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    ChangeAIScript("janx",SPECIFICS)
    ChangeAIScript("useitem",GENERAL)
    Enemy()
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !InParty(Myself)
  Global("NPCFight","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("NPCFight","LOCALS",0)
    ChangeAIScript("",GENERAL)
    ChangeAIScript("",SPECIFICS)
    Continue()
END

