IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Shout(89)
    Enemy()
END

IF
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  See(NearestEnemyOf(Myself))
  HaveSpell(PSIONIC_DOMINATION)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),PSIONIC_DOMINATION)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(PSIONIC_DETONATE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),PSIONIC_DETONATE)
END

IF
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  See(NearestEnemyOf(Myself))
  HaveSpell(PSIONIC_EGOWHIP)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),PSIONIC_EGOWHIP)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(PSIONIC_BALLISTIC)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),PSIONIC_BALLISTIC)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

