IF
  Global("JonDemonTeleport","AR2906",1)
  Global("Teleport","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("Teleport","LOCALS",1)
    CreateVisualEffectObject("SPFLSRIN",Myself)
    Wait(1)
    CreateVisualEffectObject("SPFIREPI",Myself)
    JumpToPoint([3493.2281])
    Face(6)
    SetInterrupt(TRUE)
END

IF
  Global("JonDemonTeleport","AR2906",2)
  Global("Teleport","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("Teleport","LOCALS",1)
    CreateVisualEffectObject("SPFLSRIN",Myself)
    Wait(1)
    CreateVisualEffectObject("SPFIREPI",Myself)
    JumpToPoint([1096.574])
    Face(14)
    SetInterrupt(TRUE)
END

IF
  Global("JonDemonTeleport","AR2906",3)
  Global("Teleport","LOCALS",2)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("Teleport","LOCALS",1)
    CreateVisualEffectObject("SPFLSRIN",Myself)
    Wait(1)
    CreateVisualEffectObject("SPFIREPI",Myself)
    JumpToPoint([3021.598])
    Face(2)
    SetInterrupt(TRUE)
END

IF
  Global("JonDemonTeleport","AR2906",4)
  Global("Teleport","LOCALS",3)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("Teleport","LOCALS",1)
    CreateVisualEffectObject("SPFLSRIN",Myself)
    Wait(1)
    CreateVisualEffectObject("SPFIREPI",Myself)
    JumpToPoint([2046.2748])
    Face(6)
    SetInterrupt(TRUE)
END

IF
  Global("JonDemonTeleport","AR2906",5)
  Global("Teleport","LOCALS",4)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("Teleport","LOCALS",1)
    CreateVisualEffectObject("SPFLSRIN",Myself)
    Wait(1)
    CreateVisualEffectObject("SPFIREPI",Myself)
    JumpToPoint([655.1545])
    Face(14)
    SetInterrupt(TRUE)
END

