IF
  See([ENEMY])
  Range(LastSeenBy(Myself),5)
THEN
  RESPONSE #100
    RunAwayFrom(LastSeenBy(Myself),30)
END

IF
  !See([ENEMY])
  See([PC])
  CombatCounter(0)
  InActiveArea(Myself)
  InMyArea([PC])
  Global("TalkedToHgkar01","GLOBAL",0)
THEN
  RESPONSE #100
    Dialog([PC])
END

IF
  !See([ENEMY])
  !See([PC])
  InActiveArea(Myself)
  OR(6)
    InMyArea(Player1)
    InMyArea(Player2)
    InMyArea(Player3)
    InMyArea(Player4)
    InMyArea(Player5)
    InMyArea(Player6)
  CombatCounter(0)
  Global("TalkedToHgkar01","GLOBAL",0)
THEN
  RESPONSE #100
    MoveToObject([PC])
END

