IF
  Global("AnomenTrial","GLOBAL",0)
  !See("Anomen")  // Anomen
  InParty("Anomen")  // Anomen
THEN
  RESPONSE #100
    MoveToObject("Anomen")
END

IF
  Global("AnomenTrial","GLOBAL",0)
  See("Anomen")  // Anomen
  InParty("Anomen")  // Anomen
THEN
  RESPONSE #100
    Dialog("Anomen")
END

IF
  OR(2)
    Global("AnomenTrial","GLOBAL",1)
    !InParty("Anomen")  // Anomen
THEN
  RESPONSE #100
    EscapeArea()
END

