IF
  !UnselectableVariable(0)
  Global("Xzarfight","GLOBAL",0)
THEN
  RESPONSE #100
    MakeUnselectable(0)
END

IF
  UnselectableVariable(0)
  See("Xzar")  // ~Xzar~
  Global("Xzarfight","GLOBAL",1)
THEN
  RESPONSE #100
    MakeUnselectable(5000)
END

IF
  UnselectableVariable(0)
  See("Montaron")  // Montaron
  Global("Xzarfight","GLOBAL",1)
THEN
  RESPONSE #100
    MakeUnselectable(5000)
END

IF
  !UnselectableVariable(0)
  Dead("Xzar")  // ~Xzar~
  Dead("Montaron")  // Montaron
  Global("Xzarfight","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("Xzarfight","GLOBAL",0)
    MakeUnselectable(0)
END

IF
  !UnselectableVariable(0)
  !See("Xzar")  // ~Xzar~
  !See("Montaron")  // Montaron
THEN
  RESPONSE #100
    MakeUnselectable(0)
END

IF
  Global("Xzarfight","GLOBAL",1)
  See("Montaron")  // Montaron
THEN
  RESPONSE #100
    Attack("Montaron")
END

IF
  Global("Xzarfight","GLOBAL",1)
  See("Xzar")  // ~Xzar~
THEN
  RESPONSE #100
    Attack("Xzar")
END

IF
  GlobalTimerExpired("Khalid","GLOBAL")
  Global("OffToNashkell","GLOBAL",0)
  Global("Chapter","GLOBAL",1)
  InParty(Myself)
THEN
  RESPONSE #100
    Dialog([PC])
END

IF
  GlobalTimerExpired("Khalid","GLOBAL")
  Global("OffToNashkell","GLOBAL",1)
  Global("Chapter","GLOBAL",1)
  InParty(Myself)
THEN
  RESPONSE #100
    Dialog([PC])
END

