IF
  See(Player1)
  Range(Player1,10)
  Range(NearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
  See(Player1)
  Range(Player1,10)
  !Range(NearestEnemyOf(Myself),9)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  !Range(Player1,10)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  See(Player1)
  Range(Player1,4)
THEN
  RESPONSE #100
    AttackReevaluate(Player1,45)
END

