IF
  See([PC.0.0.0.0.MALE])
  Global("KirinBehavior","GLOBAL",0)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ForceSpell([PC.0.0.0.0.MALE],SUCCUBUS_CHARM_MALE)
    Wait(2)
    ForceSpellPoint([717.886],SUCCUBUS_TELEPORT)
    Wait(1)
    ForceSpell(Myself,SUCCUBUS_ETHEREAL)
    SetGlobal("KirinBehavior","GLOBAL",1)
END

IF
  See([PC])
  Global("KirinBehavior","GLOBAL",0)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ForceSpell([PC],SUCCUBUS_CHARM_FEMALE)
    Wait(2)
    ForceSpellPoint([705.424],SUCCUBUS_TELEPORT)
    Wait(1)
    ForceSpell(Myself,SUCCUBUS_ETHEREAL)
    SetGlobal("KirinBehavior","GLOBAL",1)
END

IF
  See([PC.0.0.0.0.MALE])
  Global("KirinBehavior","GLOBAL",1)
THEN
  RESPONSE #100
    ForceSpell([PC],SUCCUBUS_ENERGY_DRAIN)
    Wait(1)
    ForceSpell([PC.0.0.0.0.MALE],SUCCUBUS_CHARM_MALE)
    Wait(2)
    ForceSpell(Myself,SUCCUBUS_ETHEREAL)
    Wait(1)
    ForceSpell(SecondNearest([PC]),SUCCUBUS_TELEPORT)
    Wait(1)
    SetGlobal("KirinBehavior","GLOBAL",2)
END

IF
  See([PC])
  Global("KirinBehavior","GLOBAL",1)
THEN
  RESPONSE #100
    ForceSpell([PC],SUCCUBUS_ENERGY_DRAIN)
    Wait(1)
    ForceSpell(SecondNearest([PC]),SUCCUBUS_CHARM_FEMALE)
    Wait(2)
    ForceSpell(Myself,SUCCUBUS_ETHEREAL)
    Wait(1)
    ForceSpell(ThirdNearest([PC]),SUCCUBUS_TELEPORT)
    Wait(1)
    SetGlobal("KirinBehavior","GLOBAL",2)
END

IF
  See([PC])
  NotStateCheck([PC],STATE_CHARMED)
  Global("KirinBehavior","GLOBAL",2)
THEN
  RESPONSE #100
    ForceSpell([PC],SUCCUBUS_ENERGY_DRAIN)
    Wait(1)
    ForceSpell(Myself,SUCCUBUS_ETHEREAL)
    Wait(12)
    AttackOneRound([PC])
    Wait(3)
    SetGlobal("KirinBehavior","GLOBAL",3)
END

IF
  See([PC])
  Global("KirinBehavior","GLOBAL",3)
THEN
  RESPONSE #100
    ForceSpell(SecondNearest([PC]),SUCCUBUS_TELEPORT)
    Wait(1)
    ForceSpell(Myself,SUCCUBUS_ETHEREAL)
    Wait(6)
    ForceSpell([PC],SUCCUBUS_CHARM_FEMALE)
    AttackOneRound(NearestEnemyOf(Myself))
    ForceSpell(Myself,SUCCUBUS_ETHEREAL)
    Wait(3)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    ForceSpell(NearestEnemyOf(Myself),SUCCUBUS_ENERGY_DRAIN)
    AttackOneRound(NearestEnemyOf(Myself))
    Wait(2)
END

