IF
  See([ENEMY])
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  Global("KPTrollFight","AR1300",0)
  AreaCheck("AR1300")
  See([PC])
THEN
  RESPONSE #100
    SetGlobal("KPTrollFight","AR1300",1)
END

IF
  Global("KPTrollFight","AR1300",0)
  AreaCheck("AR1300")
THEN
  RESPONSE #100
    Wait(1)
END

IF
  GlobalTimerExpired("TrollsDead","AR1300")
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Global("KeepPlot","GLOBAL",11)
  Global("ChangeAlignment","LOCALS",0)
  AreaCheck("AR1304")
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,GOODBUTBLUE)
    SetGlobal("ChangeAlignment","LOCALS",1)
END

IF
  GlobalGT("KeepPlot","GLOBAL",11)
  AreaCheck("AR1304")
THEN
  RESPONSE #100
    DestroySelf()
END

