IF
  HPLT(Myself,10)
  Global("LassalTalk","LOCALS",0)
THEN
  RESPONSE #100
    StartDialogNoSet(Player1)
END

IF
  Allegiance(Myself,ENEMY)
  See("Mook")  // ~Mook~
  !Dead("Mook")  // ~Mook~
THEN
  RESPONSE #100
    ReallyForceSpell("Mook",BEHOLDER_DISINTEGRATE)
    Kill("Mook")
END

IF
  Die()
THEN
  RESPONSE #100
    ReallyForceSpellDead(Myself,VAMPIRE_GAS_FORM_CHANGE)
END

IF
  TimeGT(5)
  TimeLT(DUSK_END)
  AreaType(OUTDOOR)
THEN
  RESPONSE #100
    ReallyForceSpellDead(Myself,VAMPIRE_BAT_FORM_CHANGE)
END

IF
  Allegiance(Myself,ENEMY)
  HPGT(Myself,9)
  See([PC])
  Delay(12)
THEN
  RESPONSE #100
    ReallyForceSpellDead([PC],BEHOLDER_DOMINATION)
END

