IF
  Die()
  !Dead("mourner1")  // ~Nevin~
THEN
  RESPONSE #100
    ActionOverride("mourner1",StartDialogNoSet(Player1))
END

IF
  Global("LesterDialogue","GLOBAL",0)
  !Range("mourner1",3)  // ~Nevin~
THEN
  RESPONSE #100
    MoveToObject("mourner1")
END

IF
  Global("LesterDialogue","GLOBAL",0)
  Range("mourner1",3)  // ~Nevin~
THEN
  RESPONSE #100
    StartDialogNoSet(Player1)
END

IF
  Dead("mourner1")  // ~Nevin~
  Detect([PC])
THEN
  RESPONSE #100
    StartDialogNoSet(LastSeenBy(Myself))
END

