IF
  Clicked([ANYONE])
  OpenState("DOOR08",TRUE)  // DOOR08
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    ActionOverride(LastTrigger,MoveToPoint([2120.910]))
    CloseDoor("DOOR08")
    PlaySound("AMB_D04A")
END

IF
  Clicked([ANYONE])
  OpenState("DOOR08",FALSE)  // DOOR08
  Range(LastTrigger,9)
THEN
  RESPONSE #100
    ActionOverride(LastTrigger,MoveToPoint([2120.910]))
    OpenDoor("DOOR08")
    PlaySound("AMB_D04A")
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,9)
THEN
  RESPONSE #100
    DisplayString(Myself,23565)  // ~You are too far away to operate that device.~
END

