IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SHADOW_DOOR)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHADOW_DOOR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)
  Global("Behavior","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Behavior","LOCALS",1)
    Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MONSTER_SUMMONING_3)
  Global("Behavior","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Behavior","LOCALS",2)
    Spell(NearestEnemyOf(Myself),WIZARD_MONSTER_SUMMONING_3)
END

IF
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_POWER_WORD_SILENCE)
  Detect([PC.0.0.MAGE])
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)
END

IF
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_POWER_WORD_SILENCE)
  Detect([PC.0.0.CLERIC_MAGE])
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)
END

IF
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_POWER_WORD_SILENCE)
  Detect([PC.0.0.CLERIC])
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HASTE)
  Global("Behavior","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("Behavior","LOCALS",3)
    Spell(Myself,WIZARD_HASTE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_LIGHTNING_BOLT)
  Global("Behavior","LOCALS",3)
THEN
  RESPONSE #100
    SetGlobal("Behavior","LOCALS",4)
    Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)
  Global("Behavior","LOCALS",4)
THEN
  RESPONSE #100
    SetGlobal("Behavior","LOCALS",5)
    Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FIREBALL)
  !Range(NearestEnemyOf(Myself),8)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FIREBALL)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_CONE_OF_COLD)
  !Range(NearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CONE_OF_COLD)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_CHAOS)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CHAOS)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(0)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),0)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

