IF
  StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    ForceSpell(Myself,WIZARD_VOCALIZE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("prepspells","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("prepspells","LOCALS",1)
    ForceSpell(Myself,WIZARD_MISLEAD)
    Wait(1)
    DisplayString(Myself,31247)  // ~Tattoo of Power - Spell Immunity~
    ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_INVOCATION)
END

IF
  Allegiance(Myself,ENEMY)
  Global("prepspells","LOCALS",1)
  CheckStatLT(Myself,1,STONESKINS)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    DisplayString(Myself,29736)  // ~Contingency - Stoneskin~
    ApplySpell(Myself,WIZARD_STONE_SKIN)
    SetGlobal("prepspells","LOCALS",2)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_GREATER_MALISON)
  HaveSpell(WIZARD_CHAOS)
THEN
  RESPONSE #100
    Spell(SecondNearestEnemyOf(Myself),WIZARD_GREATER_MALISON)
    Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAOS)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_PRISMATIC_SPRAY)
THEN
  RESPONSE #100
    Spell(SecondNearestEnemyOf(Myself),WIZARD_PRISMATIC_SPRAY)
END

IF
  Allegiance(Myself,ENEMY)
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
  !Range(LastSeenBy(Myself),12)
  HaveSpell(WIZARD_DEATH_SPELL)
THEN
  RESPONSE #100
    DisplayString(Myself,31024)  // ~Magic Tattoo - Mirror Image~
    ApplySpell(Myself,WIZARD_MIRROR_IMAGE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END

IF
  Allegiance(Myself,ENEMY)
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
  Range(LastSeenBy(Myself),12)
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  HaveSpell(WIZARD_FIREBALL)
THEN
  RESPONSE #100
    DisplayString(Myself,31024)  // ~Magic Tattoo - Mirror Image~
    ApplySpell(Myself,WIZARD_MIRROR_IMAGE)
    Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
    Spell(LastSeenBy(Myself),WIZARD_FIREBALL)
END

IF
  Global("prepspells","LOCALS",2)
  HaveSpell(WIZARD_STONE_SKIN)
  CheckStatLT(Myself,1,STONESKINS)
  !Dead("yself)")  // yself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_STONE_SKIN)
END

IF
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  HaveSpell(WIZARD_PIERCE_MAGIC)
  HaveSpell(WIZARD_POWER_WORD_SILENCE)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)
END

IF
  Allegiance(Myself,ENEMY)
  See(SecondNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  HaveSpell(WIZARD_POWER_WORD_STUN)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
END

IF
  Allegiance(Myself,ENEMY)
  !Range(FourthNearestEnemyOf(Myself),10)
  HaveSpell(WIZARD_FIREBALL)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_FIREBALL)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HOLD_MONSTER)
THEN
  RESPONSE #100
    Spell(ThirdNearestEnemyOf(Myself),WIZARD_HOLD_MONSTER)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MONSTER_SUMMONING_3)
THEN
  RESPONSE #100
    Spell(ThirdNearestEnemyOf(Myself),WIZARD_MONSTER_SUMMONING_3)
END

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SECRET_WORD)
  HaveSpell(WIZARD_DISINTEGRATE)
  HaveSpell(WIZARD_MIRROR_IMAGE)
THEN
  RESPONSE #10
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    Spell(NearestEnemyOf(Myself),WIZARD_SECRET_WORD)
    Spell(NearestEnemyOf(Myself),WIZARD_DISINTEGRATE)
  RESPONSE #10
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    Spell(SecondNearestEnemyOf(Myself),WIZARD_BREACH)
    Spell(SecondNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)
  RESPONSE #10
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    Spell(ThirdNearestEnemyOf(Myself),WIZARD_BREACH)
    Spell(ThirdNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)
  RESPONSE #10
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    Spell(FourthNearestEnemyOf(Myself),WIZARD_BREACH)
    Spell(FourthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)
  RESPONSE #10
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    Spell(FifthNearestEnemyOf(Myself),WIZARD_BREACH)
    Spell(FifthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)
  RESPONSE #10
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    Spell(SixthNearestEnemyOf(Myself),WIZARD_BREACH)
    Spell(SixthNearestEnemyOf(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SPELL_TURNING)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TURNING)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FLAME_ARROW)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MELF_ACID_ARROW)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MAGIC_MISSILE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_CHROMATIC_ORB)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CHROMATIC_ORB)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

