IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SHADOW_DOOR)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHADOW_DOOR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MONSTER_SUMMONING_3)
  Global("Behavior","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Behavior","LOCALS",1)
    Spell(NearestEnemyOf(Myself),WIZARD_MONSTER_SUMMONING_3)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HASTE)
  Global("Behavior","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Behavior","LOCALS",2)
    Spell(NearestEnemyOf(Myself),WIZARD_HASTE)
END

IF
  HPPercentLT([ENEMY],75)
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
THEN
  RESPONSE #100
    Spell([ENEMY],CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
  HPPercentLT(SecondNearest([ENEMY]),75)
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
THEN
  RESPONSE #100
    Spell(SecondNearest([ENEMY]),CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
  HPPercentLT(ThirdNearest([ENEMY]),75)
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
THEN
  RESPONSE #100
    Spell(ThirdNearest([ENEMY]),CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
  HPPercentLT(FourthNearest([ENEMY]),75)
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
THEN
  RESPONSE #100
    Spell(FourthNearest([ENEMY]),CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
  HPPercentLT(FifthNearest([ENEMY]),75)
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
THEN
  RESPONSE #100
    Spell(FifthNearest([ENEMY]),CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MONSTER_SUMMONING_3)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MONSTER_SUMMONING_3)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HASTE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_HASTE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_CHAOS)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CHAOS)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FLAME_ARROW)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

