IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_ARMOR)
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    SetGlobal("Prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_FLAME_ARROW)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MIRROR_IMAGE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_HORROR)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_HORROR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MELF_ACID_ARROW)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_CHROMATIC_ORB)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CHROMATIC_ORB)
END

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  HaveSpell(WIZARD_CHARM_PERSON)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CHARM_PERSON)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_COLOR_SPRAY)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_COLOR_SPRAY)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

