IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    ApplySpell(Myself,WIZARD_MINOR_SPELL_TURNING)
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    SetGlobal("Prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_STONE_SKIN)
  CheckStatLT(Myself,1,STONESKINS)
  Global("Prep","LOCALS",1)
THEN
  RESPONSE #100
    DisplayString(Myself,29736)  // ~Contingency - Stoneskin~
    ApplySpell(Myself,WIZARD_STONE_SKIN)
    SetGlobal("Prep","LOCALS",2)
END

IF
  See(NearestEnemyOf(Myself))
  See(NearestMyGroupOfType)
  !Dead("yself)")  // yself)
  Global("SpellSequencer","LOCALS",0)
THEN
  RESPONSE #100
    DisplayString(LastSeenBy(Myself),39969)  // ~Spell Sequencer - Fired~
    DisplayString(LastSeenBy(Myself),40697)  // ~Spell Sequencer - Haste~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_HASTE)
    DisplayString(LastSeenBy(Myself),40242)  // ~Spell Sequencer - Improved Invisibility~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_IMPROVED_INVISIBILITY)
    DisplayString(LastSeenBy(Myself),40696)  // ~Spell Sequencer - Strength~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_STRENGTH)
    SetGlobal("SpellSequencer","LOCALS",1)
END

IF
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  HaveSpell(WIZARD_SECRET_WORD)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)
END

IF
  See(NearestEnemyOf(Myself))
  StateCheck(Myself,STATE_SILENCED)
  HaveSpell(WIZARD_VOCALIZE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_VOCALIZE)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
  See(NearestMyGroupOfType)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),WIZARD_IMPROVED_INVISIBILITY)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_DEATH_SPELL)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_DEATH_SPELL)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_CHAOS)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CHAOS)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_TRUE_SIGHT)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_TRUE_SIGHT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SHADOW_DOOR)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHADOW_DOOR)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_CONFUSION)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CONFUSION)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_DOMINATION)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_DOMINATION)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_ANIMATE_DEAD)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_ANIMATE_DEAD)
END

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  HaveSpell(WIZARD_HOLD_PERSON)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_HOLD_PERSON)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SKULL_TRAP)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_SKULL_TRAP)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_MAGIC_MISSILE)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

