IF
  Global("Enclave","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("MallaGone","GLOBAL",1)
    DestroySelf()
END

IF
  AreaCheck("AR5507")
  Dead("malla01")  // ~Malla~
  Global("MarloweUpset","LOCALS",0)
  OR(2)
    See([PC])
    See(Player1)
  !See([ENEMY])
THEN
  RESPONSE #100
    SetGlobal("MarloweUpset","LOCALS",1)
    Dialog(LastSeenBy(Myself))
END

IF
  AreaCheck("AR5501")
  Global("TalkedToMarlowe","GLOBAL",0)
  OR(2)
    See([PC])
    See(Player1)
  !See([ENEMY])
THEN
  RESPONSE #100
    Dialog(LastSeenBy(Myself))
END

IF
  AreaCheck("AR5507")
  Global("TalkedToMarlowe","GLOBAL",1)
  Global("ApproachAgain","LOCALS",0)
  Global("MallaPlaced","AR5507",1)
  OR(2)
    See([PC])
    See(Player1)
  !See([ENEMY])
THEN
  RESPONSE #100
    SetGlobal("ApproachAgain","LOCALS",1)
    StartDialogNoSet(LastSeenBy(Myself))
END

IF
  AreaCheck("AR5509")
  Dead("amlich01")  // ~Vongoethe~
  OR(2)
    Dead("malla01")  // ~Malla~
    Global("MallaCured","GLOBAL",1)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  AreaCheck("AR5509")
  Dead("amlich01")  // ~Vongoethe~
  GlobalGT("LichJob","GLOBAL",2)
  Global("MarloweSaved","LOCALS",0)
  GlobalLT("MarloweJob","GLOBAL",3)
  CombatCounter(0)
  OR(2)
    See([PC])
    See(Player1)
THEN
  RESPONSE #100
    SetGlobal("MarloweSaved","LOCALS",1)
    DialogueInterrupt(TRUE)
    ChangeEnemyAlly(Myself,NEUTRAL)
    StartDialogNoSet(LastSeenBy(Myself))
END

IF
  See([ENEMY.UNDEAD])
THEN
  RESPONSE #100
    ApplySpellRES("runrun",Myself)  // <Invalid Strref -1>
    RunAwayFrom(LastSeenBy(Myself),60)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
  !General(NearestEnemyOf(Myself),UNDEAD)
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  AttackedBy([ANYONE],DEFAULT)
  !General(LastAttackerOf(Myself),UNDEAD)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

