IF
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  Global("confused","LOCALS",0)
  LevelPartyGT(14)
  NumInPartyGT(4)
  RandomNum(3,1)
THEN
  RESPONSE #100
    SetGlobal("confused","LOCALS",1)
    SpellNoDec(NearestEnemyOf(Myself),WIZARD_CONFUSION)
END

IF
  See(NearestEnemyOf(Myself))
  GlobalLT("Prep","LOCALS",3)
  LevelPartyGT(14)
  NumInPartyGT(4)
  RandomNum(3,1)
THEN
  RESPONSE #100
    IncrementGlobal("Prep","LOCALS",1)
    ForceSpell(NearestEnemyOf(Myself),WIZARD_POWER_WORD_STUN)
END

IF
  !See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

