IF
  See(NearestEnemyOf(Myself))
  GlobalLT("ICEMEPHIT","LOCALS",3)
THEN
  RESPONSE #100
    ForceSpell(NearestEnemyOf(Myself),MEPHIT_ICE_SHARD)
    IncrementGlobal("ICEMEPHIT","LOCALS",1)
    AttackOneRound(NearestEnemyOf(Myself))
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

