IF
  StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
THEN
  RESPONSE #50
    AttackReevaluate(SecondNearestEnemyOf(Myself),5)
  RESPONSE #50
    AttackReevaluate(NearestEnemyOf(Myself),5)
END

IF
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),30)
  Global("StartTheHorror","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("StartTheHorror","LOCALS",1)
    SetGlobalTimer("TheHorrorContinues","GLOBAL",30)
    ForceSpell(Myself,MIST_HORROR)
END

IF
  GlobalTimerExpired("TheHorrorContinues","GLOBAL")
  Global("StartTheHorror","LOCALS",1)
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),30)
THEN
  RESPONSE #100
    SetGlobalTimer("TheHorrorContinues","GLOBAL",30)
    ForceSpell(Myself,MIST_HORROR)
END

IF
  HPLT(Myself,11)
  Global("LastChanceFog","LOCALS",0)
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),30)
THEN
  RESPONSE #100
    SetGlobal("LastChanceFog","LOCALS",1)
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_DEATH_FOG)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),30)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(Myself))
END

