IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),30)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(Myself))
END

IF
  !GlobalTimerNotExpired("CastChaosAgain","LOCALS")
  RandomNum(3,1)
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),30)
THEN
  RESPONSE #100
    SetGlobalTimer("CastChaosAgain","LOCALS",30)
    ForceSpell(Myself,MIST_CHAOS)
END

IF
  OR(2)
    StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
    StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  See(SecondNearestEnemyOf(Myself))
THEN
  RESPONSE #50
    AttackReevaluate(SecondNearestEnemyOf(Myself),30)
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #50
    AttackReevaluate(WeakestOf(Myself),30)
  RESPONSE #25
    AttackReevaluate(MostDamagedOf(Myself),30)
  RESPONSE #25
    AttackReevaluate(NearestEnemyOf(Myself),30)
  RESPONSE #25
    RunAwayFrom(NearestEnemyOf(Myself),10)
  RESPONSE #100
    AttackReevaluate(WorstAC(Myself),30)
END

