IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    LeaveAreaLUAPanic("AR0072","",[0.0],0)
    LeaveAreaLUA("AR0072","",[0.0],0)
    ActionOverride(Player2,LeaveAreaLUA("AR0072","",[0.0],0))
    ActionOverride(Player3,LeaveAreaLUA("AR0072","",[0.0],0))
    ActionOverride(Player4,LeaveAreaLUA("AR0072","",[0.0],0))
    ActionOverride(Player5,LeaveAreaLUA("AR0072","",[0.0],0))
    ActionOverride(Player6,LeaveAreaLUA("AR0072","",[0.0],0))
    MultiPlayerSync()
    MoveViewPoint([1275.1050],INSTANT)
    Wait(1)
    StartCutScene("Movie04b")
END

