IF
  Entered([ANYONE])
THEN
  RESPONSE #100
    FadeToColor([20.0],0)
    Wait(1)
    ClearAllActions()
    StartCutSceneMode()
    StartCutScene("Movie04a")
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  PartyHasItem("MISCBI")  // ~Magical Rope~
THEN
  RESPONSE #100
    SaveGame(0)
    MultiPlayerSync()
    DisplayString(Myself,57046)  // ~You use your magical rope to climb down into the depths of the pit.~
    TakePartyItem("MISCBI")
    TakePartyItem("MISCBI")
    ActionOverride(Player1,MoveToPoint([4558.2639]))
    ActionOverride(Player2,MoveToPoint([4558.2639]))
    ActionOverride(Player3,MoveToPoint([4558.2639]))
    ActionOverride(Player4,MoveToPoint([4558.2639]))
    ActionOverride(Player5,MoveToPoint([4558.2639]))
    ActionOverride(Player6,MoveToPoint([4558.2639]))
    Wait(1)
    FadeToColor([20.0],0)
    Wait(1)
    ClearAllActions()
    StartCutSceneMode()
    StartCutScene("Movie04a")
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  !PartyHasItem("MISCBI")  // ~Magical Rope~
THEN
  RESPONSE #100
    DisplayString(Myself,57044)  // ~This staircase leads to a pit.  This most probably leads to the Underdark.  However, you have no method for which to climb down into the pit.  Perhaps some sort of rope would help.~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,12)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

