IF
  !See([PC])
  TimeGT(3)
  TimeLT(23)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Shout(1)
    Enemy()
END

IF
  Heard("SlumsMugger2",1)  // SlumsMugger2
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Global("SlumsMugging","AR0400",2)
  See("SlumsVictim")  // SlumsVictim
  !Dead("SlumsVictim")  // SlumsVictim
THEN
  RESPONSE #100
    Attack("SlumsVictim")
END

