IF
  Global("NaliaSummoned","GLOBAL",1)
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
END

IF
  GlobalGT("chapter","GLOBAL",7)
  Global("NewSounds","LOCALS",0)
THEN
  RESPONSE #100
    SetPlayerSound(Myself,70849,TIRED)  // ~ You know, there's little point in driving us to the breaking point.  We should stop soon.~ [NALI2518]
    SetPlayerSound(Myself,70850,BORED)  // ~ (sigh)  I don't want to be annoying, but I detest just standing around.~ [NALI2519]
    SetPlayerSound(Myself,70851,BATTLE_CRY1)  // ~ Evil falls today!~ [NALI2520]
    SetPlayerSound(Myself,70852,BATTLE_CRY2)  // ~ If you fight, you die!  You cannot match our power!!~ [NALI2521]
    SetPlayerSound(Myself,70853,AREA_DUNGEON)  // ~ There is evil, here...but there is likely also magic that can help us, I'd bet.~ [NALI2522]
    SetPlayerSound(Myself,70854,SELECT_COMMON2)  // ~ I can assist you.~ [NALI2523]
    SetPlayerSound(Myself,70855,SELECT_COMMON3)  // ~ My magic is at your command.~ [NALI2524]
    SetPlayerSound(Myself,70856,SELECT_ACTION2)  // ~ It can be done.~ [NALI2525]
    SetPlayerSound(Myself,70857,SELECT_ACTION3)  // ~ Naturally.~ [NALI2526]
    SetPlayerSound(Myself,70858,SELECT_ACTION4)  // ~ Very well.~ [NALI2527]
    SetPlayerSound(Myself,70859,SELECT_ACTION5)  // ~ Once all this would have been beyond my imagination.  But *that* was a long time ago.~ [NALI2528]
    SetGlobal("NewSounds","LOCALS",1)
END

IF
  Allegiance(Myself,ENEMY)
  !InParty(Myself)
  Global("NPCFight","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("NPCFight","LOCALS",1)
    ChangeAIScript("",DEFAULT)
    ChangeAIScript("useitem",GENERAL)
    ChangeAIScript("edwinx",SPECIFICS)
    SetDialogue("")
    Continue()
END

IF
  Allegiance(Myself,NEUTRAL)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    ChangeAIScript("useitem",GENERAL)
    ChangeAIScript("edwinx",SPECIFICS)
    Enemy()
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !InParty(Myself)
  Global("NPCFight","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("NPCFight","LOCALS",0)
    ChangeAIScript("",GENERAL)
    ChangeAIScript("",SPECIFICS)
    Continue()
END

