IF
  Global("PaladinsStartBattle","GLOBAL",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  OR(2)
    OnCreation()
    Die()
THEN
  RESPONSE #100
    SaveObjectLocation("GLOBAL","LOCpalkni04",Myself)
END

IF
  OR(2)
    !Detect(Player1)
    !Range(Player1,15)
  NumberOfTimesTalkedTo(0)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  Range(Player1,15)
  NumberOfTimesTalkedTo(0)
  Detect(Player1)
THEN
  RESPONSE #100
    StartDialogNoSet(Player1)
END

