IF
  Global("TalkedInArea","LOCALS",0)
  PartyHasItem("miscAN")  // ~Galvena's Medallion~
  AreaCheck("ar1609")
THEN
  RESPONSE #100
    SetGlobal("TalkedInArea","LOCALS",1)
    Wait(1)
    StartDialogNoSet([PC])
END

IF
  Global("TalkedInArea","LOCALS",0)
  !PartyHasItem("miscAN")  // ~Galvena's Medallion~
  AreaCheck("ar1609")
THEN
  RESPONSE #100
    SetGlobal("FreeCourtesan","LOCALS",0)
    SetGlobal("TalkedInArea","LOCALS",1)
    Wait(1)
    StartDialogNoSet([PC])
END

