IF
  Global("GalvenaHostile","GLOBAL",1)
  Global("PimurHostile08","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("PimurHostile08","LOCALS",1)
    Enemy()
END

IF
  Global("GalvenaHostile","GLOBAL",0)
  Allegiance(Myself,NEUTRAL)
  See([PC])
  Global("TalkedToPC","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("TalkedToPC","LOCALS",1)
    StartDialogNoSet([PC])
END

IF
  Global("GuardSleep","GLOBAL",1)
THEN
  RESPONSE #100
    PlayDead(999)
END

