IF
  Detect([PC])
  Range(LastSeenBy(Myself),25)
  CombatCounter(0)
  Global("firstspoke","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("firstspoke","LOCALS",1)
    StartDialogNoSet(LastSeenBy(Myself))
END

IF
  Name("ppduel2",Myself)
  !Dead("ppduel1")  // ~Andante~
  See("ppduel1")  // ~Andante~
  Global("firstspoke","LOCALS",1)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),15)
END

IF
  Name("ppduel1",Myself)
  !Dead("ppduel2")  // ~Dirbish the Black~
  See("ppduel2")  // ~Dirbish the Black~
  Global("firstspoke","LOCALS",1)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),15)
END

IF
  Name("ppduel2",Myself)
  Dead("ppduel1")  // ~Andante~
  Detect([PC])
  Global("spoke","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("spoke","LOCALS",1)
    StartDialogNoSet(LastSeenBy(Myself))
END

IF
  Name("ppduel1",Myself)
  Dead("ppduel2")  // ~Dirbish the Black~
  Detect([PC])
  Global("spoke","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("spoke","LOCALS",1)
    StartDialogNoSet(LastSeenBy(Myself))
END

