IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("Coffin1","AR1513",0)
  Global("deadjoye","AR1513",0)
THEN
  RESPONSE #100
    DisplayString(Myself,31876)  // ~This is the ornate coffin of the vampire Dace. Strange markings on the side, upon closer inspection, turn out to be the word 'Madness' etched over and over again, covering the coffin. ~
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("Coffin1","AR1513",0)
  Global("deadjoye","AR1513",1)
THEN
  RESPONSE #100
    DisplayString(Myself,31877)  // ~With a tortured cry, Dace has retreated to his coffin upon defeat. If you can but find a wooden stake, you can end his miserable existence for good.~
    SetGlobal("Coffin1","AR1513",1)
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("Coffin1","AR1513",1)
  PartyHasItem("MISC6W")  // ~Wooden Stake~
  Global("deadjoye","AR1513",1)
THEN
  RESPONSE #100
    DisplayString(Myself,35847)  // ~You pound the stake through the vampires foul heart. The creature shall prey no more on the blood of others.~
    SetGlobal("Coffin1","AR1513",2)
    AddexperienceParty(9000)
    TakePartyItem("misc6w")
    DestroyItem("misc6w")  // ~Wooden Stake~
    PlaySound("VAMPP07")
    DisplayString(Myself,48483)  // ~The hand of the staked creature comes loose in your grasp.~
    GiveItemCreate("misc9a",[PC],0,0,0)  // ~The Hand of Dace~
    CreateVisualEffectObject("SPDEATH3",Myself)
    Wait(1)
    CreateVisualEffectObject("SPFLESH2",Myself)
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("Coffin1","AR1513",2)
  Global("deadjoye","AR1513",1)
THEN
  RESPONSE #100
    DisplayString(Myself,35849)  // ~The vampire is truly dead and the coffin reeks of carrion. There is nothing else you can do with it.~
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,12)
  Global("deadjoye","AR1513",1)
THEN
  RESPONSE #100
    DisplayString(Myself,35811)  // ~The vampire retreated to this coffin once you defeated it. If you have a wooden stake, you can try to kill it.~
    SetGlobal("Coffin1","AR1513",1)
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,12)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

IF
  Global("Coffin1","AR1513",2)
  Global("deadjoye","AR1513",1)
  Global("spawnjoye2afterstake","AR1513",0)
THEN
  RESPONSE #100
    SetGlobal("spawnjoye2afterstake","AR1513",1)
    Wait(2)
    CreateVisualEffect("SPGFLSH1",[708.1797])
    Wait(1)
    CreateCreature("ppjoye2",[708.1797],14)  // ~Dace Apparition~
    Wait(1)
    ActionOverride("ppjoye2",StartDialogNoSet([PC]))
END

