IF
  Dead("UnseeingEye")  // UnseeingEye
  GlobalGT("DestroyProphets","GLOBAL",0)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Detect([PC])
  See("PROPHET1")  // ~Prophet~
  !Dead("PROPHET1")  // ~Prophet~
THEN
  RESPONSE #100
    DisplayStringHead(Myself,8250)  // ~The false god is dead and his foul prophets will fall with him!~
    Wait(1)
    DisplayStringHead("PROPHET1",3524)  // ~The sightless shall rise again! Aaagh!~
    Attack("PROPHET1")
END

IF
  Detect([PC])
  See("PROPHET2")  // ~Prophet~
  !Dead("PROPHET2")  // ~Prophet~
THEN
  RESPONSE #100
    DisplayStringHead(Myself,8250)  // ~The false god is dead and his foul prophets will fall with him!~
    Wait(1)
    DisplayStringHead("PROPHET2",3524)  // ~The sightless shall rise again! Aaagh!~
    Attack("PROPHET2")
END

IF
  Detect([PC])
  See("PROPHET3")  // ~Prophet~
  !Dead("PROPHET3")  // ~Prophet~
THEN
  RESPONSE #100
    DisplayStringHead(Myself,8250)  // ~The false god is dead and his foul prophets will fall with him!~
    Wait(1)
    DisplayStringHead("PROPHET3",3524)  // ~The sightless shall rise again! Aaagh!~
    Attack("PROPHET3")
END

IF
  Detect([PC])
  See("PROPHET4")  // ~Prophet~
  !Dead("PROPHET4")  // ~Prophet~
THEN
  RESPONSE #100
    DisplayStringHead(Myself,8250)  // ~The false god is dead and his foul prophets will fall with him!~
    Wait(1)
    DisplayStringHead("PROPHET4",3524)  // ~The sightless shall rise again! Aaagh!~
    Attack("PROPHET4")
END

