IF
  Detect([PC])
  Global("SarSpirit","AR5006",0)
THEN
  RESPONSE #100
    ClearAllActions()
    StartCutSceneMode()
    ActionOverride(LastSeenBy(Myself),FaceObject("SpiritAppear1"))
    SetGlobal("SarSpirit","AR5006",1)
    MoveViewObject(Myself,INSTANT)
    CreateVisualEffectObject("SPDEATH3",Myself)
    Wait(1)
    SmallWait(10)
    CreateCreatureObject("SARSPIR",Myself,6,0,0)  // ~Prison Spirit~
    Wait(1)
    EndCutSceneMode()
END

