IF
  OnCreation()
  GlobalGT("RakCloud","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("RakCloud","GLOBAL",0)
END

IF
  See([GOODCUTOFF])
  Global("RakshasaChange","LOCALS",0)
THEN
  RESPONSE #30
    Polymorph(RAKSHASA)
    ChangeEnemyAlly(Myself,NEUTRAL)
    SetGlobal("RakshasaChange","LOCALS",1)
  RESPONSE #30
    Polymorph(RAKSHASA)
    SetGlobal("RakshasaChange","LOCALS",1)
  RESPONSE #30
    Polymorph(RAKSHASA)
    SetGlobal("RakshasaChange","LOCALS",1)
END

IF
  See([GOODCUTOFF])
  Global("RakshasaChange","LOCALS",1)
THEN
  RESPONSE #100
    Polymorph(RAKSHASA)
    ChangeEnemyAlly(Myself,ENEMY)
    SetGlobal("RakshasaChange","LOCALS",2)
END

IF
  See([GOODCUTOFF])
  Global("RakshasaChange","LOCALS",2)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
    Polymorph(RAKSHASA)
    ChangeEnemyAlly(Myself,NEUTRAL)
    SetGlobal("RakshasaChange","LOCALS",3)
END

IF
  See([GOODCUTOFF])
  Global("RakshasaChange","LOCALS",3)
THEN
  RESPONSE #100
    Polymorph(RAKSHASA)
    ChangeEnemyAlly(Myself,ENEMY)
    SetGlobal("RakshasaChange","LOCALS",3)
END

IF
  See([GOODCUTOFF])
  Global("RakshasaChange","LOCALS",4)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FIREBALL)
    SetGlobal("RakshasaChange","LOCALS",5)
END

IF
  See([GOODCUTOFF])
THEN
  RESPONSE #100
    AttackReevaluate([GOODCUTOFF],15)
END

