IF
  See([ENEMY.0.SAHUAGIN])
  Global("RebelsAttack","AR2300",1)
  GlobalTimerExpired("PrinceAttack","AR2300")
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  !See([ENEMY.0.SAHUAGIN])
  Global("RebelsAttack","AR2300",1)
  GlobalTimerExpired("PrinceAttack","AR2300")
  !Range(Player1,5)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  Global("RebelsAttack","AR2300",1)
  GlobalTimerExpired("PrinceAttack","AR2300")
  Dead("sahkng01")  // ~King Ixilthetocal~
  Dead("sahcpt01")  // ~Captain Alyittyl~
  NumDead("sahgrd01",2)
  Dead("sahgrd02")  // ~Royal Guard~
  Dead("sahbar03")  // ~Baron Thelokassyil~
THEN
  RESPONSE #100
    SetGlobal("RebelsAttack","AR2300",2)
    StartCutSceneMode()
    StartCutScene("cut41z")
END

