IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  GlobalTimerExpired("Run","LOCALS")
  Allegiance(Myself,NEUTRAL)
  AreaCheck("AR0507")
THEN
  RESPONSE #100
    Enemy()
END

IF
  GlobalTimerExpired("Run","LOCALS")
  Allegiance(Myself,NEUTRAL)
  AreaCheck("AR0500")
  GlobalGT("Waypoint","LOCALS",0)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See([PC])
  Global("CamRetiRun","GLOBAL",1)
  Global("Waypoint","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Waypoint","LOCALS",1)
    SetGlobalTimer("Run","LOCALS",5)
END

IF
  OR(3)
    Global("Waypoint","LOCALS",2)
    Global("Waypoint","LOCALS",4)
    Global("Waypoint","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("Waypoint","LOCALS",1)
    SetGlobalTimer("Run","LOCALS",9)
END

IF
  Global("Waypoint","LOCALS",1)
  !Range("Waypoint1",4)  // Waypoint1
  OR(2)
    Allegiance(Myself,NEUTRAL)
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    MoveToObject("Waypoint1")
END

IF
  Global("Waypoint","LOCALS",1)
  Range("Waypoint1",4)  // Waypoint1
  OR(2)
    Allegiance(Myself,NEUTRAL)
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    IncrementGlobal("Waypoint","LOCALS",1)
END

IF
  Global("Waypoint","LOCALS",3)
  !Range("Waypoint2",4)  // Waypoint2
  OR(2)
    Allegiance(Myself,NEUTRAL)
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    MoveToObject("Waypoint2")
END

IF
  Global("Waypoint","LOCALS",3)
  Range("Waypoint2",4)  // Waypoint2
  OR(2)
    Allegiance(Myself,NEUTRAL)
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    IncrementGlobal("Waypoint","LOCALS",1)
END

IF
  Global("Waypoint","LOCALS",5)
  !Range("Waypoint3",4)  // Waypoint3
  OR(2)
    Allegiance(Myself,NEUTRAL)
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    MoveToObject("Waypoint3")
END

IF
  Global("Waypoint","LOCALS",5)
  Range("Waypoint3",4)  // Waypoint3
  OR(2)
    Allegiance(Myself,NEUTRAL)
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    IncrementGlobal("Waypoint","LOCALS",1)
END

IF
  Global("Waypoint","LOCALS",7)
  !Range("Waypoint4",4)  // Waypoint4
  OR(2)
    Allegiance(Myself,NEUTRAL)
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    MoveToObject("Waypoint4")
END

IF
  Global("Waypoint","LOCALS",7)
  Range("Waypoint4",4)  // Waypoint4
  OR(2)
    Allegiance(Myself,NEUTRAL)
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    EscapeArea()
END

