IF
  Clicked([ANYONE])
  Range(LastTrigger,20)
  Global("BridgeOpen","AR0204",0)
  Global("SpawnGuardian","AR0204",0)
  !Exists("Riftcr01")  // ~Greater Ghoul~
  !Dead("Riftcr01")  // ~Greater Ghoul~
THEN
  RESPONSE #100
    SetGlobal("SpawnGuardian","AR0204",1)
    CreateCreature("Riftg01",[3385.2619],0)  // ~Guardian~
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,20)
  Global("BridgeOpen","AR0204",0)
  Global("SpawnGuardian","AR0204",0)
  !Exists("Riftcr02")  // ~Skeleton Warrior~
  !Dead("Riftcr02")  // ~Skeleton Warrior~
THEN
  RESPONSE #100
    SetGlobal("SpawnGuardian","AR0204",1)
    CreateCreature("Riftg01",[3385.2619],0)  // ~Guardian~
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,20)
  Global("BridgeOpen","AR0204",0)
  Global("SpawnGuardian","AR0204",0)
  !Exists("Riftcr03")  // ~Greater Mummy~
  !Dead("Riftcr03")  // ~Greater Mummy~
THEN
  RESPONSE #100
    SetGlobal("SpawnGuardian","AR0204",1)
    CreateCreature("Riftg01",[3385.2619],0)  // ~Guardian~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,20)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

IF
  True()
THEN
  RESPONSE #100
    Wait(1)
END

