IF
  RandomNum(3,1)
  See(NearestEnemyOf(Myself))
  GlobalGT("Prepare","LOCALS",0)
THEN
  RESPONSE #20
    ForceSpell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)
  RESPONSE #20
    ForceSpell(NearestEnemyOf(Myself),WIZARD_CHROMATIC_ORB)
  RESPONSE #20
    ForceSpell(NearestEnemyOf(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
  RESPONSE #20
    ForceSpell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)
  RESPONSE #20
    ForceSpell(NearestEnemyOf(Myself),WIZARD_FLESH_TO_STONE)
END

