IF
  Opened([ANYONE])
  Global("RangerHere","AR1107",0)
THEN
  RESPONSE #100
    SetGlobal("RangerHere","AR1107",1)
    SetGlobalTimer("MoreRangerHeal","GLOBAL",ONE_DAY)
    SetGlobalTimer("MoreRangerHeal2","GLOBAL",THREE_DAYS)
END

IF
  GlobalTimerExpired("MoreRangerHeal","GLOBAL")
THEN
  RESPONSE #100
    CreateItem("POTN08",0,0,0)  // ~Potion of Healing~
    SetGlobalTimer("MoreRangerHeal","GLOBAL",TWO_DAYS)
END

IF
  GlobalTimerExpired("MoreRangerHeal2","GLOBAL")
THEN
  RESPONSE #100
    CreateItem("POTN52",0,0,0)  // ~Potion of Extra Healing~
    SetGlobalTimer("MoreRangerHeal2","GLOBAL",SEVEN_DAYS)
END

