IF
  IsOverMe([GOODCUTOFF])
  CheckStatLT(LastTrigger,15,DEX)
THEN
  RESPONSE #50
    ForceSpell(LastTrigger,TRAP_HALLWAY_SPIKES)
  RESPONSE #30
    ForceSpell(LastTrigger,TRAP_HALLWAY_SPIKES)
    ActionOverride(LastTrigger,PlayDead(30))
    ForceSpell(LastTrigger,TRAP_HALLWAY_SPIKES)
  RESPONSE #20
    Continue()
END

IF
  IsOverMe([GOODCUTOFF])
  CheckStatGT(LastTrigger,14,DEX)
THEN
  RESPONSE #50
    ForceSpell(LastTrigger,TRAP_HALLWAY_SPIKES)
  RESPONSE #50
    Continue()
END

