IF
  OR(2)
    GlobalGT("villynatyjob","GLOBAL",0)
    Dead("sahpr2")  // ~Prince Villynaty~
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Detect([PC])
  Range([PC],15)
  Global("Shout","LOCALS",0)
THEN
  RESPONSE #30
    SetGlobal("Shout","LOCALS",1)
    DisplayStringHead(Myself,53784)  // ~Surfacers! Feel our wrath!~
  RESPONSE #30
    SetGlobal("Shout","LOCALS",1)
    DisplayStringHead(Myself,53785)  // ~The Shark God take you!~
  RESPONSE #30
    SetGlobal("Shout","LOCALS",1)
    DisplayStringHead(Myself,53786)  // ~I shall taste your blood, manlings!~
END

IF
  See([PC])
  Range([PC],5)
THEN
  RESPONSE #100
    Attack(LastSeenBy(Myself))
END

IF
  Detect([PC])
  See([0.0.0.0.20])
THEN
  RESPONSE #100
    Attack(LastSeenBy(Myself))
END

