IF
  !Range("rway4",2)  // rway4
THEN
  RESPONSE #100
    MoveToObject("rway4")
    Continue()
END

IF
  Range("rway4",2)  // rway4
THEN
  RESPONSE #5
    DisplayStringHead(Myself,73813)  // ~There are just too many of them!~
  RESPONSE #10
    DisplayStringHead(Myself,73814)  // ~They are too strong!~
  RESPONSE #5
    DisplayStringHead(Myself,73815)  // ~We must keep fighting!~
  RESPONSE #80
    AttackReevaluate("sarfakie",45)
END

