IF
  Global("UnlockDoor","LOCALS",1)
  Allegiance(Myself,NEUTRAL)
  !Range("DOOR06",4)  // DOOR06
THEN
  RESPONSE #100
    MoveToObject("DOOR06")
END

IF
  Global("UnlockDoor","LOCALS",1)
  Allegiance(Myself,NEUTRAL)
  Range("DOOR06",4)  // DOOR06
THEN
  RESPONSE #100
    SetGlobal("UnlockDoor","LOCALS",2)
    Unlock("DOOR06")
    OpenDoor("DOOR06")
END

IF
  Allegiance(Myself,NEUTRAL)
  Global("UnlockDoor","LOCALS",2)
THEN
  RESPONSE #100
    MoveToPoint([838.571])
    Face(0)
    SetGlobal("UnlockDoor","LOCALS",3)
END

IF
  Global("ArdicSaved","GLOBAL",1)
THEN
  RESPONSE #100
    DestroySelf()
END

