IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    MakeUnselectable(1)
    ActionOverride(Player2,MakeUnselectable(1))
    ActionOverride(Player3,MakeUnselectable(1))
    ActionOverride(Player4,MakeUnselectable(1))
    ActionOverride(Player5,MakeUnselectable(1))
    ActionOverride(Player6,MakeUnselectable(1))
    SetCutSceneLite(FALSE)
    FadeToColor([30.0],0)
    Wait(2)
    LeaveAreaLUAPanic("AR3019","",[3151.1004],0)
    LeaveAreaLUA("AR3019","",[3151.1004],0)
    ActionOverride(Player2,LeaveAreaLUA("AR3019","",[3151.1004],0))
    ActionOverride(Player3,LeaveAreaLUA("AR3019","",[3151.1004],0))
    ActionOverride(Player4,LeaveAreaLUA("AR3019","",[3151.1004],0))
    ActionOverride(Player5,LeaveAreaLUA("AR3019","",[3151.1004],0))
    ActionOverride(Player6,LeaveAreaLUA("AR3019","",[3151.1004],0))
    Wait(2)
    MultiPlayerSync()
    FadeFromColor([30.0],0)
    Wait(1)
    GiveItemCreate("PLOT05C",Player1,0,0,0)  // ~Spirit Key~
    TriggerActivation("SpiritPortal",FALSE)
    EndCutSceneMode()
END

