IF
  Entered([ANYONE])
  Global("OpenSecretDoor","AR0701",0)
THEN
  RESPONSE #100
    SetGlobal("OpenSecretDoor","AR0701",1)
    DisplayStringHead(LastTrigger,2808)  // ~A powerful psychic force lashes out at you, preventing you from moving.  From the look at all the dead adventurers on the ground, whatever lies ahead seems extremely powerful and dangerous.~
    ForceSpell(LastTrigger,NOSAVE_PSIONIC_BLAST)
    Unlock("Door02")
    OpenDoor("Door02")
END

