IF
  HPPercentLT(Myself,50)
  Global("Hurt","LOCALS",0)
  See([PC])
THEN
  RESPONSE #100
    Wait(2)
    StartDialogNoSet([PC])
END

IF
  Global("RiatavinFight","GLOBAL",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  OR(2)
    AttackedBy([GOODCUTOFF],DEFAULT)
    HitBy([GOODCUTOFF],CRUSHING)
  Global("RiatavinFight","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("RiatavinFight","GLOBAL",1)
    Enemy()
END

