IF
  InParty("Anomen")  // Anomen
  See("Anomen")  // Anomen
  !Dead("Anomen")  // Anomen
  !StateCheck("Anomen",STATE_SLEEPING)  // Anomen
  Global("AnomenDecide","GLOBAL",2)
  Global("SaerkFightStart1","AR0505",0)
  NumTimesTalkedToGT(0)
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
END

IF
  GlobalGT("AnomenSaerk","GLOBAL",0)
THEN
  RESPONSE #100
    Kill(Myself)
END

IF
  GlobalTimerExpired("SaerkGuards","GLOBAL")
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

