IF
  See([PC])
  Range([PC],10)
  Global("SpawnHabib","GLOBAL",5)
THEN
  RESPONSE #100
    ClearAllActions()
    SetInterrupt(FALSE)
    DialogueInterrupt(FALSE)
    CreateCreature("HABIB2",[155.301],10)  // ~Habib~
    SetGlobal("SpawnHabib","GLOBAL",6)
    ActionOverride("habib",DisplayStringHead(Myself,41825))  // ~My name is Habib!~
    ActionOverride("habib",AttackOneRound(SixthNearest([PC])))
    ActionOverride("habib",SetGlobal("SpawnHabib","GLOBAL",7))
    ActionOverride("habib",EscapeArea())
    Wait(1)
    DialogueInterrupt(TRUE)
    SetInterrupt(TRUE)
END

IF
  See([PC])
  Global("SpawnHabib","GLOBAL",7)
THEN
  RESPONSE #100
    SetGlobal("SpawnHabib","GLOBAL",8)
    StartDialogNoSet([PC])
END

