IF
  Global("MONKSPAWNEDSMUGGLERPLOT","GLOBAL",2)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("Enclave","GLOBAL",2)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("ThfArrest","GLOBAL",1)
  Class(Myself,MONK)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    SetGlobal("ThfArrest","GLOBAL",0)
    SetGlobal("SMUGGLERPLOT","GLOBAL",1)
    Shout(ALERT)
END

IF
  Global("SMUGGLERPLOT","GLOBAL",1)
  !Allegiance(Myself,ENEMY)
  Class(Myself,MONK)
THEN
  RESPONSE #100
    Enemy()
END

IF
  GlobalTimerExpired("ThfMonksGone","GLOBAL")
  OR(2)
    Class(Myself,MAGE_THIEF)
    Class(Myself,MONK)
  !Detect([NEUTRAL.0.0.THIEF])
  Global("ThfArrest","GLOBAL",1)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  GlobalTimerExpired("ThievesScoot","AR5504")
  OR(2)
    Class(Myself,MAGE_THIEF)
    Class(Myself,THIEF)
  !Global("Enclave","GLOBAL",2)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Global("ThfArrest","GLOBAL",1)
  Class(Myself,MONK)
  Detect([NEUTRAL.0.0.THIEF])
  RandomNum(3,1)
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
END

IF
  Global("ThfArrest","GLOBAL",1)
  Class(Myself,THIEF)
  Range([NEUTRAL.0.0.MONK],6)
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  See([GOODCUTOFF])
  !AreaCheck("AR5500")
  !Allegiance(Myself,ENEMY)
  Class(Myself,THIEF)
  OR(2)
    GlobalTimerNotExpired("ThievesScoot","AR5504")
    Global("ThfArrest","GLOBAL",1)
THEN
  RESPONSE #100
    RandomWalkContinuous()
END

IF
  See([GOODCUTOFF])
  !AreaCheck("AR5500")
  !Allegiance(Myself,ENEMY)
  Class(Myself,THIEF)
  !Global("ThfArrest","GLOBAL",1)
  CombatCounter(0)
THEN
  RESPONSE #100
    RandomWalk()
END

