IF
  IsOverMe([ANYONE])
  Global("BridgeTrap","AR1401",0)
THEN
  RESPONSE #100
    SetGlobal("BridgeTrap","AR1401",1)
    ForceSpellPoint([1421.1294],SUMMON_SHADOW_WOLF)
    CreateCreature("SHAWOL01",[1403.1325],14)  // ~Shade Wolf~
    ForceSpellPoint([1754.1471],SUMMON_SHADOW)
    CreateCreature("SHADOW01",[1765.1416],7)  // ~Shadow~
    CreateCreature("SHADOW01",[1736.1444],8)  // ~Shadow~
END

