IF
  Die()
THEN
  RESPONSE #100
    ReallyForceSpellDead(Myself,ILLUSION_DEATH)
    Wait(1)
    DestroySelf()
END

IF
  GlobalGT("TerminselSpawn","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("TalkedToSpectres","GLOBAL",1)
  !PartyHasItem("MISC5E")  // ~Harper Amulet~
  Global("HarpistsAttack","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("HarpistsAttack","LOCALS",1)
END

IF
  AttackedBy([ANYONE],DEFAULT)
  PartyHasItem("MISC5E")  // ~Harper Amulet~
  Global("BadHarper","AR0309",0)
THEN
  RESPONSE #100
    SetGlobal("BadHarper","AR0309",1)
END

IF
  OR(2)
    Global("HarpistsAttack","LOCALS",1)
    Global("BadHarper","AR0309",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Allegiance(Myself,ENEMY)
  PartyHasItem("MISC5E")  // ~Harper Amulet~
  Global("BadHarper","AR0309",0)
  Global("HarperOKNow","LOCALS",0)
  !Dead("spech1")  // spech1
  !Dead("spech2")  // spech2
  !Dead("spech3")  // spech3
THEN
  RESPONSE #100
    SetGlobal("HarpistsAttack","LOCALS",0)
    SetGlobal("TalkedToSpectres","GLOBAL",0)
    SetGlobal("HarperOKNow","LOCALS",1)
    ChangeEnemyAlly(Myself,NEUTRAL)
    SetNumTimesTalkedTo(0)
END

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  HaveSpell(HARPER_DEATH_SONG)
THEN
  RESPONSE #30
    Spell(NearestEnemyOf(Myself),HARPER_DEATH_SONG)
    Continue()
  RESPONSE #70
    Continue()
END

