IF
  XPLT(Player1,400000)
  Entered([ANYONE])
THEN
  RESPONSE #100
    CreateCreature("vampim01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vampim01",[-1.-1],0)  // ~Vampire~
END

IF
  XPGT(Player1,399999)
  XPLT(Player1,1000000)
  Entered([ANYONE])
THEN
  RESPONSE #100
    CreateCreature("vampim01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vampim01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vampim01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamold01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamver01",[-1.-1],0)  // ~Vampire~
END

IF
  XPGT(Player1,999999)
  XPLT(Player1,2000000)
  Entered([ANYONE])
THEN
  RESPONSE #100
    CreateCreature("vampim01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vampim01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamold01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamold01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamver01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamanc01",[-1.-1],0)  // ~Vampire~
END

IF
  XPGT(Player1,1999999)
  Entered([ANYONE])
THEN
  RESPONSE #100
    CreateCreature("vamver01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamver01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamver01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamanc01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamanc01",[-1.-1],0)  // ~Vampire~
    CreateCreature("vamemi01",[-1.-1],0)  // ~Vampire~
END

