IF
  XPLT(Player1,400000)
  Entered([ANYONE])
THEN
  RESPONSE #100
    CreateCreature("mindfl01",[-1.-1],0)  // ~Mind Flayer~
END

IF
  XPGT(Player1,399999)
  XPLT(Player1,1000000)
  Entered([ANYONE])
THEN
  RESPONSE #100
    CreateCreature("mindfl01",[-1.-1],0)  // ~Mind Flayer~
    CreateCreature("mindfl01",[-1.-1],0)  // ~Mind Flayer~
END

IF
  XPGT(Player1,999999)
  XPLT(Player1,2000000)
  Entered([ANYONE])
THEN
  RESPONSE #100
    CreateCreature("mindfl01",[-1.-1],0)  // ~Mind Flayer~
    CreateCreature("mindfl01",[-1.-1],0)  // ~Mind Flayer~
    CreateCreature("mindul01",[-1.-1],0)  // ~Ulitharid~
    CreateCreature("umbhul01",[-1.-1],0)  // ~Umber Hulk~
END

IF
  XPGT(Player1,1999999)
  Entered([ANYONE])
THEN
  RESPONSE #100
    CreateCreature("mindfl01",[-1.-1],0)  // ~Mind Flayer~
    CreateCreature("mindul01",[-1.-1],0)  // ~Ulitharid~
    CreateCreature("mindul01",[-1.-1],0)  // ~Ulitharid~
    CreateCreature("mindul01",[-1.-1],0)  // ~Ulitharid~
    CreateCreature("umbhul01",[-1.-1],0)  // ~Umber Hulk~
    CreateCreature("umbhul01",[-1.-1],0)  // ~Umber Hulk~
END

