IF
  See([PC])
  !Allegiance(Myself,ENEMY)
  CombatCounter(0)
THEN
  RESPONSE #30
    DisplayStringHead(Myself,4369)  // ~Don't you try anything stupid.  I'm watching you.~
    Wait(200)
  RESPONSE #30
    DisplayStringHead(Myself,4372)  // ~Don't even think about trying to steal something.~
    Wait(200)
  RESPONSE #30
    DisplayStringHead(Myself,4372)  // ~Don't even think about trying to steal something.~
    Wait(200)
END

