IF
  Clicked([ANYONE])
  Range(LastTrigger,15)
THEN
  RESPONSE #100
    DisplayString(Myself,71133)  // ~There is an inscription chiseled clearly into the pillar of rock:"WITH MY LAST BREATH I PLACE MY GREATEST PRIZE FOREVER BEYOND THE REACH OF THE EVIL ALL AROUND ME"~
    TriggerActivation("STONE",TRUE)
    TriggerActivation(Myself,FALSE)
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,15)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

