IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Heard([ANYONE],100)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Shout(100)
    EscapeArea()
END

IF
  NumDead("sutroll",2)
  Dead("suelfw5")  // ~Elven Warrior~
  Dead("suelfw6")  // ~Elven Warrior~
  Dead("suelfw12")  // ~Elven Battle Mage~
  Global("Scene3","AR2800",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("Scene3","AR2800",2)
    DisplayStringHead(Myself,4201)  // ~Move out! The battle is far from over!~
    Wait(1)
    EscapeArea()
END

IF
  NumDead("sutroll",2)
  OR(3)
    !Dead("suelfw5")  // ~Elven Warrior~
    !Dead("suelfw6")  // ~Elven Warrior~
    !Dead("suelfw12")  // ~Elven Battle Mage~
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    Wait(1)
    EscapeArea()
END

IF
  See([ENEMY])
  Global("Scene3","AR2800",1)
THEN
  RESPONSE #100
    AttackReevaluate([ENEMY],45)
END

