IF
  HPLT(Myself,5)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,3035)  // ~With the death of your Djinni, the summoning ring vanishes.~
    TakePartyItem("ring26")
    DestroyItem("ring26")  // ~Ring of Djinni Summoning~
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
  StateCheck(Myself,STATE_INVISIBLE)
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
  See(NearestEnemyOf(Myself))
  Delay(15)
THEN
  RESPONSE #100
    ForceSpell(Myself,WIZARD_INVISIBILITY)
END

