IF
  Clicked([ANYONE])
  Range(LastTrigger,15)
  Global("SawInscription","AR3008",0)
THEN
  RESPONSE #100
    SetGlobal("SawInscription","AR3008",1)
    DisplayStringHead(Myself,71133)  // ~There is an inscription chiseled clearly into the pillar of rock:"WITH MY LAST BREATH I PLACE MY GREATEST PRIZE FOREVER BEYOND THE REACH OF THE EVIL ALL AROUND ME"~
END

IF
  Clicked([GOODCUTOFF])
  Range(LastTrigger,15)
  !Alignment(LastTrigger,LAWFUL_GOOD)
  !Alignment(LastTrigger,MASK_EVIL)
  Global("GotAvenger","GLOBAL",0)
  Global("SawInscription","AR3008",1)
THEN
  RESPONSE #100
    DisplayStringHead(LastTrigger,70419)  // ~The rock is solid.  You can do nothing to it.~
END

IF
  Clicked([GOODCUTOFF])
  Range(LastTrigger,15)
  Alignment(LastTrigger,LAWFUL_GOOD)
  Global("GotAvenger","GLOBAL",0)
  Global("SawInscription","AR3008",1)
THEN
  RESPONSE #100
    SetGlobal("GotAvenger","GLOBAL",1)
    CreateVisualEffectObject("SPHOLY",LastTrigger)
    DisplayStringHead(LastTrigger,70418)  // ~Your hand sinks into the stone column as if it were air, the surface rippling around it.  A moment later, your hand closes around a solid object and quickly pulls it out.~
    GiveItemCreate("sw1h64",LastTrigger,1,0,0)  // ~Purifier +4~
END

IF
  Clicked([GOODCUTOFF])
  Range(LastTrigger,15)
  Alignment(LastTrigger,MASK_EVIL)
  Global("GotAvenger","GLOBAL",0)
  Global("SawInscription","AR3008",1)
THEN
  RESPONSE #100
    DisplayStringHead(LastTrigger,70696)  // ~The stone emanates a feeling of 'goodness' which recoils at your touch, sending a wave of magical energy sweeping through the entire room...~
    CreateVisualEffectObject("SPPOWWRD",LastTrigger)
    ForceSpell(LastTrigger,WIZARD_METEOR_SWARM)
END

IF
  Clicked([GOODCUTOFF])
  Range(LastTrigger,15)
  Global("GotAvenger","GLOBAL",1)
THEN
  RESPONSE #100
    DisplayStringHead(LastTrigger,70419)  // ~The rock is solid.  You can do nothing to it.~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,15)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

