IF
  AttackedBy([ANYONE],DEFAULT)
  !Global("TalkedToTanally1","GLOBAL",3)
  Global("Attacked","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Attacked","LOCALS",1)
    DialogueInterrupt(TRUE)
    StartDialogNoSet([PC])
END

IF
  PartyHasItem("BOOK59")  // ~History of the Zhentarim~
  Global("BoughtBook","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("BoughtBook","LOCALS",1)
    StartDialogNoSet([PC])
END

