IF
  See([GOODCUTOFF])
  !AreaCheck("AR5201")
  Global("SaidPiece","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SaidPiece","LOCALS",1)
    DisplayStringHead(Myself,70663)  // ~Hsss!  If we baatezu are to be trapped forever in this maze, than we shall feast on the hearts of mortals!!~
    Continue()
END

IF
  See([GOODCUTOFF])
  Global("hostile","LOCALS",0)
  Global("BatEnemy","GLOBAL",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    SetGlobal("hostile","LOCALS",1)
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !GlobalTimerNotExpired("DemonFear","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("DemonFear","LOCALS",12)
    ForceSpell(NearestEnemyOf(Myself),DEMON_FEAR)
END

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !GlobalTimerNotExpired("DemonInvisibility","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("DemonInvisibility","LOCALS",6)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END

IF
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("PitSpell","LOCALS")
  !AreaCheck("AR3004")
THEN
  RESPONSE #60
    IncrementGlobal("Prep","LOCALS",1)
    SetGlobalTimer("PitSpell","LOCALS",6)
    ForceSpell(NearestEnemyOf(Myself),DEATHKNIGHT_FIREBALL)
  RESPONSE #20
    IncrementGlobal("Prep","LOCALS",1)
    SetGlobalTimer("PitSpell","LOCALS",6)
    ForceSpell(NearestEnemyOf(Myself),WIZARD_HOLD_PERSON)
  RESPONSE #20
    IncrementGlobal("Prep","LOCALS",1)
    SetGlobalTimer("PitSpell","LOCALS",6)
    ForceSpell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)
END

IF
  See([0.0.0.TANARI])
THEN
  RESPONSE #100
    AttackReevaluate([0.0.0.TANARI],30)
END

IF
  See(NearestEnemyOf(Myself))
  !AreaCheck("AR3004")
  OR(3)
    GlobalGT("Prep","LOCALS",3)
    Range(NearestEnemyOf(Myself),10)
    HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  See(NearestEnemyOf(Myself))
  AreaCheck("AR3004")
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

