IF
  Allegiance(Myself,ENEMY)
  Global("TiefFight","AR3005",0)
THEN
  RESPONSE #100
    SetGlobal("TiefFight","AR3005",1)
END

IF
  !Allegiance(Myself,ENEMY)
  Global("TiefFight","AR3005",1)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
  Global("advanced","LOCALS",0)
THEN
  RESPONSE #50
    SpellNoDec(Myself,ROGUE_EVASION)
    IncrementGlobal("advanced","LOCALS",1)
    Continue()
  RESPONSE #50
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Global("advanced","LOCALS",1)
THEN
  RESPONSE #50
    SpellNoDec(Myself,ROGUE_AVOID_DEATH)
    IncrementGlobal("advanced","LOCALS",1)
    Continue()
  RESPONSE #50
    Continue()
END

