IF
  See([PC])
  See([NEUTRAL])
  !Dead("astSeenBy(Myself))")  // astSeenBy(Myself))
  Global("warn","LOCALS",0)
THEN
  RESPONSE #80
    DisplayStringHead(Myself,61287)  // ~An alarm sounds throughout the temple.~
    SetGlobal("TempleShout0902","GLOBAL",1)
    SetGlobal("warn","LOCALS",1)
END

IF
  OR(2)
    !See([NOTGOOD])
    Global("warn","LOCALS",1)
THEN
  RESPONSE #100
    Wait(5)
    DestroySelf()
END

