IF
  Global("RomancePartFour","GLOBAL",0)
  !See("Anomen")  // Anomen
  InParty("Anomen")  // Anomen
THEN
  RESPONSE #100
    MoveToObject("Anomen")
END

IF
  Global("SaerkPlot","GLOBAL",0)
  !Dead("cor")  // ~Cor Delryn~
  !See("Anomen")  // Anomen
  InParty("Anomen")  // Anomen
THEN
  RESPONSE #100
    MoveToObject("Anomen")
END

IF
  Global("SaerkPlot","GLOBAL",0)
  !Dead("cor")  // ~Cor Delryn~
  See("Anomen")  // Anomen
  InParty("Anomen")  // Anomen
THEN
  RESPONSE #100
    Dialog("Anomen")
END

IF
  !InParty("Anomen")  // Anomen
THEN
  RESPONSE #100
    EscapeArea()
END

