IF
  Clicked([ANYONE])
  Range(LastTrigger,9)
  Global("TombClose","AR0802",0)
THEN
  RESPONSE #100
    DisplayString(Myself,36206)  // ~You may open this sarcophagus if you wish.~
    SetGlobal("TombClose","AR0802",1)
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,9)
  Global("TombClose","AR0802",1)
THEN
  RESPONSE #100
    DisplayString(Myself,36207)  // ~An undead thing pulls itself from the sarcophagus, mumbling angry words in some alien tongue. The thing turns its dead eyes towards you as you recoil in horror. ~
    CreateCreature("GRTOMB01",[813.1371],0)  // ~Skeleton Warrior~
    SetGlobal("TombClose","AR0802",2)
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,9)
  Global("TombClose","AR0802",2)
THEN
  RESPONSE #100
    DisplayString(Myself,36208)  // ~There is nothing else you can do with this sarcophagus.~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,9)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

