IF
  Clicked([ANYONE])
  Range(LastTrigger,10)
  PartyHasItem("MISCBF")  // ~Jae'llat Wardstone~
THEN
  RESPONSE #100
    TakePartyItem("MISCBF")
    DisplayString(Myself,57372)  // ~The wardstone glows briefly and disappears. You enter the momentary break in the wards.~
    StartCutSceneMode()
    Wait(2)
    FadeToColor([20.0],0)
    Wait(1)
    ActionOverride(Player1,LeaveAreaLUAPanic("AR2209","",[461.1112],8))
    ActionOverride(Player1,LeaveAreaLUA("AR2209","",[461.1112],8))
    ActionOverride(Player2,LeaveAreaLUA("AR2209","",[502.1125],8))
    ActionOverride(Player3,LeaveAreaLUA("AR2209","",[457.1157],8))
    ActionOverride(Player4,LeaveAreaLUA("AR2209","",[502.1169],8))
    ActionOverride(Player5,LeaveAreaLUA("AR2209","",[459.1203],8))
    ActionOverride(Player6,LeaveAreaLUA("AR2209","",[503.1217],8))
    MultiPlayerSync()
    EndCutSceneMode()
    FadeFromColor([20.0],0)
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,10)
  !PartyHasItem("MISCBF")  // ~Jae'llat Wardstone~
THEN
  RESPONSE #100
    DisplayString(Myself,57409)  // ~The door is magically warded. To step through it would mean instant death. You'll need to find a wardstone if you wish to enter.~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,10)
THEN
  RESPONSE #100
    DisplayString(Myself,61363)  // ~To examine this doorway, move closer.~
END

