IF
  TimeGT(5)
  TimeLT(DUSK_END)
  Global("Deactivated","LOCALS",0)
  !See([PC])
THEN
  RESPONSE #100
    SetGlobal("Deactivated","LOCALS",1)
    Deactivate(Myself)
END

IF
  TimeGT(5)
  TimeLT(DUSK_END)
  Global("Deactivated","LOCALS",1)
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    TimeLT(DAWN_START)
    TimeGT(DUSK_START)
  Global("Deactivated","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Deactivated","LOCALS",0)
    Activate(Myself)
END

