IF
  Entered([ANYONE])
THEN
  RESPONSE #20
    CreateCreature("GHASTD",[232.1379],0)  // GHASTD
    Wait(30)
  RESPONSE #20
    CreateCreature("GHASTD",[328.1446],0)  // GHASTD
    Wait(30)
  RESPONSE #20
    CreateCreature("GHASTD",[419.1509],0)  // GHASTD
    Wait(30)
  RESPONSE #20
    CreateCreature("GHASTD",[508.1574],0)  // GHASTD
    Wait(30)
  RESPONSE #20
    CreateCreature("GHASTD",[604.1638],0)  // GHASTD
    Wait(30)
  RESPONSE #20
    CreateCreature("GHASTD",[695.1698],0)  // GHASTD
    Wait(30)
END

