IF
  WalkedToTrigger([ANYONE])
  Global("WestTableClicked","AR5509",0)
  !GlobalTimerNotExpired("WestTableTimer","AR5509")
THEN
  RESPONSE #100
    ClearAllActions()
    SetGlobalTimer("WestTableTimer","AR5509",5)
    SetGlobal("WestTableClicked","AR5509",1)
    DisplayStringNoName(Myself,72141)  // ~The top of the table is covered with flaming shapes, it looks as if you might be able to turn the table.~
END

IF
  WalkedToTrigger([ANYONE])
  Global("WestTableClicked","AR5509",1)
  !GlobalTimerNotExpired("WestTableTimer","AR5509")
THEN
  RESPONSE #100
    ClearAllActions()
    StartCutSceneMode()
    DisplayStringNoName(Myself,73852)  // ~You turn the table, disabling some of the traps on the platforms above.~
    SetGlobalTimer("WestTableTimer","AR5509",5)
    SetGlobal("WestTableClicked","AR5509",2)
    CreateCreature("INVISABO",[727.596],0)  // <Invalid Strref -1>
    ReallyForceSpellRES("jwscorch","invisabo")  // <Invalid Strref -1>
    Wait(2)
    CreateCreature("ELFIRG01",[738.520],0)  // ~Greater Fire Elemental~
    CreateCreature("ELFIRG01",[844.599],4)  // ~Greater Fire Elemental~
    CreateCreature("ELFIRG01",[724.672],8)  // ~Greater Fire Elemental~
    CreateCreature("ELFIRG01",[597.596],12)  // ~Greater Fire Elemental~
    RemoveTraps("DOOR01")
    RemoveTraps("DOOR02")
    ActionOverride("invisabo",DestroySelf())
    EndCutSceneMode()
END

IF
  WalkedToTrigger([ANYONE])
  Global("WestTableClicked","AR5509",2)
  !GlobalTimerNotExpired("WestTableTimer","AR5509")
THEN
  RESPONSE #100
    ClearAllActions()
    SetGlobalTimer("WestTableTimer","AR5509",5)
    DisplayStringNoName(Myself,70896)  // ~There is nothing more that you can do with this.~
END

IF
  WalkedToTrigger([ANYONE])
  GlobalTimerNotExpired("WestTableTimer","AR5509")
THEN
  RESPONSE #100
    ClearActions(LastTrigger)
END

