IF
  Global("BeholderBehavior","LOCALS",0)
  See([0.0.MIND_FLAYER])
  Detect([GOODCUTOFF])
  HPGT(Myself,65)
THEN
  RESPONSE #100
    FaceObject([0.0.MIND_FLAYER])
    ReallyForceSpell([0.0.MIND_FLAYER],BEHOLDER_CHARM_PERSON)
    Wait(2)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([0.0.MIND_FLAYER])
  Detect([GOODCUTOFF])
  HPGT(Myself,55)
THEN
  RESPONSE #100
    FaceObject(SecondNearest([0.0.MIND_FLAYER]))
    ReallyForceSpell(SecondNearest([0.0.MIND_FLAYER]),BEHOLDER_FEAR)
    Wait(2)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([0.0.MIND_FLAYER])
  Detect([GOODCUTOFF])
  HPGT(Myself,45)
THEN
  RESPONSE #100
    FaceObject([0.0.MIND_FLAYER])
    ReallyForceSpell([0.0.MIND_FLAYER],BEHOLDER_PARALYZATION)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  See([0.0.MIND_FLAYER])
  Detect([GOODCUTOFF])
  HPGT(Myself,25)
THEN
  RESPONSE #100
    FaceObject(ThirdNearest([0.0.MIND_FLAYER]))
    ReallyForceSpell(ThirdNearest([0.0.MIND_FLAYER]),BEHOLDER_FLESH_TO_STONE)
    Wait(2)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",0)
  Detect([GOODCUTOFF])
  See([0.0.MIND_FLAYER])
THEN
  RESPONSE #100
    FaceObject([0.0.MIND_FLAYER])
    ReallyForceSpell([0.0.MIND_FLAYER],BEHOLDER_ANTIMAGIC_RAY)
    SetGlobal("BeholderBehavior","LOCALS",1)
    Wait(2)
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([0.0.MIND_FLAYER])
  Detect([GOODCUTOFF])
  HPGT(Myself,15)
THEN
  RESPONSE #100
    FaceObject([0.0.MIND_FLAYER])
    ReallyForceSpell([0.0.MIND_FLAYER],BEHOLDER_DOMINATION)
    Wait(2)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([0.0.MIND_FLAYER])
  Detect([GOODCUTOFF])
  HPGT(Myself,35)
THEN
  RESPONSE #100
    FaceObject(SecondNearest([0.0.MIND_FLAYER]))
    ReallyForceSpell(SecondNearest([0.0.MIND_FLAYER]),BEHOLDER_SLOW)
    Wait(2)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([0.0.MIND_FLAYER])
  Detect([GOODCUTOFF])
  HPGT(Myself,5)
THEN
  RESPONSE #100
    FaceObject(ThirdNearest([0.0.MIND_FLAYER]))
    ReallyForceSpell(ThirdNearest([0.0.MIND_FLAYER]),BEHOLDER_CAUSE_SERIOUS_WOUNDS)
    Wait(2)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  See([0.0.MIND_FLAYER])
  Detect([GOODCUTOFF])
  !See(LeastDamagedOf(Myself))
THEN
  RESPONSE #100
    FaceObject([0.0.MIND_FLAYER])
    ReallyForceSpell([0.0.MIND_FLAYER],BEHOLDER_DEATH_RAY)
    Continue()
END

IF
  Global("BeholderBehavior","LOCALS",1)
  Detect([GOODCUTOFF])
  See([0.0.MIND_FLAYER])
THEN
  RESPONSE #100
    FaceObject([0.0.MIND_FLAYER])
    ReallyForceSpell([0.0.MIND_FLAYER],BEHOLDER_ANTIMAGIC_RAY)
    SetGlobal("BeholderBehavior","LOCALS",0)
    Wait(2)
END

