IF
  Dead("udmaster")  // ~The Master Brain~
  Global("mindSlaveFreed","GLOBAL",1)
  Global("moved","LOCALS",0)
THEN
  RESPONSE #100
    JumpToPoint([3797.1017])
    SetGlobal("moved","LOCALS",1)
END

IF
  Dead("udmaster")  // ~The Master Brain~
  Global("mindSlaveFreed","GLOBAL",0)
THEN
  RESPONSE #100
    Kill(Myself)
END

IF
  OR(2)
    Allegiance(Myself,ENEMY)
    GlobalGT("ByeByeSlaves","AR2400",0)
THEN
  RESPONSE #100
    EscapeAreaObject("Tran2100")
END

