IF
  Clicked([ANYONE])
  Range(LastTrigger,10)
  Global("pool1","AR2402",0)
THEN
  RESPONSE #100
    DisplayString(Myself,54824)  // ~Tainted tadpoles swim in this pool.  You may take some, if you wish.~
    SetGlobal("pool1","AR2402",1)
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,10)
  Global("pool1","AR2402",1)
THEN
  RESPONSE #100
    DisplayString(Myself,54825)  // ~You take the tainted tadpoles.~
    GiveItemCreate("misc9z",LastTrigger,0,0,0)  // ~Corrupted Tadpoles~
    SetGlobal("pool1","AR2402",0)
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,10)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END

