IF
  OR(2)
    GlobalGT("OgronAttack","GLOBAL",0)
    GlobalTimerExpired("KidsRunOff","GLOBAL")
  AreaCheck("AR1106")
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  Global("firstUse","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)
    SetGlobal("firstUse","LOCALS",1)
END

IF
  Delay(12)
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),HULK_CONFUSION)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),5)
END

