IF
  Global("SummonDryads","AR1200",1)
THEN
  RESPONSE #100
    SetGlobal("SummonDryads","AR1200",2)
    StartCutSceneMode()
    StartCutScene("Cut23a")
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Global("VaelasaHostile","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("VaelasaHostile","GLOBAL",1)
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_DIRE_CHARM)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_DIRE_CHARM)
END

