IF
  Delay(10)
  See("Edwin")  // Edwin
  !Dead("Edwin")  // Edwin
  !StateCheck(Myself,STATE_INVISIBLE)
THEN
  RESPONSE #100
    Hide()
    Continue()
END

IF
  See("Edwin")  // Edwin
  !Dead("Edwin")  // Edwin
  HaveSpell(CLERIC_ARMOR_OF_FAITH)
  CheckStatGT(Myself,3,ARMORCLASS)
  HPGT(LastSeenBy(Myself),20)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_ARMOR_OF_FAITH)
END

IF
  See("Edwin")  // Edwin
  !Dead("Edwin")  // Edwin
  HaveSpell(CLERIC_BLESS)
  HPGT(LastSeenBy(Myself),20)
  !StateCheck(LastSeenBy(Myself),STATE_BLESS)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_BLESS)
END

IF
  !Dead("Edwin")  // Edwin
  OR(4)
    StateCheck(Myself,STATE_PANIC)
    SpellCast([ANYONE],WIZARD_HORROR)
    SpellCast([ANYONE],WIZARD_SPOOK)
    SpellCastPriest([ANYONE],CLERIC_CLOAK_OF_FEAR)
  HaveSpell(CLERIC_REMOVE_FEAR)
  See("Edwin")  // Edwin
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_REMOVE_FEAR)
END

IF
  !Dead("Edwin")  // Edwin
  See(NearestEnemyOfType([0.ANIMAL]))
  HaveSpell(RANGER_CHARM_ANIMAL)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),RANGER_CHARM_ANIMAL)
END

IF
  See("Edwin")  // Edwin
  !Dead("Edwin")  // Edwin
  !StateCheck(Myself,STATE_HASTED)
  HaveSpell(WIZARD_HASTE)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_HASTE)
END

IF
  HitBy([ANYONE],MISSILE)
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
  !HasImmunityEffects(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
END

IF
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
  OR(4)
    See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
    See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
    See(NearestEnemyOfType([0.0.0.BARD_ALL]))
    See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
  !HasBounceEffects(Myself)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END

IF
  See("Edwin")  // Edwin
  !Dead("Edwin")  // Edwin
  !Range(LastSeenBy(Myself),20)
  HaveSpell(CLERIC_ENTANGLE)
  AreaCheck("UTDOOR)")
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_ENTANGLE)
END

IF
  See("Edwin")  // Edwin
  !Dead("Edwin")  // Edwin
  HaveSpell(CLERIC_DOOM)
THEN
  RESPONSE #50
    Spell(LastSeenBy(Myself),CLERIC_DOOM)
  RESPONSE #50
    Continue()
END

IF
  HPPercentLT(Myself,30)
  HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
THEN
  RESPONSE #100
    Spell(MostDamagedOf(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
END

IF
  HPPercentLT(Myself,60)
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
THEN
  RESPONSE #100
    Spell(MostDamagedOf(Myself),CLERIC_CURE_LIGHT_WOUNDS)
END

IF
  AttackedBy([ANYONE],DEFAULT)
  Range(LastAttackerOf(Myself),20)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastAttackerOf(Myself),30)
END

IF
  See("Edwin")  // Edwin
  Range("Edwin",10)  // Edwin
  !Dead("Edwin")  // Edwin
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate("Edwin",30)
END

IF
  See("Edwin")  // Edwin
  !Range("Edwin",10)  // Edwin
  !Dead("Edwin")  // Edwin
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate("Edwin",30)
END

IF
  OR(2)
    Dead("Edwin")  // Edwin
    !Detect("Edwin")  // Edwin
  CombatCounter(0)
  !Allegiance(Myself,ENEMY)
  Global("EdwinValygarFight","GLOBAL",1)
  See([PC])
THEN
  RESPONSE #100
    SetGlobal("EdwinValygarFight","GLOBAL",2)
    StartDialogNoSet([PC])
END

IF
  OR(2)
    Dead("Edwin")  // Edwin
    !Detect("Edwin")  // Edwin
  CombatCounter(0)
  Global("EdwinValygarFight","GLOBAL",1)
  !See([PC])
THEN
  RESPONSE #100
    EscapeArea()
END

