IF
  Dead("Viconia")  // Viconia
THEN
  RESPONSE #100
    TriggerActivation("ViconiaStake",FALSE)
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,9)
  Global("ViconiaStake","AR1000",0)
  Global("ViconiaDeath","AR1000",0)
THEN
  RESPONSE #100
    SetGlobal("ViconiaStake","AR1000",1)
    DisplayString(Myself,29942)  // ~You see an elvish woman, a drow, tied to a stake. A mob of people stand near. The occasional shout of 'Burn her!' comes from the crowd. Anger and fear cross the drow's countenance. You could cut her down if you wish but this shall surely anger the crowd.~
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,9)
  Global("ViconiaStake","AR1000",1)
  Global("ViconiaDeath","AR1000",0)
THEN
  RESPONSE #100
    FadeToColor([20.0],0)
    Wait(1)
    ActionOverride("Viconia",JumpToPoint([1824.1141]))
    FadeFromColor([20.0],0)
    SetGlobal("ViconiaStake","AR1000",2)
    SetGlobal("ViconiaFree","AR1000",1)
    DisplayString(Myself,29943)  // ~Boldly, you walk up to the stake and cut the drow woman free. The armed men turn their ire upon you.~
END

IF
  Clicked([ANYONE])
  Range(LastTrigger,9)
  Global("ViconiaStake","AR1000",2)
THEN
  RESPONSE #100
    DisplayString(Myself,29944)  // ~There is nothing else that you can do with the stake.~
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,9)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
    ActionOverride(LastTrigger,MoveToObject("Viconia"))
END

