IF
  IsActive(Myself)
  IsOverMe([PC])
  Delay(6)
  !PartyHasItem("MISCB4")  // ~Tree of Life Nuts~
THEN
  RESPONSE #100
    DisplayString(Myself,57899)  // ~The branch goes no further and your progress is blocked. The Tree of Life seethes with energy but something holds it back from growing. Perhaps something can be done to extend the branch and allow you to cross.~
END

IF
  IsActive(Myself)
  IsOverMe([PC])
  PartyHasItem("MISCB4")  // ~Tree of Life Nuts~
THEN
  RESPONSE #100
    DisplayString(Myself,57898)  // ~One of the smaller nuts on your pack begins to grow and extend. Surprised, you place it on the branch at your feet. It grows and twists at an alarming rate, soon melding with the Tree of Life. The Tree grows to form a path to the far branch. You may now pass.~
    TakePartyItem("MISCB4")
    OpenDoor("Vine1")
    SetGlobal("Vine1Open","GLOBAL",1)
    TriggerActivation("VineTrig1A",FALSE)
    TriggerActivation("VineTrig1B",FALSE)
END

