IF
  Die()
THEN
  RESPONSE #100
    IncrementGlobal("DelFlee","GLOBAL",1)
    ReallyForceSpellDead(Myself,VAMPIRE_GAS_FORM_CHANGE)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

IF
  !Dead("vvsansuk")  // ~Sansuki~
  Global("AttackSansuki","GLOBAL",1)
THEN
  RESPONSE #100
    Attack("vvsansuk")
END

IF
  Dead("vvsansuk")  // ~Sansuki~
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    EscapeArea()
END

