IF
  Global("AranFleeVamp","GLOBAL",1)
  Dead("vvfemal1")  // ~Vampire~
  Dead("vvfemal2")  // ~Vampire~
  Dead("vvfemal3")  // ~Vampire~
  Dead("vvmale5")  // ~Vampire~
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

