IF
  Dead("vvdel")  // ~Del~
  Dead("vvmale1")  // ~Vampire~
  Dead("vvmale2")  // ~Vampire~
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

