IF
  TimeGT(5)
  TimeLT(DUSK_END)
  AreaType(OUTDOOR)
THEN
  RESPONSE #100
    ReallyForceSpellDead(Myself,VAMPIRE_BAT_FORM_CHANGE)
END

IF
  Die()
THEN
  RESPONSE #100
    ReallyForceSpellDead(Myself,VAMPIRE_GAS_FORM_CHANGE)
END

IF
  TimeGT(5)
  TimeLT(DUSK_END)
  AreaType(OUTDOOR)
THEN
  RESPONSE #100
    ReallyForceSpellDead(Myself,VAMPIRE_BAT_FORM_CHANGE)
END

IF
  See([PC])
  Delay(12)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ReallyForceSpellDead([PC],VAMPIRE_DOMINATION)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

