IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),150)
END

IF
  AttackedBy([PC],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    SetGlobal("AttackedCandleKeep","GLOBAL",1)
    Enemy()
    RunAwayFrom(NearestEnemyOf(Myself),150)
END

IF
  Global("AttackedCandleKeep","GLOBAL",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    RunAwayFrom(LastAttackerOf(Myself),150)
END

