IF
  Contains("MISC2A",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2A")  // ~Doppelganger Wardstone~
    GiveItemCreate("MISC2A",[PC],0,0,0)  // ~Doppelganger Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2B",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2B")  // ~Level 1 Exit Wardstone~
    GiveItemCreate("MISC2B",[PC],0,0,0)  // ~Level 1 Exit Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2C",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2C")  // ~Islanne Wardstone~
    GiveItemCreate("MISC2C",[PC],0,0,0)  // ~Islanne Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2D",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2D")  // ~Kiel Wardstone~
    GiveItemCreate("MISC2D",[PC],0,0,0)  // ~Kiel Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2E",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2E")  // ~Fuernebol Wardstone~
    GiveItemCreate("MISC2E",[PC],0,0,0)  // ~Fuernebol Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2G",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2G")  // ~Level 2 Exit Wardstone~
    GiveItemCreate("MISC2G",Player1,0,0,0)  // ~Level 2 Exit Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2H",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2H")  // ~Move out men! The enemy is everywhere!~
    GiveItemCreate("MISC2H",[PC],0,0,0)  // ~Move out men! The enemy is everywhere!~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2I",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2I")  // ~Wardstone Forgery~
    GiveItemCreate("MISC2I",[PC],0,0,0)  // ~Wardstone Forgery~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2J",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2J")  // ~Wardstone Forgery~
    GiveItemCreate("MISC2J",[PC],0,0,0)  // ~Wardstone Forgery~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2K",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2K")  // ~Compass Wardstone~
    GiveItemCreate("MISC2K",[PC],0,0,0)  // ~Compass Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2L",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2L")  // ~Bone Wardstone~
    GiveItemCreate("MISC2L",[PC],0,0,0)  // ~Bone Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2M",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2M")  // ~Dwarven Rune 1 Wardstone~
    GiveItemCreate("MISC2M",[PC],0,0,0)  // ~Dwarven Rune 1 Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

IF
  Contains("MISC2N",Myself)
THEN
  RESPONSE #100
    DestroyItem("MISC2N")  // ~Dwarven Rune 2 Wardstone~
    GiveItemCreate("MISC2N",[PC],0,0,0)  // ~Dwarven Rune 2 Wardstone~
    SetGlobal("UrnTrap4","GLOBAL",1)
    SetGlobal("UrnTrap5","GLOBAL",1)
    SetGlobal("UrnTrap6","GLOBAL",1)
END

