IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Shout(5)
    Enemy()
END

IF
  Heard([ANYONE],5)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

