IF
  See(NearestEnemyOf(Myself))
  Delay(12)
THEN
  RESPONSE #40
    SelectWeaponAbility(SLOT_WEAPON0,0)
    AttackReevaluate(NearestEnemyOf(Myself),15)
  RESPONSE #60
    SelectWeaponAbility(SLOT_WEAPON1,0)
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
  See(NearestEnemyOf(Myself))
  ActionListEmpty()
THEN
  RESPONSE #40
    SelectWeaponAbility(SLOT_WEAPON0,0)
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

