IF
  GlobalGT("YagaShuraHeart","GLOBAL",0)
  HasItem("invulner",Myself)  // <Invalid Strref -1>
THEN
  RESPONSE #100
    DestroyItem("invulner")  // <Invalid Strref -1>
    Continue()
END

IF
  Global("YagaShuraSpawn","AR5203",1)
  HasItem("sureHP1",Myself)  // <Invalid Strref -1>
THEN
  RESPONSE #100
    DestroyItem("sureHP1")  // <Invalid Strref -1>
    Continue()
END

IF
  NumberOfTimesTalkedTo(0)
  See([PC])
THEN
  RESPONSE #100
    StartDialogNoSet([PC])
END

IF
  GlobalGT("YagaShuraHeart","GLOBAL",0)
  GlobalLT("YagaShuraHeart","GLOBAL",3)
  HPPercentLT(Myself,100)
THEN
  RESPONSE #100
    StartDialogNoSet(Player1)
END

