IF
  InParty(Myself)
  Global("SPRITE_IS_DEADYoshimo","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("SPRITE_IS_DEADYoshimo","GLOBAL",0)
END

IF
  InParty(Myself)
  AreaCheck("AR0300")
  !Global("WorkingForBodhi","GLOBAL",1)
  See(Player1)
  !StateCheck(Player1,STATE_SLEEPING)
  Global("YoshimoMentionsRenal","LOCALS",0)
THEN
  RESPONSE #100
    StartDialogNoSet(Player1)
END

IF
  GlobalTimerExpired("YoshimoRemindsRenal","GLOBAL")
  InParty(Myself)
  Global("TalkedToRenal","GLOBAL",0)
  !Global("WorkingForBodhi","GLOBAL",1)
  AreaType(0)
  AreaType(CITY)
  !AreaCheck("AR2000")
  !Global("Chapter","GLOBAL",4)
  !Global("Chapter","GLOBAL",5)
  !Global("Chapter","GLOBAL",7)
  See(Player1)
  !StateCheck(Player1,STATE_SLEEPING)
  GlobalLT("YoshimoReminder","LOCALS",2)
THEN
  RESPONSE #100
    StartDialogNoSet(Player1)
END

IF
  GlobalGT("AsylumPlot","GLOBAL",55)
  Global("ButtPluggingCumBubble","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("ButtPluggingCumBubble","GLOBAL",1)
    Kill(Myself)
END

IF
  InParty(Myself)
  InParty("Mazzy")  // Mazzy
  See("Mazzy")  // Mazzy
  !Dead("Mazzy")  // Mazzy
  !StateCheck("Mazzy",STATE_SLEEPING)  // Mazzy
  HPLT("Mazzy",20)  // Mazzy
  CombatCounter(0)
  Global("BYoshimo1","LOCALS",0)
THEN
  RESPONSE #100
    Interact("Mazzy")
END

IF
  InParty(Myself)
  GlobalTimerExpired("YoshimoTalksPC","GLOBAL")
  See(Player1)
  !StateCheck(Player1,STATE_SLEEPING)
  CombatCounter(0)
  Global("BYoshimo3","LOCALS",0)
THEN
  RESPONSE #100
    Interact(Player1)
END

IF
  InParty(Myself)
  GlobalTimerExpired("YoshimoTalksPC2","GLOBAL")
  Global("PCYosh","LOCALS",1)
  See(Player1)
  !StateCheck(Player1,STATE_SLEEPING)
  CombatCounter(0)
  Global("BYoshimo4","LOCALS",0)
THEN
  RESPONSE #100
    Interact(Player1)
END

IF
  InParty(Myself)
  InParty("Edwin")  // Edwin
  Gender("Edwin",FEMALE)  // Edwin
  Global("SetItOnce","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SetItOnce","LOCALS",1)
    SetGlobalTimer("YoshimoMakesFun","GLOBAL",ONE_DAY)
END

IF
  InParty(Myself)
  GlobalTimerExpired("YoshimoMakesFun","GLOBAL")
  InParty("Edwin")  // Edwin
  Gender("Edwin",FEMALE)  // Edwin
  See("Edwin")  // Edwin
  !Dead("Edwin")  // Edwin
  !StateCheck("Edwin",STATE_SLEEPING)  // Edwin
  CombatCounter(0)
  Global("BYoshimo14","LOCALS",0)
THEN
  RESPONSE #100
    Interact("Edwin")
END

IF
  PartyHasItem("misc5m")  // ~Inspector's Body~
  InParty(Myself)
  See(Player1)
  !StateCheck(Player1,STATE_SLEEPING)
  OR(3)
    !InParty("Keldorn")  // Keldorn
    Dead("Keldorn")  // Keldorn
    StateCheck("Keldorn",STATE_SLEEPING)  // Keldorn
  OR(3)
    !InParty("Anomen")  // Anomen
    Dead("Anomen")  // Anomen
    StateCheck("Anomen",STATE_SLEEPING)  // Anomen
  Global("FoundAegis","GLOBAL",0)
  Global("FoundAegis2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("FoundAegis2","LOCALS",1)
    StartDialogNoSet(Player1)
END

IF
  Allegiance(Myself,ENEMY)
  !InParty(Myself)
  Global("NPCFight","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("NPCFight","LOCALS",1)
    ChangeAIScript("yoshx",SPECIFICS)
    ChangeAIScript("useitem",GENERAL)
    ChangeAIScript("",DEFAULT)
    SetDialogue("")
    Continue()
END

IF
  Allegiance(Myself,NEUTRAL)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    ChangeAIScript("yoshx",SPECIFICS)
    ChangeAIScript("useitem",GENERAL)
    ChangeAIScript("",DEFAULT)
    Enemy()
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !InParty(Myself)
  Global("NPCFight","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("NPCFight","LOCALS",0)
    ChangeAIScript("",GENERAL)
    ChangeAIScript("",SPECIFICS)
    Continue()
END

