IF
  OnCreation()
  Global("StartCaravanAttack","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("StartCaravanAttack","GLOBAL",1)
    Continue()
END

IF
  See([PC])
  Global("YagaSoldierShout","LOCALS",0)
THEN
  RESPONSE #50
    SetGlobal("YagaSoldierShout","LOCALS",1)
    DisplayStringHead(Myself,72708)  // ~It's them!  The ones Yaga Shura wanted!~
  RESPONSE #50
    SetGlobal("YagaSoldierShout","LOCALS",1)
    DisplayStringHead(Myself,72710)  // ~Get them!  There's a reward!~
  RESPONSE #100
    SetGlobal("YagaSoldierShout","LOCALS",1)
END

IF
  Global("StartCaravanAttack","GLOBAL",1)
  Global("YagaSoldTimerSet","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("YagaSoldTimerSet","LOCALS",1)
    SetGlobalTimer("YagaCarDone","LOCALS",15)
END

IF
  Global("StartCaravanAttack","GLOBAL",1)
  GlobalTimerNotExpired("YagaCarDone","LOCALS")
  See([GOODBUTBLUE])
  Range(LastSeenBy(Myself),10)
  !Class(Myself,MAGE_ALL)
  !Class(Myself,CLERIC_ALL)
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself),15)
END

