IF
  Opened([ANYONE])
THEN
  RESPONSE #100
    CreateVisualEffect("SPGFLSH1",[1183.726])
    CreateVisualEffect("SPFLESHS",[911.717])
    CreateVisualEffect("SPFLESHS",[1123.518])
    CreateVisualEffect("SPFLESHS",[1439.691])
    CreateVisualEffect("SPFLESHS",[1277.914])
    CreateVisualEffect("SPFLESHS",[1053.388])
    CreateVisualEffect("SPFLESHS",[1589.671])
    CreateCreature("HGTRL01",[911.717],0)  // ~Fire Troll~
    CreateCreature("HGTRL01",[1123.518],0)  // ~Fire Troll~
    CreateCreature("HGSAL01",[1439.691],0)  // ~Fire Salamander~
    CreateCreature("HGSAL01",[1277.914],0)  // ~Fire Salamander~
    CreateCreature("HGTRL01",[1053.388],0)  // ~Fire Troll~
    CreateCreature("HGTRL01",[1589.671],0)  // ~Fire Troll~
END

