IF
  Opened([ANYONE])
THEN
  RESPONSE #100
    CreateVisualEffect("ICWRATI",[2136.2329])
    CreateVisualEffect("SPPLANAR",[2084.2106])
    CreateVisualEffect("SPPLANAR",[1828.2367])
    CreateVisualEffect("SPPLANAR",[2461.2297])
    Wait(1)
    CreateCreature("DBONEF01",[2084.2106],0)  // ~Bone Fiend~
    CreateCreature("DBONEF01",[1828.2367],0)  // ~Bone Fiend~
    CreateCreature("GORBAT2",[2461.2297],0)  // ~Erinyes~
    ActionOverride("GORBAT2",Enemy())
END

