IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_DISPEL_MAGIC)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SHADOW_DOOR)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_SHADOW_DOOR)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

