IF
  Global("EnteredPalace","GLOBAL",0)
THEN
  RESPONSE #100
    StartMovie("PALACE")
    SetGlobal("EnteredPalace","GLOBAL",1)
END

IF
  Global("Chapter","GLOBAL",7)
  Global("SarevokBehavior","GLOBAL",0)
  !Exists("Sarevok")  // Sarevok
  !Dead("Sarevok")  // Sarevok
THEN
  RESPONSE #100
    CreateCreature("SAREVO2",[581.344])  // ~Sarevok~
    CreateCreature("LIIA",[680.356])  // ~Liia Jannath~
    CreateCreature("BELT",[735.371])  // ~Belt~
    CreateCreature("NOBLPA1",[702.485])  // ~Nobleman~
    CreateCreature("NOBLPA2",[773.466])  // ~Nobleman~
    CreateCreature("NOBLPA3",[823.407])  // ~Nobleman~
    CreateCreature("NOBLPA4",[867.462])  // ~Nobleman~
    CreateCreature("NOBLPA5",[839.518])  // ~Nobleman~
    CreateCreature("NOBLPA",[769.571])  // ~Nobleman~
END

