IF
  OnCreation()
  Global("Chapter","GLOBAL",7)
  Global("BenjySpawn","GLOBAL",0)
  !Exists("BENJY")  // ~Benjy~
THEN
  RESPONSE #100
    CreateCreature("BENJY",[1454.1019])  // ~Benjy~
    SetGlobal("BenjySpawn","GLOBAL",1)
    Continue()
END

IF
  Global("ScarMission","GLOBAL",1)
  !Exists("Scar")  // ~Scar~
  !Dead("Scar")  // ~Scar~
THEN
  RESPONSE #100
    CreateCreature("SCAR",[1515.1050])  // ~Scar~
    ActionOverride("Scar",SetNumTimesTalkedTo(1))
END

