IF
  Global("HelpTenya","GLOBAL",2)
  Exists("Sonner")  // ~Sonner~
THEN
  RESPONSE #100
    ActionOverride("Sonner",DestroySelf())
END

IF
  Global("HelpTenya","GLOBAL",2)
  Exists("Jebadoh")  // Jebadoh
THEN
  RESPONSE #100
    ActionOverride("Jebadoh",DestroySelf())
END

IF
  Global("HelpTenya","GLOBAL",2)
  Exists("Telman")  // Telman
THEN
  RESPONSE #100
    ActionOverride("Telman",DestroySelf())
END

