IF
  OnCreation()
THEN
  RESPONSE #100
    StartCutSceneMode()
    StartTimer(1,10)
END

IF
  TimerExpired(1)
THEN
  RESPONSE #100
    CreateCreature("ULRAUN",[373.428])  // ~Ulraunt~
    ActionOverride("Ulraunt",MoveToPoint([407.268]))
    ActionOverride("Ulraunt",Dialogue([PC]))
    StartTimer(2,20)
END

IF
  TimerExpired(2)
THEN
  RESPONSE #100
    CreateCreature("TETHTO2",[373.428])  // ~Tethtoril~
    ActionOverride("Tethtoril2",MoveToPoint([407.268]))
    ActionOverride("Tethtoril2",Dialogue([PC]))
END

