IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Shout(1)
END

IF
  Heard("Teven",1)  // ~Teven~
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Heard("Ardenor",1)  // Ardenor
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Heard("Teven",2)  // ~Teven~
THEN
  RESPONSE #100
    EscapeArea()
END

IF
  Heard("Bandit",1)  // ~Bandit~
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

