IF
  See([PC])
  NumberOfTimesTalkedTo(0)
THEN
  RESPONSE #100
    SmallWait(2)
    StartDialog("flam2",[PC])
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    AttackReevaluate(LastAttackerOf(Myself),30)
END

IF
  Allegiance(Myself,ENEMY)
  Range("Viconia",5)  // Viconia
  !Range([PC],5)
THEN
  RESPONSE #100
    AttackReevaluate("Viconia",30)
END

IF
  Allegiance("Viconia",ENEMY)  // Viconia
  See("Viconia")  // Viconia
THEN
  RESPONSE #100
    AttackReevaluate("Viconia",30)
END

