IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    SetGlobal("ZorlDopple","GLOBAL",1)
END

IF
  Global("ZorlDopple","GLOBAL",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    CreateCreature("DOPZORL",[768.607])  // ~Doppleganger~
    CreateCreature("DOPZORL",[710.673])  // ~Doppleganger~
    CreateCreature("DOPZORL",[881.661])  // ~Doppleganger~
    CreateCreature("DOPZORL",[942.567])  // ~Doppleganger~
    ForceSpell(Myself,DOPPLEGANGER_CHANGE2)
END

