IF
  !UnselectableVariable(0)
  Global("Kivanfight","GLOBAL",0)
THEN
  RESPONSE #100
    MakeUnselectable(0)
END

IF
  UnselectableVariable(0)
  See("Viconia")  // Viconia
  Global("Kivanfight","GLOBAL",1)
THEN
  RESPONSE #100
    MakeUnselectable(5000)
END

IF
  !UnselectableVariable(0)
  Dead("Viconia")  // Viconia
  Global("Kivanfight","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("Edwinfight","GLOBAL",0)
    MakeUnselectable(0)
END

IF
  !UnselectableVariable(0)
  !See("Viconia")  // Viconia
THEN
  RESPONSE #100
    MakeUnselectable(0)
END

IF
  Global("Kivanfight","GLOBAL",1)
  See("Viconia")  // Viconia
THEN
  RESPONSE #100
    EquipRanged()
    Attack("Viconia")
END

