IF
  Delay(15)
  See(NearestEnemyOf(Myself))
  Exists(LastAttackerOf(LastSeenBy(Myself)))
  NumCreatureGT([ENEMY],1)
THEN
  RESPONSE #100
    RandomWalk()
END

IF
  See(NearestEnemyOf(Myself))
  Class(NearestEnemyOf(Myself),FIGHTER)
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),60)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),60)
END

