IF
  See(NearestEnemyOf(Myself))
  HaveSpell(CLERIC_HOLD_PERSON)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),CLERIC_HOLD_PERSON)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    SetGlobal("AttackedCandleKeep","GLOBAL",1)
    Enemy()
END

IF
  Global("AttackedCandleKeep","GLOBAL",1)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Global("Chapter","GLOBAL",0)
THEN
  RESPONSE #30
    MoveToPoint([3402.2331])
    MoveToPoint([2997.2799])
    MoveToPoint([1995.2835])
    MoveToPoint([981.2262])
    MoveToPoint([624.1941])
    MoveToPoint([471.1860])
    Wait(30)
    MoveToPoint([624.1941])
    MoveToPoint([981.2262])
    MoveToPoint([1995.2835])
    MoveToPoint([2997.2799])
    MoveToPoint([3402.2331])
    MoveToPoint([2601.1674])
    DestroySelf()
  RESPONSE #30
    MoveToPoint([3402.2331])
    MoveToPoint([2997.2799])
    MoveToPoint([1995.2835])
    MoveToPoint([981.2262])
    MoveToPoint([618.1744])
    MoveToPoint([470.1716])
    Wait(30)
    MoveToPoint([618.1744])
    MoveToPoint([981.2262])
    MoveToPoint([1995.2835])
    MoveToPoint([2997.2799])
    MoveToPoint([3402.2331])
    MoveToPoint([2601.1674])
    DestroySelf()
  RESPONSE #30
    MoveToPoint([3402.2331])
    MoveToPoint([2997.2799])
    MoveToPoint([1995.2835])
    MoveToPoint([981.2262])
    MoveToPoint([573.1574])
    MoveToPoint([426.1554])
    Wait(30)
    MoveToPoint([573.1574])
    MoveToPoint([981.2262])
    MoveToPoint([1995.2835])
    MoveToPoint([2997.2799])
    MoveToPoint([3402.2331])
    MoveToPoint([2601.1674])
    DestroySelf()
END

