IF
  Global("SemajBehavior","GLOBAL",0)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CLOUDKILL)
    SetGlobal("SemajBehavior","GLOBAL",1)
END

IF
  Global("SemajBehavior","GLOBAL",1)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_DIRE_CHARM)
    SetGlobal("SemajBehavior","GLOBAL",2)
END

IF
  Global("SemajBehavior","GLOBAL",2)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SpellPoint([1018.912],WIZARD_DIMENSION_DOOR)
    SetGlobal("SemajBehavior","GLOBAL",3)
END

IF
  Global("SemajBehavior","GLOBAL",3)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_WEB)
    SetGlobal("SemajBehavior","GLOBAL",4)
END

IF
  Global("SemajBehavior","GLOBAL",4)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_FIREBALL)
    SetGlobal("SemajBehavior","GLOBAL",5)
END

IF
  Global("SemajBehavior","GLOBAL",5)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SpellPoint([875.582],WIZARD_DIMENSION_DOOR)
    SetGlobal("SemajBehavior","GLOBAL",6)
END

IF
  Global("SemajBehavior","GLOBAL",6)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_CONFUSION)
    SetGlobal("SemajBehavior","GLOBAL",7)
END

IF
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_LIGHTNING_BOLT)
THEN
  RESPONSE #100
    Spell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

