IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),150)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Shout(5)
    Enemy()
    RunAwayFrom(NearestEnemyOf(Myself),150)
END

IF
  Heard([ANYONE],5)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    RunAwayFrom(LastAttackerOf(Myself),150)
END

