IF
  True()
THEN
  RESPONSE #100
    ChangeCurrentScript("00aAtGB")
  RESPONSE #100
    ChangeCurrentScript("00aAtGC")
  RESPONSE #100
    ChangeCurrentScript("00aAtGD")
  RESPONSE #100
    ChangeCurrentScript("00aAtGF")
  RESPONSE #100
    ChangeCurrentScript("00aAtGH")
  RESPONSE #100
    ChangeCurrentScript("00aAtGM")
  RESPONSE #100
    ChangeCurrentScript("00aAtGP")
  RESPONSE #100
    ChangeCurrentScript("00aAtGR")
  RESPONSE #100
    ChangeCurrentScript("00aAtGS")
  RESPONSE #100
    ChangeCurrentScript("00aAtGT")
  RESPONSE #100
    ChangeCurrentScript("00aAtGW")
END

