IF
  !CreatureHidden(Myself)
  HaveSpell(INNATE_BOMBARDIER_BEETLE_CLOUD)
  !TimerActive(5)
  See(NearestEnemyOf(Myself),0)
  Range(LastSeenBy(Myself),7,LESS_THAN)
THEN
  RESPONSE #100
    StartTimer(5,21)
    ForceSpell(LastSeenBy(Myself),INNATE_BOMBARDIER_BEETLE_CLOUD)
    RemoveSpell(INNATE_BOMBARDIER_BEETLE_CLOUD)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
  RESPONSE #25
    Continue()
END

