IF
  GlobalLT("Use_Spore_Attack","LOCALS",3)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    IncrementGlobal("Use_Spore_Attack","LOCALS",1)
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(LastMarkedObject,INNATE_MYCONID_SPORES,SPELLCAST_IGNORE_HAS_CHECK)
THEN
  RESPONSE #100
    SetGlobal("Use_Spore_Attack","LOCALS",0)
    ForceSpell(LastMarkedObject,INNATE_MYCONID_SPORES)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

