IF
  !CheckSpellState(Myself,RED_FIRESHIELD)
THEN
  RESPONSE #100
    ForceSpell(Myself,WIZARD_FIRESHIELD_RED)
    SpellWait(WIZARD_FIRESHIELD_RED)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],0)
THEN
  RESPONSE #100
    Enemy()
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  GlobalLT("Action","LOCALS",2)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    IncrementGlobal("Action","LOCALS",1)
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_BURNING_HANDS,SPELLCAST_IGNORE_HAS_CHECK)
THEN
  RESPONSE #100
    SetGlobal("Action","LOCALS",0)
    ForceSpell(LastMarkedObject,WIZARD_BURNING_HANDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

