IF
  !Global("00SELEM0_Mark","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",0)
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See([ANYONE],0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(SecondNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(ThirdNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(FourthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(FifthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(SixthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(SeventhNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(EighthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(NinthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SELEM0_Mark","LOCALS",0)
  See(TenthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),ELEMENTAL)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SELEM0_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  !Allegiance(MyTarget,ENEMY)
  Or(7)
    Allegiance(MyTarget,PC)
    Allegiance(MyTarget,CHARMED)
    Allegiance(MyTarget,CONTROLLED)
    Allegiance(MyTarget,ENEMY_OF_EVIL)
    Allegiance(MyTarget,GOODCUTOFF)
    Allegiance(MyTarget,ALLY)
    Allegiance(MyTarget,FAMILIAR)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,ENEMY)
    SetCreatureAreaFlag(Myself,NO_TALK,TRUE)
    DialogInterrupt(FALSE)
    Continue()
END

IF
  !Allegiance(MyTarget,GOODCUTOFF)
  Or(8)
    Allegiance(MyTarget,NOTGOOD)
    Allegiance(MyTarget,ANYTHING)
    Allegiance(MyTarget,NEUTRAL)
    Allegiance(MyTarget,NOTEVIL)
    Allegiance(MyTarget,EVILCUTOFF)
    Allegiance(MyTarget,ARENA_PC)
    Allegiance(MyTarget,CHARMED_PC)
    Allegiance(MyTarget,ENEMY)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,ENEMY_OF_EVIL)
    SetCreatureAreaFlag(Myself,NO_TALK,TRUE)
    DialogInterrupt(FALSE)
    Continue()
END

IF
  !Global("00SELEM0_Mark","LOCALS",0)
  See(MyTarget,0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

