IF
  Global("SH_No_Demons","GLOBAL",1)
  Or(21)
    CurrentAreaIs(Myself,6301)
    CurrentAreaIs(Myself,6302)
    CurrentAreaIs(Myself,6303)
    CurrentAreaIs(Myself,6304)
    CurrentAreaIs(Myself,6305)
    CurrentAreaIs(Myself,6400)
    CurrentAreaIs(Myself,6401)
    CurrentAreaIs(Myself,6402)
    CurrentAreaIs(Myself,6403)
    CurrentAreaIs(Myself,6500)
    CurrentAreaIs(Myself,6501)
    CurrentAreaIs(Myself,6502)
    CurrentAreaIs(Myself,6503)
    CurrentAreaIs(Myself,6600)
    CurrentAreaIs(Myself,6601)
    CurrentAreaIs(Myself,6602)
    CurrentAreaIs(Myself,6603)
    CurrentAreaIs(Myself,6700)
    CurrentAreaIs(Myself,6701)
    CurrentAreaIs(Myself,6702)
    CurrentAreaIs(Myself,6703)
THEN
  RESPONSE #100
    SpellHitEffectSprite(Myself,Myself,CONE_OF_COLD,0)
    DestroySelf()
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  !Global("00SGLB_Mark","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",0)
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See([ANYONE],0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(SecondNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(ThirdNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(FourthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(FifthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(SixthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(SeventhNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(EighthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(NinthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  Global("00SGLB_Mark","LOCALS",0)
  See(TenthNearest,0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
  !Race(LastSeenBy(Myself),TANARI)
  !General(LastSeenBy(Myself),GENERAL_ITEM)
  !Race(LastSeenBy(Myself),KEG)
  !IsPathCriticalObject(LastSeenBy(Myself))
  !IsCreatureAreaFlag(LastSeenBy(Myself),INVULNERABLE)
  !IsCreatureAreaFlag(LastSeenBy(Myself),NON_THREATING_ENEMY)
THEN
  RESPONSE #100
    SetGlobal("00SGLB_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    FaceObject(LastSeenBy(Myself))
    Continue()
END

IF
  !Allegiance(MyTarget,ENEMY)
  Or(7)
    Allegiance(MyTarget,PC)
    Allegiance(MyTarget,CHARMED)
    Allegiance(MyTarget,CONTROLLED)
    Allegiance(MyTarget,ENEMY_OF_EVIL)
    Allegiance(MyTarget,GOODCUTOFF)
    Allegiance(MyTarget,ALLY)
    Allegiance(MyTarget,FAMILIAR)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,ENEMY)
    SetCreatureAreaFlag(Myself,NO_TALK,TRUE)
    DialogInterrupt(FALSE)
    Continue()
END

IF
  !Allegiance(MyTarget,GOODCUTOFF)
  Or(8)
    Allegiance(MyTarget,NOTGOOD)
    Allegiance(MyTarget,ANYTHING)
    Allegiance(MyTarget,NEUTRAL)
    Allegiance(MyTarget,NOTEVIL)
    Allegiance(MyTarget,EVILCUTOFF)
    Allegiance(MyTarget,ARENA_PC)
    Allegiance(MyTarget,CHARMED_PC)
    Allegiance(MyTarget,ENEMY)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,ENEMY_OF_EVIL)
    SetCreatureAreaFlag(Myself,NO_TALK,TRUE)
    DialogInterrupt(FALSE)
    Continue()
END

IF
  Global("OncePerDaySummoning","LOCALS",0)
  !Global("00SGLB_Mark","LOCALS",0)
  HPPercentLT(Myself,35)
THEN
  RESPONSE #100
    SetGlobal("OncePerDaySummoning","LOCALS",1)
    ForceSpell(MyTarget,INNATE_SUMMONED_GLABREZU_SUMMONING)
    SpellWait(INNATE_SUMMONED_GLABREZU_SUMMONING)
    Continue()
END

IF
  !Global("00SGLB_Mark","LOCALS",0)
  GlobalLT("Action","LOCALS",2)
  Range(MyTarget,2,GREATER_THAN)
THEN
  RESPONSE #100
    SpellHitEffectSprite(Myself,Myself,DIMENSION_DOOR_ORIGIN,0)
    HideCreature(Myself,TRUE)
    FloatMessage(Myself,38707)  // ~.:Casts Teleport Without Error:.~
    JumpToObject(MyTarget)
    FaceObject(MyTarget)
    SpellHitEffectSprite(Myself,Myself,DIMENSION_DOOR_DESTINATION,0)
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  See(MyTarget,0)
  !Global("00SGLB_Mark","LOCALS",0)
  GlobalLT("Action","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Action","LOCALS",1)
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(MyTarget,0)
  !Global("00SGLB_Mark","LOCALS",0)
  Global("Action","LOCALS",2)
THEN
  RESPONSE #100
    MarkSpellAndObject("221222122212",Myself,7)
      // WIZARD_MIRROR_IMAGE
      // WIZARD_MIRROR_IMAGE
      // WIZARD_MIRROR_IMAGE
    MarkSpellAndObject("210321042411242013252705",LastMarkedObject,7)
      // WIZARD_BURNING_HANDS
      // WIZARD_CHARM_PERSON
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_EMOTION_FEAR
      // CLERIC_UNHOLY_BLIGHT
      // WIZARD_POWER_WORD_STUN
    Continue()
  RESPONSE #100
    MarkSpellAndObject("210321042411242013252705",LastMarkedObject,7)
      // WIZARD_BURNING_HANDS
      // WIZARD_CHARM_PERSON
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_EMOTION_FEAR
      // CLERIC_UNHOLY_BLIGHT
      // WIZARD_POWER_WORD_STUN
    MarkSpellAndObject("221222122212",Myself,7)
      // WIZARD_MIRROR_IMAGE
      // WIZARD_MIRROR_IMAGE
      // WIZARD_MIRROR_IMAGE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
  !Dead(SpellTarget)  // 
THEN
  RESPONSE #100
    SetGlobal("Action","LOCALS",0)
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  !Global("00SGLB_Mark","LOCALS",0)
  See(MyTarget,0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(Nearest(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("2212",Myself,7)
      // WIZARD_MIRROR_IMAGE
    MarkSpellAndObject("21031325270524202411",LastMarkedObject,7)
      // WIZARD_BURNING_HANDS
      // CLERIC_UNHOLY_BLIGHT
      // WIZARD_POWER_WORD_STUN
      // WIZARD_EMOTION_FEAR
      // WIZARD_EMOTION_HOPELESSNESS
    Continue()
  RESPONSE #100
    MarkSpellAndObject("21031325270524202411",LastMarkedObject,7)
      // WIZARD_BURNING_HANDS
      // CLERIC_UNHOLY_BLIGHT
      // WIZARD_POWER_WORD_STUN
      // WIZARD_EMOTION_FEAR
      // WIZARD_EMOTION_HOPELESSNESS
    MarkSpellAndObject("2212",Myself,7)
      // WIZARD_MIRROR_IMAGE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
  !Dead(SpellTarget)  // 
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  True()
THEN
  RESPONSE #100
    RandomWalk()
END

