IF
  Global("Player","LOCALS",0)
  !IsPlayerNumber(Myself,1)
  !IsPlayerNumber(Myself,2)
  !IsPlayerNumber(Myself,3)
  !IsPlayerNumber(Myself,4)
  !IsPlayerNumber(Myself,5)
  !IsPlayerNumber(Myself,6)
THEN
  RESPONSE #100
    SetGlobal("Player","LOCALS",-1)
    ChangeEnemyAlly(Myself,ENEMY_OF_EVIL)
END

IF
  Global("Player","LOCALS",-1)
  !Allegiance(Myself,ENEMY_OF_EVIL)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,ENEMY_OF_EVIL)
    Continue()
END

IF
  Global("Player","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Player","LOCALS",1)
    Continue()
END

IF
  !StateCheck(Myself,STATE_CHARMED)
  !StateCheck(Myself,STATE_SUMMONED_CREATURE)
  Global("Player","LOCALS",-1)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,ENEMY)
    ChangeCurrentScript("")
END

IF
  !StateCheck(Myself,STATE_CHARMED)
  StateCheck(Myself,STATE_SUMMONED_CREATURE)
  Global("Player","LOCALS",-1)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,PC)
    ChangeCurrentScript("")
END

IF
  !StateCheck(Myself,STATE_CHARMED)
  Global("Player","LOCALS",1)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,PC)
    ChangeCurrentScript("")
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
  Range(LastSeenBy(Myself),5,LESS_THAN)
THEN
  RESPONSE #100
    MarkSpellAndObject("32603236",Myself,3)
      // INNATE_BARBARIAN_RAGE_GREATER
      // INNATE_BARBARIAN_RAGE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  !TimerActive(22)
  !Range(NearestPC,15,LESS_THAN)
THEN
  RESPONSE #100
    MoveToObject(NearestPC)
    StartTimer(22,5)
END

IF
  True()
THEN
  RESPONSE #100
    NoAction()
END

