IF
  GlobalTimerExpired("WOLF_BREATH","LOCALS")
  See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(LastMarkedObject,INNATE_WINTER_WOLF_BREATH,SPELLCAST_IGNORE_HAS_CHECK)
THEN
  RESPONSE #100
    ForceSpell(LastMarkedObject,INNATE_WINTER_WOLF_BREATH)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    SetGlobalTimerRandom("WOLF_BREATH","LOCALS",6,9)
END

