IF
  !Global("TEAM_2","MYAREA",1)
  Or(2)
    AttackedBy([GOODCUTOFF],0)
    PickPocketFailed([PC])
THEN
  RESPONSE #100
    SetGlobal("TEAM_2","MYAREA",1)
    Continue()
END

IF
  CreatureHidden(Myself)
  !Global("TEAM_2","MYAREA",0)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  !IsTeamBitOn(TEAM_2_BIT)
THEN
  RESPONSE #100
    SetTeamBit(TEAM_2_BIT,TRUE)
    Continue()
END

IF
  !Global("TEAM_2","MYAREA",1)
  Allegiance(Myself,ENEMY)
  !CreatureHidden(Myself)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    SetGlobal("TEAM_2","MYAREA",1)
    Continue()
END

