IF
  !Global("TEAM_14","MYAREA",1)
  Or(2)
    AttackedBy([GOODCUTOFF],0)
    PickPocketFailed([PC])
THEN
  RESPONSE #100
    SetGlobal("TEAM_14","MYAREA",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("TEAM_14","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  CreatureHidden(Myself)
  !Global("TEAM_14","MYAREA",0)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

