IF
  !Global("TEAM_20","MYAREA",1)
  Or(2)
    AttackedBy([GOODCUTOFF],0)
    PickPocketFailed([PC])
THEN
  RESPONSE #100
    SetGlobal("TEAM_20","MYAREA",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("TEAM_20","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  !IsTeamBitOn(TEAM_20_BIT)
THEN
  RESPONSE #100
    SetTeamBit(TEAM_20_BIT,TRUE)
    Continue()
END

IF
  !Global("TEAM_20","MYAREA",1)
  Allegiance(Myself,ENEMY)
  !CreatureHidden(Myself)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    SetGlobal("TEAM_20","MYAREA",1)
    Continue()
END

