IF
  Global("TEAM_0","MYAREA",0)
  !TimerActive(2)
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    StartTimer(2,6)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  Or(2)
    AttackedBy([GOODCUTOFF],0)
    PickPocketFailed([PC])
  Or(13)
    HitBy([GOODCUTOFF],SLASHING)
    HitBy([GOODCUTOFF],CRUSHING)
    HitBy([GOODCUTOFF],PIERCING)
    HitBy([GOODCUTOFF],MISSILE)
    HitBy([GOODCUTOFF],FIRE)
    HitBy([GOODCUTOFF],ELECTRICITY)
    HitBy([GOODCUTOFF],POISON)
    HitBy([GOODCUTOFF],MAGIC)
    HitBy([GOODCUTOFF],COLD)
    HitBy([GOODCUTOFF],ACID)
    HitBy([GOODCUTOFF],MAGICFIRE)
    HitBy([GOODCUTOFF],MAGICCOLD)
    PickPocketFailed([PC])
THEN
  RESPONSE #100
    Enemy()
    SetGlobal("TOWNIE_HOSTILE","MYAREA",1)
    Help()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("TEAM_0","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Dead(Myself)  // 
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  Global("TEAM_0","MYAREA",0)
  !Global("TOWNIE_HOSTILE","MYAREA",0)
  !CreatureHidden(Myself)
  Help([ANYTHING])
THEN
  RESPONSE #100
    SetGlobal("TEAM_0","MYAREA",1)
    Enemy()
END

