IF
  !CreatureHidden(Myself)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    Wait(1)
    PlaySequence(Myself,SLEEP)
    Wait(1)
    HideCreature(Myself,TRUE)
END

IF
  CreatureHidden(Myself)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    PlaySequence(Myself,AWAKE)
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

