IF
  !TimerActive(18)
  Global("Crandall_Leave","GLOBAL",0)
  !See([ENEMY.0.GOBLIN],0)
THEN
  RESPONSE #20
    FloatMessage(Myself,1771)  // ~"Where are the rest of the Targos Guard?"~
    StartRandomTimer(18,10,15)
    Continue()
  RESPONSE #20
    FloatMessage(Myself,1772)  // ~"How did the goblins reach the docks?"~
    StartRandomTimer(18,10,15)
    Continue()
  RESPONSE #20
    FloatMessage(Myself,1773)  // ~"Goblins... there's goblins everywhere..."~
    StartRandomTimer(18,10,15)
    Continue()
  RESPONSE #240
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,1317,1489,4)
THEN
  RESPONSE #100
    SetStartPos([1317.1489])
    SetGlobal("ML_0","LOCALS",1)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
  !Global("Crandall_Leave","GLOBAL",0)
THEN
  RESPONSE #100
    MoveToPoint([1317.1489])
END

IF
  Global("ML_0","LOCALS",1)
  ActionListEmpty()
  NearLocation(Myself,733,1450,4)
THEN
  RESPONSE #100
    SetStartPos([733.1450])
    SetGlobal("ML_0","LOCALS",2)
    Continue()
END

IF
  Global("ML_0","LOCALS",1)
  !Global("Crandall_Leave","GLOBAL",0)
THEN
  RESPONSE #100
    MoveToPoint([733.1450])
END

IF
  Global("ML_0","LOCALS",2)
  ActionListEmpty()
  NearLocation(Myself,221,1356,4)
THEN
  RESPONSE #100
    SetStartPos([221.1356])
    SetGlobal("ML_0","LOCALS",3)
    Continue()
END

IF
  Global("ML_0","LOCALS",2)
  !Global("Crandall_Leave","GLOBAL",0)
THEN
  RESPONSE #100
    MoveToPoint([221.1356])
END

IF
  Global("ML_0","LOCALS",3)
  ActionListEmpty()
  NearLocation(Myself,335,819,4)
THEN
  RESPONSE #100
    SetStartPos([335.819])
    SetGlobal("ML_0","LOCALS",4)
    Continue()
END

IF
  Global("ML_0","LOCALS",3)
  !Global("Crandall_Leave","GLOBAL",0)
THEN
  RESPONSE #100
    MoveToPoint([335.819])
END

IF
  Global("ML_0","LOCALS",4)
  ActionListEmpty()
  NearLocation(Myself,225,383,4)
THEN
  RESPONSE #100
    SetStartPos([225.383])
    SetGlobal("ML_0","LOCALS",5)
    Continue()
END

IF
  Global("ML_0","LOCALS",4)
  !Global("Crandall_Leave","GLOBAL",0)
THEN
  RESPONSE #100
    MoveToPoint([225.383])
END

IF
  Global("ML_0","LOCALS",5)
  ActionListEmpty()
  NearLocation(Myself,159,31,4)
THEN
  RESPONSE #100
    SetStartPos([159.31])
    SetGlobal("ML_0","LOCALS",6)
    Continue()
END

IF
  Global("ML_0","LOCALS",5)
  !Global("Crandall_Leave","GLOBAL",0)
THEN
  RESPONSE #100
    MoveToPoint([159.31])
END

IF
  Global("ML_0","LOCALS",6)
  !Global("Crandall_Leave","GLOBAL",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  !TimerActive(20)
  !NearSavedLocation(3)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ReturnToSavedLocation(0)
    StartTimer(20,5)
END

