IF
  Global("I_LIKE_DWARVES","LOCALS",0)
  See([PC],0)
THEN
  RESPONSE #75
    SetGlobal("I_LIKE_DWARVES","LOCALS",2)
    Continue()
  RESPONSE #25
    SetGlobal("I_LIKE_DWARVES","LOCALS",1)
    Continue()
END

IF
  Global("I_LIKE_DWARVES","LOCALS",1)
  Or(2)
    See([PC.0.DWARF],0)
    See([0.0.DWARF],0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  Or(11)
    See(NearestEnemyOf(Myself),0)
    See("CAT_1",0)  // CAT_1
    See("CAT_2",0)  // CAT_2
    See("CAT_3",0)  // CAT_3
    See("CAT_4",0)  // CAT_4
    See("CAT_5",0)  // CAT_5
    See("CAT_6",0)  // CAT_6
    See("CAT_7",0)  // CAT_7
    See("CAT_8",0)  // CAT_8
    See("CAT_9",0)  // CAT_9
    See("FIRTHA",0)  // FIRTHA
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

