IF
  Global("I_LIKE_DWARVES","LOCALS",0)
  See([PC],0)
THEN
  RESPONSE #75
    SetGlobal("I_LIKE_DWARVES","LOCALS",2)
    Continue()
  RESPONSE #25
    SetGlobal("I_LIKE_DWARVES","LOCALS",1)
    Continue()
END

IF
  Global("I_LIKE_DWARVES","LOCALS",1)
  Or(2)
    See([PC.0.DWARF],0)
    See([0.0.DWARF],0)
THEN
  RESPONSE #100
    SetBestWeapon(LastMarkedObject,3)
    AttackReevaluate(LastMarkedObject,45)
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    SetBestWeapon(LastMarkedObject,3)
    AttackReevaluate(LastMarkedObject,45)
END

