IF
  Global("HINT_2_GIVEN","MYAREA",0)
  Entered([PC])
THEN
  RESPONSE #100
    FloatMessage("Door_Hint_Text_02",38691)  // ~Some objects may be trapped.  To detect traps, simply select the "search" button and wait - if detected, the trapped object will be highlighted in red.  To disarm a trapped object, select the thief skills button and click on the trapped object. ~
    SetGlobal("HINT_2_GIVEN","MYAREA",1)
    Continue()
END

