IF
  !CreatureHidden(Myself)
  TimerActive(4)
THEN
  RESPONSE #100
    HideCreature(Myself,TRUE)
END

IF
  !See([PC],0)
  TimeGT(DAWN_START)
  TimeLT(20)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  See([PC],0)
  TimeGT(DAWN_START)
  TimeLT(20)
THEN
  RESPONSE #100
    UseItem("11Veira4",Myself)  // <Invalid Strref -1>
    Wait(1)
    DestroySelf()
END

IF
  !CreatureHidden(Myself)
  !TimerActive(4)
  Or(3)
    HPPercentLT(Myself,100)
    HitBy([GOODCUTOFF],CRUSHING)
    AttackedBy([GOODCUTOFF],0)
THEN
  RESPONSE #100
    StartTimer(4,43200)
    UseItem("11Veira4",Myself)  // <Invalid Strref -1>
    Wait(1)
    HideCreature(Myself,TRUE)
END

IF
  !CreatureHidden(Myself)
  Or(2)
    GlobalGT("Veira_Quest","GLOBAL",1)
    !Global("Let_Me_Go","GLOBAL",0)
THEN
  RESPONSE #100
    UseItem("11Veira4",Myself)  // <Invalid Strref -1>
    Wait(1)
    DestroySelf()
END

IF
  Global("SAVED_LOCATION","LOCALS",0)
THEN
  RESPONSE #100
    SetSavedLocationPoint(459,199,N)
    SetGlobal("SAVED_LOCATION","LOCALS",1)
    Continue()
END

IF
  Global("FL_0","LOCALS",0)
  !TimerActive(18)
  !CreatureHidden(Myself)
  Global("Let_Me_Go","GLOBAL",0)
  GlobalLT("Veira_Turned","GLOBAL",2)
  Global("Veira_Happy","GLOBAL",0)
  GlobalLT("Veira_Quest","GLOBAL",2)
THEN
  RESPONSE #100
    FloatMessage(Myself,8650)  // ~::Weeping::~
    StartTimer(18,5)
    IncrementGlobal("FL_0","LOCALS",1)
END

IF
  Global("FL_0","LOCALS",1)
  !TimerActive(18)
  !CreatureHidden(Myself)
  Global("Let_Me_Go","GLOBAL",0)
  GlobalLT("Veira_Turned","GLOBAL",2)
  Global("Veira_Happy","GLOBAL",0)
  GlobalLT("Veira_Quest","GLOBAL",2)
THEN
  RESPONSE #100
    FloatMessage(Myself,8651)  // ~- Donovan -~
    StartTimer(18,5)
    IncrementGlobal("FL_0","LOCALS",1)
END

IF
  Global("FL_0","LOCALS",2)
  !TimerActive(18)
  !CreatureHidden(Myself)
  Global("Let_Me_Go","GLOBAL",0)
  GlobalLT("Veira_Turned","GLOBAL",2)
  Global("Veira_Happy","GLOBAL",0)
  GlobalLT("Veira_Quest","GLOBAL",2)
THEN
  RESPONSE #100
    FloatMessage(Myself,8653)  // ~- Where are you my love -~
    StartTimer(18,5)
    SetGlobal("FL_0","LOCALS",0)
END

IF
  !TimerActive(19)
  !IsFacingSavedRotation(Myself)
THEN
  RESPONSE #100
    FaceSavedLocation(Myself)
    StartTimer(19,5)
END

