IF
  !TimerActive(18)
  !Global("Goblin_Palisade_Quest","GLOBAL",0)
  See([PC],0)
THEN
  RESPONSE #100
    FloatMessage(Myself,34234)  // ~"You've saved us!"~
    StartRandomTimer(18,13,16)
    FaceObject(LastSeenBy(Myself))
  RESPONSE #100
    FloatMessage(Myself,34840)  // ~"Thank the Gods you were here!"~
    StartRandomTimer(18,13,16)
    FaceObject(LastSeenBy(Myself))
  RESPONSE #100
    FloatMessage(Myself,40131)  // ~"May Waukeen bless your path with gold!"~
    StartRandomTimer(18,13,16)
    FaceObject(LastSeenBy(Myself))
END

IF
  !TimerActive(18)
  !Global("Goblins_Attack_Palisade","GLOBAL",0)
  See([PC],0)
THEN
  RESPONSE #100
    FloatMessage(Myself,40132)  // ~"Are there still goblins out there?!"~
    StartRandomTimer(18,13,16)
    FaceObject(LastSeenBy(Myself))
  RESPONSE #100
    FloatMessage(Myself,40133)  // ~"As soon as this battle is over, I'm leaving Targos for good, penance be damned!"~
    StartRandomTimer(18,13,16)
    FaceObject(LastSeenBy(Myself))
  RESPONSE #100
    FloatMessage(Myself,40134)  // ~"Do you need healing?  If not, get out there and kill some goblins!"~
    StartRandomTimer(18,13,16)
    FaceObject(LastSeenBy(Myself))
END

IF
  !TimerActive(18)
  Global("Goblins_Attack_Palisade","GLOBAL",0)
  Global("Goblin_Palisade_Quest","GLOBAL",0)
THEN
  RESPONSE #100
    FloatMessage(Myself,40135)  // ~"I have no idea what possessed Quinn to send me *here.*"~
    StartRandomTimer(18,13,16)
  RESPONSE #100
    FloatMessage(Myself,40136)  // ~"Hmmmph."~
    StartRandomTimer(18,13,16)
  RESPONSE #100
    FloatMessage(Myself,40137)  // ~"Those goblins won't be foolish enough to attack again... I hope."~
    StartRandomTimer(18,13,16)
  RESPONSE #100
    FloatMessage(Myself,40138)  // ~"If I have to heal one more case of frostbite, I'm leaving town."~
    StartRandomTimer(18,13,16)
END

