IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Torak4")  // 
    StopJoinRequests()
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    MultiPlayerSync()
    HideCreature("Torak4",FALSE)
    MoveViewPoint([1569.367],15)
    MoveToPoint([1569.367])
    FaceObject(NearestPC)
    MultiPlayerSync()
    SetNumTimesTalkedTo(3)
    SetDialogueRange(300)
    Dialogue(NearestPC)
END

