IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Torak4")  // 
    MoveToPoint([1636.379])
    MultiPlayerSync()
    Wait(1)
    Face(E)
    Wait(1)
    Unlock("AR2000_Door1_Bridge")
    OpenDoor("AR2000_Door1_Bridge")
    PlaySoundPoint("AM2000g",[1636.37])
    Wait(1)
    MoveToPoint([2000.238])
    MultiPlayerSync()
    EndCutSceneMode()
    ResetJoinRequests()
    MultiPlayerSync()
    DestroySelf()
END

