IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Torak2")  // 
    StopJoinRequests()
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    MultiPlayerSync()
    HideCreature("Torak2",FALSE)
    MoveViewPoint([2010.1650],15)
    MoveToPoint([2010.1650])
    FaceObject(NearestPC)
    MultiPlayerSync()
    SetNumTimesTalkedTo(1)
    SetDialogueRange(300)
    Dialogue(NearestPC)
END

