IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  HPLostGT(Myself,12)
  IsSpellTargetValid(Myself,CLERIC_CURE_LIGHT_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),3)
END

IF
  HaveSpell(CLERIC_CHARM_PERSON_OR_MAMMAL)
  See(NearestEnemySummoned(Myself),0)
  IsSpellTargetValid(LastMarkedObject,CLERIC_CHARM_PERSON_OR_MAMMAL,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,CLERIC_CHARM_PERSON_OR_MAMMAL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("122111051250",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // CLERIC_RAINSTORM
      // CLERIC_ENTANGLE
      // CLERIC_SUMMON_NATURES_ALLY_2
    MarkSpellAndObject("1250",LastMarkedObject,7)
      // CLERIC_SUMMON_NATURES_ALLY_2
    Continue()
  RESPONSE #100
    MarkSpellAndObject("1250",LastMarkedObject,7)
      // CLERIC_SUMMON_NATURES_ALLY_2
    MarkSpellAndObject("122111051250",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // CLERIC_RAINSTORM
      // CLERIC_ENTANGLE
      // CLERIC_SUMMON_NATURES_ALLY_2
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  HasItem("BClaw",Myself)  // ~Beast Claw~
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    AttackOneRound(LastMarkedObject)
END

IF
  HaveSpell(CLERIC_BEAST_CLAW)
  See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(Myself,CLERIC_BEAST_CLAW,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_BEAST_CLAW)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

