IF
  !Global("TEAM_4","MYAREA",0)
  Global("TEAM_2","MYAREA",0)
  LOS([PC],28)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  !See("Dynokeg",0)  // ~Keg of Blasting~
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  Or(2)
    Global("SR_Villagers_Dead","GLOBAL",1)
    See([PC],0)
  See("Dynokeg",0)  // ~Keg of Blasting~
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  True()
THEN
  RESPONSE #100
    NoAction()
END

