IF
  CreatureHidden(Myself)
  Global("unload","LOCALS",1)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  Global("Unload","LOCALS",1)
THEN
  RESPONSE #100
    ChangeCurrentScript("00aAtGN")
END

IF
  Allegiance(Myself,ENEMY)
  !Global("Villagers_Rescued","MYAREA",1)
THEN
  RESPONSE #100
    FloatMessage(Myself,25005)  // ~"To arms!  To arms!  Slay prisoners now!"~
    SetGlobal("Unload","LOCALS",1)
    SetGlobal("SR_Villagers_Dead","GLOBAL",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Dead(Myself)  // 
  !Allegiance(Myself,ENEMY)
  See([PC],0)
THEN
  RESPONSE #100
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  !Allegiance(Myself,ENEMY)
  See([ENEMY],0)
THEN
  RESPONSE #100
    SetGlobal("SR_Villagers_Dead","GLOBAL",1)
    SetGlobal("Unload","LOCALS",1)
    Enemy()
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

