IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Cutscene")  // 
    MultiPlayerSync()
    ScreenShake(30,25,25)
    OpenDoor("AR2101_Door5_Dam")
    PlaySoundPoint("AM2101g",[1228.373])
    MultiPlayerSync()
    EndCutSceneMode()
    AddXPVar("Level_3_Hard",27774)  // ~You have destroyed the dam that spanned the Shaengarne River.~
    AddJournalEntry(28186)
    SetGlobal("Destroy_Dam_Quest","GLOBAL",4)
    MultiPlayerSync()
END

