IF
  !NumberOfTimesTalkedTo(0)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

IF
  HaveSpell(CLERIC_HEAL)
  HPPercentLT(Myself,20)
  IsSpellTargetValid(Myself,CLERIC_HEAL,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_HEAL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  HPLostGT(Myself,29)
  IsSpellTargetValid(Myself,CLERIC_CURE_CRITICAL_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_CRITICAL_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
  HPLostGT(Myself,23)
  IsSpellTargetValid(Myself,CLERIC_CURE_SERIOUS_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_SERIOUS_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  HPLostGT(Myself,11)
  IsSpellTargetValid(Myself,CLERIC_CURE_MODERATE_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_MODERATE_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_HEAL)
  See("Kristian",0)  // Kristian
  HPPercentLT(LastSeenBy(Myself),20)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_HEAL,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_HEAL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("Kristian",0)  // Kristian
  HPLostGT(LastSeenBy(Myself),29)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
  See("Kristian",0)  // Kristian
  HPLostGT(LastSeenBy(Myself),23)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See("Kristian",0)  // Kristian
  HPLostGT(LastSeenBy(Myself),11)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_HEAL)
  See("WarriorofVirtue1",0)  // WarriorofVirtue1
  HPPercentLT(LastSeenBy(Myself),20)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_HEAL,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_HEAL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("WarriorofVirtue1",0)  // WarriorofVirtue1
  HPLostGT(LastSeenBy(Myself),29)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
  See("WarriorofVirtue1",0)  // WarriorofVirtue1
  HPLostGT(LastSeenBy(Myself),23)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See("WarriorofVirtue1",0)  // WarriorofVirtue1
  HPLostGT(LastSeenBy(Myself),11)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_HEAL)
  See("WarriorofVirtue2",0)  // WarriorofVirtue2
  HPPercentLT(LastSeenBy(Myself),20)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_HEAL,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_HEAL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("WarriorofVirtue2",0)  // WarriorofVirtue2
  HPLostGT(LastSeenBy(Myself),29)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
  See("WarriorofVirtue2",0)  // WarriorofVirtue2
  HPLostGT(LastSeenBy(Myself),23)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See("WarriorofVirtue2",0)  // WarriorofVirtue2
  HPLostGT(LastSeenBy(Myself),11)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_HEAL)
  See("WarriorofVirtue3",0)  // WarriorofVirtue3
  HPPercentLT(LastSeenBy(Myself),20)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_HEAL,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_HEAL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  See("WarriorofVirtue3",0)  // WarriorofVirtue3
  HPLostGT(LastSeenBy(Myself),29)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
  See("WarriorofVirtue3",0)  // WarriorofVirtue3
  HPLostGT(LastSeenBy(Myself),23)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  See("WarriorofVirtue3",0)  // WarriorofVirtue3
  HPLostGT(LastSeenBy(Myself),11)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  NumberOfTimesTalkedTo(0)
  See([PC],0)
THEN
  RESPONSE #100
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("1414","Kristian",0)
      // CLERIC_RECITATION
    MarkSpellAndObject("14231721",LastMarkedObject,3)
      // CLERIC_WALL_OF_MOONLIGHT
      // CLERIC_HOLY_WORD
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  NumCreatureGT([ENEMY],1)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("12261518130313101324250725072507",LastMarkedObject,7)
      // CLERIC_MOON_MOTES
      // CLERIC_GREATER_COMMAND
      // CLERIC_DISPEL_MAGIC
      // CLERIC_MISCAST_MAGIC
      // CLERIC_HOLY_SMITE
      // WIZARD_DOMINATE_PERSON
      // WIZARD_DOMINATE_PERSON
      // WIZARD_DOMINATE_PERSON
    MarkSpellAndObject("23062306230612112425",LastMarkedObject,7)
      // WIZARD_HOLD_PERSON
      // WIZARD_HOLD_PERSON
      // WIZARD_HOLD_PERSON
      // CLERIC_SILENCE_15_RADIUS
      // CLERIC_CONTAGION
    Continue()
  RESPONSE #100
    MarkSpellAndObject("23062306230612112425",LastMarkedObject,7)
      // WIZARD_HOLD_PERSON
      // WIZARD_HOLD_PERSON
      // WIZARD_HOLD_PERSON
      // CLERIC_SILENCE_15_RADIUS
      // CLERIC_CONTAGION
    MarkSpellAndObject("12261518130313101324250725072507",LastMarkedObject,7)
      // CLERIC_MOON_MOTES
      // CLERIC_GREATER_COMMAND
      // CLERIC_DISPEL_MAGIC
      // CLERIC_MISCAST_MAGIC
      // CLERIC_HOLY_SMITE
      // WIZARD_DOMINATE_PERSON
      // WIZARD_DOMINATE_PERSON
      // WIZARD_DOMINATE_PERSON
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  Or(2)
    HasItem("CMDamag",Myself)  // ~Inflict Moderate Wounds~
    HasItem("MStone",Myself)  // ~Magic Stone~
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("131912181106",Myself,3)
      // CLERIC_CIRCLE_OF_BONES
      // CLERIC_CAUSE_MODERATE_WOUNDS
      // CLERIC_MAGICAL_STONE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

