IF
  !Global("OTYUGH_ESCAPE","MYAREA",0)
  Heard([ANYONE],66)
THEN
  RESPONSE #100
    MoveToObjectUntilSee(LastHeardBy(Myself))
END

IF
  !Global("OTYUGH_ESCAPE","MYAREA",0)
  !Dead("03_Oty_01")  // 
THEN
  RESPONSE #100
    ChangeCurrentScript("3002mBt1")
  RESPONSE #100
    Continue()
END

IF
  !Global("OTYUGH_ESCAPE","MYAREA",0)
  !Dead("03_Oty_02")  // 
THEN
  RESPONSE #100
    ChangeCurrentScript("3002mBt2")
  RESPONSE #100
    Continue()
END

IF
  !Global("OTYUGH_ESCAPE","MYAREA",0)
  !IsScriptName("Fire_Beetle_Queen",Myself)
  !Dead("Fire_Beetle_Queen")  // 
THEN
  RESPONSE #100
    ChangeCurrentScript("3002mBt3")
  RESPONSE #100
    Continue()
END

IF
  !Global("OTYUGH_ESCAPE","MYAREA",0)
  Dead("03_Oty_01")  // 
  Dead("03_Oty_02")  // 
  Dead("Fire_Beetle_Queen")  // 
THEN
  RESPONSE #100
    ChangeCurrentScript("3002mBt0")
  RESPONSE #100
    Continue()
END

IF
  Dead("Fire_Beetle_Queen")  // 
  Dead("03_Oty_01")  // 
  Dead("03_Oty_02")  // 
THEN
  RESPONSE #100
    ChangeCurrentScript("00aMvW")
END

IF
  !TimerActive(22)
THEN
  RESPONSE #100
    RandomWalk()
    StartRandomTimer(22,3,11)
END

