IF
  !Global("DRUM_1_STATE","MYAREA",2)
  !Dead("DRUM_1")  // 
  Or(4)
    !Global("TEAM_2","MYAREA",0)
    Global("DRUM_1_STATE","MYAREA",1)
    See(NearestEnemyOf(Myself),0)
    AttackedBy([PC],0)
THEN
  RESPONSE #100
    SetGlobal("I_PLAY_DRUMS","LOCALS",1)
    SetCreatureAreaFlag(Myself,IGNORE_RETURN_TO_START_POS,TRUE)
    SetGlobal("DRUM_1_STATE","MYAREA",2)
    FloatMessage(Myself,471)  // ~"Drum!  Me get drum!"~
    ChangeCurrentScript("")
END

