IF
  !Global("DRUM_4_STATE","MYAREA",2)
  !Dead("DRUM_4")  // 
  Or(3)
    Global("DRUM_4_STATE","MYAREA",1)
    See(NearestEnemyOf(Myself),0)
    AttackedBy([PC],0)
THEN
  RESPONSE #100
    SetGlobal("I_PLAY_DRUMS","LOCALS",1)
    SetCreatureAreaFlag(Myself,IGNORE_RETURN_TO_START_POS,TRUE)
    SetGlobal("DRUM_4_STATE","MYAREA",2)
    FloatMessage(Myself,472)  // ~"Hit drums!  Kill foes!"~
    ChangeCurrentScript("")
END

