IF
  Global("30enneli_Healed","GLOBAL",0)
  HPGT(Myself,6)
THEN
  RESPONSE #100
    SetGlobal("30enneli_Healed","GLOBAL",1)
    Continue()
END

IF
  Global("30enneli_Healed","GLOBAL",1)
  !Allegiance(Myself,ENEMY)
  Dead([ENEMY])  // 
  See([PC],0)
THEN
  RESPONSE #100
    Dialogue(LastSeenBy(Myself))
END

IF
  Global("ENNELIA_BRASTON_TEAM","MYAREA",0)
  !Global("ENNELIA_SAW_BRASTON","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("ENNELIA_BRASTON_TEAM","MYAREA",1)
    Continue()
END

IF
  Global("ENNELIA_SAW_BRASTON","MYAREA",0)
  See("Braston",0)  // Braston
THEN
  RESPONSE #100
    SetGlobal("ENNELIA_SAW_BRASTON","MYAREA",1)
    FaceObject(LastSeenBy(Myself))
    FloatMessage(Myself,17050)  // ~"Braston!"~
    Wait(1)
    Continue()
END

IF
  HasItem("00swdL02",Myself)  // ~Masterwork Longsword~
  !Global("ENNELIA_SAW_BRASTON","MYAREA",0)
  !Dead("Braston")  // 
  Range("Braston",6,LESS_THAN)  // Braston
THEN
  RESPONSE #100
    GiveItem("00swdL02","Braston")  // ~Masterwork Longsword~
    Continue()
END

IF
  HasItem("00swdL02",Myself)  // ~Masterwork Longsword~
  !Dead("Braston")  // 
  Or(2)
    !Global("BRASTON_SAW_ENNELIA","MYAREA",0)
    !Global("ENNELIA_SAW_BRASTON","MYAREA",0)
THEN
  RESPONSE #100
    MoveToObject("Braston")
END

