IF
  !TimerActive(21)
THEN
  RESPONSE #50
    FloatMessage(Myself,580)  // ~"Me hungry."~
    StartRandomTimer(21,5,15)
    Continue()
  RESPONSE #50
    FloatMessage(Myself,581)  // ~"Me hate orcs."~
    StartRandomTimer(21,5,15)
    Continue()
  RESPONSE #50
    FloatMessage(Myself,582)  // ~"Stupid orcs get all food."~
    StartRandomTimer(21,5,15)
    Continue()
  RESPONSE #150
    StartRandomTimer(21,5,15)
    Continue()
END

