IF
  !NearSavedLocation(3)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  !TimerActive(21)
THEN
  RESPONSE #50
    FloatMessage(Myself,628)  // ~"Spiders good to eat."~
    StartRandomTimer(21,8,20)
  RESPONSE #50
    FloatMessage(Myself,629)  // ~"Must clean out spider guts."~
    StartRandomTimer(21,8,20)
  RESPONSE #100
    StartRandomTimer(21,8,20)
END

IF
  Global("ML_0","LOCALS",0)
THEN
  RESPONSE #100
    PlaySequence(Myself,ATTACK_SLASH)
    SetGlobal("ML_0","LOCALS",0)
  RESPONSE #100
    PlaySequence(Myself,ATTACK_BACKSLASH)
    SetGlobal("ML_0","LOCALS",0)
END

