IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See([PC],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("1101",Myself,3)
      // CLERIC_BLESS
    MarkSpellAndObject("1111",LastMarkedObject,3)
      // CLERIC_BANE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

