IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("2104",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_CHARM_PERSON
    MarkSpellAndObject("21122118",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    MarkSpellAndObject("211221182318",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
      // WIZARD_ICELANCE
    MarkSpellAndObject("2205",[PC],SPELLCAST_RANDOM)
      // WIZARD_HORROR
    MarkSpellAndObject("2220",ThirdNearestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_SNILLOCS_SNOWBALL_SWARM
    MarkSpellAndObject("2203",Myself,7)
      // WIZARD_SEE_INVISIBILITY
    Continue()
  RESPONSE #100
    MarkSpellAndObject("21122118",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    MarkSpellAndObject("211221182318",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
      // WIZARD_ICELANCE
    MarkSpellAndObject("2205",[PC],SPELLCAST_RANDOM)
      // WIZARD_HORROR
    MarkSpellAndObject("2220",ThirdNearestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_SNILLOCS_SNOWBALL_SWARM
    MarkSpellAndObject("2203",Myself,7)
      // WIZARD_SEE_INVISIBILITY
    MarkSpellAndObject("2104",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_CHARM_PERSON
    Continue()
  RESPONSE #100
    MarkSpellAndObject("211221182318",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
      // WIZARD_ICELANCE
    MarkSpellAndObject("2205",[PC],SPELLCAST_RANDOM)
      // WIZARD_HORROR
    MarkSpellAndObject("2220",ThirdNearestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_SNILLOCS_SNOWBALL_SWARM
    MarkSpellAndObject("2203",Myself,7)
      // WIZARD_SEE_INVISIBILITY
    MarkSpellAndObject("2104",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_CHARM_PERSON
    MarkSpellAndObject("21122118",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2205",[PC],SPELLCAST_RANDOM)
      // WIZARD_HORROR
    MarkSpellAndObject("2220",ThirdNearestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_SNILLOCS_SNOWBALL_SWARM
    MarkSpellAndObject("2203",Myself,7)
      // WIZARD_SEE_INVISIBILITY
    MarkSpellAndObject("2104",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_CHARM_PERSON
    MarkSpellAndObject("21122118",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    MarkSpellAndObject("211221182318",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
      // WIZARD_ICELANCE
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2220",ThirdNearestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_SNILLOCS_SNOWBALL_SWARM
    MarkSpellAndObject("2203",Myself,7)
      // WIZARD_SEE_INVISIBILITY
    MarkSpellAndObject("2104",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_CHARM_PERSON
    MarkSpellAndObject("21122118",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    MarkSpellAndObject("211221182318",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
      // WIZARD_ICELANCE
    MarkSpellAndObject("2205",[PC],SPELLCAST_RANDOM)
      // WIZARD_HORROR
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2203",Myself,7)
      // WIZARD_SEE_INVISIBILITY
    MarkSpellAndObject("2104",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_CHARM_PERSON
    MarkSpellAndObject("21122118",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    MarkSpellAndObject("211221182318",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
      // WIZARD_ICELANCE
    MarkSpellAndObject("2205",[PC],SPELLCAST_RANDOM)
      // WIZARD_HORROR
    MarkSpellAndObject("2220",ThirdNearestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_SNILLOCS_SNOWBALL_SWARM
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

