IF
  CreatureHidden(Myself)
  !Global("SPAWN","LOCALS",0)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  Global("SPAWN","LOCALS",0)
  See(NearestEnemyOf(Myself),0)
  !TargetUnreachable(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SpellHitEffectSprite(Myself,Myself,ANIMAL_SUMMONING_CIRCLE,10)
    SmallWait(7)
    SpellHitEffectSprite(Myself,Myself,CAUSE_CRITICAL_WOUNDS,10)
    FaceObject(NearestEnemyOf(Myself))
    SetGlobal("SPAWN","LOCALS",1)
END

IF
  Global("SPAWN","LOCALS",0)
THEN
  RESPONSE #100
    JumpToObject(NearestPC)
    SpellHitEffectSprite(Myself,Myself,ANIMAL_SUMMONING_CIRCLE,10)
    SmallWait(7)
    SpellHitEffectSprite(Myself,Myself,CAUSE_CRITICAL_WOUNDS,10)
    FaceObject(NearestEnemyOf(Myself))
    SetGlobal("SPAWN","LOCALS",1)
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

