IF
  Global("ML_0","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,1720,390,4)
THEN
  RESPONSE #100
    SetStartPos([1720.390])
    SetGlobal("ML_0","LOCALS",1)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
THEN
  RESPONSE #100
    MoveToPoint([1720.390])
END

IF
  Global("ML_0","LOCALS",1)
  !TimerActive(22)
THEN
  RESPONSE #100
    StartTimer(22,2)
    SetGlobal("ML_0","LOCALS",2)
END

IF
  Global("ML_0","LOCALS",2)
  NearSavedLocation(4)
THEN
  RESPONSE #100
    SetGlobal("ML_0","LOCALS",3)
    SetStartPos([-1.-1])
    Continue()
END

IF
  Global("ML_0","LOCALS",2)
  !TimerActive(22)
  !NearSavedLocation(4)
THEN
  RESPONSE #100
    ReturnToSavedLocation(0)
END

IF
  Global("ML_0","LOCALS",3)
  !TimerActive(22)
THEN
  RESPONSE #100
    StartTimer(22,2)
    SetGlobal("ML_0","LOCALS",0)
END

