IF
  HaveSpell(WIZARD_FLAME_ARROW)
  Or(2)
    See([PC],0)
    See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_FLAME_ARROW,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,WIZARD_FLAME_ARROW)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(WIZARD_MIRROR_IMAGE)
  See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(Myself,WIZARD_MIRROR_IMAGE,0)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(WIZARD_CHARM_PERSON)
  Or(2)
    See([PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],0)
    See([PC],0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_CHARM_PERSON,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,WIZARD_CHARM_PERSON)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("221721122118",LastMarkedObject,7)
      // WIZARD_AGANNAZAR_SCORCHER
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    MarkSpellAndObject("2112",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
    MarkSpellAndObject("2215",[PC],SPELLCAST_RANDOM)
      // WIZARD_WEB
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2112",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
    MarkSpellAndObject("2215",[PC],SPELLCAST_RANDOM)
      // WIZARD_WEB
    MarkSpellAndObject("221721122118",LastMarkedObject,7)
      // WIZARD_AGANNAZAR_SCORCHER
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2215",[PC],SPELLCAST_RANDOM)
      // WIZARD_WEB
    MarkSpellAndObject("221721122118",LastMarkedObject,7)
      // WIZARD_AGANNAZAR_SCORCHER
      // WIZARD_MAGIC_MISSILE
      // WIZARD_CHROMATIC_ORB
    MarkSpellAndObject("2112",[PC],SPELLCAST_RANDOM)
      // WIZARD_MAGIC_MISSILE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

