IF
  Global("ML_0","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,430,980,4)
THEN
  RESPONSE #100
    SetStartPos([430.980])
    SetGlobal("ML_0","LOCALS",1)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
THEN
  RESPONSE #100
    MoveToPoint([430.980])
END

IF
  Global("ML_0","LOCALS",1)
  !TimerActive(22)
THEN
  RESPONSE #100
    Face(NW)
    SetGlobal("ML_0","LOCALS",2)
END

IF
  Global("ML_0","LOCALS",2)
  !TimerActive(22)
THEN
  RESPONSE #100
    StartTimer(22,5)
    SetGlobal("ML_0","LOCALS",3)
END

IF
  Global("ML_0","LOCALS",3)
  NearSavedLocation(4)
THEN
  RESPONSE #100
    SetGlobal("ML_0","LOCALS",4)
    SetStartPos([-1.-1])
    Continue()
END

IF
  Global("ML_0","LOCALS",3)
  !TimerActive(22)
  !NearSavedLocation(4)
THEN
  RESPONSE #100
    ReturnToSavedLocation(0)
END

IF
  Global("ML_0","LOCALS",4)
  !TimerActive(22)
THEN
  RESPONSE #100
    StartTimer(22,1)
    SetGlobal("ML_0","LOCALS",0)
END

