IF
  HaveSpell(WIZARD_HOLD_PERSON)
  See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_HOLD_PERSON,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,WIZARD_HOLD_PERSON)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_UNHOLY_BLIGHT)
  See([PC],0)
  IsSpellTargetValid(LastMarkedObject,CLERIC_UNHOLY_BLIGHT,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,CLERIC_UNHOLY_BLIGHT)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_COMMAND)
  Or(2)
    See([PC],0)
    See([PC],0)
  IsSpellTargetValid(LastMarkedObject,CLERIC_COMMAND,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,CLERIC_COMMAND)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

