IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  HPLostGT(Myself,18)
  IsSpellTargetValid(Myself,CLERIC_CURE_MODERATE_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_MODERATE_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  HPLostGT(Myself,8)
  IsSpellTargetValid(Myself,CLERIC_CURE_LIGHT_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_COMMAND)
  Or(3)
    See([PC],0)
    See([PC],0)
    See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(LastMarkedObject,CLERIC_COMMAND,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,CLERIC_COMMAND)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See([PC],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("1101",Myself,7)
      // CLERIC_BLESS
    MarkSpellAndObject("111111051204",LastMarkedObject,7)
      // CLERIC_BANE
      // CLERIC_ENTANGLE
      // CLERIC_CHARM_PERSON_OR_MAMMAL
    MarkSpellAndObject("1204",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // CLERIC_CHARM_PERSON_OR_MAMMAL
    Continue()
  RESPONSE #100
    MarkSpellAndObject("111111051204",LastMarkedObject,7)
      // CLERIC_BANE
      // CLERIC_ENTANGLE
      // CLERIC_CHARM_PERSON_OR_MAMMAL
    MarkSpellAndObject("1204",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // CLERIC_CHARM_PERSON_OR_MAMMAL
    MarkSpellAndObject("1101",Myself,7)
      // CLERIC_BLESS
    Continue()
  RESPONSE #100
    MarkSpellAndObject("1204",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // CLERIC_CHARM_PERSON_OR_MAMMAL
    MarkSpellAndObject("1101",Myself,7)
      // CLERIC_BLESS
    MarkSpellAndObject("111111051204",LastMarkedObject,7)
      // CLERIC_BANE
      // CLERIC_ENTANGLE
      // CLERIC_CHARM_PERSON_OR_MAMMAL
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

