IF
  True()
THEN
  RESPONSE #100
    MultiPlayerSync()
    CutSceneId(Player3)  // 
    FadeToColor([0.0],0)
    ActionOverride("Illium",JumpToPoint([1933.323]))
    ApplySpell(Player3,CLERIC_DISPEL_MAGIC)
    SetGlobal("40OdeaMadeOffer","GLOBAL",2)
    ActionOverride(Player3,JumpToPoint([1848.415]))
    ActionOverride("Odea",JumpToPoint([2048.384]))
    MoveViewPoint([1848.415],INSTANT)
    FadeFromColor([0.0],0)
    EndCutSceneMode()
END

