IF
  AttackedBy([GOODCUTOFF],0)
  GlobalLT("40GoublikaAfraid","GLOBAL",1)
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    Debug("GoublikaAfraid")
    SetGlobal("40GoublikaAfraid","GLOBAL",2)
    SetGlobal("TalkToPlayer","LOCALS",1)
    Continue()
END

IF
  Global("TalkToPlayer","LOCALS",1)
  See([PC],0)
THEN
  RESPONSE #100
    Debug("GoublikaTalkToPlayer")
    ClearAllActions()
    SetGlobal("TEAM_3","MYAREA",0)
    SetGlobal("TEAM_9","MYAREA",0)
    ClearSpriteEffects(Myself)
    ClearSpriteEffects("03_Fomorian_01")
    ClearSpriteEffects("03_Fomorian_02")
    ClearSpriteEffects("03_Fomorian_03")
    ClearSpriteEffects("03_Fomorian_04")
    ClearSpriteEffects("03_Fomorian_05")
    ClearSpriteEffects("03_Fomorian_06")
    ClearSpriteEffects("03_Fomorian_07")
    ClearSpriteEffects("03_Fomorian_08")
    ClearSpriteEffects("03_Fomorian_09")
    ClearSpriteEffects("03_Wolf_01")
    ClearSpriteEffects("03_Wolf_02")
    ClearSpriteEffects("03_Wolf_03")
    ClearSpriteEffects("03_Wolf_04")
    ClearSpriteEffects("03_Wolf_05")
    ClearSpriteEffects("03_Wolf_06")
    ClearSpriteEffects("03_Wolf_07")
    ClearSpriteEffects("03_Wolf_08")
    ClearSpriteEffects("03_Wolf_09")
    ClearSpriteEffects("03_Wolf_10")
    ChangeEnemyAlly(Myself,NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_01",NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_02",NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_03",NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_04",NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_05",NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_06",NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_07",NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_08",NEUTRAL)
    ChangeEnemyAlly("03_Fomorian_09",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_01",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_02",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_03",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_04",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_05",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_06",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_07",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_08",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_09",NEUTRAL)
    ChangeEnemyAlly("03_Wolf_10",NEUTRAL)
    SetDialogueRange(0)
    Dialogue(LastMarkedObject)
    SetGlobal("TalkToPlayer","LOCALS",0)
    SetGlobal("GoublikaSawAttack","MYAREA",0)
    ReturnToSavedLocation(5)
END

IF
  Global("TalkToPlayer","LOCALS",1)
  Range(NearestPC,25,GREATER_THAN)
THEN
  RESPONSE #100
    Debug("GoublikaMoveToPlayer")
    MoveToObject(NearestPC)
END

IF
  Global("GoublikaSawAttack","MYAREA",1)
  Global("CallForHelp","LOCALS",0)
THEN
  RESPONSE #100
    Debug("GoublikaSawAttack")
    SetGlobal("CallForHelp","LOCALS",1)
    SetGlobal("TalkToPlayer","LOCALS",1)
END

IF
  Global("GoublikaSawAttack","MYAREA",1)
  Global("CallForHelp","LOCALS",2)
THEN
  RESPONSE #100
    Debug("GoublikaSawAnotherAttack")
    Enemy()
    SetGlobal("CallForHelp","LOCALS",-1)
END

IF
  !Global("TEAM_3","MYAREA",1)
  Or(2)
    AttackedBy([GOODCUTOFF],0)
    PickPocketFailed([PC])
THEN
  RESPONSE #100
    SetGlobal("TEAM_3","MYAREA",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("TEAM_3","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],0)
THEN
  RESPONSE #100
    SetGlobal("40GoublikaOrder","GLOBAL",0)
    SetGlobal("TEAM_3","MYAREA",1)
    SetGlobal("TEAM_9","MYAREA",1)
END

IF
  GlobalGT("40GoublikaOrder","GLOBAL",0)
  Or(2)
    !Global("TEAM_3","MYAREA",0)
    !Global("TEAM_9","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("TEAM_3","MYAREA",0)
    SetGlobal("TEAM_9","MYAREA",0)
END

