IF
  OpenState(Myself,TRUE)
THEN
  RESPONSE #100
    TriggerActivation("LifeTrapMirror",TRUE)
    TriggerActivation("InfoLifeTrapMirror",TRUE)
    HideCreature("02_Assassin_01",FALSE)
    HideCreature("02_Bishop_02",FALSE)
    HideCreature("02_Mystic_03",FALSE)
    HideCreature("02_Warrior_04",FALSE)
    HideCreature("02_Henchman_05",FALSE)
    HideCreature("02_Henchman_06",FALSE)
    HideCreature("02_Henchman_07",FALSE)
    HideCreature("02_Henchman_08",FALSE)
    HideCreature("02_Henchman_09",FALSE)
    HideCreature("02_Henchman_10",FALSE)
    HideCreature("02_Henchman_11",FALSE)
    HideCreature("02_Henchman_12",FALSE)
    HideCreature("02_Henchman_13",FALSE)
    SetGlobal("PlayerSawMirrorTrap","MYAREA",1)
    ChangeCurrentScript("")
END

