IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  !Global("TEAM_0","MYAREA",1)
  Or(2)
    AttackedBy([GOODCUTOFF],0)
    PickPocketFailed([PC])
THEN
  RESPONSE #100
    SetGlobal("TEAM_0","MYAREA",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("TEAM_0","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  !Global("TEAM_0","MYAREA",1)
  Allegiance(Myself,ENEMY)
  !CreatureHidden(Myself)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    SetGlobal("TEAM_0","MYAREA",1)
    Continue()
END

IF
  Global("TEAM_0","MYAREA",1)
  Exists(NearestPC)
  !See(NearestPC,0)
THEN
  RESPONSE #100
    MoveToObject(NearestPC)
END

IF
  Global("TEAM_0","MYAREA",0)
THEN
  RESPONSE #100
    NoAction()
END

IF
  Or(2)
    CreatureHidden(Myself)
    !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    NoAction()
END

IF
  !TimerActive(22)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToObject(NearestPC)
    StartTimer(22,5)
END

