IF
  Global("41ZackTask","GLOBAL",14)
THEN
  RESPONSE #100
    MoveToObjectUntilSee("41Zack")
END

IF
  Global("INITIALIZED_41AOCHA","LOCALS",0)
THEN
  RESPONSE #100
    SetCreatureAreaFlag(Myself,IGNORE_RETURN_TO_START_POS,TRUE)
    SetGlobal("INITIALIZED_41AOCHA","LOCALS",1)
    Continue()
END

IF
  AttackedBy([GOODCUTOFF],0)
THEN
  RESPONSE #100
    SetGlobal("41PlayerKilledAocha","GLOBAL",1)
    Enemy()
    ChangeCurrentScript("")
END

