IF
  !Allegiance(Myself,ENEMY)
  See([PC],0)
  HasItem("41AmulHS",LastMarkedObject)  // ~Aurilite Holy Symbol~
THEN
  RESPONSE #100
    EquipItem("00CIHELA",1)
    EquipItem("00CIHELB",1)
    EquipItem("00CISHLD",1)
    EquipItem("00CISHLB",1)
    EquipItem("00CWSWDB",1)
    EquipItem("00MSTR96",1)
    Enemy()
END

IF
  !Allegiance(Myself,ENEMY)
  AttackedBy([GOODCUTOFF],0)
THEN
  RESPONSE #100
    EquipItem("00CIHELA",1)
    EquipItem("00CIHELB",1)
    EquipItem("00CISHLD",1)
    EquipItem("00CISHLB",1)
    EquipItem("00CWSWDB",1)
    EquipItem("00MSTR96",1)
    Enemy()
END

IF
  !Allegiance(Myself,ENEMY)
  Exists(Player1)
  HasItem("41AmulHS",Player1)  // ~Aurilite Holy Symbol~
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  !Allegiance(Myself,ENEMY)
  Exists(Player2)
  HasItem("41AmulHS",Player2)  // ~Aurilite Holy Symbol~
THEN
  RESPONSE #100
    MoveToObject(Player2)
END

IF
  !Allegiance(Myself,ENEMY)
  Exists(Player3)
  HasItem("41AmulHS",Player3)  // ~Aurilite Holy Symbol~
THEN
  RESPONSE #100
    MoveToObject(Player3)
END

IF
  !Allegiance(Myself,ENEMY)
  Exists(Player4)
  HasItem("41AmulHS",Player4)  // ~Aurilite Holy Symbol~
THEN
  RESPONSE #100
    MoveToObject(Player4)
END

IF
  !Allegiance(Myself,ENEMY)
  Exists(Player5)
  HasItem("41AmulHS",Player5)  // ~Aurilite Holy Symbol~
THEN
  RESPONSE #100
    MoveToObject(Player5)
END

IF
  !Allegiance(Myself,ENEMY)
  Exists(Player6)
  HasItem("41AmulHS",Player6)  // ~Aurilite Holy Symbol~
THEN
  RESPONSE #100
    MoveToObject(Player6)
END

IF
  Allegiance(Myself,ENEMY)
  !See([PC],0)
THEN
  RESPONSE #100
    EquipItem("00CIHELA",0)
    EquipItem("00CIHELB",0)
    EquipItem("00CISHLD",0)
    EquipItem("00CISHLB",0)
    EquipItem("00CWSWDB",0)
    EquipItem("00MSTR96",0)
    ChangeEnemyAlly(Myself,NEUTRAL)
END

IF
  Or(2)
    Allegiance(Myself,ENEMY)
    AttackedBy([GOODCUTOFF],0)
  See(LastAttackerOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastAttackerOf(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  See([PC],0)
  HasItem("41AmulHS",LastMarkedObject)  // ~Aurilite Holy Symbol~
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

