IF
  Global("CurrentSacrifice","MYAREA",0)
THEN
  RESPONSE #100
    SetMyTarget("04_Prisoner_01")
    SetGlobal("SacrificeMarked","LOCALS",1)
    Continue()
END

IF
  Global("CurrentSacrifice","MYAREA",1)
  GlobalTimerExpired("SacrificeTimer1","MYAREA")
THEN
  RESPONSE #100
    SetMyTarget("04_Prisoner_02")
    SetGlobal("SacrificeMarked","LOCALS",1)
    Continue()
END

IF
  Global("CurrentSacrifice","MYAREA",2)
  GlobalTimerExpired("SacrificeTimer2","MYAREA")
THEN
  RESPONSE #100
    SetMyTarget("04_Prisoner_03")
    SetGlobal("SacrificeMarked","LOCALS",1)
    Continue()
END

IF
  Global("CurrentSacrifice","MYAREA",3)
  GlobalTimerExpired("SacrificeTimer3","MYAREA")
THEN
  RESPONSE #100
    SetMyTarget("04_Prisoner_04")
    SetGlobal("SacrificeMarked","LOCALS",1)
    Continue()
END

IF
  Global("CurrentSacrifice","MYAREA",4)
  GlobalTimerExpired("SacrificeTimer4","MYAREA")
THEN
  RESPONSE #100
    SetMyTarget("04_Prisoner_05")
    SetGlobal("SacrificeMarked","LOCALS",1)
    Continue()
END

IF
  Global("CurrentSacrifice","MYAREA",5)
  GlobalTimerExpired("SacrificeTimer5","MYAREA")
THEN
  RESPONSE #100
    SetMyTarget("Nathaniel")
    SetGlobal("SacrificeMarked","LOCALS",1)
    Continue()
END

IF
  Global("CurrentSacrifice","MYAREA",6)
  GlobalTimerExpired("SacrificeTimer6","MYAREA")
THEN
  RESPONSE #100
    SetMyTarget("04_Prisoner_06")
    SetGlobal("SacrificeMarked","LOCALS",1)
    Continue()
END

IF
  Global("SacrificeMarked","LOCALS",1)
  !Global("CurrentSacrifice","MYAREA",5)
  Exists(MyTarget)
  !See(MyTarget,0)
THEN
  RESPONSE #100
    ActionOverride(MyTarget,JumpToPoint([1138.853]))
END

IF
  Global("SacrificeMarked","LOCALS",1)
  !Global("CurrentSacrifice","MYAREA",5)
  See(MyTarget,0)
THEN
  RESPONSE #100
    Kill(MyTarget)
    Continue()
END

IF
  Global("SacrificeMarked","LOCALS",1)
  Global("CurrentSacrifice","MYAREA",5)
  Exists(MyTarget)
THEN
  RESPONSE #100
    ActionOverride(MyTarget,SetSavedLocationPoint(800,2655,SSW))
    ActionOverride(MyTarget,JumpToPoint([800.2655]))
    SetGlobal("41NateFreeQuest","GLOBAL",4)
    Unlock("AR4101_Door12")
    OpenDoor("AR4101_Door12")
    Continue()
END

IF
  Global("SacrificeMarked","LOCALS",1)
THEN
  RESPONSE #100
    IncrementGlobal("CurrentSacrifice","MYAREA",1)
    SetGlobal("SacrificeMarked","LOCALS",0)
    Continue()
END

IF
  GlobalGT("CurrentSacrifice","MYAREA",6)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

