IF
  NumberOfTimesTalkedTo(0)
  See([PC],0)
  !Dead(Myself)  // 
THEN
  RESPONSE #100
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  Global("NathanielTalk","MYAREA",1)
  See([PC],0)
  !Dead(Myself)  // 
THEN
  RESPONSE #100
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
    SetGlobal("NathanielTalk","MYAREA",2)
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("ML_2","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,384,2688,4)
THEN
  RESPONSE #100
    SetStartPos([384.2688])
    SetGlobal("ML_2","LOCALS",1)
    Continue()
END

IF
  Global("ML_2","LOCALS",0)
  Global("41NateDestroySourceQuest","GLOBAL",4)
  CurrentAreaIs(Myself,4101)
THEN
  RESPONSE #100
    MoveToPoint([384.2688])
END

IF
  Global("ML_2","LOCALS",1)
  Global("41NateDestroySourceQuest","GLOBAL",4)
  CurrentAreaIs(Myself,4101)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Or(2)
    Global("PartyResting","LOCALS",1)
    Global("PartyResting","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("PartyResting","LOCALS",1)
    FadeToColor([0.0],0)
    Continue()
END

IF
  Global("PartyResting","LOCALS",2)
THEN
  RESPONSE #100
    RestParty()
    SetGlobalTimer("RestTimer","LOCALS",3)
    SetGlobal("PartyResting","LOCALS",4)
END

IF
  Global("PartyResting","LOCALS",3)
THEN
  RESPONSE #100
    RestUntilHealed()
    SetGlobal("PartyResting","LOCALS",4)
    Continue()
END

IF
  Global("PartyResting","LOCALS",4)
  GlobalTimerExpired("RestTimer","LOCALS")
THEN
  RESPONSE #100
    FadeFromColor([0.0],0)
    SetGlobal("PartyResting","LOCALS",0)
END

IF
  GlobalGT("NathanielTalk","MYAREA",0)
  !See([PC],0)
THEN
  RESPONSE #100
    SetGlobal("NathanielTalk","MYAREA",0)
END

