IF
  HPLostGT(Myself,18)
  HasItem("00Potn05",Myself)  // ~Potion of Extra Healing~
THEN
  RESPONSE #100
    UseItem("00Potn05",Myself)  // ~Potion of Extra Healing~
END

IF
  Global("CheckTouch","LOCALS",1)
  HasItem("VTouch5",Myself)  // ~Vampiric Touch~
  See([GOODCUTOFF],0)
THEN
  RESPONSE #100
    AttackOneRound(LastMarkedObject)
END

IF
  Global("CheckTouch","LOCALS",1)
  !HasItem("VTouch5",Myself)  // ~Vampiric Touch~
THEN
  RESPONSE #100
    SetGlobal("CheckTouch","LOCALS",0)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  Global("CheckTouch","LOCALS",0)
  RandomNum(5,1)
  HaveSpell(WIZARD_VAMPIRIC_TOUCH)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_VAMPIRIC_TOUCH)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    SetGlobal("CheckTouch","LOCALS",1)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  Or(2)
    RandomNum(10,1)
    !See([ENEMY],0)
  See(FarthestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("250125132313",LastMarkedObject,7)
      // WIZARD_ANIMATE_DEAD
      // WIZARD_SUMMON_SHADOW
      // WIZARD_SKULL_TRAP
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  RandomNum(2,1)
  See([GOODCUTOFF],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("2417222522052119",LastMarkedObject,7)
      // WIZARD_BELTYNS_BURNING_BLOOD
      // WIZARD_POWER_WORD_SLEEP
      // WIZARD_HORROR
      // WIZARD_LARLOCHS_MINOR_DRAIN
    MarkSpellAndObject("222824142212",Myself,7)
      // WIZARD_DEATH_ARMOR
      // WIZARD_SPIRIT_ARMOR
      // WIZARD_MIRROR_IMAGE
    Continue()
  RESPONSE #100
    MarkSpellAndObject("222824142212",Myself,7)
      // WIZARD_DEATH_ARMOR
      // WIZARD_SPIRIT_ARMOR
      // WIZARD_MIRROR_IMAGE
    MarkSpellAndObject("2417222522052119",LastMarkedObject,7)
      // WIZARD_BELTYNS_BURNING_BLOOD
      // WIZARD_POWER_WORD_SLEEP
      // WIZARD_HORROR
      // WIZARD_LARLOCHS_MINOR_DRAIN
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  AttackedBy([GOODCUTOFF],0)
  !See(LastAttackerOf(Myself),0)
  HaveSpell(WIZARD_SKULL_TRAP)
THEN
  RESPONSE #100
    Spell(LastAttackerOf(Myself),WIZARD_SKULL_TRAP)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  AttackedBy([GOODCUTOFF],0)
  !See(LastAttackerOf(Myself),0)
  HaveSpell(WIZARD_CIRCLE_OF_DEATH)
  Range(LastAttackerOf(Myself),9,GREATER_THAN)
THEN
  RESPONSE #100
    Spell(LastAttackerOf(Myself),WIZARD_CIRCLE_OF_DEATH)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HitBy([PC],MAGIC)
  HaveSpell(WIZARD_SHIELD)
  IsSpellTargetValid(Myself,WIZARD_SHIELD,0)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHIELD)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

