IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  Global("ML_0","LOCALS",-1)
  See([PC],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("2118211223082215",LastMarkedObject,7)
      // WIZARD_CHROMATIC_ORB
      // WIZARD_MAGIC_MISSILE
      // WIZARD_LIGHTNING_BOLT
      // WIZARD_WEB
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  Global("ML_0","LOCALS",-1)
  See([PC.HUMANOID],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("21042316230622252420220524012411",LastMarkedObject,7)
      // WIZARD_CHARM_PERSON
      // WIZARD_DIRE_CHARM
      // WIZARD_HOLD_PERSON
      // WIZARD_POWER_WORD_SLEEP
      // WIZARD_EMOTION_FEAR
      // WIZARD_HORROR
      // WIZARD_CONFUSION
      // WIZARD_EMOTION_HOPELESSNESS
    MarkSpellAndObject("21222220",LastMarkedObject,7)
      // WIZARD_ICE_DAGGER
      // WIZARD_SNILLOCS_SNOWBALL_SWARM
    Continue()
  RESPONSE #100
    MarkSpellAndObject("21222220",LastMarkedObject,7)
      // WIZARD_ICE_DAGGER
      // WIZARD_SNILLOCS_SNOWBALL_SWARM
    MarkSpellAndObject("21042316230622252420220524012411",LastMarkedObject,7)
      // WIZARD_CHARM_PERSON
      // WIZARD_DIRE_CHARM
      // WIZARD_HOLD_PERSON
      // WIZARD_POWER_WORD_SLEEP
      // WIZARD_EMOTION_FEAR
      // WIZARD_HORROR
      // WIZARD_CONFUSION
      // WIZARD_EMOTION_HOPELESSNESS
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  Global("ML_0","LOCALS",-1)
  See([PC],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("22012206221223052405240824142311",Myself,7)
      // WIZARD_BLUR
      // WIZARD_INVISIBILITY
      // WIZARD_MIRROR_IMAGE
      // WIZARD_HASTE
      // WIZARD_IMPROVED_INVISIBILITY
      // WIZARD_STONESKIN
      // WIZARD_SPIRIT_ARMOR
      // WIZARD_PROTECTION_FROM_NORMAL_MISSILES
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  Global("ML_0","LOCALS",0)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    SpellPoint([2048.1760],WIZARD_DIMENSION_DOOR)
    SetGlobal("ML_0","LOCALS",1)
END

IF
  Global("ML_0","LOCALS",1)
  ActionListEmpty()
  NearLocation(Myself,2048,1760,4)
THEN
  RESPONSE #100
    SetStartPos([2048.1760])
    SetGlobal("ML_0","LOCALS",2)
    Continue()
END

IF
  Global("ML_0","LOCALS",1)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([2048.1760])
END

IF
  Global("ML_0","LOCALS",2)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Face(NW)
    SetGlobal("ML_0","LOCALS",3)
END

IF
  Global("ML_0","LOCALS",3)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SUMMON_MONSTER_IV)
    SetGlobal("ML_0","LOCALS",4)
END

IF
  Global("ML_0","LOCALS",4)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPIDER_SPAWN)
    SetGlobal("ML_0","LOCALS",5)
END

IF
  Global("ML_0","LOCALS",5)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SHADOW_CONJURATION)
    SetGlobal("ML_0","LOCALS",6)
END

IF
  Global("ML_0","LOCALS",6)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_AEGIS)
    SetGlobal("ML_0","LOCALS",-1)
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MLS_1","LOCALS",1)
    Continue()
  RESPONSE #100
    SetGlobal("MLS_1","LOCALS",2)
    Continue()
  RESPONSE #100
    SetGlobal("MLS_1","LOCALS",3)
    Continue()
  RESPONSE #100
    SetGlobal("MLS_1","LOCALS",4)
    Continue()
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",1)
  ActionListEmpty()
  NearLocation(Myself,2010,1314,4)
THEN
  RESPONSE #100
    SetStartPos([2010.1314])
    SetGlobal("ML_1","LOCALS",0)
    SetGlobal("MLS_1","LOCALS",0)
    Continue()
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",1)
  AttackedBy([ANYONE],0)
  Range(LastAttackerOf(Myself),5,LESS_THAN)
THEN
  RESPONSE #100
    MoveToPoint([2010.1314])
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",2)
  ActionListEmpty()
  NearLocation(Myself,1809,1529,4)
THEN
  RESPONSE #100
    SetStartPos([1809.1529])
    SetGlobal("ML_1","LOCALS",0)
    SetGlobal("MLS_1","LOCALS",0)
    Continue()
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",2)
  AttackedBy([ANYONE],0)
  Range(LastAttackerOf(Myself),5,LESS_THAN)
THEN
  RESPONSE #100
    MoveToPoint([1809.1529])
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",3)
  ActionListEmpty()
  NearLocation(Myself,2090,1644,4)
THEN
  RESPONSE #100
    SetStartPos([2090.1644])
    SetGlobal("ML_1","LOCALS",0)
    SetGlobal("MLS_1","LOCALS",0)
    Continue()
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",3)
  AttackedBy([ANYONE],0)
  Range(LastAttackerOf(Myself),5,LESS_THAN)
THEN
  RESPONSE #100
    MoveToPoint([2090.1644])
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",4)
  ActionListEmpty()
  NearLocation(Myself,2286,1440,4)
THEN
  RESPONSE #100
    SetStartPos([2286.1440])
    SetGlobal("ML_1","LOCALS",0)
    SetGlobal("MLS_1","LOCALS",0)
    Continue()
END

IF
  Global("ML_1","LOCALS",0)
  Global("MLS_1","LOCALS",4)
  AttackedBy([ANYONE],0)
  Range(LastAttackerOf(Myself),5,LESS_THAN)
THEN
  RESPONSE #100
    MoveToPoint([2286.1440])
END

