IF
  Clicked([PC])
  OpenState(Myself,FALSE)
THEN
  RESPONSE #100
    OpenDoor("AR4102_Switch4")
    OpenDoor("AR4102_Switch6")
    OpenDoor("AR4102_Switch7")
    OpenDoor("AR4102_Switch8")
    OpenDoor("AR4102_Switch9")
    OpenDoor("AR4102_Switch10")
    OpenDoor("AR4102_Switch11")
    OpenDoor("AR4102_Switch12")
    OpenDoor("AR4102_Switch13")
    FloatMessage("GameMaster",30925)  // ~"Rank two selected."~
    SetGlobal("BattleSquareRank","MYAREA",2)
END

