IF
  Global("CheckDaisCombination","MYAREA",1)
  Global("LastDaisRight","MYAREA",5)
  Global("LastDaisLeft","MYAREA",1)
THEN
  RESPONSE #100
    SetGlobal("CheckDaisCombination","MYAREA",0)
    SetGlobal("41PlayerLiftedShell","GLOBAL",1)
    SetGlobal("41NateSaidShell","GLOBAL",1)
    TriggerActivation("AntimagicAdd",FALSE)
    PlaySound("EFF_E01")
    DisplayMessage(32103)  // ~The prison's antimagic shroud has been lifted.~
END

IF
  Global("CheckDaisCombination","MYAREA",1)
  GlobalGT("41PartyPrisonEntry","GLOBAL",1)
  Global("LastDaisRight","MYAREA",7)
  Global("LastDaisLeft","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("CheckDaisCombination","MYAREA",0)
    Unlock("AR4101_Door5")
    Unlock("AR4101_Door7")
    Unlock("AR4101_Door8")
    Unlock("AR4101_Door10")
    Unlock("AR4101_Door11")
    Unlock("AR4101_Door12")
    Unlock("AR4101_Door17")
    Unlock("AR4101_Door20")
    Unlock("AR4101_Door21")
    Unlock("AR4101_Door22")
    Unlock("AR4101_Door23")
    Unlock("AR4101_Door24")
    DisplayMessage(33624)  // ~The sound of maniacal laughter fills the air then quickly fades away, followed by the subtle crackle of ice rubbing against frozen snow.~
END

IF
  Clicked([PC])
THEN
  RESPONSE #100
    SetGlobal("41PlayerSawDais","GLOBAL",1)
    Continue()
END

IF
  Clicked([PC])
  Range(LastTrigger,3,GREATER_THAN)
THEN
  RESPONSE #100
    SetGlobal("DaisLeftClick","MYAREA",1)
    ActionOverride(LastTrigger,MoveToPoint([1084.828]))
END

IF
  Or(2)
    Clicked([PC])
    Global("DaisLeftClick","MYAREA",1)
  Range(LastTrigger,4,LESS_THAN)
  Global("DaisSequence","MYAREA",0)
THEN
  RESPONSE #100
    PlaySound("AM4101b")
    PlaySequence("Dais",AWAKE)
    DisplayMessage(32072)  // ~The dais is currently facing west.~
    SetGlobal("DaisSequence","MYAREA",1)
    SetGlobal("LastDaisLeft","MYAREA",1)
    SetGlobal("DaisLeftClick","MYAREA",0)
    SetGlobal("CheckDaisCombination","MYAREA",1)
END

IF
  Or(2)
    Clicked([PC])
    Global("DaisLeftClick","MYAREA",1)
  Range(LastTrigger,4,LESS_THAN)
  Global("DaisSequence","MYAREA",1)
THEN
  RESPONSE #100
    PlaySound("AM4101b")
    PlaySequence("Dais",CAST)
    DisplayMessage(32071)  // ~The dais is currently facing southwest.~
    SetGlobal("DaisSequence","MYAREA",2)
    SetGlobal("LastDaisLeft","MYAREA",2)
    SetGlobal("DaisLeftClick","MYAREA",0)
END

IF
  Or(2)
    Clicked([PC])
    Global("DaisLeftClick","MYAREA",1)
  Range(LastTrigger,4,LESS_THAN)
  Global("DaisSequence","MYAREA",2)
THEN
  RESPONSE #100
    PlaySound("AM4101b")
    PlaySequence("Dais",CONJURE)
    DisplayMessage(32070)  // ~The dais is currently facing south.~
    SetGlobal("DaisSequence","MYAREA",3)
    SetGlobal("LastDaisLeft","MYAREA",3)
    SetGlobal("DaisLeftClick","MYAREA",0)
END

IF
  Or(2)
    Clicked([PC])
    Global("DaisLeftClick","MYAREA",1)
  Range(LastTrigger,4,LESS_THAN)
  Global("DaisSequence","MYAREA",3)
THEN
  RESPONSE #100
    PlaySound("AM4101b")
    PlaySequence("Dais",DAMAGE)
    DisplayMessage(32069)  // ~The dais is currently facing southeast.~
    SetGlobal("DaisSequence","MYAREA",4)
    SetGlobal("LastDaisLeft","MYAREA",4)
    SetGlobal("DaisLeftClick","MYAREA",0)
END

IF
  Or(2)
    Clicked([PC])
    Global("DaisLeftClick","MYAREA",1)
  Range(LastTrigger,4,LESS_THAN)
  Global("DaisSequence","MYAREA",4)
THEN
  RESPONSE #100
    PlaySound("AM4101b")
    PlaySequence("Dais",DIE)
    DisplayMessage(32068)  // ~The dais is currently facing east.~
    SetGlobal("DaisSequence","MYAREA",5)
    SetGlobal("LastDaisLeft","MYAREA",5)
    SetGlobal("DaisLeftClick","MYAREA",0)
END

IF
  Or(2)
    Clicked([PC])
    Global("DaisLeftClick","MYAREA",1)
  Range(LastTrigger,4,LESS_THAN)
  Global("DaisSequence","MYAREA",5)
THEN
  RESPONSE #100
    PlaySound("AM4101b")
    PlaySequence("Dais",HEAD_TURN)
    DisplayMessage(32067)  // ~The dais is currently facing northeast.~
    SetGlobal("DaisSequence","MYAREA",6)
    SetGlobal("LastDaisLeft","MYAREA",6)
    SetGlobal("DaisLeftClick","MYAREA",0)
END

IF
  Or(2)
    Clicked([PC])
    Global("DaisLeftClick","MYAREA",1)
  Range(LastTrigger,4,LESS_THAN)
  Global("DaisSequence","MYAREA",6)
THEN
  RESPONSE #100
    PlaySound("AM4101b")
    PlaySequence("Dais",READY)
    DisplayMessage(32066)  // ~The dais is currently facing north.~
    SetGlobal("DaisSequence","MYAREA",7)
    SetGlobal("LastDaisLeft","MYAREA",7)
    SetGlobal("DaisLeftClick","MYAREA",0)
END

IF
  Or(2)
    Clicked([PC])
    Global("DaisLeftClick","MYAREA",1)
  Range(LastTrigger,4,LESS_THAN)
  Global("DaisSequence","MYAREA",7)
THEN
  RESPONSE #100
    PlaySound("AM4101b")
    PlaySequence("Dais",ATTACK)
    DisplayMessage(32073)  // ~The dais is currently facing northwest.~
    SetGlobal("DaisSequence","MYAREA",0)
    SetGlobal("LastDaisLeft","MYAREA",0)
    SetGlobal("DaisLeftClick","MYAREA",0)
    SetGlobal("CheckDaisCombination","MYAREA",1)
END

