IF
  GlobalTimerNotExpired("PrismFireDelay","MYAREA")
THEN
  RESPONSE #100
    NoAction()
END

IF
  Global("41PrismTarget","MYAREA",1)
THEN
  RESPONSE #100
    ForceSpellPoint([940.326],2092)
    TriggerActivation(Myself,FALSE)
END

IF
  Global("41PrismTarget","MYAREA",2)
THEN
  RESPONSE #100
    ForceSpellPoint([502.766],2092)
    SetGlobalTimer("PrismFireDelay","MYAREA",1)
    TriggerActivation("Mirror9",TRUE)
    TriggerActivation(Myself,FALSE)
END

