IF
  Clicked([PC])
  !CheckDoorFlags(Myself,DOORLOCKED)
THEN
  RESPONSE #100
    PlaySound("AM4100d")
    OpenDoor("AR4100_Lever1_RocksDumped")
    SetDoorFlag("AR4100_Lever1_RocksDumped",HIDDEN,FALSE)
    ForceSpellPoint([1217.1548],2097)
    ForceSpellPoint([1217.1548],2097)
    ForceSpellPoint([1217.1548],2097)
    ForceSpellPoint([1217.1548],2097)
    ForceSpellPoint([1217.1548],2097)
    ForceSpellPoint([1217.1548],2097)
    ForceSpellPoint([1217.1548],2097)
    ForceSpellPoint([1217.1548],2097)
    Lock(Myself)
END

IF
  Clicked([PC])
  CheckDoorFlags(Myself,DOORLOCKED)
  OpenState(Myself,TRUE)
  OpenState("AR4100_Lever1_RocksDumped",FALSE)  // AR4100_Lever1_RocksDumped
  Range(LastTrigger,4,LESS_THAN)
  HasItem("41GenRP",LastTrigger)  // ~Rock Pile~
THEN
  RESPONSE #100
    ActionOverride(LastTrigger,DestroyItem("41GenRP"))  // ~Rock Pile~
    CloseDoor(Myself)
    Unlock(Myself)
END

IF
  Clicked([PC])
  CheckDoorFlags(Myself,DOORLOCKED)
  Range(LastTrigger,4,LESS_THAN)
  !HasItem("41GenRP",LastTrigger)  // ~Rock Pile~
THEN
  RESPONSE #100
    DisplayMessage(31992)  // ~This pole cannot be used to launch another deadfall until its rocks have been collected.~
END

