IF
  True()
THEN
  RESPONSE #100
    CutSceneId(NearestPC)  // 
    SetVisualRange(100)
    MultiPlayerSync()
    MoveViewPointUntilDone([426.371],15)
    SpellHitEffectPoint(Myself,[426.371],ACID_STORM,0)
    Wait(1)
    SpellHitEffectPoint(Myself,[345.342],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[449.273],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[493.264],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[501.303],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[460.303],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[492.325],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[415.307],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[458.362],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[429.410],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[484.390],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[370.380],DARKTREE_ATTACK,0)
    SpellHitEffectPoint(Myself,[415.278],DARKTREE_ATTACK,0)
    Wait(1)
    TriggerActivation("To5004",TRUE)
    OpenDoor("AR5015_North")
    AddJournalEntry(33414)
    AddXPVar("LEVEL_9_AVERAGE",33413)  // ~You have slain the Dark Treants and freed the Fell Wood from their warping influence.~
    Wait(1)
    MultiPlayerSync()
    SetGlobal("AR5003_DARK_TREE_CLEAR","GLOBAL",2)
    EndCutSceneMode()
    SetVisualRange(0)
    MoveViewObject([PC][0.0.10000.10000],15)
END

