IF
  True()
THEN
  RESPONSE #100
    CutSceneId("01_50Limha_01")  // 
    Enemy()
    SetGlobal("TEAM_1","MYAREA",1)
    SetGlobal("LIHMA_OUTSIDE","GLOBAL",1)
    SetGlobalTimer("LIMHA_TELEPORT_TIMER","GLOBAL",5)
    PlaySequence(Myself,CAST)
    Wait(1)
    SpellHitEffectSprite(Myself,Myself,DIMENSION_DOOR_ORIGIN,0)
    Wait(1)
    HideCreature(Myself,TRUE)
    DisplayMessage(33648)  // ~Limha- Dimension Door~
    Wait(1)
    EndCutSceneMode()
    DestroySelf()
END

