IF
  True()
THEN
  RESPONSE #100
    CutSceneId("07_50ISAIR_01")  // 
    FaceObject([PC])
    SpellHitEffectSprite(Myself,Myself,DIMENSION_DOOR_DESTINATION,0)
    HideCreature(Myself,FALSE)
    StartCutScene("50cTwin4")
    SetDialogueRange(300)
    Wait(2)
    UnhideGUI()
    MultiPlayerSync()
    Dialogue(Protagonist)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("07_50MADAE_02")  // 
    FaceObject([PC])
    SpellHitEffectSprite(Myself,Myself,DIMENSION_DOOR_DESTINATION,0)
    HideCreature(Myself,FALSE)
END

