IF
  True()
THEN
  RESPONSE #100
    CutSceneId("05_50Venla_02")  // 
    HideGUI()
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    MultiPlayerSync()
    Wait(1)
    FadeToColor([0.0],0)
    Wait(1)
    MoveViewPoint([2150.823],FASTEST)
    ClearSpriteEffects(Player1)
    ClearSpriteEffects(Player2)
    ClearSpriteEffects(Player3)
    ClearSpriteEffects(Player4)
    ClearSpriteEffects(Player5)
    ClearSpriteEffects(Player6)
    MultiPlayerSync()
    AdvanceTime(500)
    JumpToPoint([2070.930])
    StartCutScene("50cVenl2")
    HideCreature("ZOMBIE_1",TRUE)
    HideCreature("ZOMBIE_2",TRUE)
    HideCreature("ZOMBIE_3",TRUE)
    HideCreature("ZOMBIE_4",TRUE)
    HideCreature("ZOMBIE_5",TRUE)
    MoveViewPoint([2150.823],INSTANT)
    CreateCreature("50HNT","HUNTER_1_NEW",[2005.1070],0)  // ~Hunter~
    ActionOverride(LastMarkedObject,FaceObject([PC]))
    CreateCreature("50HNT","HUNTER_2_NEW",[1985.1150],10)  // ~Hunter~
    ActionOverride(LastMarkedObject,FaceObject([PC]))
    CreateCreature("50HNT2","HUNTER_3_NEW",[1955.1110],12)  // ~Hunter~
    ActionOverride(LastMarkedObject,FaceObject([PC]))
    CreateCreature("50HNT2","HUNTER_4_NEW",[2055.1105],4)  // ~Hunter~
    ActionOverride(LastMarkedObject,FaceObject([PC]))
    CreateCreature("50HNT3","HUNTER_5_NEW",[2040.1150],6)  // ~Hunter~
    ActionOverride(LastMarkedObject,FaceObject([PC]))
    FaceObject([PC])
    HideCreature(Myself,FALSE)
    MultiPlayerSync()
    SetDialogueRange(300)
    MultiPlayerSync()
    StartCutScene("50cVenl1")
    FadeFromColor([0.0],0)
    Wait(1)
    Wait(2)
    MultiPlayerSync()
    Dialogue([PC])
END

