IF
  !TimerActive(18)
THEN
  RESPONSE #15
    FloatMessage(Myself,17035)  // ~"I wonder where that Pairi's gone off to..."~
    StartRandomTimer(18,15,20)
  RESPONSE #15
    FloatMessage(Myself,17036)  // ~"Hmm... I'd best gather more herbs for next month."~
    StartRandomTimer(18,15,20)
  RESPONSE #170
    StartRandomTimer(18,15,20)
END

IF
  !TimerActive(19)
  !NearSavedLocation(4)
THEN
  RESPONSE #100
    ReturnToSavedLocation(0)
    StartTimer(19,5)
END

