IF
  !TimerActive(18)
  !CreatureHidden(Myself)
  !See([ENEMY],0)
THEN
  RESPONSE #15
    FloatMessage(Myself,17070)  // ~"So much to do today..."~
    StartRandomTimer(18,15,20)
    Continue()
  RESPONSE #15
    FloatMessage(Myself,17071)  // ~"That *should* be enough to last the rest of the month..."~
    StartRandomTimer(18,15,20)
    Continue()
  RESPONSE #15
    FloatMessage(Myself,17072)  // ~"I wonder if there's anything else I needed...?"~
    StartRandomTimer(18,15,20)
    Continue()
  RESPONSE #255
    StartRandomTimer(18,15,20)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,2150,840,4)
THEN
  RESPONSE #100
    SetStartPos([2150.840])
    SetGlobal("ML_0","LOCALS",1)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
THEN
  RESPONSE #100
    MoveToPoint([2150.840])
END

IF
  Global("ML_0","LOCALS",1)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",2)
END

IF
  Global("ML_0","LOCALS",2)
  ActionListEmpty()
  NearLocation(Myself,2270,915,4)
THEN
  RESPONSE #100
    SetStartPos([2270.915])
    SetGlobal("ML_0","LOCALS",3)
    Continue()
END

IF
  Global("ML_0","LOCALS",2)
THEN
  RESPONSE #100
    MoveToPoint([2270.915])
END

IF
  Global("ML_0","LOCALS",3)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",4)
END

IF
  Global("ML_0","LOCALS",4)
  ActionListEmpty()
  NearLocation(Myself,2270,680,4)
THEN
  RESPONSE #100
    SetStartPos([2270.680])
    SetGlobal("ML_0","LOCALS",5)
    Continue()
END

IF
  Global("ML_0","LOCALS",4)
THEN
  RESPONSE #100
    MoveToPoint([2270.680])
END

IF
  Global("ML_0","LOCALS",5)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",6)
END

IF
  Global("ML_0","LOCALS",6)
  NearSavedLocation(4)
THEN
  RESPONSE #100
    SetGlobal("ML_0","LOCALS",7)
    SetStartPos([-1.-1])
    Continue()
END

IF
  Global("ML_0","LOCALS",6)
  !TimerActive(19)
  !NearSavedLocation(4)
THEN
  RESPONSE #100
    ReturnToSavedLocation(0)
END

IF
  Global("ML_0","LOCALS",7)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",0)
END

