IF
  !TimerActive(18)
  !CreatureHidden(Myself)
  !See([ENEMY],0)
THEN
  RESPONSE #15
    FloatMessage(Myself,17070)  // ~"So much to do today..."~
    StartRandomTimer(18,15,20)
    Continue()
  RESPONSE #15
    FloatMessage(Myself,17071)  // ~"That *should* be enough to last the rest of the month..."~
    StartRandomTimer(18,15,20)
    Continue()
  RESPONSE #15
    FloatMessage(Myself,17072)  // ~"I wonder if there's anything else I needed...?"~
    StartRandomTimer(18,15,20)
    Continue()
  RESPONSE #255
    StartRandomTimer(18,15,20)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,1920,640,4)
THEN
  RESPONSE #100
    SetStartPos([1920.640])
    SetGlobal("ML_0","LOCALS",1)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
THEN
  RESPONSE #100
    MoveToPoint([1920.640])
END

IF
  Global("ML_0","LOCALS",1)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",2)
END

IF
  Global("ML_0","LOCALS",2)
  ActionListEmpty()
  NearLocation(Myself,1920,770,4)
THEN
  RESPONSE #100
    SetStartPos([1920.770])
    SetGlobal("ML_0","LOCALS",3)
    Continue()
END

IF
  Global("ML_0","LOCALS",2)
THEN
  RESPONSE #100
    MoveToPoint([1920.770])
END

IF
  Global("ML_0","LOCALS",3)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",4)
END

IF
  Global("ML_0","LOCALS",4)
  ActionListEmpty()
  NearLocation(Myself,1995,835,4)
THEN
  RESPONSE #100
    SetStartPos([1995.835])
    SetGlobal("ML_0","LOCALS",5)
    Continue()
END

IF
  Global("ML_0","LOCALS",4)
THEN
  RESPONSE #100
    MoveToPoint([1995.835])
END

IF
  Global("ML_0","LOCALS",5)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",6)
END

IF
  Global("ML_0","LOCALS",6)
  ActionListEmpty()
  NearLocation(Myself,2075,755,4)
THEN
  RESPONSE #100
    SetStartPos([2075.755])
    SetGlobal("ML_0","LOCALS",7)
    Continue()
END

IF
  Global("ML_0","LOCALS",6)
THEN
  RESPONSE #100
    MoveToPoint([2075.755])
END

IF
  Global("ML_0","LOCALS",7)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",8)
END

IF
  Global("ML_0","LOCALS",8)
  NearSavedLocation(4)
THEN
  RESPONSE #100
    SetGlobal("ML_0","LOCALS",9)
    SetStartPos([-1.-1])
    Continue()
END

IF
  Global("ML_0","LOCALS",8)
  !TimerActive(19)
  !NearSavedLocation(4)
THEN
  RESPONSE #100
    ReturnToSavedLocation(0)
END

IF
  Global("ML_0","LOCALS",9)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,1)
    SetGlobal("ML_0","LOCALS",0)
END

