IF
  !Global("TEAM_7","MYAREA",0)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  !Global("TEAM_7","MYAREA",0)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  Global("TEAM_7","MYAREA",0)
  !Global("Rock_Row_1_Moved","MYAREA",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    PlaySound("am1000j")
    SetGlobal("TEAM_7","MYAREA",1)
    SetGlobal("TEAM_5","MYAREA",1)
    SetInterrupt(TRUE)
END

