IF
  !TimerActive(5)
  !CreatureHidden(Myself)
  HitBy([GOODCUTOFF],CRUSHING)
THEN
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([485.369])
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([1110.463])
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([1682.561])
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([433.616])
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([1370.787])
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([2101.538])
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([68.1249])
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([1527.1005])
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,FALSE)
    HideCreature(Myself,TRUE)
    StartRandomTimer(5,3,7)
    JumpToPoint([2745.971])
END

IF
  CreatureHidden(Myself)
  !TimerActive(5)
  !Range(NearestPC,5,GREATER_THAN)
THEN
  RESPONSE #100
    XEquipItem("00CIWSP2",Myself,SLOT_AMULET,TRUE)
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  CreatureHidden(Myself)
  !TimerActive(5)
  Range([PC],5,GREATER_THAN)
THEN
  RESPONSE #100
    JumpToObject(NearestPC)
END

IF
  !CreatureHidden(Myself)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackReevaluate(LastMarkedObject,180)
END

IF
  !TimerActive(19)
  !CreatureHidden(Myself)
  !Range(NearestPC,4,LESS_THAN)
THEN
  RESPONSE #100
    MoveToObject(NearestPC)
    StartTimer(19,5)
END

IF
  CreatureHidden(Myself)
  ActionListEmpty()
THEN
  RESPONSE #100
    RandomWalk()
END

