IF
  GlobalLT("50Dragon","GLOBAL",3)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    SetGlobal("50Dragon","GLOBAL",3)
    Continue()
END

IF
  GlobalTimerExpired("DRAGON_BREATH","LOCALS")
  See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(LastMarkedObject,INNATE_DRAGON_BREATH_REDUCED_DAMAGE,SPELLCAST_IGNORE_HAS_CHECK)
THEN
  RESPONSE #100
    SetGlobalTimer("DRAGON_BREATH","LOCALS",20)
    ForceSpell(LastMarkedObject,INNATE_DRAGON_BREATH_REDUCED_DAMAGE)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  AttackedBy([GOODCUTOFF],0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

