IF
  Allegiance(Myself,ENEMY)
  Or(2)
    See([GOODCUTOFF.0.0.0.150],0)
    See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  !Dead("13_51Barud_04")  // 
THEN
  RESPONSE #100
    MoveToObjectFollow("13_51Barud_04")
END

IF
  ActionListEmpty()
  Allegiance(Myself,ENEMY)
  !Dead([GOODCUTOFF.0.0.0.150][0.0.10000.10000])  // 
THEN
  RESPONSE #100
    MoveToObjectUntilSee([GOODCUTOFF.0.0.0.150][0.0.10000.10000])
END

