IF
  !IsCreatureAreaFlag(Myself,IGNORE_AI_INHIBIT)
THEN
  RESPONSE #100
    SetCreatureAreaFlag(Myself,IGNORE_AI_INHIBIT,TRUE)
    Continue()
END

IF
  CreatureHidden(Myself)
  !Global("TEAM_12","MYAREA",0)
THEN
  RESPONSE #100
    SpellHitEffectSprite(Myself,Myself,SLOW_POISON,10)
    Wait(1)
    FaceObject(NearestPC)
    HideCreature(Myself,FALSE)
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

