IF
  !Global("TEAM_0","MYAREA",1)
  Or(2)
    AttackedBy([GOODCUTOFF],0)
    PickPocketFailed([PC])
THEN
  RESPONSE #100
    SetGlobal("TEAM_0","MYAREA",1)
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !Global("TEAM_0","MYAREA",0)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  !IsTeamBitOn(TEAM_1_BIT)
THEN
  RESPONSE #100
    SetTeamBit(TEAM_1_BIT,TRUE)
    Continue()
END

IF
  Or(2)
    !Global("TEAM_0","MYAREA",1)
    !Global("TEAM_1","MYAREA",1)
  Allegiance(Myself,ENEMY)
  !CreatureHidden(Myself)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    SetGlobal("TEAM_0","MYAREA",1)
    SetGlobal("TEAM_1","MYAREA",1)
    Continue()
END

