IF
  Or(2)
    !Global("52Morohem_Master","GLOBAL",5)
    Global("WATCHING_PLAYER","MYAREA",0)
  Or(2)
    !CheckDoorFlags(Myself,DOORLOCKED)
    OpenState(Myself,TRUE)
THEN
  RESPONSE #100
    Unlock(Myself)
    CloseDoor(Myself)
    Lock(Myself)
END

IF
  Global("CHAMBER_5_NO_FIRE","MYAREA",0)
  !Global("WATCHING_PLAYER","MYAREA",0)
  Global("52Morohem_Master","GLOBAL",5)
  !CheckDoorFlags(Myself,DOORLOCKED)
  OpenState(Myself,TRUE)
THEN
  RESPONSE #100
    Lock(Myself)
    ForceSpellPoint([1950.1226],WIZARD_AGANNAZAR_SCORCHER)
END

IF
  Or(2)
    CheckDoorFlags(Myself,DOORLOCKED)
    !Global("CHAMBER_5_NO_FIRE","MYAREA",0)
THEN
  RESPONSE #100
    NoAction()
END

