IF
  GlobalGT("52Morohem_Master","GLOBAL",7)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("52Morohem_Master","GLOBAL",7)
  !Global("WATCHING_PLAYER","MYAREA",0)
  Global("C7_WATCHER_2A_STATE","MYAREA",0)
  Or(4)
    Range([PC],2,LESS_THAN)
    Range("C7_MONK_1",2,LESS_THAN)  // C7_MONK_1
    Range("C7_MONK_2",2,LESS_THAN)  // C7_MONK_2
    Range([ENEMY],2,LESS_THAN)
THEN
  RESPONSE #100
    SetGlobal("C7_WATCHER_2A_STATE","MYAREA",1)
    Continue()
END

IF
  Global("52Morohem_Master","GLOBAL",7)
  !Global("WATCHING_PLAYER","MYAREA",0)
  Global("C7_WATCHER_2A_STATE","MYAREA",1)
  OpenState("AR5202_Switch11",FALSE)  // AR5202_Switch11
  !Range([PC],2,LESS_THAN)
  !Range("C7_MONK_1",2,LESS_THAN)  // C7_MONK_1
  !Range("C7_MONK_2",2,LESS_THAN)  // C7_MONK_2
  !Range([ENEMY],2,LESS_THAN)
THEN
  RESPONSE #100
    SetGlobal("C7_WATCHER_2A_STATE","MYAREA",0)
    Continue()
END

IF
  Global("52Morohem_Master","GLOBAL",7)
  !Global("WATCHING_PLAYER","MYAREA",0)
  OpenState("AR5202_Switch11",FALSE)  // AR5202_Switch11
  CheckDoorFlags("AR5202_Switch11",DOORLOCKED)  // AR5202_Switch11
  Global("C7_WATCHER_2A_STATE","MYAREA",1)
  Global("C7_WATCHER_2B_STATE","MYAREA",1)
THEN
  RESPONSE #100
    Unlock("AR5202_Switch11")
    SpellHitEffectSprite("C7_SWITCH_EFFECT_LEFT","C7_SWITCH_EFFECT_LEFT",CURSE,0)
    DisplayMessage(38104)  // ~A nearby mechanism has unlocked.~
END

IF
  Global("52Morohem_Master","GLOBAL",7)
  !Global("WATCHING_PLAYER","MYAREA",0)
  OpenState("AR5202_Switch11",FALSE)  // AR5202_Switch11
  !CheckDoorFlags("AR5202_Switch11",DOORLOCKED)  // AR5202_Switch11
  Or(2)
    Global("C7_WATCHER_2A_STATE","MYAREA",0)
    Global("C7_WATCHER_2B_STATE","MYAREA",0)
THEN
  RESPONSE #100
    Lock("AR5202_Switch11")
    SpellHitEffectSprite("C7_PORTAL_2A","C7_PORTAL_2A",RECITATION,0)
    DisplayMessage(39363)  // ~A nearby mechanism has relocked itself.~
END

