IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    SetGlobal("50DUERGAR_DESTROY","GLOBAL",1)
    MultiPlayerSync()
    MoveViewObject(NearestPC,INSTANT)
    SetVisualRange(0)
    MultiPlayerSync()
    SmallWait(10)
    ActionOverride(Player1,FaceObject(NearestEnemyOf(Myself)))
    ActionOverride(Player2,FaceObject(NearestEnemyOf(Myself)))
    ActionOverride(Player3,FaceObject(NearestEnemyOf(Myself)))
    ActionOverride(Player4,FaceObject(NearestEnemyOf(Myself)))
    ActionOverride(Player5,FaceObject(NearestEnemyOf(Myself)))
    ActionOverride(Player6,FaceObject(NearestEnemyOf(Myself)))
    Wait(1)
    MultiPlayerSync()
    EndCutSceneMode()
END

