IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    ClearAllActions()
    MultiPlayerSync()
    Wait(1)
    StartCutSceneMode()
    ActionOverride("08_52MNKCRG_01",DestroySelf())
    ActionOverride("08_52MNKCRG_02",DestroySelf())
    SetGlobal("CHAMBER_3_SWITCH_ACTIVE","MYAREA",0)
    ChangeEnemyAlly(Player1,PC)
    ChangeEnemyAlly(Player2,PC)
    ChangeEnemyAlly(Player3,PC)
    ChangeEnemyAlly(Player4,PC)
    ChangeEnemyAlly(Player5,PC)
    ChangeEnemyAlly(Player6,PC)
    MoveViewPointUntilDone([585.640],25)
    ResetJoinRequests()
    MultiPlayerSync()
    SetGlobal("FORCE_PARTY_EA","MYAREA",1)
    MultiPlayerSync()
    EndCutSceneMode()
END

