IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    MultiPlayerSync()
    StopJoinRequests()
    MultiPlayerSync()
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    MultiPlayerSync()
    FaceObject(Player6)
    MoveViewObject(Player6,15)
    Wait(1)
    ClearSpriteEffects(Player6)
    ChangeEnemyAlly(Player1,NEUTRAL)
    ChangeEnemyAlly(Player2,NEUTRAL)
    ChangeEnemyAlly(Player3,NEUTRAL)
    ChangeEnemyAlly(Player4,NEUTRAL)
    ChangeEnemyAlly(Player5,NEUTRAL)
    ActionOverride(Player6,SetSavedLocation())
    PlaySequence(Myself,SHOOT)
    SmallWait(5)
    SpellHitEffectSprite(Player6,Player6,SOLS_SEARING_ORB,10)
    SmallWait(5)
    SpellHitEffectSprite(Player6,Player6,CONE_OF_COLD,10)
    SmallWait(5)
    HideCreature(Player6,TRUE)
    ActionOverride(Player6,JumpToPoint([2045.860]))
    SetGlobal("WATCHING_PLAYER","MYAREA",6)
    SetGlobal("5200_SPIPW_DEAD","GLOBAL",0)
    MultiPlayerSync()
    CreateCreature("52SpiPW","05_52SPIPW_1",[1595.780],2)  // ~Poisonweb Spider~
    CreateCreature("52SpiPW","05_52SPIPW_2",[1805.905],10)  // ~Poisonweb Spider~
    CreateCreature("52SpiPW","05_52SPIPW_3",[1735.745],6)  // ~Poisonweb Spider~
    CreateCreature("52SpiPW","05_52SPIPW_4",[1775.765],14)  // ~Poisonweb Spider~
    CreateCreature("52SpiPW","05_52SPIPW_5",[1835.685],0)  // ~Poisonweb Spider~
    CreateCreature("52SpiPW","05_52SPIPW_6",[1810.670],0)  // ~Poisonweb Spider~
    CreateCreature("52SpiPW","05_52SPIPW_7",[1594.880],4)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_8",[1880.1080],8)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_9",[2100.900],4)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_10",[1975.995],4)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_11",[1915.1055],6)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_12",[1795.1100],8)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_13",[1705.1055],8)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_14",[1560.975],8)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_15",[1485.940],10)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_16",[1630.1015],10)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_17",[2040.945],4)  // ~Poisonweb Spider~
    CreateCreature("52SPIPWr","05_52SPIPW_18",[2160.855],4)  // ~Poisonweb Spider~
    MultiPlayerSync()
    ActionOverride(Player6,Face(NW))
    MoveViewPoint([2045.860],20)
    Wait(3)
    SpellHitEffectSprite(Player6,Player6,SOLS_SEARING_ORB,10)
    SmallWait(5)
    SpellHitEffectSprite(Player6,Player6,CONE_OF_COLD,10)
    SmallWait(5)
    HideCreature(Player6,FALSE)
    Wait(1)
    MultiPlayerSync()
    EndCutSceneMode()
END

