IF
  !TimerActive(18)
THEN
  RESPONSE #100
    FloatMessage(Myself,20770)  // ~"No, no - like *this.*"~
    StartRandomTimer(18,5,10)
    PlaySequence(Myself,ATTACK)
    SmallWait(4)
  RESPONSE #100
    FloatMessage(Myself,20771)  // ~"Use your hips, not your shoulders."~
    StartRandomTimer(18,5,10)
    PlaySequence(Myself,ATTACK)
    SmallWait(4)
  RESPONSE #100
    FloatMessage(Myself,20772)  // ~"Yes, well done.  Continue."~
    StartRandomTimer(18,5,10)
    PlaySequence(Myself,ATTACK)
    SmallWait(4)
END

IF
  Global("ML_0","LOCALS",0)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,2)
    SetGlobal("ML_0","LOCALS",1)
END

IF
  Global("ML_0","LOCALS",1)
  !TimerActive(19)
THEN
  RESPONSE #100
    Face(N)
    SetGlobal("ML_0","LOCALS",2)
END

IF
  Global("ML_0","LOCALS",2)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,4)
    SetGlobal("ML_0","LOCALS",3)
END

IF
  Global("ML_0","LOCALS",3)
  !TimerActive(19)
THEN
  RESPONSE #100
    Face(NE)
    SetGlobal("ML_0","LOCALS",4)
END

IF
  Global("ML_0","LOCALS",4)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,2)
    SetGlobal("ML_0","LOCALS",5)
END

IF
  Global("ML_0","LOCALS",5)
  !TimerActive(19)
THEN
  RESPONSE #100
    Face(E)
    SetGlobal("ML_0","LOCALS",6)
END

IF
  Global("ML_0","LOCALS",6)
  !TimerActive(19)
THEN
  RESPONSE #100
    StartTimer(19,4)
    SetGlobal("ML_0","LOCALS",7)
END

IF
  Global("ML_0","LOCALS",7)
  !TimerActive(19)
THEN
  RESPONSE #100
    Face(NE)
    SetGlobal("ML_0","LOCALS",0)
END

