IF
  Global("52Ven_Loot","GLOBAL",4)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("VEN_GET_LOOT","LOCALS",4)
  !IsCreatureHiddenInShadows(Myself)
  !TimerActive(4)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    StartRandomTimer(4,3,9)
    ForceHide(Myself)
END

IF
  AttackedBy([GOODCUTOFF],0)
  NearSavedLocation(3)
THEN
  RESPONSE #100
    SetSavedLocationPoint(276,1276,S)
    ChangeCurrentScript("52VenH2")
  RESPONSE #100
    SetSavedLocationPoint(1175,1143,S)
    ChangeCurrentScript("52VenH3")
  RESPONSE #100
    SetSavedLocationPoint(2296,946,S)
    ChangeCurrentScript("52VenH4")
END

IF
  !IsCreatureHiddenInShadows(Myself)
  See(NearestEnemyOf(Myself),0)
  NearSavedLocation(3)
THEN
  RESPONSE #100
    SetSavedLocationPoint(276,1276,S)
    ChangeCurrentScript("52VenH2")
  RESPONSE #100
    SetSavedLocationPoint(1175,1143,S)
    ChangeCurrentScript("52VenH3")
  RESPONSE #100
    SetSavedLocationPoint(2296,946,S)
    ChangeCurrentScript("52VenH4")
END

IF
  !IsCreatureHiddenInShadows(Myself)
  !NearSavedLocation(3)
  Or(2)
    See(NearestEnemyOf(Myself),0)
    AttackedBy(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    RunAwayFrom(LastSeenBy,45)
END

IF
  !NearSavedLocation(3)
THEN
  RESPONSE #100
    MoveToPoint([-2.-2])
END

