IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DroPr")  // 
    HideCreature(Myself,FALSE)
    SetDialogueRange(300)
    Wait(1)
    Dialogue([PC])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosSS_01")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosSS_02")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosSS_03")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosAs_01")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosAs_02")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosAs_03")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosAs_04")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosAs_05")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosAs_06")  // 
    HideCreature(Myself,FALSE)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("53DrosAs_07")  // 
    HideCreature(Myself,FALSE)
END

