IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    MultiPlayerSync()
    StopJoinRequests()
    SetGlobal("RJ_AR6000","GLOBAL",1)
    MultiPlayerSync()
    EndCutSceneMode()
    StartCutScene("LUA6000a")
END

