IF
  Global("Alert_Teams","LOCALS",0)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    SetGlobal("Alert_Teams","LOCALS",1)
    SetGlobal("TEAM_4","MYAREA",1)
    SetGlobal("TEAM_8","MYAREA",1)
    SetGlobal("TEAM_9","MYAREA",1)
    SetGlobal("TEAM_10","MYAREA",1)
    SetGlobal("TEAM_11","MYAREA",1)
    SetGlobal("TEAM_13","MYAREA",1)
    Continue()
END

IF
  NumberOfTimesTalkedTo(0)
  !Allegiance(Myself,ENEMY)
  !Dead(Myself)  // 
  See([PC],0)
THEN
  RESPONSE #100
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("32193220",LastMarkedObject,15)
      // INNATE_ULTRABLAST
      // INNATE_MASS_DOMINATE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    ForceSpell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

