IF
  NumberOfTimesTalkedTo(0)
  !Allegiance(Myself,ENEMY)
  !Dead(Myself)  // 
  See([PC],0)
THEN
  RESPONSE #100
    Dialogue(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  SetLastMarkedObject(Myself)
THEN
  RESPONSE #100
    MarkSpellAndObject("221221142201",Myself,3)
      // WIZARD_MIRROR_IMAGE
      // WIZARD_SHIELD
      // WIZARD_BLUR
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    OpenDoor("AR5301_Cells")
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
    Continue()
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("26152404211821032308240124242510",LastMarkedObject,7)
      // WIZARD_FLESH_TO_STONE
      // WIZARD_ICE_STORM
      // WIZARD_CHROMATIC_ORB
      // WIZARD_BURNING_HANDS
      // WIZARD_LIGHTNING_BOLT
      // WIZARD_CONFUSION
      // WIZARD_VITRIOLIC_SPHERE
      // WIZARD_FEEBLEMIND
    MarkSpellAndObject("25192227",Myself,7)
      // WIZARD_SUNFIRE
      // WIZARD_GEDLEES_ELECTRIC_LOOP
    MarkSpellAndObject("2304222224222504231221122319",LastMarkedObject,7)
      // WIZARD_FIREBALL
      // WIZARD_BLINDNESS
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_CONE_OF_COLD
      // WIZARD_SLOW
      // WIZARD_MAGIC_MISSILE
      // WIZARD_LANCE_OF_DISRUPTION
    MarkSpellAndObject("24112505",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_SUMMON_MONSTER_V
    MarkSpellAndObject("2305","Spithdrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Celeridrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Cradoldrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    Continue()
  RESPONSE #100
    MarkSpellAndObject("25192227",Myself,7)
      // WIZARD_SUNFIRE
      // WIZARD_GEDLEES_ELECTRIC_LOOP
    MarkSpellAndObject("2304222224222504231221122319",LastMarkedObject,7)
      // WIZARD_FIREBALL
      // WIZARD_BLINDNESS
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_CONE_OF_COLD
      // WIZARD_SLOW
      // WIZARD_MAGIC_MISSILE
      // WIZARD_LANCE_OF_DISRUPTION
    MarkSpellAndObject("24112505",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_SUMMON_MONSTER_V
    MarkSpellAndObject("2305","Spithdrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Celeridrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Cradoldrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("26152404211821032308240124242510",LastMarkedObject,7)
      // WIZARD_FLESH_TO_STONE
      // WIZARD_ICE_STORM
      // WIZARD_CHROMATIC_ORB
      // WIZARD_BURNING_HANDS
      // WIZARD_LIGHTNING_BOLT
      // WIZARD_CONFUSION
      // WIZARD_VITRIOLIC_SPHERE
      // WIZARD_FEEBLEMIND
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2304222224222504231221122319",LastMarkedObject,7)
      // WIZARD_FIREBALL
      // WIZARD_BLINDNESS
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_CONE_OF_COLD
      // WIZARD_SLOW
      // WIZARD_MAGIC_MISSILE
      // WIZARD_LANCE_OF_DISRUPTION
    MarkSpellAndObject("24112505",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_SUMMON_MONSTER_V
    MarkSpellAndObject("2305","Spithdrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Celeridrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Cradoldrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("26152404211821032308240124242510",LastMarkedObject,7)
      // WIZARD_FLESH_TO_STONE
      // WIZARD_ICE_STORM
      // WIZARD_CHROMATIC_ORB
      // WIZARD_BURNING_HANDS
      // WIZARD_LIGHTNING_BOLT
      // WIZARD_CONFUSION
      // WIZARD_VITRIOLIC_SPHERE
      // WIZARD_FEEBLEMIND
    MarkSpellAndObject("25192227",Myself,7)
      // WIZARD_SUNFIRE
      // WIZARD_GEDLEES_ELECTRIC_LOOP
    Continue()
  RESPONSE #100
    MarkSpellAndObject("24112505",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_SUMMON_MONSTER_V
    MarkSpellAndObject("2305","Spithdrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Celeridrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Cradoldrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("26152404211821032308240124242510",LastMarkedObject,7)
      // WIZARD_FLESH_TO_STONE
      // WIZARD_ICE_STORM
      // WIZARD_CHROMATIC_ORB
      // WIZARD_BURNING_HANDS
      // WIZARD_LIGHTNING_BOLT
      // WIZARD_CONFUSION
      // WIZARD_VITRIOLIC_SPHERE
      // WIZARD_FEEBLEMIND
    MarkSpellAndObject("25192227",Myself,7)
      // WIZARD_SUNFIRE
      // WIZARD_GEDLEES_ELECTRIC_LOOP
    MarkSpellAndObject("2304222224222504231221122319",LastMarkedObject,7)
      // WIZARD_FIREBALL
      // WIZARD_BLINDNESS
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_CONE_OF_COLD
      // WIZARD_SLOW
      // WIZARD_MAGIC_MISSILE
      // WIZARD_LANCE_OF_DISRUPTION
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2305","Spithdrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Celeridrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Cradoldrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("26152404211821032308240124242510",LastMarkedObject,7)
      // WIZARD_FLESH_TO_STONE
      // WIZARD_ICE_STORM
      // WIZARD_CHROMATIC_ORB
      // WIZARD_BURNING_HANDS
      // WIZARD_LIGHTNING_BOLT
      // WIZARD_CONFUSION
      // WIZARD_VITRIOLIC_SPHERE
      // WIZARD_FEEBLEMIND
    MarkSpellAndObject("25192227",Myself,7)
      // WIZARD_SUNFIRE
      // WIZARD_GEDLEES_ELECTRIC_LOOP
    MarkSpellAndObject("2304222224222504231221122319",LastMarkedObject,7)
      // WIZARD_FIREBALL
      // WIZARD_BLINDNESS
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_CONE_OF_COLD
      // WIZARD_SLOW
      // WIZARD_MAGIC_MISSILE
      // WIZARD_LANCE_OF_DISRUPTION
    MarkSpellAndObject("24112505",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_SUMMON_MONSTER_V
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2305","Celeridrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Cradoldrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("26152404211821032308240124242510",LastMarkedObject,7)
      // WIZARD_FLESH_TO_STONE
      // WIZARD_ICE_STORM
      // WIZARD_CHROMATIC_ORB
      // WIZARD_BURNING_HANDS
      // WIZARD_LIGHTNING_BOLT
      // WIZARD_CONFUSION
      // WIZARD_VITRIOLIC_SPHERE
      // WIZARD_FEEBLEMIND
    MarkSpellAndObject("25192227",Myself,7)
      // WIZARD_SUNFIRE
      // WIZARD_GEDLEES_ELECTRIC_LOOP
    MarkSpellAndObject("2304222224222504231221122319",LastMarkedObject,7)
      // WIZARD_FIREBALL
      // WIZARD_BLINDNESS
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_CONE_OF_COLD
      // WIZARD_SLOW
      // WIZARD_MAGIC_MISSILE
      // WIZARD_LANCE_OF_DISRUPTION
    MarkSpellAndObject("24112505",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_SUMMON_MONSTER_V
    MarkSpellAndObject("2305","Spithdrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2305","Cradoldrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("26152404211821032308240124242510",LastMarkedObject,7)
      // WIZARD_FLESH_TO_STONE
      // WIZARD_ICE_STORM
      // WIZARD_CHROMATIC_ORB
      // WIZARD_BURNING_HANDS
      // WIZARD_LIGHTNING_BOLT
      // WIZARD_CONFUSION
      // WIZARD_VITRIOLIC_SPHERE
      // WIZARD_FEEBLEMIND
    MarkSpellAndObject("25192227",Myself,7)
      // WIZARD_SUNFIRE
      // WIZARD_GEDLEES_ELECTRIC_LOOP
    MarkSpellAndObject("2304222224222504231221122319",LastMarkedObject,7)
      // WIZARD_FIREBALL
      // WIZARD_BLINDNESS
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_CONE_OF_COLD
      // WIZARD_SLOW
      // WIZARD_MAGIC_MISSILE
      // WIZARD_LANCE_OF_DISRUPTION
    MarkSpellAndObject("24112505",FarthestEnemyOf(Myself),SPELLCAST_RANDOM)
      // WIZARD_EMOTION_HOPELESSNESS
      // WIZARD_SUMMON_MONSTER_V
    MarkSpellAndObject("2305","Spithdrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    MarkSpellAndObject("2305","Celeridrider",SPELLCAST_RANDOM)
      // WIZARD_HASTE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    ClearActions("53GolIm_01")
    ClearActions("53GolIm_02")
    ChangeSpecifics([GOODCUTOFF.0.0.0.0.255][0.0.10000.10000],0)
    ChangeSpecifics(LastMarkedObject,255)
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  Global("OBJ_SP_53IMPHRC_2","LOCALS",-1)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    ClearActions("53GolIm_01")
    ClearActions("53GolIm_02")
    ChangeSpecifics([GOODCUTOFF.0.0.0.0.255][0.0.10000.10000],0)
    ChangeSpecifics(LastMarkedObject,255)
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

