IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  !Global("OBJ_SP_53KADREC_0","LOCALS",-1)
  Allegiance(Myself,ENEMY)
  SetLastMarkedObject(Myself)
THEN
  RESPONSE #100
    MarkSpellAndObject("12151115",Myself,7)
      // CLERIC_DRAW_UPON_HOLY_MIGHT
      // CLERIC_ARMOR_OF_FAITH
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
    SetGlobal("OBJ_SP_53KADREC_0","LOCALS",-1)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Or(2)
    See(NearestEnemyOf(Myself),0)
    See([0.0.DRIDER],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("23061304150314171418132523062306",LastMarkedObject,3)
      // WIZARD_HOLD_PERSON
      // CLERIC_GLYPH_OF_WARDING
      // CLERIC_FLAME_STRIKE
      // CLERIC_CLOUD_OF_PESTILENCE
      // CLERIC_POISON
      // CLERIC_UNHOLY_BLIGHT
      // WIZARD_HOLD_PERSON
      // WIZARD_HOLD_PERSON
    MarkSpellAndObject("1304",LastMarkedObject,3)
      // CLERIC_GLYPH_OF_WARDING
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  Or(2)
    See(NearestEnemyOf(Myself),0)
    See([0.0.DRIDER],0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

