IF
  Global("ML_0","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,690,1950,4)
THEN
  RESPONSE #100
    SetStartPos([690.1950])
    SetGlobal("ML_0","LOCALS",1)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([690.1950])
END

IF
  Global("ML_0","LOCALS",1)
  ActionListEmpty()
  NearLocation(Myself,1070,2280,4)
THEN
  RESPONSE #100
    SetStartPos([1070.2280])
    SetGlobal("ML_0","LOCALS",2)
    Continue()
END

IF
  Global("ML_0","LOCALS",1)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1070.2280])
END

IF
  Global("ML_0","LOCALS",2)
  ActionListEmpty()
  NearLocation(Myself,1420,1990,4)
THEN
  RESPONSE #100
    SetStartPos([1420.1990])
    SetGlobal("ML_0","LOCALS",3)
    Continue()
END

IF
  Global("ML_0","LOCALS",2)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1420.1990])
END

IF
  Global("ML_0","LOCALS",3)
  ActionListEmpty()
  NearLocation(Myself,1280,1860,4)
THEN
  RESPONSE #100
    SetStartPos([1280.1860])
    SetGlobal("ML_0","LOCALS",4)
    Continue()
END

IF
  Global("ML_0","LOCALS",3)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1280.1860])
END

IF
  Global("ML_0","LOCALS",4)
  ActionListEmpty()
  NearLocation(Myself,1570,1710,4)
THEN
  RESPONSE #100
    SetStartPos([1570.1710])
    SetGlobal("ML_0","LOCALS",5)
    Continue()
END

IF
  Global("ML_0","LOCALS",4)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1570.1710])
END

IF
  Global("ML_0","LOCALS",5)
  ActionListEmpty()
  NearLocation(Myself,1440,1490,4)
THEN
  RESPONSE #100
    SetStartPos([1440.1490])
    SetGlobal("ML_0","LOCALS",6)
    Continue()
END

IF
  Global("ML_0","LOCALS",5)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1440.1490])
END

IF
  Global("ML_0","LOCALS",6)
  ActionListEmpty()
  NearLocation(Myself,1280,1490,4)
THEN
  RESPONSE #100
    SetStartPos([1280.1490])
    SetGlobal("ML_0","LOCALS",7)
    Continue()
END

IF
  Global("ML_0","LOCALS",6)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1280.1490])
END

IF
  Global("ML_0","LOCALS",7)
  ActionListEmpty()
  NearLocation(Myself,1310,1290,4)
THEN
  RESPONSE #100
    SetStartPos([1310.1290])
    SetGlobal("ML_0","LOCALS",8)
    Continue()
END

IF
  Global("ML_0","LOCALS",7)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1310.1290])
END

IF
  Global("ML_0","LOCALS",8)
  ActionListEmpty()
  NearLocation(Myself,1140,1250,4)
THEN
  RESPONSE #100
    SetStartPos([1140.1250])
    SetGlobal("ML_0","LOCALS",9)
    Continue()
END

IF
  Global("ML_0","LOCALS",8)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1140.1250])
END

IF
  Global("ML_0","LOCALS",9)
  ActionListEmpty()
  NearLocation(Myself,1090,1420,4)
THEN
  RESPONSE #100
    SetStartPos([1090.1420])
    SetGlobal("ML_0","LOCALS",10)
    Continue()
END

IF
  Global("ML_0","LOCALS",9)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([1090.1420])
END

IF
  Global("ML_0","LOCALS",10)
  ActionListEmpty()
  NearLocation(Myself,730,1420,4)
THEN
  RESPONSE #100
    SetStartPos([730.1420])
    SetGlobal("ML_0","LOCALS",11)
    Continue()
END

IF
  Global("ML_0","LOCALS",10)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([730.1420])
END

IF
  Global("ML_0","LOCALS",11)
  ActionListEmpty()
  NearLocation(Myself,760,1210,4)
THEN
  RESPONSE #100
    SetStartPos([760.1210])
    SetGlobal("ML_0","LOCALS",12)
    Continue()
END

IF
  Global("ML_0","LOCALS",11)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([760.1210])
END

IF
  Global("ML_0","LOCALS",12)
  ActionListEmpty()
  NearLocation(Myself,570,1180,4)
THEN
  RESPONSE #100
    SetStartPos([570.1180])
    SetGlobal("ML_0","LOCALS",13)
    Continue()
END

IF
  Global("ML_0","LOCALS",12)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([570.1180])
END

IF
  Global("ML_0","LOCALS",13)
  ActionListEmpty()
  NearLocation(Myself,520,1690,4)
THEN
  RESPONSE #100
    SetStartPos([520.1690])
    SetGlobal("ML_0","LOCALS",14)
    Continue()
END

IF
  Global("ML_0","LOCALS",13)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([520.1690])
END

IF
  Global("ML_0","LOCALS",14)
  ActionListEmpty()
  NearLocation(Myself,530,1450,4)
THEN
  RESPONSE #100
    SetStartPos([530.1450])
    SetGlobal("ML_0","LOCALS",15)
    Continue()
END

IF
  Global("ML_0","LOCALS",14)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([530.1450])
END

IF
  Global("ML_0","LOCALS",15)
  ActionListEmpty()
  NearLocation(Myself,320,1450,4)
THEN
  RESPONSE #100
    SetStartPos([320.1450])
    SetGlobal("ML_0","LOCALS",16)
    Continue()
END

IF
  Global("ML_0","LOCALS",15)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([320.1450])
END

IF
  Global("ML_0","LOCALS",16)
  ActionListEmpty()
  NearLocation(Myself,370,1720,4)
THEN
  RESPONSE #100
    SetStartPos([370.1720])
    SetGlobal("ML_0","LOCALS",17)
    Continue()
END

IF
  Global("ML_0","LOCALS",16)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([370.1720])
END

IF
  Global("ML_0","LOCALS",17)
  ActionListEmpty()
  NearLocation(Myself,520,1690,4)
THEN
  RESPONSE #100
    SetStartPos([520.1690])
    SetGlobal("ML_0","LOCALS",0)
    Continue()
END

IF
  Global("ML_0","LOCALS",17)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToPoint([520.1690])
END

