IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  !Global("OBJ_SP_53VIIZRC_0","LOCALS",-1)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("141413131215",Myself,7)
      // CLERIC_RECITATION
      // CLERIC_PRAYER
      // CLERIC_DRAW_UPON_HOLY_MIGHT
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
    SetGlobal("OBJ_SP_53VIIZRC_0","LOCALS",-1)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Range(LastSeenBy(Myself),5,GREATER_THAN)
  Or(2)
    See(NearestEnemyOf(Myself),0)
    See([0.0.DRIDER],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("1503230612111325",LastMarkedObject,7)
      // CLERIC_FLAME_STRIKE
      // WIZARD_HOLD_PERSON
      // CLERIC_SILENCE_15_RADIUS
      // CLERIC_UNHOLY_BLIGHT
    MarkSpellAndObject("2507",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_DOMINATE_PERSON
    MarkSpellAndObject("2507",[ENEMY.0.DRIDER],SPELLCAST_RANDOM)
      // WIZARD_DOMINATE_PERSON
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2507",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_DOMINATE_PERSON
    MarkSpellAndObject("2507",[ENEMY.0.DRIDER],SPELLCAST_RANDOM)
      // WIZARD_DOMINATE_PERSON
    MarkSpellAndObject("1503230612111325",LastMarkedObject,7)
      // CLERIC_FLAME_STRIKE
      // WIZARD_HOLD_PERSON
      // CLERIC_SILENCE_15_RADIUS
      // CLERIC_UNHOLY_BLIGHT
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2507",[ENEMY.0.DRIDER],SPELLCAST_RANDOM)
      // WIZARD_DOMINATE_PERSON
    MarkSpellAndObject("1503230612111325",LastMarkedObject,7)
      // CLERIC_FLAME_STRIKE
      // WIZARD_HOLD_PERSON
      // CLERIC_SILENCE_15_RADIUS
      // CLERIC_UNHOLY_BLIGHT
    MarkSpellAndObject("2507",[PC.0.0.0.0.0.0.0.0.CLASSMASK_GROUP_WARRIORS],SPELLCAST_RANDOM)
      // WIZARD_DOMINATE_PERSON
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  Or(2)
    HasItem("SLiving",Myself)  // ~Slay Living~
    HasItem("CSDamag",Myself)  // ~Inflict Serious Wounds~
  Or(2)
    Range(LastSeenBy(Myself),6,LESS_THAN)
    Global("SPELL_LIST_1_INDEX","LOCALS",-1)
  Or(2)
    See(NearestEnemyOf(Myself),0)
    See([0.0.DRIDER],0)
THEN
  RESPONSE #100
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Or(2)
    Range(LastSeenBy(Myself),6,LESS_THAN)
    Global("SPELL_LIST_1_INDEX","LOCALS",-1)
  Or(2)
    See(NearestEnemyOf(Myself),0)
    See([0.0.DRIDER],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("151513191416",Myself,7)
      // CLERIC_SLAY_LIVING
      // CLERIC_CIRCLE_OF_BONES
      // CLERIC_CAUSE_SERIOUS_WOUNDS
    MarkSpellAndObject("1418",LastMarkedObject,7)
      // CLERIC_POISON
    Continue()
  RESPONSE #100
    MarkSpellAndObject("1418",LastMarkedObject,7)
      // CLERIC_POISON
    MarkSpellAndObject("151513191416",Myself,7)
      // CLERIC_SLAY_LIVING
      // CLERIC_CIRCLE_OF_BONES
      // CLERIC_CAUSE_SERIOUS_WOUNDS
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

