IF
  !CreatureHidden(Myself)
  Global("GroupBuff4TimerStarted","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("GroupBuff4TimerStarted","MYAREA",1)
    SetGlobalTimer("GroupBuff4Timer","MYAREA",21)
END

IF
  CreatureHidden(Myself)
  Global("6001_Dead_BattleGroup3","MYAREA",1)
THEN
  RESPONSE #100
    Enemy()
    SpellHitEffectSprite(Myself,Myself,DIMENSION_DOOR_DESTINATION,0)
    HideCreature(Myself,FALSE)
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  !CreatureHidden(Myself)
  GlobalGT("GroupBuff4TimerStarted","MYAREA",0)
  Or(3)
    GlobalTimerExpired("GroupBuff4Timer","MYAREA")
    !ClassEx(Myself,FIGHTER)
    AttackedBy([ANYONE],0)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  Global("GroupBuff4TimerStarted","MYAREA",1)
THEN
  RESPONSE #100
    SetGlobal("GroupBuff4TimerStarted","MYAREA",2)
    SetGlobalTimer("GroupBuff4Timer","MYAREA",1)
END

IF
  True()
THEN
  RESPONSE #100
    NoAction()
END

