IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("29092910",Myself,7)
      // WIZARD_AEGIS
      // WIZARD_EXECUTIONERS_EYES
    MarkSpellAndObject("29062911281028052903270524222424",LastMarkedObject,7)
      // WIZARD_WAIL_OF_THE_BANSHEE
      // WIZARD_MASS_DOMINATE
      // WIZARD_FLAYING
      // WIZARD_ABI_DALZIMS_HORRID_WILTING
      // WIZARD_POWER_WORD_KILL
      // WIZARD_POWER_WORD_STUN
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_VITRIOLIC_SPHERE
    MarkSpellAndObject("2422",LastMarkedObject,7)
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
    Continue()
  RESPONSE #100
    MarkSpellAndObject("29062911281028052903270524222424",LastMarkedObject,7)
      // WIZARD_WAIL_OF_THE_BANSHEE
      // WIZARD_MASS_DOMINATE
      // WIZARD_FLAYING
      // WIZARD_ABI_DALZIMS_HORRID_WILTING
      // WIZARD_POWER_WORD_KILL
      // WIZARD_POWER_WORD_STUN
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_VITRIOLIC_SPHERE
    MarkSpellAndObject("2422",LastMarkedObject,7)
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
    MarkSpellAndObject("29092910",Myself,7)
      // WIZARD_AEGIS
      // WIZARD_EXECUTIONERS_EYES
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2422",LastMarkedObject,7)
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
    MarkSpellAndObject("29092910",Myself,7)
      // WIZARD_AEGIS
      // WIZARD_EXECUTIONERS_EYES
    MarkSpellAndObject("29062911281028052903270524222424",LastMarkedObject,7)
      // WIZARD_WAIL_OF_THE_BANSHEE
      // WIZARD_MASS_DOMINATE
      // WIZARD_FLAYING
      // WIZARD_ABI_DALZIMS_HORRID_WILTING
      // WIZARD_POWER_WORD_KILL
      // WIZARD_POWER_WORD_STUN
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_VITRIOLIC_SPHERE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  HasItem("BBoDisa",Myself)  // ~Black Blade of Disaster~
  SetLastMarkedObject(Myself)
THEN
  RESPONSE #100
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  SetLastMarkedObject(Myself)
THEN
  RESPONSE #100
    MarkSpellAndObject("26232907",Myself,3)
      // WIZARD_IMPROVED_HASTE
      // WIZARD_BLACK_BLADE_OF_DISASTER
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  SetLastMarkedObject(Myself)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

