IF
  !Global("Fire_Room_Armed","MYAREA",0)
  Or(2)
    CheckDoorFlags("AR6051_Lava_Art",DOOROPEN)  // AR6051_Lava_Art
    CheckDoorFlags("AR6051_Lava_Switch",DOOROPEN)  // AR6051_Lava_Switch
THEN
  RESPONSE #100
    CloseDoor("AR6051_Lava_Art")
    CloseDoor("AR6051_Lava_Switch")
END

IF
  Global("Fire_Room_Armed","MYAREA",0)
  Global("Fire_Room_Active","MYAREA",1)
THEN
  RESPONSE #100
    SetGlobal("Fire_Room_Active","MYAREA",0)
    CloseDoor("AR6051_Lava_Art")
    CloseDoor("AR6051_Lava_Switch")
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
    Wait(7)
END

IF
  Global("Fire_Room_Armed","MYAREA",0)
  GlobalGT("Fire_Room_Active","MYAREA",1)
THEN
  RESPONSE #100
    OpenDoor("AR6051_Lava_Art")
    OpenDoor("AR6051_Lava_Switch")
    ForceSpellPoint([222.1392],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([222.1487],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([326.1432],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([287.1539],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([410.1489],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([364.1554],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([437.1589],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([525.1528],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([510.1626],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([622.1578],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([597.1657],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([712.1594],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([682.1690],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([822.1631],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([780.1673],TRAP_LAKE_OF_FIRE)
    ForceSpellPoint([755.1713],TRAP_LAKE_OF_FIRE)
    Wait(7)
    IncrementGlobal("Fire_Room_Active","MYAREA",-1)
END

IF
  Global("Fire_Room_Armed","MYAREA",0)
  Global("Fire_Room_Active","MYAREA",0)
  IsOverMe([ANYONE])
THEN
  RESPONSE #100
    Wait(3)
    SetGlobal("Fire_Room_Active","MYAREA",11)
END

