IF
  !CreatureHidden(Myself)
  Global("60Egenia_Gone","GLOBAL",1)
THEN
  RESPONSE #100
    UseItem("11Veira4",Myself)  // <Invalid Strref -1>
    Wait(1)
    DestroySelf()
END

IF
  !CreatureHidden(Myself)
  Or(4)
    HPPercentLT(Myself,100)
    Allegiance(Myself,ENEMY)
    HitBy([ANYONE],CRUSHING)
    AttackedBy([ANYONE],0)
THEN
  RESPONSE #100
    SetHPPercent(Myself,100,MAX_HP)
    HideCreature(Myself,TRUE)
END

IF
  Global("60Egenia_Gone","GLOBAL",1)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  !CreatureHidden(Myself)
  Global("60OkayToUnhideEgenia","GLOBAL",1)
  TimeGT(DAWN_START)
  TimeLT(DUSK_END)
THEN
  RESPONSE #100
    HideCreature(Myself,TRUE)
    Continue()
END

IF
  CreatureHidden(Myself)
  Global("60OkayToUnhideEgenia","GLOBAL",1)
  Or(2)
    TimeLT(DAWN_END)
    TimeGT(DUSK_START)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  !TimerActive(21)
  !CreatureHidden(Myself)
THEN
  RESPONSE #100
    FloatMessage(Myself,28897)  // ~- Isair come it is time to eat -~
    StartTimer(21,15)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,28898)  // ~- Gather your sister - ~
    StartTimer(21,15)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,28899)  // ~- Come Madae do not linger -~
    StartTimer(21,15)
    Continue()
  RESPONSE #100
    FloatMessage(Myself,28900)  // ~- Someone may see you -~
    StartTimer(21,15)
    Continue()
END

IF
  Global("60OkayToUnhideEgenia","GLOBAL",0)
  GlobalGT("Kuldahar_6002_UndeadKilled","GLOBAL",0)
  GlobalGT("60Egenia_Quest","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("60OkayToUnhideEgenia","GLOBAL",1)
END

