IF
  Exists("HC3")  // HC3
THEN
  RESPONSE #100
    Continue()
END

IF
  Contains("60Heart3","HC3")  // HC3
THEN
  RESPONSE #100
    Continue()
END

IF
  Exists("HC3")  // HC3
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
    MoveToObject("HC3")
END

IF
  True()
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",0)
    SetMyTarget(Nothing)
    Continue()
END

IF
  HasItem("60Heart3",Player1)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",1)
    SetMyTarget(Player1)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart3",Player2)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",2)
    SetMyTarget(Player2)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart3",Player3)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",3)
    SetMyTarget(Player3)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart3",Player4)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",4)
    SetMyTarget(Player4)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart3",Player5)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",5)
    SetMyTarget(Player5)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart3",Player6)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",6)
    SetMyTarget(Player6)
    Continue()
END

IF
  !Global("Marked_Player","LOCALS",0)
  !See(MyTarget,0)
THEN
  RESPONSE #100
    MoveToObject(MyTarget)
END

IF
  Range("HC3",3,LESS_THAN)  // HC3
THEN
  RESPONSE #100
    SetGlobal("DropInventory","LOCALS",1)
    TransferInventory("HC3",Myself)
    DestroyItem("60Heart3")  // ~Desiccated Heart~
    Wait(4)
END

IF
  Global("DropInventory","LOCALS",1)
THEN
  RESPONSE #100
    DropInventory()
    Kill(Myself)
END

