IF
  Global("ar6051_Kill_HeartlessDead","GLOBAL",1)
THEN
  RESPONSE #100
    Kill(Myself)
END

IF
  Range("HC1",3,LESS_THAN)  // HC1
THEN
  RESPONSE #100
    SetGlobal("DropInventory","LOCALS",1)
    TransferInventory("HC1",Myself)
    DestroyItem("60Heart1")  // ~Desiccated Heart~
    Wait(4)
END

IF
  Global("DropInventory","LOCALS",1)
THEN
  RESPONSE #100
    DropInventory()
    Kill(Myself)
END

IF
  True()
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",0)
    SetMyTarget(Nothing)
    Continue()
END

IF
  HasItem("60Heart1",Player1)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",1)
    SetMyTarget(Player1)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart1",Player2)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",2)
    SetMyTarget(Player2)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart1",Player3)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",3)
    SetMyTarget(Player3)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart1",Player4)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",4)
    SetMyTarget(Player4)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart1",Player5)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",5)
    SetMyTarget(Player5)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  HasItem("60Heart1",Player6)  // ~Desiccated Heart~
THEN
  RESPONSE #100
    SetGlobal("Marked_Player","LOCALS",6)
    SetMyTarget(Player6)
    Continue()
END

IF
  Global("Marked_Player","LOCALS",0)
  AttackedBy([ANYONE],0)
THEN
  RESPONSE #100
    Enemy()
    EquipWeapon()
    AttackOneRound(LastAttackerOf(Myself))
END

IF
  Global("Marked_Player","LOCALS",0)
  See(LastAttackerOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastAttackerOf(Myself))
END

IF
  Global("Marked_Player","LOCALS",0)
  Allegiance(Myself,ENEMY)
  Or(2)
    !AttackedBy([ANYONE],0)
    !See(LastAttackerOf(Myself),0)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
END

IF
  !Global("Marked_Player","LOCALS",0)
  See(MyTarget,0)
THEN
  RESPONSE #100
    Enemy()
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

