IF
  Clicked([PC])
THEN
  RESPONSE #100
    MarkObject(LastTrigger)
END

IF
  Or(2)
    !HasItem("Misc07",Myself)  // ~Gold~
    !HasItem("00Gem27",Myself)  // ~Emerald~
THEN
  RESPONSE #100
    Debug("60PALTAR_Altar_Trap")
    DisplayMessage(34281)  // ~You have defiled the altar of Sseth, infidel!~
    ReallyForceSpell(LastMarkedObject,TRAP_POISON_DAMAGE_DARTS)
    ReallyForceSpell(LastMarkedObject,CLERIC_TREMOR)
    ChangeCurrentScript("")
END

