IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  Global("MoveToPoint_15_10","MYAREA",0)
  NearLocation(Myself,3250,480,4)
THEN
  RESPONSE #100
    IncrementGlobal("MoveToPoint_15_10","MYAREA",1)
    Continue()
END

IF
  Global("MoveToPoint_15_10","MYAREA",1)
  NearLocation(Myself,2620,1240,4)
THEN
  RESPONSE #100
    IncrementGlobal("MoveToPoint_15_10","MYAREA",1)
    Continue()
END

IF
  Global("MoveToPoint_15_10","MYAREA",2)
THEN
  RESPONSE #100
    SetGlobal("MoveToPoint_15_10","MYAREA",0)
    SetGlobal("OkayToGo_15_10_0","LOCALS",0)
    SetGlobal("OkayToGo_15_10_1","LOCALS",0)
    SetGlobal("OkayToGo_15_10_2","LOCALS",0)
    SetGlobal("OkayToGo_15_10_3","LOCALS",0)
    SetGlobal("OkayToGo_15_10_4","LOCALS",0)
    SetGlobal("OkayToGo_15_10_5","LOCALS",0)
    SetGlobal("OkayToGo_15_10_6","LOCALS",0)
    SetGlobal("OkayToGo_15_10_7","LOCALS",0)
    SetGlobal("OkayToGo_15_10_8","LOCALS",0)
    Continue()
END

IF
  Global("MoveToPoint_15_10","MYAREA",0)
  Global("MoveToPoint_15_09","MYAREA",0)
  Global("OkayToGo_15_10_0","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("OkayToGo_15_10_0","LOCALS",1)
    MoveToPoint([3250.480])
    Continue()
END

IF
  Global("MoveToPoint_15_10","MYAREA",1)
  Global("MoveToPoint_15_09","MYAREA",1)
  Global("OkayToGo_15_10_1","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("OkayToGo_15_10_1","LOCALS",1)
    MoveToPoint([2620.1240])
    Continue()
END

