IF
  Clicked([PC])
  OpenState(Myself,FALSE)
  GlobalTimerExpired("BrickTimer","MYAREA")
THEN
  RESPONSE #100
    SetGlobalTimer("BrickTimer","MYAREA",1)
    SetGlobal("Brick01","MYAREA",1)
    Unlock("AR6051_Brick1")
    OpenDoor("AR6051_Brick1")
    Lock("AR6051_Brick1")
    PlaySoundPoint("AM6051d",[3102.1511])
    SetGlobal("Brick08","MYAREA",1)
    MultiPlayerSync()
END

IF
  OpenState(Myself,FALSE)
  Global("Brick01","MYAREA",1)
THEN
  RESPONSE #100
    SetGlobalTimer("BrickTimer","MYAREA",1)
    SetGlobal("Brick01","MYAREA",1)
    Unlock("AR6051_Brick1")
    OpenDoor("AR6051_Brick1")
    Lock("AR6051_Brick1")
    PlaySoundPoint("AM6051d",[3102.1511])
    MultiPlayerSync()
END

IF
  OpenState(Myself,TRUE)
  Global("Brick01","MYAREA",2)
THEN
  RESPONSE #100
    SetGlobalTimer("BrickTimer","MYAREA",1)
    SetGlobal("Brick01","MYAREA",2)
    Unlock("AR6051_Brick1")
    CloseDoor("AR6051_Brick1")
    Lock("AR6051_Brick1")
    PlaySoundPoint("AM6051d",[3102.1511])
    MultiPlayerSync()
END

