IF
  Clicked([PC])
  OpenState(Myself,FALSE)
  GlobalTimerExpired("BrickTimer","MYAREA")
THEN
  RESPONSE #100
    SetGlobalTimer("BrickTimer","MYAREA",1)
    SetGlobal("Brick05","MYAREA",1)
    Unlock("AR6051_Brick5")
    OpenDoor("AR6051_Brick5")
    Lock("AR6051_Brick5")
    PlaySoundPoint("AM6051d",[2338.1515])
    SetGlobal("Brick01","MYAREA",2)
    MultiPlayerSync()
END

IF
  OpenState(Myself,FALSE)
  Global("Brick05","MYAREA",1)
THEN
  RESPONSE #100
    SetGlobalTimer("BrickTimer","MYAREA",1)
    SetGlobal("Brick05","MYAREA",1)
    Unlock("AR6051_Brick5")
    OpenDoor("AR6051_Brick5")
    Lock("AR6051_Brick5")
    PlaySoundPoint("AM6051d",[2338.1515])
    MultiPlayerSync()
END

IF
  OpenState(Myself,TRUE)
  Global("Brick05","MYAREA",2)
THEN
  RESPONSE #100
    SetGlobalTimer("BrickTimer","MYAREA",1)
    SetGlobal("Brick05","MYAREA",2)
    Unlock("AR6051_Brick5")
    CloseDoor("AR6051_Brick5")
    Lock("AR6051_Brick5")
    PlaySoundPoint("AM6051d",[2338.1515])
    MultiPlayerSync()
END

