IF
  See([ENEMY.0.YUANTI],0)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Global("ar6051_Kill_Archers","GLOBAL",1)
THEN
  RESPONSE #100
    Kill(Myself)
END

IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  NumberOfTimesTalkedTo(0)
  !Allegiance(Myself,ENEMY)
  !Dead(Myself)  // 
  Global("YTArcherGuard_t11_Talked","MYAREA",0)
  See([PC],0)
THEN
  RESPONSE #100
    SetGlobal("YTArcherGuard_t11_Talked","MYAREA",1)
    SetGlobal("YTArcherGuard_OkayToTalk","LOCALS",1)
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  NumberOfTimesTalkedTo(0)
  !Allegiance(Myself,ENEMY)
  !Dead(Myself)  // 
  Global("YTArcherGuard_OkayToTalk","LOCALS",1)
  See([PC],0)
THEN
  RESPONSE #100
    Dialogue(LastMarkedObject)
END

