IF
  Global("AlchemistCallForHelp","MYAREA",1)
THEN
  RESPONSE #100
    FloatMessage(Myself,41074)  // ~"Guards!  I am being threatened - assist me!"~
    Shout(106)
    IncrementGlobal("YuantiCallForHelp","MYAREA",5)
    IncrementGlobal("61HalfbreedDied","GLOBAL",5)
    SetGlobal("AlchemistCallForHelp","MYAREA",0)
END

IF
  Global("61Alchemist_Intimidated","GLOBAL",0)
  Global("AlchemistCallForHelp","MYAREA",0)
  GlobalTimerExpired("AlchemistTalkTimer","LOCALS")
  See([PC],0)
THEN
  RESPONSE #100
    SetGlobalTimer("AlchemistTalkTimer","LOCALS",300)
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  Global("ML_0","LOCALS",0)
  Global("AlchemistCallForHelp","MYAREA",0)
  Global("61PlayerMetThorasskus","GLOBAL",0)
  GlobalTimerExpired("AlchemistWaitTimer","MYAREA")
  OpenState("AR6102_Lever2",TRUE)  // AR6102_Lever2
  Global("WorkRoomActive","MYAREA",0)
  Range("AR6102_LEVER2",4,LESS_THAN)  // AR6102_LEVER2
THEN
  RESPONSE #100
    SetGlobal("ML_0","LOCALS",1)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
  Global("AlchemistCallForHelp","MYAREA",0)
  Global("61PlayerMetThorasskus","GLOBAL",0)
  GlobalTimerExpired("AlchemistWaitTimer","MYAREA")
  OpenState("AR6102_Lever2",TRUE)  // AR6102_Lever2
  Global("WorkRoomActive","MYAREA",0)
THEN
  RESPONSE #100
    MoveToObject("AR6102_LEVER2")
END

IF
  Global("ML_0","LOCALS",1)
  Global("AlchemistCallForHelp","MYAREA",0)
  Global("61PlayerMetThorasskus","GLOBAL",0)
  GlobalTimerExpired("AlchemistWaitTimer","MYAREA")
  OpenState("AR6102_Lever2",TRUE)  // AR6102_Lever2
  Global("WorkRoomActive","MYAREA",0)
THEN
  RESPONSE #100
    FaceObject("AR6102_LEVER2")
    SetGlobal("ML_0","LOCALS",2)
END

IF
  Global("ML_0","LOCALS",2)
  Global("AlchemistCallForHelp","MYAREA",0)
  Global("61PlayerMetThorasskus","GLOBAL",0)
  GlobalTimerExpired("AlchemistWaitTimer","MYAREA")
  OpenState("AR6102_Lever2",TRUE)  // AR6102_Lever2
  Global("WorkRoomActive","MYAREA",0)
THEN
  RESPONSE #100
    PlaySequence(Myself,ATTACK)
    SetGlobal("ML_0","LOCALS",3)
END

IF
  Global("ML_0","LOCALS",3)
  Global("AlchemistCallForHelp","MYAREA",0)
  Global("61PlayerMetThorasskus","GLOBAL",0)
  GlobalTimerExpired("AlchemistWaitTimer","MYAREA")
  OpenState("AR6102_Lever2",TRUE)  // AR6102_Lever2
  Global("WorkRoomActive","MYAREA",0)
THEN
  RESPONSE #100
    SendTrigger("AR6102_LEVER2",0)
    SetGlobal("ML_0","LOCALS",4)
END

IF
  Global("ML_0","LOCALS",4)
  NearSavedLocation(4)
  Global("AlchemistCallForHelp","MYAREA",0)
  Global("61PlayerMetThorasskus","GLOBAL",0)
  GlobalTimerExpired("AlchemistWaitTimer","MYAREA")
  OpenState("AR6102_Lever2",TRUE)  // AR6102_Lever2
  Global("WorkRoomActive","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("ML_0","LOCALS",5)
    SetStartPos([-1.-1])
    Continue()
END

IF
  Global("ML_0","LOCALS",4)
  !NearSavedLocation(4)
  Global("AlchemistCallForHelp","MYAREA",0)
  Global("61PlayerMetThorasskus","GLOBAL",0)
  GlobalTimerExpired("AlchemistWaitTimer","MYAREA")
  OpenState("AR6102_Lever2",TRUE)  // AR6102_Lever2
  Global("WorkRoomActive","MYAREA",0)
THEN
  RESPONSE #100
    ReturnToSavedLocation(0)
END

IF
  Global("ML_0","LOCALS",5)
  Global("AlchemistCallForHelp","MYAREA",0)
  Global("61PlayerMetThorasskus","GLOBAL",0)
  GlobalTimerExpired("AlchemistWaitTimer","MYAREA")
  OpenState("AR6102_Lever2",TRUE)  // AR6102_Lever2
  Global("WorkRoomActive","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobalTimer("ALCHEMISTWAITTIMER","MYAREA",2400)
    SetGlobal("ML_0","LOCALS",0)
END

IF
  Global("RW_61ALCHEM1","LOCALS",0)
  !NearSavedLocation(20)
THEN
  RESPONSE #100
    SetGlobal("RW_61ALCHEM1","LOCALS",1)
    Continue()
END

IF
  !Global("RW_61ALCHEM1","LOCALS",0)
  NearSavedLocation(20)
THEN
  RESPONSE #100
    SetGlobal("RW_61ALCHEM1","LOCALS",0)
    NoAction()
END

IF
  !Global("RW_61ALCHEM1","LOCALS",0)
  !Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    MoveToPoint([-2.-2])
END

IF
  !TimerActive(23)
  Global("RW_61ALCHEM1","LOCALS",0)
  !Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    RandomWalk()
    StartTimer(23,5)
END

