IF
  True()
THEN
  RESPONSE #100
    MultiPlayerSync()
    CutSceneId("Thorasskus")  // 
    HideGUI()
    Explore()
    MoveViewObject("Alchemist",INSTANT)
    ActionOverride("Alchemist",DestroySelf())
    CreateCreature("61Alchem","Alchemist",[1215.1985],12)  // ~D'hey-jazerrion~
    SpellHitEffectPoint("Thorasskus",[1215.1985],RESURRECTION,0)
    SetGlobal("Alchemist_dead","GLOBAL",0)
    Wait(5)
    MoveViewObject(NearestPC,INSTANT)
    UnhideGUI()
    EndCutSceneMode()
END

