IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Lothar4")  // 
    MultiPlayerSync()
    HideGUI()
    SetVisualRange(100)
    MoveViewObject(Myself,VERY_FAST)
    Wait(5)
    SetGlobalTimer("YUANTIATTACKTIMER","MYAREA",120)
    PlaySequence(Myself,ATTACK)
    UseItemPoint("00Potn53",[3490.1500],0)
    TriggerActivation("KillEastWall",TRUE)
    FloatMessage(Myself,36803)  // ~"Rise, my faithful warriors... RISE and face your king."~
    Wait(5)
    PlaySequence("EfreetiAssassin_01",TWITCH)
    PlaySequence("EfreetiAssassin_02",TWITCH)
    PlaySequence("EfreetiAssassin_03",TWITCH)
    PlaySequence("EfreetiAssassin_04",TWITCH)
    PlaySequence("EfreetiAssassin_05",TWITCH)
    PlaySequence("EfreetiAssassin_06",TWITCH)
    PlaySequence("EfreetiAssassin_07",TWITCH)
    PlaySequence("EfreetiAssassin_08",TWITCH)
    PlaySequence("EfreetiAssassin_09",TWITCH)
    PlaySequence("EfreetiAssassin_10",TWITCH)
    HideCreature("EfreetiAssassin_01",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_01",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_01",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_01",AWAKE)
    HideCreature("EfreetiAssassin_02",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_02",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_02",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_02",AWAKE)
    HideCreature("EfreetiAssassin_03",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_03",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_03",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_03",AWAKE)
    HideCreature("EfreetiAssassin_04",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_04",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_04",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_04",AWAKE)
    HideCreature("EfreetiAssassin_05",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_05",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_05",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_05",AWAKE)
    HideCreature("EfreetiAssassin_06",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_06",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_06",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_06",AWAKE)
    HideCreature("EfreetiAssassin_07",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_07",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_07",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_07",AWAKE)
    HideCreature("EfreetiAssassin_08",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_08",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_08",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_08",AWAKE)
    HideCreature("EfreetiAssassin_09",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_09",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_09",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_09",AWAKE)
    HideCreature("EfreetiAssassin_10",FALSE)
    SpellHitEffectSprite(Myself,"EfreetiAssassin_10",MONSTER_SUMMONING_V,0)
    ActionOverride("EfreetiAssassin_10",FaceObject("Lothar4"))
    PlaySequence("EfreetiAssassin_10",AWAKE)
    Wait(1)
    FloatMessage("EfreetiAssassin_01",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_02",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_03",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_04",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_05",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_06",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_07",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_08",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_09",36804)  // ~"Yes, Master?"~
    FloatMessage("EfreetiAssassin_10",36804)  // ~"Yes, Master?"~
    Wait(5)
    ActionOverride(Myself,FaceObject("EfreetiAssassin_02"))
    ActionOverride("EfreetiAssassin_02",FaceObject(Myself))
    FloatMessage(Myself,36805)  // ~"Bring me the head of High Priest Thorasskus - whatever form it's in.  Burn anything that gets in your way."~
    Wait(10)
    FloatMessage("EfreetiAssassin_01",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_02",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_03",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_04",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_05",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_06",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_07",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_08",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_09",36806)  // ~"Yes, Master."~
    FloatMessage("EfreetiAssassin_10",36806)  // ~"Yes, Master."~
    Wait(5)
    SetCriticalPathObject(Myself,FALSE)
    SetGlobal("LotharOnPatrol","MYAREA",1)
    SetGlobal("LotharDestroyEmbassy","MYAREA",0)
    SetVisualRange(0)
    Wait(1)
    UnhideGUI()
    EndCutSceneMode()
    AddJournalEntry(41385)
END

