IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Protagonist)  // 
    HideGUI()
    MoveViewPoint([960.2368],VERY_FAST)
    ActionOverride("VenominSuicide",MoveToPoint([960.2368]))
    Wait(4)
    MoveViewObject("VenominSuicide",INSTANT)
    SpellHitEffectSprite("VenominSuicide","VenominSuicide",FLAME_STRIKE,0)
    DisplayString("VenominSuicide",14026)  // ~Death~
    SetCriticalPathObject("VenominSuicide",FALSE)
    Wait(1)
    ActionOverride("VenominSuicide",DestroySelf())
    MoveViewObject(Protagonist,VERY_FAST)
    Wait(2)
    UnhideGUI()
    EndCutSceneMode()
END

