IF
  Global("CurrentAction","LOCALS",3)
THEN
  RESPONSE #100
    SetGlobal("Rested","LOCALS",1)
    SetGlobal("CurrentAction","LOCALS",0)
    Rest()
    ApplySpell(Myself,2096)
END

IF
  !IsCreatureAreaFlag(Myself,IGNORE_RETURN_TO_START_POS)
THEN
  RESPONSE #100
    SetCreatureAreaFlag(Myself,IGNORE_RETURN_TO_START_POS,TRUE)
END

IF
  !Allegiance(Myself,ENEMY)
  Global("CurrentAction","LOCALS",4)
  See([ENEMY],0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  AttackedBy([GOODCUTOFF],0)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

IF
  Global("ML_0","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,510,2200,4)
THEN
  RESPONSE #100
    SetStartPos([510.2200])
    SetGlobal("ML_0","LOCALS",1)
    Continue()
END

IF
  Global("ML_0","LOCALS",0)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_DumbPrisoner_03",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    MoveToPoint([510.2200])
END

IF
  Global("ML_0","LOCALS",1)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_DumbPrisoner_03",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    Unlock("ARMORYCHEST1")
    SetGlobal("ML_0","LOCALS",2)
END

IF
  Global("ML_0","LOCALS",2)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_DumbPrisoner_03",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    TransferInventory("ARMORYCHEST1",Myself)
    SetGlobal("ML_0","LOCALS",3)
END

IF
  Global("ML_0","LOCALS",3)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_DumbPrisoner_03",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    EquipItem("00BRAC03",1)
    SetGlobal("ML_0","LOCALS",4)
END

IF
  Global("ML_0","LOCALS",4)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_DumbPrisoner_03",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    EquipItem("00BULL89",1)
    SetGlobal("ML_0","LOCALS",5)
END

IF
  Global("ML_0","LOCALS",5)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_DumbPrisoner_03",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    SetGlobal("EQUIPPED","LOCALS",1)
    SetGlobal("ML_0","LOCALS",6)
END

IF
  Global("ML_0","LOCALS",6)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_DumbPrisoner_03",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    SetGlobal("CURRENTACTION","LOCALS",4)
    SetGlobal("ML_0","LOCALS",0)
END

IF
  Global("ML_1","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,670,2320,4)
THEN
  RESPONSE #100
    SetStartPos([670.2320])
    SetGlobal("ML_1","LOCALS",1)
    Continue()
END

IF
  Global("ML_1","LOCALS",0)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_SmartPrisoner_04",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    MoveToPoint([670.2320])
END

IF
  Global("ML_1","LOCALS",1)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_SmartPrisoner_04",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    Unlock("ARMORYCHEST2")
    SetGlobal("ML_1","LOCALS",2)
END

IF
  Global("ML_1","LOCALS",2)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_SmartPrisoner_04",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    TransferInventory("ARMORYCHEST2",Myself)
    SetGlobal("ML_1","LOCALS",3)
END

IF
  Global("ML_1","LOCALS",3)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_SmartPrisoner_04",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    EquipItem("00PLAT11",1)
    SetGlobal("ML_1","LOCALS",4)
END

IF
  Global("ML_1","LOCALS",4)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_SmartPrisoner_04",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    EquipItem("00SHLD86",1)
    SetGlobal("ML_1","LOCALS",5)
END

IF
  Global("ML_1","LOCALS",5)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_SmartPrisoner_04",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    EquipItem("00HELM01",1)
    SetGlobal("ML_1","LOCALS",6)
END

IF
  Global("ML_1","LOCALS",6)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_SmartPrisoner_04",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    SetGlobal("EQUIPPED","LOCALS",1)
    SetGlobal("ML_1","LOCALS",7)
END

IF
  Global("ML_1","LOCALS",7)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_SmartPrisoner_04",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    SetGlobal("CURRENTACTION","LOCALS",4)
    SetGlobal("ML_1","LOCALS",0)
END

IF
  Global("ML_2","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,730,2385,4)
THEN
  RESPONSE #100
    SetStartPos([730.2385])
    SetGlobal("ML_2","LOCALS",1)
    Continue()
END

IF
  Global("ML_2","LOCALS",0)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_FemalePrisoner_07",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    MoveToPoint([730.2385])
END

IF
  Global("ML_2","LOCALS",1)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_FemalePrisoner_07",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    Unlock("ARMORYCHEST3")
    SetGlobal("ML_2","LOCALS",2)
END

IF
  Global("ML_2","LOCALS",2)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_FemalePrisoner_07",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    TransferInventory("ARMORYCHEST3",Myself)
    SetGlobal("ML_2","LOCALS",3)
END

IF
  Global("ML_2","LOCALS",3)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_FemalePrisoner_07",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    EquipItem("00LEAT92",1)
    SetGlobal("ML_2","LOCALS",4)
END

IF
  Global("ML_2","LOCALS",4)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_FemalePrisoner_07",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    EquipItem("00SHLD92",1)
    SetGlobal("ML_2","LOCALS",5)
END

IF
  Global("ML_2","LOCALS",5)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_FemalePrisoner_07",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    EquipItem("00BOLT04",1)
    SetGlobal("ML_2","LOCALS",6)
END

IF
  Global("ML_2","LOCALS",6)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_FemalePrisoner_07",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    SetGlobal("EQUIPPED","LOCALS",1)
    SetGlobal("ML_2","LOCALS",7)
END

IF
  Global("ML_2","LOCALS",7)
  Global("CurrentAction","LOCALS",1)
  Or(3)
    IsScriptName("04_FemalePrisoner_07",Myself)
    IsScriptName("05_TrollPrisoner",Myself)
    IsScriptName("05_WizardPrisoner",Myself)
THEN
  RESPONSE #100
    SetGlobal("CURRENTACTION","LOCALS",4)
    SetGlobal("ML_2","LOCALS",0)
END

IF
  Global("ML_3","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,297,1218,4)
THEN
  RESPONSE #100
    SetStartPos([297.1218])
    SetGlobal("ML_3","LOCALS",1)
    Continue()
END

IF
  Global("ML_3","LOCALS",0)
  Global("CurrentAction","LOCALS",5)
THEN
  RESPONSE #100
    MoveToPoint([297.1218])
END

IF
  Global("ML_3","LOCALS",1)
  Global("CurrentAction","LOCALS",5)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  Global("ML_4","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,3096,439,4)
THEN
  RESPONSE #100
    SetStartPos([3096.439])
    SetGlobal("ML_4","LOCALS",1)
    Continue()
END

IF
  Global("ML_4","LOCALS",0)
  Global("CurrentAction","LOCALS",6)
THEN
  RESPONSE #100
    MoveToPoint([3096.439])
END

IF
  Global("ML_4","LOCALS",1)
  Global("CurrentAction","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("61NUMPRISONERSSENTTORAKSHASA","GLOBAL",1)
    SetGlobal("ML_4","LOCALS",2)
END

IF
  Global("ML_4","LOCALS",2)
  Global("CurrentAction","LOCALS",6)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  !TimerActive(27)
  !Allegiance(Myself,ENEMY)
  Global("CurrentAction","LOCALS",4)
THEN
  RESPONSE #100
    RandomWalk()
    StartTimer(27,5)
END

