IF
  Or(2)
    !IsCreatureAreaFlag(Myself,IGNORE_RETURN_TO_START_POS)
    !IsCreatureAreaFlag(Myself,IGNORE_AI_INHIBIT)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,253)
    SetCreatureAreaFlag(Myself,IGNORE_RETURN_TO_START_POS,TRUE)
    SetCreatureAreaFlag(Myself,IGNORE_AI_INHIBIT,TRUE)
    Continue()
END

IF
  GlobalGT("61VolcanoStatus","GLOBAL",0)
THEN
  RESPONSE #100
    SpellHitEffectSprite("INVISIBLE",Myself,ALTERATION,0)
    DestroySelf()
END

IF
  !Allegiance(Myself,ENEMY)
  Global("61CurrentDay","GLOBAL",2)
  OpenState("AR6104_Cage",FALSE)  // AR6104_Cage
  Global("SpeakToPlayer","LOCALS",0)
  See([PC],0)
THEN
  RESPONSE #100
    SetGlobal("SpeakToPlayer","LOCALS",2)
END

IF
  !Allegiance(Myself,ENEMY)
  Global("SpeakToPlayer","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("SpeakToPlayer","LOCALS",1)
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  !Allegiance(Myself,ENEMY)
  Global("61CurrentDay","GLOBAL",0)
  Global("SpeakToPlayer","LOCALS",0)
  See([PC],0)
THEN
  RESPONSE #100
    SetGlobal("SpeakToPlayer","LOCALS",1)
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  HPLostGT(Myself,25)
  HasItem("0potn07,Myself)",Myself)  // 0potn07,Myself)
THEN
  RESPONSE #100
    UseItem("0potn07",Myself)  // 0potn07
    Continue()
END

IF
  Global("61CurrentDay","GLOBAL",0)
  Global("IzbelahCastSpell","MYAREA",1)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,0)
    SetGlobal("Level1Spells","LOCALS",7)
    SetGlobal("Level2Spells","LOCALS",7)
    SetGlobal("Level3Spells","LOCALS",7)
    SetGlobal("Level4Spells","LOCALS",7)
    SetGlobal("Level5Spells","LOCALS",6)
    SetGlobal("Level6Spells","LOCALS",6)
    SetGlobal("Level7Spells","LOCALS",6)
    SetGlobal("Level8Spells","LOCALS",6)
    SetGlobal("Level9Spells","LOCALS",6)
    SetGlobal("IzbelahCastSpell","MYAREA",2)
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    StartCutScene("61cIzSpe")
END

IF
  Global("IzbelahCastSpell","MYAREA",2)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level2Spells","LOCALS",-1)
    Spell(Myself,WIZARD_MIRROR_IMAGE)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",3)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level2Spells","LOCALS",-1)
    Spell(Myself,WIZARD_CATS_GRACE)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",4)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level2Spells","LOCALS",-1)
    Spell(Myself,WIZARD_BLUR)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",5)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level9Spells","LOCALS",-1)
    Spell(Myself,WIZARD_AEGIS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",6)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level9Spells","LOCALS",-1)
    Spell("EmbassySummonSpot",WIZARD_SUMMON_MONSTER_IX)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",7)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level5Spells","LOCALS",-1)
    Spell("EmbassySummonSpot",WIZARD_ANIMATE_DEAD)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",8)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level4Spells","LOCALS",-1)
    Spell(Myself,WIZARD_SPIDER_SPAWN)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",9)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level7Spells","LOCALS",-1)
    Spell(Myself,WIZARD_SEVEN_EYES)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",10)
THEN
  RESPONSE #100
    IncrementGlobal("IzbelahCastSpell","MYAREA",1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level5Spells","LOCALS",-1)
    Spell("EmbassyShelf",WIZARD_SUMMON_SHADOW)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",11)
THEN
  RESPONSE #100
    SetGlobal("IzbelahCastSpell","MYAREA",-1)
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level9Spells","LOCALS",-1)
    Spell(Myself,2081)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",-1)
  !Specifics(Myself,100)
  ActionListEmpty()
THEN
  RESPONSE #100
    SetGlobal("CurrentTarget","LOCALS",0)
    IncrementGlobal("Level9Spells","LOCALS",-1)
    Spell(Myself,2081)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Global("IzbelahCastSpell","MYAREA",-1)
  Specifics(Myself,100)
THEN
  RESPONSE #100
    EndGame(39400)  // ~Unable to prevent Izbelah from casting her Temporal Stasis spell, you have been caught in its time loop forever.~
END

IF
  Allegiance(Myself,ENEMY)
  RandomNum(2,1)
  HasItem("00WAND36",Myself)  // ~Hold Person Wand~
  See([PC],0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_HOLD_PERSON,0)
THEN
  RESPONSE #100
    PlaySequence(Myself,CAST)
    UseItem("00WAND36",LastMarkedObject)  // ~Hold Person Wand~
END

IF
  HasItem("MSword",Myself)  // ~Mordenkainen's Sword~
  Allegiance(Myself,ENEMY)
  GlobalGT("Level7Spells","LOCALS",0)
  Global("IzbelahCastSpell","MYAREA",-1)
  RandomNum(5,1)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    IncrementGlobal("Level7Spells","LOCALS",-1)
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  GlobalGT("Level7Spells","LOCALS",0)
  Global("IzbelahCastSpell","MYAREA",-1)
  RandomNum(5,1)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("27032708271527162714271327112707",LastMarkedObject,15)
      // WIZARD_SUMMON_MONSTER_VII
      // WIZARD_ACID_STORM
      // WIZARD_SUMMON_EFREETI
      // WIZARD_SUMMON_DJINNI
      // WIZARD_DELAYED_BLAST_FIREBALL
      // WIZARD_CACOFIEND
      // WIZARD_SUFFOCATE
      // WIZARD_MALAVONS_RAGE
    MarkSpellAndObject("27102712270927042719",Myself,15)
      // WIZARD_SEVEN_EYES
      // WIZARD_ELEMENTAL_BARRIER
      // WIZARD_MASS_INVISIBILITY
      // WIZARD_MORDENKAINENS_SWORD
      // WIZARD_VIPERGOUT
    MarkSpellAndObject("27062705",LastMarkedObject,15)
      // WIZARD_PRISMATIC_SPRAY
      // WIZARD_POWER_WORD_STUN
    Continue()
  RESPONSE #100
    MarkSpellAndObject("27102712270927042719",Myself,15)
      // WIZARD_SEVEN_EYES
      // WIZARD_ELEMENTAL_BARRIER
      // WIZARD_MASS_INVISIBILITY
      // WIZARD_MORDENKAINENS_SWORD
      // WIZARD_VIPERGOUT
    MarkSpellAndObject("27062705",LastMarkedObject,15)
      // WIZARD_PRISMATIC_SPRAY
      // WIZARD_POWER_WORD_STUN
    MarkSpellAndObject("27032708271527162714271327112707",LastMarkedObject,15)
      // WIZARD_SUMMON_MONSTER_VII
      // WIZARD_ACID_STORM
      // WIZARD_SUMMON_EFREETI
      // WIZARD_SUMMON_DJINNI
      // WIZARD_DELAYED_BLAST_FIREBALL
      // WIZARD_CACOFIEND
      // WIZARD_SUFFOCATE
      // WIZARD_MALAVONS_RAGE
    Continue()
  RESPONSE #100
    MarkSpellAndObject("27062705",LastMarkedObject,15)
      // WIZARD_PRISMATIC_SPRAY
      // WIZARD_POWER_WORD_STUN
    MarkSpellAndObject("27032708271527162714271327112707",LastMarkedObject,15)
      // WIZARD_SUMMON_MONSTER_VII
      // WIZARD_ACID_STORM
      // WIZARD_SUMMON_EFREETI
      // WIZARD_SUMMON_DJINNI
      // WIZARD_DELAYED_BLAST_FIREBALL
      // WIZARD_CACOFIEND
      // WIZARD_SUFFOCATE
      // WIZARD_MALAVONS_RAGE
    MarkSpellAndObject("27102712270927042719",Myself,15)
      // WIZARD_SEVEN_EYES
      // WIZARD_ELEMENTAL_BARRIER
      // WIZARD_MASS_INVISIBILITY
      // WIZARD_MORDENKAINENS_SWORD
      // WIZARD_VIPERGOUT
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    IncrementGlobal("Level7Spells","LOCALS",-1)
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  Or(2)
    HasItem("DoBone",Myself)  // ~Dart of Bone~
    HasItem("LTouch",Myself)  // ~Lich Touch~
  Allegiance(Myself,ENEMY)
  GlobalGT("Level6Spells","LOCALS",0)
  Global("IzbelahCastSpell","MYAREA",-1)
  RandomNum(5,1)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    IncrementGlobal("Level6Spells","LOCALS",-1)
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  GlobalGT("Level6Spells","LOCALS",0)
  Global("IzbelahCastSpell","MYAREA",-1)
  RandomNum(5,1)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("26032605260626092611261226132614",LastMarkedObject,15)
      // WIZARD_CHAIN_LIGHTNING
      // WIZARD_ACID_FOG
      // WIZARD_CIRCLE_OF_DEATH
      // WIZARD_INVISIBLE_STALKER
      // WIZARD_SUMMON_MONSTER_VI
      // WIZARD_OTILUKES_FREEZING_SPHERE
      // WIZARD_SHADES
      // WIZARD_STONE_TO_FLESH
    MarkSpellAndObject("26172619262126222626262826272629",LastMarkedObject,15)
      // WIZARD_POWER_WORD_SILENCE
      // WIZARD_SOUL_EATER
      // WIZARD_CARRION_SUMMONS
      // WIZARD_CONJURE_AIR_ELEMENTAL
      // WIZARD_WYVERN_CALL
      // WIZARD_CONJURE_EARTH_ELEMENTAL
      // WIZARD_CONJURE_FIRE_ELEMENTAL
      // WIZARD_CONJURE_WATER_ELEMENTAL
    MarkSpellAndObject("261826012608261026202623",Myself,15)
      // WIZARD_DARTS_OF_BONE
      // WIZARD_ANTIMAGIC_SHELL
      // WIZARD_GLOBE_OF_INVULNERABILITY
      // WIZARD_LICH_TOUCH
      // WIZARD_TROLLISH_FORTITUDE
      // WIZARD_IMPROVED_HASTE
    Continue()
  RESPONSE #100
    MarkSpellAndObject("26172619262126222626262826272629",LastMarkedObject,15)
      // WIZARD_POWER_WORD_SILENCE
      // WIZARD_SOUL_EATER
      // WIZARD_CARRION_SUMMONS
      // WIZARD_CONJURE_AIR_ELEMENTAL
      // WIZARD_WYVERN_CALL
      // WIZARD_CONJURE_EARTH_ELEMENTAL
      // WIZARD_CONJURE_FIRE_ELEMENTAL
      // WIZARD_CONJURE_WATER_ELEMENTAL
    MarkSpellAndObject("261826012608261026202623",Myself,15)
      // WIZARD_DARTS_OF_BONE
      // WIZARD_ANTIMAGIC_SHELL
      // WIZARD_GLOBE_OF_INVULNERABILITY
      // WIZARD_LICH_TOUCH
      // WIZARD_TROLLISH_FORTITUDE
      // WIZARD_IMPROVED_HASTE
    MarkSpellAndObject("26032605260626092611261226132614",LastMarkedObject,15)
      // WIZARD_CHAIN_LIGHTNING
      // WIZARD_ACID_FOG
      // WIZARD_CIRCLE_OF_DEATH
      // WIZARD_INVISIBLE_STALKER
      // WIZARD_SUMMON_MONSTER_VI
      // WIZARD_OTILUKES_FREEZING_SPHERE
      // WIZARD_SHADES
      // WIZARD_STONE_TO_FLESH
    Continue()
  RESPONSE #100
    MarkSpellAndObject("261826012608261026202623",Myself,15)
      // WIZARD_DARTS_OF_BONE
      // WIZARD_ANTIMAGIC_SHELL
      // WIZARD_GLOBE_OF_INVULNERABILITY
      // WIZARD_LICH_TOUCH
      // WIZARD_TROLLISH_FORTITUDE
      // WIZARD_IMPROVED_HASTE
    MarkSpellAndObject("26032605260626092611261226132614",LastMarkedObject,15)
      // WIZARD_CHAIN_LIGHTNING
      // WIZARD_ACID_FOG
      // WIZARD_CIRCLE_OF_DEATH
      // WIZARD_INVISIBLE_STALKER
      // WIZARD_SUMMON_MONSTER_VI
      // WIZARD_OTILUKES_FREEZING_SPHERE
      // WIZARD_SHADES
      // WIZARD_STONE_TO_FLESH
    MarkSpellAndObject("26172619262126222626262826272629",LastMarkedObject,15)
      // WIZARD_POWER_WORD_SILENCE
      // WIZARD_SOUL_EATER
      // WIZARD_CARRION_SUMMONS
      // WIZARD_CONJURE_AIR_ELEMENTAL
      // WIZARD_WYVERN_CALL
      // WIZARD_CONJURE_EARTH_ELEMENTAL
      // WIZARD_CONJURE_FIRE_ELEMENTAL
      // WIZARD_CONJURE_WATER_ELEMENTAL
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    IncrementGlobal("Level6Spells","LOCALS",-1)
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  !Allegiance(Myself,ENEMY)
  Global("61CurrentDay","GLOBAL",2)
  OpenState("AR6104_Cage",FALSE)  // AR6104_Cage
THEN
  RESPONSE #100
    RandomTurn()
END

