IF
  Global("TellStory","LOCALS",0)
  See(Player1,0)
  HasItem("00SWDL07",Player1)  // ~The Sword of Myrloch Vale~
THEN
  RESPONSE #100
    SetGlobal("TellStory","LOCALS",-1)
END

IF
  Global("TellStory","LOCALS",0)
  See(Player2,0)
  HasItem("00SWDL07",Player2)  // ~The Sword of Myrloch Vale~
THEN
  RESPONSE #100
    SetGlobal("TellStory","LOCALS",-1)
END

IF
  Global("TellStory","LOCALS",0)
  See(Player3,0)
  HasItem("00SWDL07",Player3)  // ~The Sword of Myrloch Vale~
THEN
  RESPONSE #100
    SetGlobal("TellStory","LOCALS",-1)
END

IF
  Global("TellStory","LOCALS",0)
  See(Player4,0)
  HasItem("00SWDL07",Player4)  // ~The Sword of Myrloch Vale~
THEN
  RESPONSE #100
    SetGlobal("TellStory","LOCALS",-1)
END

IF
  Global("TellStory","LOCALS",0)
  See(Player5,0)
  HasItem("00SWDL07",Player5)  // ~The Sword of Myrloch Vale~
THEN
  RESPONSE #100
    SetGlobal("TellStory","LOCALS",-1)
END

IF
  Global("TellStory","LOCALS",0)
  See(Player6,0)
  HasItem("00SWDL07",Player6)  // ~The Sword of Myrloch Vale~
THEN
  RESPONSE #100
    SetGlobal("TellStory","LOCALS",-1)
END

IF
  Global("TellStory","LOCALS",-1)
THEN
  RESPONSE #100
    ClearAllActions()
    SetCreatureAreaFlag(Myself,INVULNERABLE,TRUE)
    ChangeEnemyAlly(Myself,NEUTRAL)
    SpellHitEffectSprite(Myself,Myself,RESURRECTION,0)
    XEquipItem("00CIPFND",Myself,SLOT_RING_RIGHT,FALSE)
    DestroyItem("00CIPFND")  // <Invalid Strref -1>
    GiveItemCreate("00CITrn1",Myself,0,0,0)  // <Invalid Strref -1>
    Polymorph(THIEF_MALE_HUMAN)
    XEquipItem("00CITrn1",Myself,SLOT_RING_RIGHT,TRUE)
    TakePartyItem("00SWDL07")
    EquipItem("00SWDL07",1)
    SetGlobal("TellStory","LOCALS",1)
END

IF
  Global("TellStory","LOCALS",1)
THEN
  RESPONSE #100
    ClearAllActions()
    MultiPlayerSync()
    StartCutSceneMode()
    CutSceneId(Myself)  // 
    HideGUI()
    MoveViewObject(Myself,VERY_FAST)
    ActionOverride(Player1,JumpToObject(Myself))
    ActionOverride(Player2,JumpToObject(Myself))
    ActionOverride(Player3,JumpToObject(Myself))
    ActionOverride(Player4,JumpToObject(Myself))
    ActionOverride(Player5,JumpToObject(Myself))
    ActionOverride(Player6,JumpToObject(Myself))
    ApplySpell(Player1,WIZARD_INVISIBILITY)
    ApplySpell(Player2,WIZARD_INVISIBILITY)
    ApplySpell(Player3,WIZARD_INVISIBILITY)
    ApplySpell(Player4,WIZARD_INVISIBILITY)
    ApplySpell(Player5,WIZARD_INVISIBILITY)
    ApplySpell(Player6,WIZARD_INVISIBILITY)
    FaceObject(NearestPC)
    FloatMessage(Myself,35385)  // ~"Soul - free...  Thee - I thank - I thank."~
    Wait(5)
    FaceObject(NearestPC)
    FloatMessage(Myself,35386)  // ~"Follow..."~
    Wait(5)
    SpellHitEffectSprite(Myself,Myself,PRAYER,0)
    SpellHitEffectSprite(Myself,Player1,PRAYER,0)
    SpellHitEffectSprite(Myself,Player2,PRAYER,0)
    SpellHitEffectSprite(Myself,Player3,PRAYER,0)
    SpellHitEffectSprite(Myself,Player4,PRAYER,0)
    SpellHitEffectSprite(Myself,Player5,PRAYER,0)
    SpellHitEffectSprite(Myself,Player6,PRAYER,0)
    FadeToColor([0.0],0)
    JumpToPoint([2920.2140])
    ActionOverride(Player1,JumpToPoint([2920.2140]))
    ActionOverride(Player2,JumpToPoint([2920.2140]))
    ActionOverride(Player3,JumpToPoint([2920.2140]))
    ActionOverride(Player4,JumpToPoint([2920.2140]))
    ActionOverride(Player5,JumpToPoint([2920.2140]))
    ActionOverride(Player6,JumpToPoint([2920.2140]))
    ActionOverride(Player1,JumpToPoint([2920.2140]))
    ActionOverride(Player2,JumpToPoint([2920.2140]))
    ActionOverride(Player3,JumpToPoint([2920.2140]))
    ActionOverride(Player4,JumpToPoint([2920.2140]))
    ActionOverride(Player5,JumpToPoint([2920.2140]))
    ActionOverride(Player6,JumpToPoint([2920.2140]))
    MoveViewObject(Myself,INSTANT)
    FadeFromColor([0.0],0)
    FaceObject(NearestPC)
    FloatMessage(Myself,35387)  // ~"Snakes - down below...  Poisoned...!  Sword I drop...  Sword I lose...  Sword you found."~
    Wait(7)
    FaceObject(NearestPC)
    FloatMessage(Myself,35386)  // ~"Follow..."~
    Wait(1)
    SpellHitEffectSprite(Myself,Myself,PRAYER,0)
    SpellHitEffectSprite(Myself,Player1,PRAYER,0)
    SpellHitEffectSprite(Myself,Player2,PRAYER,0)
    SpellHitEffectSprite(Myself,Player3,PRAYER,0)
    SpellHitEffectSprite(Myself,Player4,PRAYER,0)
    SpellHitEffectSprite(Myself,Player5,PRAYER,0)
    SpellHitEffectSprite(Myself,Player6,PRAYER,0)
    FadeToColor([0.0],0)
    JumpToPoint([1220.1980])
    ActionOverride(Player1,JumpToPoint([1220.1980]))
    ActionOverride(Player2,JumpToPoint([1220.1980]))
    ActionOverride(Player3,JumpToPoint([1220.1980]))
    ActionOverride(Player4,JumpToPoint([1220.1980]))
    ActionOverride(Player5,JumpToPoint([1220.1980]))
    ActionOverride(Player6,JumpToPoint([1220.1980]))
    ActionOverride(Player1,JumpToPoint([1220.1980]))
    ActionOverride(Player2,JumpToPoint([1220.1980]))
    ActionOverride(Player3,JumpToPoint([1220.1980]))
    ActionOverride(Player4,JumpToPoint([1220.1980]))
    ActionOverride(Player5,JumpToPoint([1220.1980]))
    ActionOverride(Player6,JumpToPoint([1220.1980]))
    MoveViewObject(Myself,INSTANT)
    FadeFromColor([0.0],0)
    Wait(1)
    ActionOverride(Player1,MoveToPoint([1570.2020]))
    ActionOverride(Player2,MoveToPoint([1570.2020]))
    ActionOverride(Player3,MoveToPoint([1570.2020]))
    ActionOverride(Player4,MoveToPoint([1570.2020]))
    ActionOverride(Player5,MoveToPoint([1570.2020]))
    ActionOverride(Player6,MoveToPoint([1570.2020]))
    MoveViewPoint([1570.2020],FAST)
    MoveToPoint([1570.2020])
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    ActionOverride(Player1,MoveToPoint([1973.2056]))
    ActionOverride(Player2,MoveToPoint([1973.2056]))
    ActionOverride(Player3,MoveToPoint([1973.2056]))
    ActionOverride(Player4,MoveToPoint([1973.2056]))
    ActionOverride(Player5,MoveToPoint([1973.2056]))
    ActionOverride(Player6,MoveToPoint([1973.2056]))
    MoveViewPoint([1973.2056],FAST)
    MoveToPoint([1973.2056])
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    FaceObject(NearestPC)
    FloatMessage(Myself,35388)  // ~"Poisoned...!  Dying...  Evading...  Here I stop - toss root over top of stone...  Root - snakes no find...  Nheero - safe."~
    Wait(6)
    DropInventoryEX("FakeRoot")
    ActionOverride("FakeRoot",DestroySelf())
    Wait(6)
    FaceObject(NearestPC)
    FloatMessage(Myself,35386)  // ~"Follow..."~
    Wait(1)
    SpellHitEffectSprite(Myself,Myself,PRAYER,0)
    SpellHitEffectSprite(Myself,Player1,PRAYER,0)
    SpellHitEffectSprite(Myself,Player2,PRAYER,0)
    SpellHitEffectSprite(Myself,Player3,PRAYER,0)
    SpellHitEffectSprite(Myself,Player4,PRAYER,0)
    SpellHitEffectSprite(Myself,Player5,PRAYER,0)
    SpellHitEffectSprite(Myself,Player6,PRAYER,0)
    FadeToColor([0.0],0)
    JumpToPoint([3550.1270])
    ActionOverride(Player1,JumpToPoint([3550.1270]))
    ActionOverride(Player2,JumpToPoint([3550.1270]))
    ActionOverride(Player3,JumpToPoint([3550.1270]))
    ActionOverride(Player4,JumpToPoint([3550.1270]))
    ActionOverride(Player5,JumpToPoint([3550.1270]))
    ActionOverride(Player6,JumpToPoint([3550.1270]))
    ActionOverride(Player1,JumpToPoint([3550.1270]))
    ActionOverride(Player2,JumpToPoint([3550.1270]))
    ActionOverride(Player3,JumpToPoint([3550.1270]))
    ActionOverride(Player4,JumpToPoint([3550.1270]))
    ActionOverride(Player5,JumpToPoint([3550.1270]))
    ActionOverride(Player6,JumpToPoint([3550.1270]))
    MoveViewObject(Myself,INSTANT)
    FadeFromColor([0.0],0)
    FaceObject(NearestPC)
    FloatMessage(Myself,35389)  // ~"Poisoned...!  Dying...  Evading...  Here I stop...  Ball - no stop...  Rolling...  Crushing..."~
    Wait(7)
    FaceObject(NearestPC)
    FloatMessage(Myself,35390)  // ~"Dying...  Dying...  Dying..."~
    Wait(7)
    FaceObject(NearestPC)
    FloatMessage(Myself,35385)  // ~"Soul - free...  Thee - I thank - I thank."~
    Wait(5)
    SpellHitEffectSprite(Myself,Myself,DEATH_SPELL,0)
    SetCriticalPathObject(Myself,FALSE)
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    UnhideGUI()
    EndCutSceneMode()
    DestroySelf()
END

IF
  Allegiance(Myself,ENEMY)
  See([GOODCUTOFF],0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  Global("RW_61MANDAL0","LOCALS",0)
  !NearSavedLocation(20)
THEN
  RESPONSE #100
    SetGlobal("RW_61MANDAL0","LOCALS",1)
    Continue()
END

IF
  !Global("RW_61MANDAL0","LOCALS",0)
  NearSavedLocation(20)
THEN
  RESPONSE #100
    SetGlobal("RW_61MANDAL0","LOCALS",0)
    NoAction()
END

IF
  !Global("RW_61MANDAL0","LOCALS",0)
THEN
  RESPONSE #100
    MoveToPoint([-2.-2])
END

IF
  !TimerActive(22)
  Global("RW_61MANDAL0","LOCALS",0)
THEN
  RESPONSE #100
    RandomWalk()
    StartTimer(22,5)
END

