IF
  !BitGlobal("61BrazierTally","GLOBAL",4,AND)
  Clicked([PC])
  !HasItem("00Gem01",Myself)  // ~Fire Agate Gem~
  PartyHasItem("00Gem01")  // ~Fire Agate Gem~
  Range(NearestPC,6,LESS_THAN)
THEN
  RESPONSE #100
    FloatMessage(LastTrigger,41115)  // ~Placing the fire agate within the brazier causes it to suddenly erupt in magical flames. ~
    TakePartyItemNum("00Gem01",1)
    StartCutSceneMode()
    EndCutSceneMode()
    IncrementGlobal("61BrazierTally","GLOBAL",4)
END

IF
  BitGlobal("61BrazierTally","GLOBAL",4,AND)
  HasItem("00Gem01",Myself)  // ~Fire Agate Gem~
THEN
  RESPONSE #100
    PlaySound("aft_p31a")
    DestroyItem("00Gem01")  // ~Fire Agate Gem~
    Activate("BrazierFlame3")
    Deactivate("BrazierGem3")
    TriggerActivation("InfoBrazier3",FALSE)
    ChangeCurrentScript("")
END

IF
  !BitGlobal("61BrazierTally","GLOBAL",4,AND)
  TotalItemCntGT(Myself,0)
  Range(NearestPC,25,LESS_THAN)
THEN
  RESPONSE #100
    TransferInventory(Myself,LastMarkedObject)
    DisplayString(LastMarkedObject,34923)  // ~The item you placed inside the brazier spins around the pan a few revolutions before tumbling out, but you catch it before it hits the ground.~
    StartCutSceneMode()
    EndCutSceneMode()
END

IF
  Clicked([PC])
THEN
  RESPONSE #100
    NoAction()
END

