IF
  Entered([PC])
THEN
  RESPONSE #100
    Activate("ExitTrap")
    PlaySequence("ExitTrap",AWAKE)
    DisplayMessage(14381)  // ~Trap Sprung~ [AMB_D05C]
    SetGlobal("TEAM_7","MYAREA",1)
    Shout(107)
    SetGlobal("LastShout","LOCALS",107)
    FloatMessage(Myself,35589)  // ~"Yemen detptos.["Enemy spotted." reordered and scrambled]"~
    StartTimer(102,7)
    IncrementGlobal("YuantiCallForHelp","MYAREA",5)
    IncrementGlobal("61HalfbreedDied","GLOBAL",5)
    TriggerActivation("ExitTrapVisible",TRUE)
    SmallWait(1)
    ForceSpell(LastTrigger,WIZARD_DISPEL_MAGIC)
    ForceSpell(LastTrigger,2095)
    Wait(2)
    Deactivate("ExitTrap")
END

