IF
  Clicked([PC])
THEN
  RESPONSE #100
    DisplayMessage(14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastMarkedObject,TRAP_ARROW_ACID)
  RESPONSE #100
    DisplayMessage(14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastMarkedObject,TRAP_ARROW_BITING)
  RESPONSE #100
    DisplayMessage(14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastMarkedObject,TRAP_DISEASE_DARTS)
  RESPONSE #100
    DisplayMessage(14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastMarkedObject,TRAP_POISON_CONFUSION_DARTS)
  RESPONSE #100
    DisplayMessage(14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastMarkedObject,TRAP_POISON_DAMAGE_DARTS)
  RESPONSE #100
    DisplayMessage(14381)  // ~Trap Sprung~ [AMB_D05C]
    ReallyForceSpell(LastMarkedObject,TRAP_POISON_PARALYZATION_DARTS)
END

