IF
  IsOverMe([ANYONE])
THEN
  RESPONSE #100
    ActionOverride(LastTrigger,JumpToPoint([3300.1310]))
  RESPONSE #100
    ActionOverride(LastTrigger,JumpToPoint([3230.1440]))
  RESPONSE #100
    ActionOverride(LastTrigger,JumpToPoint([3260.1560]))
END

IF
  !IsOverMe([ANYONE])
THEN
  RESPONSE #100
    ScreenShake(50,16,12)
    CloseDoor("AR6104_East_Rocks")
    ChangeCurrentScript("")
    TriggerActivation(Myself,FALSE)
END

