IF
  Global("CheckCure","LOCALS",0)
  Global("Rested","LOCALS",1)
  GlobalTimerExpired("CheckCureTimer","LOCALS")
  Or(5)
    HaveSpell(CLERIC_NEUTRALIZE_POISON)
    HaveSpell(CLERIC_EXALTATION)
    HaveSpell(CLERIC_REMOVE_PARALYSIS)
    HaveSpell(CLERIC_CURE_DISEASE)
    HaveSpell(CLERIC_DISPEL_MAGIC)
THEN
  RESPONSE #100
    SetGlobal("CheckCure","LOCALS",1)
    Continue()
END

IF
  Global("CheckCure","LOCALS",1)
  !Allegiance(Myself,ENEMY)
  Or(2)
    See(MostDamagedOf(Myself),0)
    See([GOODCUTOFF],0)
THEN
  RESPONSE #100
    SetMyTarget(LastMarkedObject)
    SetGlobal("CheckCure","LOCALS",2)
    Continue()
END

IF
  Global("CheckCure","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(MostDamagedOf(Myself),0)
  Allegiance(LastMarkedObject,ENEMY)
THEN
  RESPONSE #100
    SetMyTarget(LastMarkedObject)
    SetGlobal("CheckCure","LOCALS",2)
    Continue()
END

IF
  Global("CheckCure","LOCALS",2)
  HaveSpell(CLERIC_NEUTRALIZE_POISON)
  StateCheck(MyTarget,STATE_POISONED)
  !CheckSpellState(MyTarget,GLOBE_OF_INVULNERABILITY)
THEN
  RESPONSE #100
    Spell(MyTarget,CLERIC_NEUTRALIZE_POISON)
    SetGlobal("CheckCure","LOCALS",0)
END

IF
  Global("CheckCure","LOCALS",2)
  HaveSpell(CLERIC_EXALTATION)
  Or(8)
    StateCheck(MyTarget,STATE_PANIC)
    StateCheck(MyTarget,STATE_SLEEPING)
    StateCheck(MyTarget,STATE_FEEBLEMINDED)
    StateCheck(MyTarget,STATE_STUNNED)
    StateCheck(MyTarget,STATE_HELPLESS)
    StateCheck(MyTarget,STATE_BERSERK)
    StateCheck(MyTarget,STATE_CONFUSED)
    CheckSpellState(MyTarget,HOPELESSNESS)
  !CheckSpellState(MyTarget,GLOBE_OF_INVULNERABILITY)
  !CheckSpellState(MyTarget,MINOR_GLOBE_OF_INVULNERABILITY)
THEN
  RESPONSE #100
    Spell(MyTarget,CLERIC_EXALTATION)
    SetGlobal("CheckCure","LOCALS",0)
END

IF
  Global("CheckCure","LOCALS",2)
  HaveSpell(CLERIC_REMOVE_PARALYSIS)
  CheckSpellState(MyTarget,HELD)
  !CheckSpellState(MyTarget,GLOBE_OF_INVULNERABILITY)
  !CheckSpellState(MyTarget,MINOR_GLOBE_OF_INVULNERABILITY)
THEN
  RESPONSE #100
    Spell(MyTarget,CLERIC_REMOVE_PARALYSIS)
    SetGlobal("CheckCure","LOCALS",0)
END

IF
  Global("CheckCure","LOCALS",2)
  HaveSpell(CLERIC_CURE_DISEASE)
  StateCheck(MyTarget,STATE_DISEASED)
  !CheckSpellState(MyTarget,GLOBE_OF_INVULNERABILITY)
  !CheckSpellState(MyTarget,MINOR_GLOBE_OF_INVULNERABILITY)
THEN
  RESPONSE #100
    Spell(MyTarget,CLERIC_CURE_DISEASE)
    SetGlobal("CheckCure","LOCALS",0)
END

IF
  Global("CheckCure","LOCALS",2)
  HaveSpell(CLERIC_DISPEL_MAGIC)
  Or(8)
    StateCheck(MyTarget,STATE_HELPLESS)
    StateCheck(MyTarget,STATE_STUNNED)
    StateCheck(MyTarget,STATE_PANIC)
    StateCheck(MyTarget,STATE_SLEEPING)
    StateCheck(MyTarget,STATE_SILENCED)
    StateCheck(MyTarget,STATE_CHARMED)
    StateCheck(MyTarget,STATE_FEEBLEMINDED)
    StateCheck(MyTarget,STATE_CONFUSED)
  !CheckSpellState(MyTarget,GLOBE_OF_INVULNERABILITY)
  !CheckSpellState(MyTarget,MINOR_GLOBE_OF_INVULNERABILITY)
THEN
  RESPONSE #100
    Spell(MyTarget,CLERIC_DISPEL_MAGIC)
    SetGlobal("CheckCure","LOCALS",0)
END

IF
  GlobalGT("CheckCure","LOCALS",-1)
  Global("Rested","LOCALS",1)
  GlobalTimerExpired("CheckCureTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("CheckCureTimer","LOCALS",10)
    SetGlobal("CheckCure","LOCALS",0)
    Continue()
END

IF
  HaveSpell(CLERIC_HEAL)
  Global("Rested","LOCALS",1)
  See(MostDamagedOf(Myself),0)
  HPPercentLT(LastSeenBy(Myself),50)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_HEAL,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_HEAL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
  Global("Rested","LOCALS",1)
  See(MostDamagedOf(Myself),0)
  HPLostGT(LastSeenBy(Myself),46)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
  Global("Rested","LOCALS",1)
  See(MostDamagedOf(Myself),0)
  HPLostGT(LastSeenBy(Myself),37)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  Global("Rested","LOCALS",1)
  See(MostDamagedOf(Myself),0)
  HPLostGT(LastSeenBy(Myself),18)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_MODERATE_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  Global("Rested","LOCALS",1)
  See(MostDamagedOf(Myself),0)
  HPLostGT(LastSeenBy(Myself),8)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Allegiance(Myself,ENEMY)
  GlobalGT("CheckDead","LOCALS",-1)
THEN
  RESPONSE #100
    SetGlobal("CheckDead","LOCALS",-1)
END

IF
  Global("CheckDead","LOCALS",0)
  Global("Rested","LOCALS",1)
  GlobalTimerExpired("CheckDeadTimer","LOCALS")
  Or(2)
    HaveSpell(CLERIC_RAISE_DEAD)
    HaveSpell(CLERIC_RESURRECTION)
  See([PC],0)
THEN
  RESPONSE #100
    SetGlobal("CheckDead","LOCALS",1)
    Continue()
END

IF
  Global("CheckDead","LOCALS",1)
  Dead(Player1)  // 
THEN
  RESPONSE #100
    SetMyTarget(Player1)
    SetGlobal("CheckDead","LOCALS",2)
    Continue()
END

IF
  Global("CheckDead","LOCALS",1)
  NumInPartyGT(1)
  Dead(Player2)  // 
THEN
  RESPONSE #100
    SetMyTarget(Player2)
    SetGlobal("CheckDead","LOCALS",2)
    Continue()
END

IF
  Global("CheckDead","LOCALS",1)
  NumInPartyGT(2)
  Dead(Player3)  // 
THEN
  RESPONSE #100
    SetMyTarget(Player3)
    SetGlobal("CheckDead","LOCALS",2)
    Continue()
END

IF
  Global("CheckDead","LOCALS",1)
  NumInPartyGT(3)
  Dead(Player4)  // 
THEN
  RESPONSE #100
    SetMyTarget(Player4)
    SetGlobal("CheckDead","LOCALS",2)
    Continue()
END

IF
  Global("CheckDead","LOCALS",1)
  NumInPartyGT(4)
  Dead(Player5)  // 
THEN
  RESPONSE #100
    SetMyTarget(Player5)
    SetGlobal("CheckDead","LOCALS",2)
    Continue()
END

IF
  Global("CheckDead","LOCALS",1)
  NumInPartyGT(5)
  Dead(Player6)  // 
THEN
  RESPONSE #100
    SetMyTarget(Player6)
    SetGlobal("CheckDead","LOCALS",2)
    Continue()
END

IF
  Global("CheckDead","LOCALS",2)
  HaveSpell(CLERIC_RAISE_DEAD)
  !Race(MyTarget,ELF)
THEN
  RESPONSE #100
    Spell(MyTarget,CLERIC_RAISE_DEAD)
    SetGlobal("CheckDead","LOCALS",0)
END

IF
  Global("CheckDead","LOCALS",2)
  HaveSpell(CLERIC_RESURRECTION)
THEN
  RESPONSE #100
    Spell(MyTarget,CLERIC_RESURRECTION)
    SetGlobal("CheckDead","LOCALS",0)
END

IF
  GlobalGT("CheckDead","LOCALS",-1)
  GlobalTimerExpired("CheckDeadTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("CheckDeadTimer","LOCALS",10)
    SetGlobal("CheckDead","LOCALS",0)
    Continue()
END

