IF
  Allegiance(Myself,ENEMY)
  OpenState("AR6102_Trees",TRUE)  // AR6102_Trees
THEN
  RESPONSE #100
    SetGlobal("61RakshasaOfferValid","GLOBAL",0)
    SpellHitEffectSprite(Myself,Myself,ILLUSION,0)
    Polymorph(Rakshasa)
    SetApparentNameSTRREF(Myself,27113)  // ~Rakshasa Maharajah~
    SetRegularNameSTRREF(Myself,27113)  // ~Rakshasa Maharajah~
    SpellHitEffectPoint(Myself,[160.1312],ILLUSION,0)
    SpellHitEffectPoint(Myself,[256.1088],ILLUSION,0)
    SpellHitEffectPoint(Myself,[352.1248],ILLUSION,0)
    SpellHitEffectPoint(Myself,[352.1504],ILLUSION,0)
    SpellHitEffectPoint(Myself,[512.1152],ILLUSION,0)
    HideCreature("03_Jaguar_01",FALSE)
    HideCreature("03_Jaguar_02",FALSE)
    HideCreature("03_Jaguar_03",FALSE)
    HideCreature("03_Jaguar_04",FALSE)
    HideCreature("03_Jaguar_05",FALSE)
    HideCreature("03_Jaguar_06",FALSE)
    Deactivate("jungleoasis")
    CloseDoor("AR6102_Trees")
END

IF
  Allegiance(Myself,ENEMY)
  Global("GaveSpeech","LOCALS",0)
  See(Player1,0)
  !CheckSpellState(LastMarkedObject,HELD)
THEN
  RESPONSE #100
    Dialogue(LastMarkedObject)
END

IF
  Allegiance(Myself,ENEMY)
  Global("GaveSpeech","LOCALS",0)
  See(Player2,0)
  !CheckSpellState(LastMarkedObject,HELD)
THEN
  RESPONSE #100
    Dialogue(LastMarkedObject)
END

IF
  Allegiance(Myself,ENEMY)
  Global("GaveSpeech","LOCALS",0)
  See(Player3,0)
  !CheckSpellState(LastMarkedObject,HELD)
THEN
  RESPONSE #100
    Dialogue(LastMarkedObject)
END

IF
  Allegiance(Myself,ENEMY)
  Global("GaveSpeech","LOCALS",0)
  See(Player4,0)
  !CheckSpellState(LastMarkedObject,HELD)
THEN
  RESPONSE #100
    Dialogue(LastMarkedObject)
END

IF
  Allegiance(Myself,ENEMY)
  Global("GaveSpeech","LOCALS",0)
  See(Player5,0)
  !CheckSpellState(LastMarkedObject,HELD)
THEN
  RESPONSE #100
    Dialogue(LastMarkedObject)
END

IF
  Allegiance(Myself,ENEMY)
  Global("GaveSpeech","LOCALS",0)
  See(Player6,0)
  !CheckSpellState(LastMarkedObject,HELD)
THEN
  RESPONSE #100
    Dialogue(LastMarkedObject)
END

IF
  Allegiance(Myself,ENEMY)
  Global("GaveSpeech","LOCALS",0)
  !See([PC],0)
THEN
  RESPONSE #100
    ClearSpriteEffects(Myself)
    MoveToObject(NearestPC)
END

IF
  Global("61JagDied","GLOBAL",1)
  GlobalLT("61NumJagsKilled","GLOBAL",30)
THEN
  RESPONSE #100
    CreateCreature("61Jaguar","",[352.1632],8)  // ~Ferocious Jaguar~
    SetGlobal("61JagDied","GLOBAL",0)
    Continue()
  RESPONSE #100
    CreateCreature("61Jaguar","",[1152.1024],4)  // ~Ferocious Jaguar~
    SetGlobal("61JagDied","GLOBAL",0)
    Continue()
END

IF
  !TimerActive(101)
THEN
  RESPONSE #100
    Rest()
    StartTimer(101,2400)
END

IF
  HasItem("00potn05",Myself)  // ~Potion of Extra Healing~
  Allegiance(Myself,ENEMY)
  HPPercentLT(Myself,75)
THEN
  RESPONSE #100
    UseItem("00potn05",Myself)  // ~Potion of Extra Healing~
END

IF
  HaveSpell(CLERIC_CURE_MODERATE_WOUNDS)
  Allegiance(Myself,ENEMY)
  HPLostGT(Myself,18)
  IsSpellTargetValid(Myself,CLERIC_CURE_MODERATE_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_MODERATE_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
  Allegiance(Myself,ENEMY)
  HPLostGT(Myself,8)
  IsSpellTargetValid(Myself,CLERIC_CURE_LIGHT_WOUNDS,0)
THEN
  RESPONSE #100
    Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(CLERIC_HEALING_CIRCLE)
  Allegiance(Myself,ENEMY)
  See([ENEMY.ANIMAL],0)
  HPLostGT(LastSeenBy(Myself),18)
  IsSpellTargetValid(LastSeenBy(Myself),CLERIC_HEALING_CIRCLE,0)
THEN
  RESPONSE #100
    Spell(LastSeenBy(Myself),CLERIC_HEALING_CIRCLE)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  Or(4)
    HasItem("CDiseas",Myself)  // ~Contagion~
    HasItem("BClaw",Myself)  // ~Beast Claw~
    HasItem("CSDamag",Myself)  // ~Inflict Serious Wounds~
    HasItem("PBlade",Myself)  // ~Phantom Blade~
  Allegiance(Myself,ENEMY)
  !Global("OBJ_SP_61RAKSHA_0","LOCALS",-1)
  See([GOODCUTOFF],0)
THEN
  RESPONSE #100
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  !Global("OBJ_SP_61RAKSHA_0","LOCALS",-1)
  Allegiance(Myself,ENEMY)
  !Global("OBJ_SP_61RAKSHA_0","LOCALS",-1)
  See([GOODCUTOFF],0)
THEN
  RESPONSE #100
    MarkSpellAndObject("11131204222222242512241825132613",LastMarkedObject,7)
      // CLERIC_SUNSCORCH
      // CLERIC_CHARM_PERSON_OR_MAMMAL
      // WIZARD_BLINDNESS
      // WIZARD_DEAFNESS
      // WIZARD_GREATER_SHADOW_CONJURATION
      // WIZARD_SHADOW_CONJURATION
      // WIZARD_SUMMON_SHADOW
      // WIZARD_SHADES
    MarkSpellAndObject("13151217131214162120220122122206",Myself,7)
      // CLERIC_CAUSE_DISEASE
      // CLERIC_BEAST_CLAW
      // CLERIC_STRENGTH_OF_ONE
      // CLERIC_CAUSE_SERIOUS_WOUNDS
      // WIZARD_MINOR_MIRROR_IMAGE
      // WIZARD_BLUR
      // WIZARD_MIRROR_IMAGE
      // WIZARD_INVISIBILITY
    MarkSpellAndObject("232124052521",Myself,7)
      // WIZARD_INVISIBILITY_10_RADIUS
      // WIZARD_IMPROVED_INVISIBILITY
      // WIZARD_PHANTOM_BLADE
    MarkSpellAndObject("1402",LastMarkedObject,7)
      // CLERIC_SUMMON_NATURES_ALLY_4
    Continue()
  RESPONSE #100
    MarkSpellAndObject("13151217131214162120220122122206",Myself,7)
      // CLERIC_CAUSE_DISEASE
      // CLERIC_BEAST_CLAW
      // CLERIC_STRENGTH_OF_ONE
      // CLERIC_CAUSE_SERIOUS_WOUNDS
      // WIZARD_MINOR_MIRROR_IMAGE
      // WIZARD_BLUR
      // WIZARD_MIRROR_IMAGE
      // WIZARD_INVISIBILITY
    MarkSpellAndObject("232124052521",Myself,7)
      // WIZARD_INVISIBILITY_10_RADIUS
      // WIZARD_IMPROVED_INVISIBILITY
      // WIZARD_PHANTOM_BLADE
    MarkSpellAndObject("1402",LastMarkedObject,7)
      // CLERIC_SUMMON_NATURES_ALLY_4
    MarkSpellAndObject("11131204222222242512241825132613",LastMarkedObject,7)
      // CLERIC_SUNSCORCH
      // CLERIC_CHARM_PERSON_OR_MAMMAL
      // WIZARD_BLINDNESS
      // WIZARD_DEAFNESS
      // WIZARD_GREATER_SHADOW_CONJURATION
      // WIZARD_SHADOW_CONJURATION
      // WIZARD_SUMMON_SHADOW
      // WIZARD_SHADES
    Continue()
  RESPONSE #100
    MarkSpellAndObject("232124052521",Myself,7)
      // WIZARD_INVISIBILITY_10_RADIUS
      // WIZARD_IMPROVED_INVISIBILITY
      // WIZARD_PHANTOM_BLADE
    MarkSpellAndObject("1402",LastMarkedObject,7)
      // CLERIC_SUMMON_NATURES_ALLY_4
    MarkSpellAndObject("11131204222222242512241825132613",LastMarkedObject,7)
      // CLERIC_SUNSCORCH
      // CLERIC_CHARM_PERSON_OR_MAMMAL
      // WIZARD_BLINDNESS
      // WIZARD_DEAFNESS
      // WIZARD_GREATER_SHADOW_CONJURATION
      // WIZARD_SHADOW_CONJURATION
      // WIZARD_SUMMON_SHADOW
      // WIZARD_SHADES
    MarkSpellAndObject("13151217131214162120220122122206",Myself,7)
      // CLERIC_CAUSE_DISEASE
      // CLERIC_BEAST_CLAW
      // CLERIC_STRENGTH_OF_ONE
      // CLERIC_CAUSE_SERIOUS_WOUNDS
      // WIZARD_MINOR_MIRROR_IMAGE
      // WIZARD_BLUR
      // WIZARD_MIRROR_IMAGE
      // WIZARD_INVISIBILITY
    Continue()
  RESPONSE #100
    MarkSpellAndObject("1402",LastMarkedObject,7)
      // CLERIC_SUMMON_NATURES_ALLY_4
    MarkSpellAndObject("11131204222222242512241825132613",LastMarkedObject,7)
      // CLERIC_SUNSCORCH
      // CLERIC_CHARM_PERSON_OR_MAMMAL
      // WIZARD_BLINDNESS
      // WIZARD_DEAFNESS
      // WIZARD_GREATER_SHADOW_CONJURATION
      // WIZARD_SHADOW_CONJURATION
      // WIZARD_SUMMON_SHADOW
      // WIZARD_SHADES
    MarkSpellAndObject("13151217131214162120220122122206",Myself,7)
      // CLERIC_CAUSE_DISEASE
      // CLERIC_BEAST_CLAW
      // CLERIC_STRENGTH_OF_ONE
      // CLERIC_CAUSE_SERIOUS_WOUNDS
      // WIZARD_MINOR_MIRROR_IMAGE
      // WIZARD_BLUR
      // WIZARD_MIRROR_IMAGE
      // WIZARD_INVISIBILITY
    MarkSpellAndObject("232124052521",Myself,7)
      // WIZARD_INVISIBILITY_10_RADIUS
      // WIZARD_IMPROVED_INVISIBILITY
      // WIZARD_PHANTOM_BLADE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  !Global("OBJ_SP_61RAKSHA_0","LOCALS",-1)
  !HaveSpell(CLERIC_SUNSCORCH)
  !HaveSpell(CLERIC_CHARM_PERSON_OR_MAMMAL)
  !HaveSpell(CLERIC_CAUSE_DISEASE)
  !HaveSpell(WIZARD_BLINDNESS)
  !HaveSpell(WIZARD_DEAFNESS)
  !HaveSpell(WIZARD_GREATER_SHADOW_CONJURATION)
  !HaveSpell(WIZARD_SHADOW_CONJURATION)
  !HaveSpell(WIZARD_SUMMON_SHADOW)
  !HaveSpell(WIZARD_SHADES)
  !HaveSpell(CLERIC_BEAST_CLAW)
  !HaveSpell(CLERIC_STRENGTH_OF_ONE)
  !HaveSpell(CLERIC_CAUSE_SERIOUS_WOUNDS)
  !HaveSpell(WIZARD_MINOR_MIRROR_IMAGE)
  !HaveSpell(WIZARD_BLUR)
  !HaveSpell(WIZARD_MIRROR_IMAGE)
  !HaveSpell(WIZARD_INVISIBILITY)
  !HaveSpell(WIZARD_INVISIBILITY_10_RADIUS)
  !HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
  !HaveSpell(WIZARD_PHANTOM_BLADE)
  !HaveSpell(CLERIC_SUMMON_NATURES_ALLY_4)
THEN
  RESPONSE #100
    SetGlobal("OBJ_SP_61RAKSHA_0","LOCALS",-1)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  HaveSpell(CLERIC_HOLD_ANIMAL)
  See([GOODCUTOFF.ANIMAL],0)
  IsSpellTargetValid(LastMarkedObject,CLERIC_HOLD_ANIMAL,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,CLERIC_HOLD_ANIMAL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

