IF
  NumberOfTimesTalkedTo(0)
  See([PC],0)
THEN
  RESPONSE #100
    SetGlobal("61PlayerMetThorasskus","GLOBAL",1)
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

IF
  Global("ChangeForm","LOCALS",-1)
  See([PC],0)
THEN
  RESPONSE #100
    SetCreatureAreaFlag(Myself,INVULNERABLE,FALSE)
    SpellHitEffectSprite(Myself,Myself,ALTERATION,0)
    SpellHitEffectPoint(Myself,[2000.2470],ALTERATION,0)
    Polymorph("""""Yuan Ti, Priest""""")
    EquipItem("00RING22",1)
    OpenDoor("AR6103_Bridge")
    TriggerActivation("InfoBridge",TRUE)
    TriggerActivation("To6103a",TRUE)
    TriggerActivation("To6103b",TRUE)
    TriggerActivation("InfoTunnelA",TRUE)
    TriggerActivation("InfoTunnelB",TRUE)
    TriggerActivation("TunnelHint",TRUE)
    FloatMessage("TunnelFloat",32698)  // ~You feel a slight breeze coming from the southeast corner of this room.~
    Unlock("AR6103_Treasure_Room")
    SetDialogueRange(300)
    DialogInterrupt(TRUE)
    Dialogue(LastMarkedObject)
    SetGlobal("ChangeForm","LOCALS",0)
    ChangeCurrentScript("")
END

IF
  Global("RW_61THORAM0","LOCALS",0)
  !NearSavedLocation(20)
THEN
  RESPONSE #100
    SetGlobal("RW_61THORAM0","LOCALS",1)
    Continue()
END

IF
  !Global("RW_61THORAM0","LOCALS",0)
  NearSavedLocation(20)
THEN
  RESPONSE #100
    SetGlobal("RW_61THORAM0","LOCALS",0)
    NoAction()
END

IF
  !Global("RW_61THORAM0","LOCALS",0)
  !Allegiance(Myself,ENEMY)
  GlobalLT("61NumEfreetiKilled","GLOBAL",10)
THEN
  RESPONSE #100
    MoveToPoint([-2.-2])
END

IF
  !TimerActive(22)
  Global("RW_61THORAM0","LOCALS",0)
  !Allegiance(Myself,ENEMY)
  GlobalLT("61NumEfreetiKilled","GLOBAL",10)
THEN
  RESPONSE #100
    RandomWalk()
    StartTimer(22,5)
END

IF
  Global("ML_1","LOCALS",0)
  ActionListEmpty()
  NearLocation(Myself,1600,2140,4)
THEN
  RESPONSE #100
    SetStartPos([1600.2140])
    SetGlobal("ML_1","LOCALS",1)
    Continue()
END

IF
  Global("ML_1","LOCALS",0)
  !Allegiance(Myself,ENEMY)
  Global("ChangeForm","LOCALS",1)
  Global("CurrentForm","LOCALS",1)
THEN
  RESPONSE #100
    MoveToPoint([1600.2140])
END

IF
  Global("ML_1","LOCALS",1)
  !Allegiance(Myself,ENEMY)
  Global("ChangeForm","LOCALS",1)
  Global("CurrentForm","LOCALS",1)
THEN
  RESPONSE #100
    FaceObject(NearestPC)
    SetGlobal("ML_1","LOCALS",2)
END

IF
  Global("ML_1","LOCALS",2)
  !Allegiance(Myself,ENEMY)
  Global("ChangeForm","LOCALS",1)
  Global("CurrentForm","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("CHANGEFORM","LOCALS",-1)
    SetGlobal("ML_1","LOCALS",-1)
END

