IF
  Global("Freed_Elves","GLOBAL",2)
  IsScriptName("Tsol_Silverblade",Myself)
THEN
  RESPONSE #100
    StartCutSceneMode()
    FadeFromColor([0.0],0)
    Wait(1)
    HideCreature(Myself,TRUE)
    ActionOverride("ElvenFighter1",DestroySelf())
    ActionOverride("ElvenFighter2",DestroySelf())
    ActionOverride("ElvenFighter3",DestroySelf())
    FadeFromColor([0.0],0)
    Wait(1)
    EndCutSceneMode()
    DestroySelf()
END

