IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  Global("Dialog","LOCALS",0)
  GlobalLT("SH_3WayDialog","MYAREA",3)
  Or(7)
    See([PC],0)
    LOS(Player1,25)
    LOS(Player2,25)
    LOS(Player3,25)
    LOS(Player4,25)
    LOS(Player5,25)
    LOS(Player6,25)
THEN
  RESPONSE #100
    SetGlobal("Dialog","LOCALS",1)
    IncrementGlobal("SH_3WayDialog","MYAREA",1)
END

IF
  Global("SH_3WayDialog","MYAREA",3)
THEN
  RESPONSE #100
    SetDialogueRange(300)
    Dialogue([PC])
END

IF
  True()
THEN
  RESPONSE #100
    NoAction()
END

