IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Isair2")  // 
    SetGlobal("Final_Battle_Part2","MYAREA",1)
    SetNumTimesTalkedTo(1)
    Wait(3)
    FadeToColor([0.0],0)
    Wait(1)
    ActionOverride(Player1,JumpToPoint([2405.1062]))
    ActionOverride(Player2,JumpToPoint([2348.1081]))
    MultiPlayerSync()
    ActionOverride(Player3,JumpToPoint([2399.1110]))
    ActionOverride(Player4,JumpToPoint([2443.1158]))
    MultiPlayerSync()
    ActionOverride(Player5,JumpToPoint([2369.1166]))
    ActionOverride(Player6,JumpToPoint([2302.1170]))
    ActionOverride(Player1,FaceObject("Isair2"))
    ActionOverride(Player2,FaceObject("Isair2"))
    MultiPlayerSync()
    ActionOverride(Player3,FaceObject("Isair2"))
    ActionOverride(Player4,FaceObject("Isair2"))
    MultiPlayerSync()
    ActionOverride(Player5,FaceObject("Isair2"))
    ActionOverride(Player6,FaceObject("Isair2"))
    ActionOverride("Ormis_Dohor",DestroySelf())
    ActionOverride("Monk_Sand",DestroySelf())
    ActionOverride("Monk_Shadow",DestroySelf())
    ActionOverride("Monk_Crystalline",DestroySelf())
    Wait(1)
    MoveViewPoint([2405.1062],99)
    FadeFromColor([0.0],0)
    Wait(1)
    Wait(1)
    SetDialogueRange(300)
    Dialogue([PC])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    Wait(1)
    MoveToPoint([2395.994])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    Wait(1)
    MoveToPoint([2395.994])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    Wait(1)
    MoveToPoint([2395.994])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    Wait(1)
    MoveToPoint([2395.994])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    Wait(1)
    MoveToPoint([2395.994])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    Wait(1)
    MoveToPoint([2395.994])
END

