IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    MultiPlayerSync()
    FadeToColor([0.0],0)
    Wait(1)
    MoveViewPoint([1114.1108],999)
    JumpToPoint([1450.1530])
    Face(S)
    Wait(1)
    FadeFromColor([0.0],0)
    Wait(1)
    UnhideGUI()
    EndCutSceneMode()
    MultiPlayerSync()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    Wait(1)
    JumpToPoint([1114.1108])
    Face(S)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)  // 
    Wait(1)
    JumpToPoint([1114.1108])
    Face(S)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)  // 
    Wait(1)
    JumpToPoint([1114.1108])
    Face(S)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)  // 
    Wait(1)
    JumpToPoint([1114.1108])
    Face(S)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)  // 
    Wait(1)
    JumpToPoint([1114.1108])
    Face(S)
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)  // 
    Wait(1)
    JumpToPoint([1114.1108])
    Face(S)
END

