IF
  Global("SH_GlobeVulnerable","MYAREA",0)
  GlobalGT("SH_Perform_Illmater_Ritual","GLOBAL",3)
THEN
  RESPONSE #100
    SetGlobal("SH_GlobeVulnerable","MYAREA",1)
    SetCreatureAreaFlag(Myself,INVULNERABLE,FALSE)
END

IF
  Global("MakeVulnerable","LOCALS",1)
  !Global("TEAM_1","MYAREA",0)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  Global("TEAM_1","MYAREA",0)
  AttackedBy([GOODCUTOFF],0)
THEN
  RESPONSE #100
    SetGlobal("TEAM_1","MYAREA",1)
END

