IF
  Global("Pool_Tainted","GLOBAL",1)
  Global("TeleportIsairMadaeHP33","MYAREA",0)
  HPPercentGT(Myself,33)
THEN
  RESPONSE #100
    MatchHP("Isair2",CURRENT_HP)
    Continue()
END

IF
  Global("Obj0","LOCALS",0)
  See(NearestEnemyOf(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_SUMMON_MONSTER_III_ISAIR,SPELLCAST_IGNORE_HAS_CHECK)
THEN
  RESPONSE #100
    SetGlobal("Obj0","LOCALS",1)
    ForceSpell(LastMarkedObject,WIZARD_SUMMON_MONSTER_III_ISAIR)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(WIZARD_SOUL_EATER)
  See(Nearest(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_SOUL_EATER,0)
  Global("Obj1","LOCALS",0)
  StateCheck(LastMarkedObject,STATE_SUMMONED_CREATURE)
THEN
  RESPONSE #100
    SetGlobal("Obj1","LOCALS",1)
    Spell(LastMarkedObject,WIZARD_SOUL_EATER)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(WIZARD_SOUL_EATER)
  See(SecondNearest(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_SOUL_EATER,0)
  Global("Obj1","LOCALS",0)
  StateCheck(LastMarkedObject,STATE_SUMMONED_CREATURE)
THEN
  RESPONSE #100
    SetGlobal("Obj1","LOCALS",1)
    Spell(LastMarkedObject,WIZARD_SOUL_EATER)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(WIZARD_SOUL_EATER)
  See(ThirdNearest(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_SOUL_EATER,0)
  Global("Obj1","LOCALS",0)
  StateCheck(LastMarkedObject,STATE_SUMMONED_CREATURE)
THEN
  RESPONSE #100
    SetGlobal("Obj1","LOCALS",1)
    Spell(LastMarkedObject,WIZARD_SOUL_EATER)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(WIZARD_SOUL_EATER)
  See(FourthNearest(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_SOUL_EATER,0)
  Global("Obj1","LOCALS",0)
  StateCheck(LastMarkedObject,STATE_SUMMONED_CREATURE)
THEN
  RESPONSE #100
    SetGlobal("Obj1","LOCALS",1)
    Spell(LastMarkedObject,WIZARD_SOUL_EATER)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(WIZARD_SOUL_EATER)
  See(FifthNearest(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_SOUL_EATER,0)
  Global("Obj1","LOCALS",0)
  StateCheck(LastMarkedObject,STATE_SUMMONED_CREATURE)
THEN
  RESPONSE #100
    SetGlobal("Obj1","LOCALS",1)
    Spell(LastMarkedObject,WIZARD_SOUL_EATER)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HaveSpell(WIZARD_SOUL_EATER)
  See(SixthNearest(Myself),0)
  IsSpellTargetValid(LastMarkedObject,WIZARD_SOUL_EATER,0)
  Global("Obj1","LOCALS",0)
  StateCheck(LastMarkedObject,STATE_SUMMONED_CREATURE)
THEN
  RESPONSE #100
    SetGlobal("Obj1","LOCALS",1)
    Spell(LastMarkedObject,WIZARD_SOUL_EATER)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  HasItem("BBoDisa",Myself)  // ~Black Blade of Disaster~
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("2907",Myself,3)
      // WIZARD_BLACK_BLADE_OF_DISASTER
    MarkSpellAndObject("2910",LastMarkedObject,3)
      // WIZARD_EXECUTIONERS_EYES
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  HasItem("BBoDisa",Myself)  // ~Black Blade of Disaster~
  HaveSpell(WIZARD_ANTIMAGIC_SHELL)
  SetLastMarkedObject(Myself)
  IsSpellTargetValid(LastMarkedObject,WIZARD_ANTIMAGIC_SHELL,0)
THEN
  RESPONSE #100
    Spell(LastMarkedObject,WIZARD_ANTIMAGIC_SHELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  !See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MoveToObjectUntilSee(NearestPC)
END

IF
THEN
  RESPONSE #100
    MoveToObject(NearestPC)
END

