IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  Allegiance(Myself,ENEMY)
  SetLastMarkedObject(Myself)
THEN
  RESPONSE #100
    MarkSpellAndObject("210223052408",Myself,3)
      // WIZARD_ARMOR
      // WIZARD_HASTE
      // WIZARD_STONESKIN
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  Or(6)
    HasItem("SGrasp",Myself)  // ~Shocking Grasp~
    HasItem("SGrasp1",Myself)  // ~Shocking Grasp~
    HasItem("SGrasp2",Myself)  // ~Shocking Grasp~
    HasItem("SGrasp3",Myself)  // ~Shocking Grasp~
    HasItem("SGrasp4",Myself)  // ~Shocking Grasp~
    HasItem("SGrasp5",Myself)  // ~Shocking Grasp~
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("24262115",Myself,7)
      // WIZARD_FIRESHIELD_BLUE
      // WIZARD_SHOCKING_GRASP
    MarkSpellAndObject("2112210323122318242824222501",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_BURNING_HANDS
      // WIZARD_SLOW
      // WIZARD_ICELANCE
      // WIZARD_SPIDER_SPAWN
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_ANIMATE_DEAD
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_CLERIC],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_DRUID],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("2302",[ANYONE],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2112210323122318242824222501",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_BURNING_HANDS
      // WIZARD_SLOW
      // WIZARD_ICELANCE
      // WIZARD_SPIDER_SPAWN
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_ANIMATE_DEAD
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_CLERIC],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_DRUID],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("2302",[ANYONE],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("24262115",Myself,7)
      // WIZARD_FIRESHIELD_BLUE
      // WIZARD_SHOCKING_GRASP
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_CLERIC],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_DRUID],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("2302",[ANYONE],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("24262115",Myself,7)
      // WIZARD_FIRESHIELD_BLUE
      // WIZARD_SHOCKING_GRASP
    MarkSpellAndObject("2112210323122318242824222501",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_BURNING_HANDS
      // WIZARD_SLOW
      // WIZARD_ICELANCE
      // WIZARD_SPIDER_SPAWN
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_ANIMATE_DEAD
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_DRUID],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("2302",[ANYONE],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("24262115",Myself,7)
      // WIZARD_FIRESHIELD_BLUE
      // WIZARD_SHOCKING_GRASP
    MarkSpellAndObject("2112210323122318242824222501",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_BURNING_HANDS
      // WIZARD_SLOW
      // WIZARD_ICELANCE
      // WIZARD_SPIDER_SPAWN
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_ANIMATE_DEAD
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_CLERIC],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2302",[ANYONE],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("24262115",Myself,7)
      // WIZARD_FIRESHIELD_BLUE
      // WIZARD_SHOCKING_GRASP
    MarkSpellAndObject("2112210323122318242824222501",LastMarkedObject,7)
      // WIZARD_MAGIC_MISSILE
      // WIZARD_BURNING_HANDS
      // WIZARD_SLOW
      // WIZARD_ICELANCE
      // WIZARD_SPIDER_SPAWN
      // WIZARD_MORDENKAINENS_FORCE_MISSILES
      // WIZARD_ANIMATE_DEAD
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_CLERIC],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    MarkSpellAndObject("2302",[PC.0.0.0.0.0.0.0.0.CLASSMASK_DRUID],SPELLCAST_RANDOM)
      // WIZARD_DISPEL_MAGIC
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

