IF
  !TimerActive(17)
  HaveSpell(WIZARD_MALAVONS_RAGE)
  Range(ThirdNearestEnemyOf(Myself),15,LESS_THAN)
THEN
  RESPONSE #100
    StartTimer(17,21)
    Spell(ThirdNearestEnemyOf(Myself),WIZARD_MALAVONS_RAGE)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("2425260321182612261328032424",LastMarkedObject,7)
      // CLERIC_CONTAGION
      // WIZARD_CHAIN_LIGHTNING
      // WIZARD_CHROMATIC_ORB
      // WIZARD_OTILUKES_FREEZING_SPHERE
      // WIZARD_SHADES
      // WIZARD_SUMMON_MONSTER_VIII
      // WIZARD_VITRIOLIC_SPHERE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

