IF
  Global("SH_LeaveSeveredHand","GLOBAL",0)
  Global("StartCutscene_63cFB06","MYAREA",1)
  Clicked([PC])
  Or(2)
    Range(Player1,10,LESS_THAN)
    Dead(Player1)  // 
  Or(2)
    Range(Player2,10,LESS_THAN)
    Dead(Player2)  // 
  Or(2)
    Range(Player3,10,LESS_THAN)
    Dead(Player3)  // 
  Or(2)
    Range(Player4,10,LESS_THAN)
    Dead(Player4)  // 
  Or(2)
    Range(Player5,10,LESS_THAN)
    Dead(Player5)  // 
  Or(2)
    Range(Player6,10,LESS_THAN)
    Dead(Player6)  // 
THEN
  RESPONSE #100
    SetGlobal("EndCredits","MYAREA",1)
    SaveGame(41118)  // ~End Game~
    EndCredits()
END

IF
  Clicked([PC])
THEN
  RESPONSE #100
    ActionOverride(Player1,MoveToPoint([1245.1289]))
    ActionOverride(Player2,MoveToPoint([1245.1289]))
    ActionOverride(Player3,MoveToPoint([1245.1289]))
    ActionOverride(Player4,MoveToPoint([1245.1289]))
    ActionOverride(Player5,MoveToPoint([1245.1289]))
    ActionOverride(Player6,MoveToPoint([1245.1289]))
END

