IF
  !Global("63PITFIC_Mark","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",0)
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(NearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(SecondNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(ThirdNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(FourthNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(FifthNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(SixthNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(SeventhNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(EigthNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(NinthNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("63PITFIC_Mark","LOCALS",0)
  See(TenthNearestEnemyOf(Myself),0)
  !CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobal("63PITFIC_Mark","LOCALS",1)
    SetMyTarget(LastSeenBy(Myself))
    Continue()
END

IF
  Global("0","LOCALS",0)
  See([PC],0)
THEN
  RESPONSE #100
    FloatMessage(Myself,33185)  // ~"Ah.  Dinner is served at last... "~
    SetGlobal("0","LOCALS",1)
    Continue()
END

IF
  !Global("63PITFIC_Mark","LOCALS",0)
  GlobalLT("Action","LOCALS",2)
  Range(MyTarget,2,GREATER_THAN)
THEN
  RESPONSE #100
    SpellHitEffectSprite(Myself,Myself,DIMENSION_DOOR_ORIGIN,0)
    HideCreature(Myself,TRUE)
    FloatMessage(Myself,38707)  // ~.:Casts Teleport Without Error:.~
    JumpToObject(MyTarget)
    FaceObject(MyTarget)
    SpellHitEffectSprite(Myself,Myself,DIMENSION_DOOR_DESTINATION,0)
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  !Global("63PITFIC_Mark","LOCALS",0)
  GlobalLT("Action","LOCALS",2)
  See(MyTarget,0)
THEN
  RESPONSE #100
    IncrementGlobal("Action","LOCALS",1)
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  !Global("63PITFIC_Mark","LOCALS",0)
  Global("Action","LOCALS",2)
  See(MyTarget,0)
THEN
  RESPONSE #100
    MarkSpellAndObject("2504240423182501",LastMarkedObject,7)
      // WIZARD_CONE_OF_COLD
      // WIZARD_ICE_STORM
      // WIZARD_ICELANCE
      // WIZARD_ANIMATE_DEAD
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    SetGlobal("Action","LOCALS",0)
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  !Global("63PITFIC_Mark","LOCALS",0)
  See(MyTarget,0)
THEN
  RESPONSE #100
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

