IF
  Global("Saablic_Dead","GLOBAL",1)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  CreatureHidden(Myself)
  Global("Saablic_Dead","GLOBAL",0)
  Global("SH_Teleported_To_6303","GLOBAL",1)
THEN
  RESPONSE #100
    HideCreature(Myself,FALSE)
    Continue()
END

IF
  !CreatureHidden(Myself)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  CreatureHidden(Myself)
THEN
  RESPONSE #100
    NoAction()
END

