IF
  Global("Started_Cutscene_GMeet","MYAREA",1)
THEN
  RESPONSE #100
    ChangeCurrentScript("")
END

IF
  Global("Started_Cutscene_GMeet","MYAREA",0)
  IsScriptName("Zigma",Myself)
  LOS([PC],28)
THEN
  RESPONSE #100
    SetGlobal("Started_Cutscene_GMeet","MYAREA",1)
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    StartCutScene("63cGMeet")
    ChangeCurrentScript("")
END

IF
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ChangeEnemyAlly(Myself,NEUTRAL)
END

