IF
  !Global("63Thayvian_Ruse","GLOBAL",2)
  Dead("Demonic_Construct1")  // 
  Dead("Demonic_Construct2")  // 
  Dead("Demonic_Construct3")  // 
THEN
  RESPONSE #100
    SetGlobal("63Thayvian_Ruse","GLOBAL",2)
END

IF
  NumberOfTimesTalkedTo(0)
  !Allegiance(Myself,ENEMY)
  !Dead(Myself)  // 
  Global("63Thayvian_Ruse","GLOBAL",0)
  See([PC],0)
THEN
  RESPONSE #100
    SetGlobal("63Thayvian_Ruse","GLOBAL",1)
    SetDialogueRange(300)
    Dialogue(LastMarkedObject)
END

