IF
  True()
THEN
  RESPONSE #100
    SetGlobal("FloatMessage","LOCALS",0)
    SetGlobal("Player1OnPad","LOCALS",0)
    SetGlobal("Player2OnPad","LOCALS",0)
    SetGlobal("Player3OnPad","LOCALS",0)
    SetGlobal("Player4OnPad","LOCALS",0)
    SetGlobal("Player5OnPad","LOCALS",0)
    SetGlobal("Player6OnPad","LOCALS",0)
    SetGlobal("Player1HasAmulet","LOCALS",0)
    SetGlobal("Player2HasAmulet","LOCALS",0)
    SetGlobal("Player3HasAmulet","LOCALS",0)
    SetGlobal("Player4HasAmulet","LOCALS",0)
    SetGlobal("Player5HasAmulet","LOCALS",0)
    SetGlobal("Player6HasAmulet","LOCALS",0)
    SetGlobal("Player1Exists","LOCALS",0)
    SetGlobal("Player2Exists","LOCALS",0)
    SetGlobal("Player3Exists","LOCALS",0)
    SetGlobal("Player4Exists","LOCALS",0)
    SetGlobal("Player5Exists","LOCALS",0)
    SetGlobal("Player6Exists","LOCALS",0)
    SetGlobal("Player1ReadyForTransport","LOCALS",0)
    SetGlobal("Player2ReadyForTransport","LOCALS",0)
    SetGlobal("Player3ReadyForTransport","LOCALS",0)
    SetGlobal("Player4ReadyForTransport","LOCALS",0)
    SetGlobal("Player5ReadyForTransport","LOCALS",0)
    SetGlobal("Player6ReadyForTransport","LOCALS",0)
    Continue()
END

IF
  Exists(Player1)
  HPPercentGT(Player1,0)
THEN
  RESPONSE #100
    SetGlobal("Player1Exists","LOCALS",1)
    Continue()
END

IF
  !Global("Player1Exists","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player1ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  Exists(Player2)
  HPPercentGT(Player2,0)
THEN
  RESPONSE #100
    SetGlobal("Player2Exists","LOCALS",1)
    Continue()
END

IF
  !Global("Player2Exists","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player2ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  Exists(Player3)
  HPPercentGT(Player3,0)
THEN
  RESPONSE #100
    SetGlobal("Player3Exists","LOCALS",1)
    Continue()
END

IF
  !Global("Player3Exists","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player3ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  Exists(Player4)
  HPPercentGT(Player4,0)
THEN
  RESPONSE #100
    SetGlobal("Player4Exists","LOCALS",1)
    Continue()
END

IF
  !Global("Player4Exists","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player4ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  Exists(Player5)
  HPPercentGT(Player5,0)
THEN
  RESPONSE #100
    SetGlobal("Player5Exists","LOCALS",1)
    Continue()
END

IF
  !Global("Player5Exists","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player5ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  Exists(Player6)
  HPPercentGT(Player6,0)
THEN
  RESPONSE #100
    SetGlobal("Player6Exists","LOCALS",1)
    Continue()
END

IF
  !Global("Player6Exists","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player6ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  Global("Player1Exists","LOCALS",1)
  Range(Player1,6,LESS_THAN)
THEN
  RESPONSE #100
    SetGlobal("Player1OnPad","LOCALS",1)
    Continue()
END

IF
  Global("Player1Exists","LOCALS",1)
  !Global("Player1OnPad","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player2Exists","LOCALS",1)
  Range(Player2,6,LESS_THAN)
THEN
  RESPONSE #100
    SetGlobal("Player2OnPad","LOCALS",1)
    Continue()
END

IF
  Global("Player2Exists","LOCALS",1)
  !Global("Player2OnPad","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player3Exists","LOCALS",1)
  Range(Player3,6,LESS_THAN)
THEN
  RESPONSE #100
    SetGlobal("Player3OnPad","LOCALS",1)
    Continue()
END

IF
  Global("Player3Exists","LOCALS",1)
  !Global("Player3OnPad","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player4Exists","LOCALS",1)
  Range(Player4,6,LESS_THAN)
THEN
  RESPONSE #100
    SetGlobal("Player4OnPad","LOCALS",1)
    Continue()
END

IF
  Global("Player4Exists","LOCALS",1)
  !Global("Player4OnPad","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player5Exists","LOCALS",1)
  Range(Player5,6,LESS_THAN)
THEN
  RESPONSE #100
    SetGlobal("Player5OnPad","LOCALS",1)
    Continue()
END

IF
  Global("Player5Exists","LOCALS",1)
  !Global("Player5OnPad","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player6Exists","LOCALS",1)
  Range(Player6,6,LESS_THAN)
THEN
  RESPONSE #100
    SetGlobal("Player6OnPad","LOCALS",1)
    Continue()
END

IF
  Global("Player6Exists","LOCALS",1)
  !Global("Player6OnPad","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  HasItem("63AMULIX",Player1)  // ~Iyachtu Xvim Holy Symbol~
THEN
  RESPONSE #100
    SetGlobal("Player1HasAmulet","LOCALS",1)
    Continue()
END

IF
  !Global("Player1HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  HasItem("63AMULIX",Player2)  // ~Iyachtu Xvim Holy Symbol~
THEN
  RESPONSE #100
    SetGlobal("Player2HasAmulet","LOCALS",1)
    Continue()
END

IF
  !Global("Player2HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  HasItem("63AMULIX",Player3)  // ~Iyachtu Xvim Holy Symbol~
THEN
  RESPONSE #100
    SetGlobal("Player3HasAmulet","LOCALS",1)
    Continue()
END

IF
  !Global("Player3HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  HasItem("63AMULIX",Player4)  // ~Iyachtu Xvim Holy Symbol~
THEN
  RESPONSE #100
    SetGlobal("Player4HasAmulet","LOCALS",1)
    Continue()
END

IF
  !Global("Player4HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  HasItem("63AMULIX",Player5)  // ~Iyachtu Xvim Holy Symbol~
THEN
  RESPONSE #100
    SetGlobal("Player5HasAmulet","LOCALS",1)
    Continue()
END

IF
  !Global("Player5HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  HasItem("63AMULIX",Player6)  // ~Iyachtu Xvim Holy Symbol~
THEN
  RESPONSE #100
    SetGlobal("Player6HasAmulet","LOCALS",1)
    Continue()
END

IF
  !Global("Player6HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player1Exists","LOCALS",1)
  Global("Player1HasAmulet","LOCALS",1)
  Global("Player1OnPad","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player1ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  !Global("Player1ReadyForTransport","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player2Exists","LOCALS",1)
  Global("Player2HasAmulet","LOCALS",1)
  Global("Player2OnPad","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player2ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  !Global("Player2ReadyForTransport","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player3Exists","LOCALS",1)
  Global("Player3HasAmulet","LOCALS",1)
  Global("Player3OnPad","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player3ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  !Global("Player3ReadyForTransport","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player4Exists","LOCALS",1)
  Global("Player4HasAmulet","LOCALS",1)
  Global("Player4OnPad","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player4ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  !Global("Player4ReadyForTransport","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player5Exists","LOCALS",1)
  Global("Player5HasAmulet","LOCALS",1)
  Global("Player5OnPad","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player5ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  !Global("Player5ReadyForTransport","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("Player6Exists","LOCALS",1)
  Global("Player6HasAmulet","LOCALS",1)
  Global("Player6OnPad","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Player6ReadyForTransport","LOCALS",1)
    Continue()
END

IF
  !Global("Player6ReadyForTransport","LOCALS",1)
THEN
  RESPONSE #100
    Continue()
END

IF
  Global("SaveGame","MYAREA",0)
  !TimerActive(93)
  Global("Player1ReadyForTransport","LOCALS",1)
  Global("Player2ReadyForTransport","LOCALS",1)
  Global("Player3ReadyForTransport","LOCALS",1)
  Global("Player4ReadyForTransport","LOCALS",1)
  Global("Player5ReadyForTransport","LOCALS",1)
  Global("Player6ReadyForTransport","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("SaveGame","MYAREA",1)
    SaveGame(39403)  // ~Tyrannar Brutai Mar's Chambers~
    Continue()
END

IF
  Global("SaveGame","MYAREA",1)
THEN
  RESPONSE #100
    SetGlobal("SaveGame","MYAREA",0)
    SetGlobal("65Party_Teleported","GLOBAL",1)
    StartTimer(93,7)
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    StartCutScene("65cTele")
    Continue()
END

IF
  Global("Player1Exists","LOCALS",1)
  Global("Player1OnPad","LOCALS",1)
  !Global("Player1HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    StartTimer(99,7)
    SetGlobal("FloatMessage","LOCALS",1)
    ReallyForceSpell(Player1,TRAP_CALL_LIGHTNING)
    Continue()
END

IF
  Global("Player2Exists","LOCALS",1)
  Global("Player2OnPad","LOCALS",1)
  !Global("Player2HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    StartTimer(98,7)
    SetGlobal("FloatMessage","LOCALS",1)
    ReallyForceSpell(Player2,TRAP_CALL_LIGHTNING)
    Continue()
END

IF
  Global("Player3Exists","LOCALS",1)
  Global("Player3OnPad","LOCALS",1)
  !Global("Player3HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    StartTimer(97,7)
    SetGlobal("FloatMessage","LOCALS",1)
    ReallyForceSpell(Player3,TRAP_CALL_LIGHTNING)
    Continue()
END

IF
  Global("Player4Exists","LOCALS",1)
  Global("Player4OnPad","LOCALS",1)
  !Global("Player4HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    StartTimer(96,7)
    SetGlobal("FloatMessage","LOCALS",1)
    ReallyForceSpell(Player4,TRAP_CALL_LIGHTNING)
    Continue()
END

IF
  Global("Player5Exists","LOCALS",1)
  Global("Player5OnPad","LOCALS",1)
  !Global("Player5HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    StartTimer(95,7)
    SetGlobal("FloatMessage","LOCALS",1)
    ReallyForceSpell(Player5,TRAP_CALL_LIGHTNING)
    Continue()
END

IF
  Global("Player6Exists","LOCALS",1)
  Global("Player6OnPad","LOCALS",1)
  !Global("Player6HasAmulet","LOCALS",1)
THEN
  RESPONSE #100
    StartTimer(94,7)
    SetGlobal("FloatMessage","LOCALS",1)
    ReallyForceSpell(Player6,TRAP_CALL_LIGHTNING)
    Continue()
END

IF
  Global("FloatMessage","LOCALS",1)
THEN
  RESPONSE #100
    FloatMessage(Myself,34573)  // ~Every party member needs an Iyachtu Xvim Holy Symbol to teleport.~
    Continue()
END

