IF
  True()
THEN
  RESPONSE #100
    CutSceneId("TyrannarBrutaiMar")  // 
    Explore()
    HideGUI()
    SetVisualRange(99)
    MultiPlayerSync()
    MoveViewObject(Myself,999)
    FloatMessage(Myself,27191)  // ~"Intruders!  Kill them at once!"~
    Wait(1)
    MoveViewPoint([616.757],VERY_VERY_FAST)
    MoveToPoint([616.757])
    SpellHitEffectSprite(Myself,Myself,CALL_LIGHTNING,0)
    HideCreature(Myself,TRUE)
    Wait(1)
    SetGlobal("TEAM_2","MYAREA",1)
    SetVisualRange(0)
    EndCutSceneMode()
    UnhideGUI()
    MultiPlayerSync()
    DestroySelf()
END

