IF
  !TimerActive(14)
  Heard([ENEMY],0)
  Range(LastHeardBy(Myself),10,LESS_THAN)
THEN
  RESPONSE #100
    StartTimer(14,21)
    ForceSpell(LastHeardBy(Myself),CLERIC_INVISIBILITY_PURGE)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
END

IF
  !TimerActive(13)
  Or(2)
    StateCheck(LastAttackerOf(Myself),STATE_INVISIBLE)
    IsCreatureHiddenInShadows(LastAttackerOf(Myself))
  StateCheck(LastAttackerOf(Myself),STATE_NONDETECTION)
THEN
  RESPONSE #100
    StartTimer(13,7)
    ForceSpell(LastAttackerOf(Myself),CLERIC_INVISIBILITY_PURGE)
    Wait(0)
END

IF
  !TimerActive(21)
  HPPercentGT(Myself,10)
THEN
  RESPONSE #80
    FloatMessage(Myself,33959)  // ~"I'll eat your soul!"~
    StartRandomTimer(21,5,10)
    Continue()
  RESPONSE #80
    FloatMessage(Myself,33960)  // ~"Embrace my darkness so you may relish in my minions nipping at your tender flesh!"~
    StartRandomTimer(21,5,10)
    Continue()
  RESPONSE #80
    FloatMessage(Myself,33961)  // ~"Each cut I dig into you feeds my skin!"~
    StartRandomTimer(21,5,10)
    Continue()
  RESPONSE #60
    StartRandomTimer(21,5,10)
    Continue()
END

IF
  !TimerActive(21)
  HPPercentLT(Myself,11)
THEN
  RESPONSE #90
    FloatMessage(Myself,33962)  // ~"No!  I'm of Bane's blood!  You cannot defeat me!"~
    StartRandomTimer(21,5,10)
    SetGlobal("Desperate","LOCALS",1)
    Continue()
  RESPONSE #90
    FloatMessage(Myself,33963)  // ~"I AM IYACHTU XVIM!  I AM IMMORTAL!  NOOOOO!"~
    StartRandomTimer(21,5,10)
    SetGlobal("Desperate","LOCALS",1)
    Continue()
  RESPONSE #20
    StartRandomTimer(21,5,10)
    Continue()
END

IF
  Global("Desperate","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Desperate","LOCALS",2)
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_EVIL)
    Wait(1)
    ForceSpell(NearestEnemyOf(Myself),WIZARD_GATE)
    Wait(1)
END

IF
  GlobalLT("Action","LOCALS",3)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    IncrementGlobal("Action","LOCALS",1)
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

IF
  ForceMarkedSpell(MARKED_SPELL)
  SetSpellTarget(Nothing)
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    MarkSpellAndObject("2519",Myself,7)
      // WIZARD_SUNFIRE
    MarkSpellAndObject("2603280628022908",LastMarkedObject,7)
      // WIZARD_CHAIN_LIGHTNING
      // WIZARD_GREAT_SHOUT
      // WIZARD_FIERY_CLOUD
      // WIZARD_METEOR_SWARM
    Continue()
  RESPONSE #100
    MarkSpellAndObject("2603280628022908",LastMarkedObject,7)
      // WIZARD_CHAIN_LIGHTNING
      // WIZARD_GREAT_SHOUT
      // WIZARD_FIERY_CLOUD
      // WIZARD_METEOR_SWARM
    MarkSpellAndObject("2519",Myself,7)
      // WIZARD_SUNFIRE
    Continue()
END

IF
  !IsMarkedSpell(MARKED_SPELL)
THEN
  RESPONSE #100
    SetGlobal("Action","LOCALS",0)
    Spell(SpellTarget,MARKED_SPELL)
    WaitAnimation(Myself,WALK)
    WaitAnimation(Myself,CONJURE)
    WaitAnimation(Myself,CAST)
    ForceMarkedSpell(MARKED_SPELL)
END

IF
  See(NearestEnemyOf(Myself),0)
THEN
  RESPONSE #100
    SetGlobal("Action","LOCALS",0)
    EquipWeapon()
    AttackOneRound(LastMarkedObject)
END

