IF
  Global("Removed_Key_Item","MYAREA",0)
  OpenState("AR2101_Door1_Bridge",TRUE)  // AR2101_Door1_Bridge
THEN
  RESPONSE #100
    SetGlobal("Removed_Key_Item","MYAREA",1)
    TakePartyItem("21GenWP")
    Kill("Support_Beam_R")
    Kill("Support_Beam_M")
    Continue()
END

IF
  Global("Opened_Middle_Support","MYAREA",0)
  Dead("Support_Beam_M")  // 
THEN
  RESPONSE #100
    SetGlobal("Opened_Middle_Support","MYAREA",1)
    OpenDoor("AR2101_Door3_Support2")
    PlaySoundPoint("AM2101e",[1228.373])
    Continue()
END

IF
  Global("Opened_Right_Support","MYAREA",0)
  Dead("Support_Beam_R")  // 
THEN
  RESPONSE #100
    SetGlobal("Opened_Right_Support","MYAREA",1)
    OpenDoor("AR2101_Door4_Support3")
    PlaySoundPoint("AM2101d",[2458.567])
    Continue()
END

IF
  Global("Played_Dam_Broke_Scene","MYAREA",0)
  Dead("Support_Beam_R")  // 
  Dead("Support_Beam_M")  // 
  OpenState("AR2101_Door4_Support3",TRUE)  // AR2101_Door4_Support3
  OpenState("AR2101_Door3_Support2",TRUE)  // AR2101_Door3_Support2
  OpenState("AR2101_Door2_Support1",TRUE)  // AR2101_Door2_Support1
THEN
  RESPONSE #100
    SetGlobal("Played_Dam_Broke_Scene","MYAREA",1)
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    StartCutScene("21cDam0")
END

IF
  Global("Shaengarne_Award_XPVar","GLOBAL",0)
  Global("AR2102_Visited","GLOBAL",1)
  Global("Destroy_Shaengarne_Bridge","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Destroy_Shaengarne_Bridge","GLOBAL",1)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

IF
  !CreatureHidden("Cutscene")  // Cutscene
THEN
  RESPONSE #100
    HideCreature("Cutscene",TRUE)
    Continue()
END

