IF
  !Global("BRASTON_DELETE_AR3101","GLOBAL",0)
  !Dead("Braston")  // 
THEN
  RESPONSE #100
    ActionOverride("Braston",DestroySelf())
    SetGlobal("BRASTON_DELETE_AR3101","GLOBAL",0)
    Continue()
END

IF
  !Global("TEAM_5","MYAREA",0)
  Or(3)
    Global("TEAM_2","MYAREA",0)
    Global("TEAM_3","MYAREA",0)
    Global("TEAM_6","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("TEAM_2","MYAREA",1)
    SetGlobal("TEAM_3","MYAREA",1)
    SetGlobal("TEAM_6","MYAREA",1)
    Continue()
END

IF
  GlobalLT("SP_BATTLE_MUSIC","MYAREA",2)
  Dead("05_BugGut")  // 
  !AnyPCSeesEnemy()
THEN
  RESPONSE #100
    SetMusic(COMBAT_NORMAL,none)
    SetGlobal("SP_BATTLE_MUSIC","MYAREA",2)
    Continue()
END

IF
  Global("SP_BATTLE_MUSIC","MYAREA",0)
  !CreatureHidden("05_BugGut")  // 05_BugGut
  Allegiance("05_BugGut",ENEMY)  // 05_BugGut
THEN
  RESPONSE #100
    SetMusic(COMBAT_NORMAL,BA3101)
    SetGlobal("SP_BATTLE_MUSIC","MYAREA",1)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

