IF
  !Global("FW_WILL_O_WISPS_DEAD","GLOBAL",0)
  Or(9)
    !Dead("01_50RDEAR_01")  // 
    !Dead("01_50RDEAR_02")  // 
    !Dead("01_50RDEAR_03")  // 
    !Dead("01_50RDEAR_04")  // 
    !Dead("01_50RDEAR_05")  // 
    !Dead("01_50RDEBA_06")  // 
    !Dead("01_50RDEBA_07")  // 
    !Dead("01_50RDEHU_08")  // 
    !Dead("01_50RDEHU_09")  // 
THEN
  RESPONSE #100
    ActionOverride("01_50RDEAR_01",DestroySelf())
    ActionOverride("01_50RDEAR_02",DestroySelf())
    ActionOverride("01_50RDEAR_03",DestroySelf())
    ActionOverride("01_50RDEAR_04",DestroySelf())
    ActionOverride("01_50RDEAR_05",DestroySelf())
    ActionOverride("01_50RDEBA_06",DestroySelf())
    ActionOverride("01_50RDEBA_07",DestroySelf())
    ActionOverride("01_50RDEHU_08",DestroySelf())
    ActionOverride("01_50RDEHU_09",DestroySelf())
    Continue()
END

IF
  !Global("FW_WILL_O_WISPS_DEAD","GLOBAL",0)
  !Dead("TRAP_WISP")  // 
THEN
  RESPONSE #100
    ActionOverride("TRAP_WISP",DestroySelf())
    Continue()
END

IF
  Global("AR5026_STATE","GLOBAL",2)
  Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("ACTIVE_DARK_TREE","MYAREA",0)
    SetGlobal("AR5026_STATE","GLOBAL",3)
    HideCreature("TRAP_WISP",FALSE)
    ActionOverride("TRAP_WISP",JumpToPoint([300.400]))
    Continue()
  RESPONSE #100
    SetGlobal("ACTIVE_DARK_TREE","MYAREA",1)
    SetGlobal("AR5026_STATE","GLOBAL",3)
    HideCreature("TRAP_WISP",FALSE)
    ActionOverride("TRAP_WISP",JumpToPoint([600.350]))
    Continue()
  RESPONSE #100
    SetGlobal("ACTIVE_DARK_TREE","MYAREA",2)
    SetGlobal("AR5026_STATE","GLOBAL",3)
    HideCreature("TRAP_WISP",FALSE)
    ActionOverride("TRAP_WISP",JumpToPoint([800.850]))
    Continue()
END

IF
  !Global("ACTIVE_DARK_TREE","MYAREA",-1)
  !Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("ACTIVE_DARK_TREE","MYAREA",-1)
    Continue()
END

IF
  IsExtendedNight()
  !Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetExtendedNight(FALSE)
    Continue()
END

IF
  OnCreation()
  !Global("AR5027_STATE","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("AR5027_STATE","GLOBAL",0)
    SetGlobal("AR5027_ARCHER_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5027_BARBARIAN_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5027_BARBARIAN_1_SPAWN","GLOBAL",0)
    SetGlobal("AR5027_HUNTER_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5027_HUNTER_1_SPAWN","GLOBAL",0)
    SetGlobal("AR5027_HUNTER_2_SPAWN","GLOBAL",0)
    Continue()
END

IF
  OnCreation()
  Global("AR5027_STATE","GLOBAL",0)
  Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #33
    SetGlobal("AR5027_STATE","GLOBAL",2)
    Continue()
  RESPONSE #66
    Continue()
END

IF
  Global("AR5027_STATE","GLOBAL",2)
  !Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("AR5027_STATE","GLOBAL",0)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

