IF
  !Global("AR5100_VISITED","GLOBAL",0)
  !Dead("50DRAWY_01")  // 
THEN
  RESPONSE #100
    ActionOverride("50DRAWY_01",DestroySelf())
    Continue()
END

IF
  Global("5005_DRAGON_DEAD","GLOBAL",0)
  Global("AR5100_VISITED","GLOBAL",0)
  Dead("50DRAWY_01")  // 
THEN
  RESPONSE #100
    SetGlobal("5005_DRAGON_DEAD","GLOBAL",1)
    Continue()
END

IF
  Global("5005_INGRATH_VISIBLE","GLOBAL",0)
  Global("5005_INGRATH_NO_SHOW","GLOBAL",0)
  Global("50DRAGON","GLOBAL",1)
THEN
  RESPONSE #100
    HideCreature("01_41INGRAT_01",FALSE)
    HideCreature("01_50NWSOLD_02",FALSE)
    HideCreature("01_50NWSOLD_03",FALSE)
    HideCreature("01_50NWSOLD_04",FALSE)
    HideCreature("01_50NWSOLD_05",FALSE)
    HideCreature("01_50NWSOLD_06",FALSE)
    HideCreature("01_50NWSOLD_07",FALSE)
    SetGlobal("5005_INGRATH_VISIBLE","GLOBAL",1)
    Continue()
END

IF
  Global("5005_INGRATH_VISIBLE","GLOBAL",2)
THEN
  RESPONSE #100
    HideCreature("01_41INGRAT_01",TRUE)
    HideCreature("01_50NWSOLD_02",TRUE)
    HideCreature("01_50NWSOLD_03",TRUE)
    HideCreature("01_50NWSOLD_04",TRUE)
    HideCreature("01_50NWSOLD_05",TRUE)
    HideCreature("01_50NWSOLD_06",TRUE)
    HideCreature("01_50NWSOLD_07",TRUE)
    SetGlobal("5005_INGRATH_VISIBLE","GLOBAL",3)
    ActionOverride("01_41INGRAT_01",DestroySelf())
    ActionOverride("01_50NWSOLD_02",DestroySelf())
    ActionOverride("01_50NWSOLD_03",DestroySelf())
    ActionOverride("01_50NWSOLD_04",DestroySelf())
    ActionOverride("01_50NWSOLD_05",DestroySelf())
    ActionOverride("01_50NWSOLD_06",DestroySelf())
    ActionOverride("01_50NWSOLD_07",DestroySelf())
    Continue()
END

IF
  Global("50Ingrath_Attack","GLOBAL",0)
  !Global("TEAM_1","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("50Ingrath_Attack","GLOBAL",1)
    Continue()
END

IF
  !Global("5005_INGRATH_VISIBLE","GLOBAL",0)
  GlobalLT("50Dragon","GLOBAL",4)
  Global("TEAM_1","MYAREA",0)
  Global("50Ingrath_Attack","GLOBAL",0)
  !Global("5005_DRAGON_DEAD","GLOBAL",0)
  Dead("02_50WyrWh_01")  // 
  Dead("02_50WyrWh_02")  // 
  Dead("02_50WyrWh_03")  // 
  Dead("02_50WyrWh_04")  // 
THEN
  RESPONSE #100
    SetGlobal("50Dragon","GLOBAL",4)
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    StartCutScene("50cDrag2")
END

IF
  IsActive("dragonsingles")  // dragonsingles
  !Global("5100_DRAGONS_DEAD","GLOBAL",0)
THEN
  RESPONSE #100
    Deactivate([ANYONE])
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

