IF
  !Global("FW_WILL_O_WISPS_DEAD","GLOBAL",0)
  !Dead("TRAP_WISP")  // 
THEN
  RESPONSE #100
    ActionOverride("TRAP_WISP",DestroySelf())
    Continue()
END

IF
  Global("AR5023_STATE","GLOBAL",2)
  Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("ACTIVE_DARK_TREE","MYAREA",0)
    SetGlobal("AR5023_STATE","GLOBAL",3)
    HideCreature("TRAP_WISP",FALSE)
    ActionOverride("TRAP_WISP",JumpToPoint([400.350]))
    Continue()
  RESPONSE #100
    SetGlobal("ACTIVE_DARK_TREE","MYAREA",1)
    SetGlobal("AR5023_STATE","GLOBAL",3)
    HideCreature("TRAP_WISP",FALSE)
    ActionOverride("TRAP_WISP",JumpToPoint([350.600]))
    Continue()
END

IF
  !Global("ACTIVE_DARK_TREE","MYAREA",-1)
  !Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("ACTIVE_DARK_TREE","MYAREA",-1)
    Continue()
END

IF
  IsExtendedNight()
  !Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetExtendedNight(FALSE)
    Continue()
END

IF
  OnCreation()
  !Global("AR5021_STATE","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("AR5021_STATE","GLOBAL",0)
    SetGlobal("AR5021_ARCHER_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5021_BARBARIAN_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5021_BARBARIAN_1_SPAWN","GLOBAL",0)
    SetGlobal("AR5021_HUNTER_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5021_HUNTER_1_SPAWN","GLOBAL",0)
    SetGlobal("AR5021_HUNTER_2_SPAWN","GLOBAL",0)
    Continue()
END

IF
  OnCreation()
  Global("AR5021_STATE","GLOBAL",0)
  Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #33
    SetGlobal("AR5021_STATE","GLOBAL",2)
    Continue()
  RESPONSE #66
    Continue()
END

IF
  Global("AR5021_STATE","GLOBAL",2)
  !Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("AR5021_STATE","GLOBAL",0)
    Continue()
END

IF
  OnCreation()
  !Global("AR5030_STATE","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("AR5030_STATE","GLOBAL",0)
    SetGlobal("AR5030_ARCHER_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5030_BARBARIAN_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5030_BARBARIAN_1_SPAWN","GLOBAL",0)
    SetGlobal("AR5030_HUNTER_0_SPAWN","GLOBAL",0)
    SetGlobal("AR5030_HUNTER_1_SPAWN","GLOBAL",0)
    SetGlobal("AR5030_HUNTER_2_SPAWN","GLOBAL",0)
    Continue()
END

IF
  OnCreation()
  Global("AR5030_STATE","GLOBAL",0)
  Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #33
    SetGlobal("AR5030_STATE","GLOBAL",2)
    Continue()
  RESPONSE #66
    Continue()
END

IF
  Global("AR5030_STATE","GLOBAL",2)
  !Global("AR5003_DARK_TREE_CLEAR","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("AR5030_STATE","GLOBAL",0)
    Continue()
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

