IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

IF
  Global("6101Visited","MYAREA",0)
THEN
  RESPONSE #100
    HideCreature("05_TrollPrisoner",TRUE)
    SetGlobal("6101Visited","MYAREA",1)
    Continue()
END

IF
  OnCreation()
  OpenState("AR6101_Switch",FALSE)  // AR6101_Switch
THEN
  RESPONSE #100
    PlaySequence("PendulumFront",AWAKE)
    PlaySequence("PendulumBack",AWAKE)
    PlaySequence("PendulumShadow",AWAKE)
END

IF
  GlobalGT("61VolcanoStatus","GLOBAL",0)
THEN
  RESPONSE #100
    ScreenShake(15,4,3)
    Continue()
END

IF
  GlobalGT("61VolcanoStatus","GLOBAL",0)
  GlobalTimerExpired("LocalEruptionTimer","MYAREA")
  See([ANYONE][0.0.10000.10000],0)
  !InParty(LastMarkedObject)
  CheckStatLT(LastMarkedObject,100,RESISTFIRE)
THEN
  RESPONSE #100
    ApplySpell(LastMarkedObject,2099)
    Continue()
END

IF
  GlobalGT("61VolcanoStatus","GLOBAL",0)
  GlobalTimerExpired("LocalEruptionTimer","MYAREA")
THEN
  RESPONSE #100
    ScreenShake(75,40,30)
    ApplySpell(Player1,2099)
    ApplySpell(Player2,2099)
    ApplySpell(Player3,2099)
    ApplySpell(Player4,2099)
    ApplySpell(Player5,2099)
    ApplySpell(Player6,2099)
    Continue()
END

IF
  GlobalGT("61VolcanoStatus","GLOBAL",0)
  GlobalTimerExpired("EruptionTimer","GLOBAL")
THEN
  RESPONSE #100
    SetGlobal("61VolcanoStatus","GLOBAL",-1)
    Continue()
END

IF
  GlobalGT("61VolcanoStatus","GLOBAL",0)
  !AreaRestDisabled()
THEN
  RESPONSE #100
    Debug("DisableResting")
    AllowAreaResting(FALSE)
    Continue()
END

IF
  Global("61VolcanoStatus","GLOBAL",-1)
  AreaRestDisabled()
THEN
  RESPONSE #100
    Debug("EnableResting")
    AllowAreaResting(TRUE)
    Continue()
END

IF
  GlobalGT("61VolcanoStatus","GLOBAL",0)
  GlobalTimerExpired("LocalEruptionTimer","MYAREA")
THEN
  RESPONSE #100
    SetGlobalTimer("LocalEruptionTimer","MYAREA",7)
    Continue()
END

