IF
  Global("TeleportIsairMadaeHP33","MYAREA",0)
  Or(2)
    HPPercentLT("Isair",50)  // Isair
    HPPercentLT("Madae",50)  // Madae
THEN
  RESPONSE #100
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    SetGlobal("TeleportIsairMadaeHP33","MYAREA",1)
    SetGlobal("Ready_To_Retreat","GLOBAL",1)
    SetGlobal("SH_SpawnGlaberazu_63GlabSL","MYAREA",2)
    SetGlobal("SH_SpawnGlaberazu_63GlabSR","MYAREA",2)
    ActionOverride("Madae",FaceObject("Isair"))
    ActionOverride("Isair",Dialogue([PC]))
    SetHP("63GlabSL",10)
    SetHP("63GlabSR",10)
    SetGlobal("SH_SpawnGlaberazu_63GlabSL","MYAREA",-1)
    SetGlobal("SH_SpawnGlaberazu_63GlabSR","MYAREA",-1)
    SetGlobal("SH_SpawnGlaberazu_Glaberazu_1","MYAREA",-1)
    SetGlobal("SH_SpawnGlaberazu_Glaberazu_2","MYAREA",-1)
    ActionOverride("63GlabSL",NoAction())
    ActionOverride("63GlabSR",NoAction())
END

IF
  Global("WarpSequenceHP33","MYAREA",0)
  Global("Final_Battle_Part2","MYAREA",1)
  Or(2)
    HPPercentLT("Isair2",33)  // Isair2
    HPPercentLT("Madae2",33)  // Madae2
THEN
  RESPONSE #100
    SetGlobal("WarpSequenceHP33","MYAREA",1)
    ActionOverride("Isair2",PlaySequence(Myself,ATTACK_BACKSLASH))
    ActionOverride("Madae2",PlaySequence(Myself,ATTACK_BACKSLASH))
    Continue()
END

IF
  Global("WarpSequenceHP25","MYAREA",0)
  Global("Final_Battle_Part2","MYAREA",1)
  Or(2)
    HPPercentLT("Isair2",25)  // Isair2
    HPPercentLT("Madae2",25)  // Madae2
THEN
  RESPONSE #100
    SetGlobal("WarpSequenceHP25","MYAREA",1)
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    StartCutScene("63cFB05")
END

IF
  !Global("SH_SpawnGlaberazu_63GlabSL","MYAREA",1)
  !Global("SH_SpawnGlaberazu_63GlabSL","MYAREA",-1)
  !Global("63GlabSL_Dead","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("SH_SpawnGlaberazu_63GlabSL","MYAREA",1)
    SetGlobal("63GlabSL_Dead","GLOBAL",0)
    Continue()
END

IF
  !Global("SH_SpawnGlaberazu_63GlabSR","MYAREA",1)
  !Global("SH_SpawnGlaberazu_63GlabSR","MYAREA",-1)
  !Global("63GlabSR_Dead","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("SH_SpawnGlaberazu_63GlabSR","MYAREA",1)
    SetGlobal("63GlabSR_Dead","GLOBAL",0)
    Continue()
END

IF
  !Global("SH_SpawnGlaberazu_63GlabSL","MYAREA",-1)
  !Global("SH_SpawnGlaberazu_63GlabSL","MYAREA",2)
  Global("SH_SpawnGlaberazu_63GlabSL","MYAREA",1)
  !Global("SH_SGem_Destroyed","GLOBAL",1)
THEN
  RESPONSE #100
    SpellHitEffectSprite("63GlabSL","63GlabSL",CURE_SERIOUS_WOUNDS,0)
    CreateCreature("63GlabSL","",[806.547],0)  // ~Glabrezu Guard~
    SetGlobal("SH_SpawnGlaberazu_63GlabSL","MYAREA",2)
    Continue()
END

IF
  !Global("SH_SpawnGlaberazu_63GlabSL","MYAREA",-1)
  !Global("SH_SpawnGlaberazu_63GlabSL","MYAREA",2)
  Global("SH_SGem_Destroyed","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("SH_SpawnGlaberazu_63GlabSL","MYAREA",-1)
    ActionOverride("63GlabSL",DestroySelf())
    Continue()
END

IF
  Global("SH_SpawnGlaberazuXP_Glaberazu_1","MYAREA",0)
  Or(2)
    Global("SH_SGem_Destroyed","GLOBAL",1)
    Global("SH_No_Demons","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("SH_SpawnGlaberazu_63GlabSL","MYAREA",-1)
    SetGlobal("SH_SpawnGlaberazuXP_Glaberazu_1","MYAREA",1)
    ActionOverride("63GlabSL",DestroySelf())
    HideCreature("Glaberazu_1",FALSE)
    Continue()
END

IF
  !Global("SH_SpawnGlaberazu_63GlabSR","MYAREA",-1)
  !Global("SH_SpawnGlaberazu_63GlabSR","MYAREA",2)
  Global("SH_SpawnGlaberazu_63GlabSR","MYAREA",1)
  !Global("SH_SGem_Destroyed","GLOBAL",1)
THEN
  RESPONSE #100
    SpellHitEffectSprite("63GlabSR","63GlabSR",CURE_SERIOUS_WOUNDS,0)
    CreateCreature("63GlabSR","",[1178.434],0)  // ~Glabrezu Guard~
    SetGlobal("SH_SpawnGlaberazu_63GlabSR","MYAREA",2)
    Continue()
END

IF
  !Global("SH_SpawnGlaberazu_63GlabSR","MYAREA",-1)
  !Global("SH_SpawnGlaberazu_63GlabSR","MYAREA",2)
  Global("SH_SGem_Destroyed","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("SH_SpawnGlaberazu_63GlabSR","MYAREA",-1)
    ActionOverride("63GlabSR",DestroySelf())
    Continue()
END

IF
  Global("SH_SpawnGlaberazuXP_Glaberazu_2","MYAREA",0)
  Or(2)
    Global("SH_SGem_Destroyed","GLOBAL",1)
    Global("SH_No_Demons","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("SH_SpawnGlaberazu_63GlabSR","MYAREA",-1)
    SetGlobal("SH_SpawnGlaberazuXP_Glaberazu_2","MYAREA",1)
    ActionOverride("63GlabSR",DestroySelf())
    HideCreature("Glaberazu_2",FALSE)
    Continue()
END

IF
  Global("StartCutscene_63cFB01","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("StartCutscene_63cFB01","MYAREA",1)
    AllowAreaResting(FALSE)
    SetGlobal("SH_Teleported_To_6303","GLOBAL",1)
    HideCreature("Isair",FALSE)
    HideCreature("Madae",FALSE)
    HideCreature("Serak",FALSE)
    HideCreature("Mourn",FALSE)
    HideCreature("Zilvar",FALSE)
    HideCreature("Tilzen",FALSE)
    HideCreature("Phaen",FALSE)
    HideCreature("Chimera",FALSE)
    HideCreature("Buvai_deNaly",FALSE)
    ActionOverride("Isair",ReallyForceSpell(Myself,WIZARD_AEGIS))
    ActionOverride("Isair",ReallyForceSpell(Myself,WIZARD_SEVEN_EYES))
    ActionOverride("Isair",ReallyForceSpell(Myself,WIZARD_FIRESHIELD_BLUE))
    ActionOverride("Madae",ReallyForceSpell(Myself,CLERIC_DIVINE_SHELL))
    ActionOverride("Madae",ReallyForceSpell(Myself,CLERIC_IRON_SKINS))
    ActionOverride("Madae",ReallyForceSpell(Myself,CLERIC_CLOAK_OF_FEAR))
    ActionOverride("Madae",ReallyForceSpell(Myself,WIZARD_ELEMENTAL_BARRIER))
    SetCreatureAreaFlag("Isair",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Madae",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Isair2",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Madae2",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Serak",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Mourn",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Zilvar",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Tilzen",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Phaen",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Chimera",IGNORE_AI_INHIBIT,TRUE)
    SetCreatureAreaFlag("Buvai_deNaly",IGNORE_AI_INHIBIT,TRUE)
END

IF
  Global("StartCutscene_63cFB01","MYAREA",1)
THEN
  RESPONSE #100
    SetGlobal("StartCutscene_63cFB01","MYAREA",2)
    SetGlobal("SH_Teleported_To_6303","GLOBAL",2)
    StartCutScene("63cFB01")
END

IF
  Global("StartCutscene_63cFB03","MYAREA",0)
  !InCutsceneMode()
  GlobalGT("StartCutscene_63cFB02","MYAREA",0)
  Global("TeleportIsairMadaeHP33","MYAREA",1)
  Dead("Serak")  // 
  Dead("Mourn")  // 
  Dead("Zilvar")  // 
  Dead("Tilzen")  // 
  Dead("Phaen")  // 
  Dead("Chimera")  // 
  Dead("Buvai_deNaly")  // 
THEN
  RESPONSE #100
    SetGlobal("StartCutscene_63cFB03","MYAREA",1)
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    StartCutScene("63cFB03")
END

IF
  Global("LoweredHP","MYAREA",0)
  Global("Pool_Tainted","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("LoweredHP","MYAREA",1)
    SetHPPercent("Isair2",33,MAX_HP)
    SetHPPercent("Madae2",33,MAX_HP)
END

IF
  Global("StartCutscene_63cFB04","MYAREA",0)
  Global("StartCutscene_63cFB03","MYAREA",1)
  !InCutsceneMode()
  CheckDoorFlags("AR6303_Door1",DOOROPEN)  // AR6303_Door1
THEN
  RESPONSE #100
    SetGlobal("StartCutscene_63cFB04","MYAREA",1)
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    StartCutScene("63cFB04")
END

IF
  Global("StartCutscene_63cFB06","MYAREA",1)
  GlobalTimerExpired("Screenshake","MYAREA")
THEN
  RESPONSE #100
    SetGlobalTimerRandom("Screenshake","MYAREA",5,10)
    ScreenShake(15,10,10)
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

