IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Myself)  // 
    StartCutSceneMode()
    ClearAllActions()
    MultiPlayerSync()
    ClearActions(Player1)
    ClearActions(Player2)
    ClearActions(Player3)
    ClearActions(Player4)
    ClearActions(Player5)
    ClearActions(Player6)
    MultiPlayerSync()
    FadeToColor([0.0],0)
    Wait(1)
    StopJoinRequests()
    SetGlobal("RJ_AR5200","GLOBAL",1)
    MultiPlayerSync()
    EndCutSceneMode()
    StartCutScene("LUA5200a")
END

